
IF
	InParty(Myself)
	InParty("Sarevok")
	TriggerOverride("Sarevok", GlobalLT("XA_LC_CorwinBantersEnd", "LOCALS", 1))
THEN
	RESPONSE #100
		ActionOverride("Sarevok", SetGlobal("XA_LC_CorwinBantersEnd", "LOCALS", 3))
		Continue()
END

IF
	InParty(Myself)
	InParty("XACAELAR")
	TriggerOverride("XACAELAR", GlobalLT("XA_LC_CorwinBantersEnd", "LOCALS", 1))
THEN
	RESPONSE #100
		ActionOverride("XACAELAR", SetGlobal("XA_LC_CorwinBantersEnd", "LOCALS", 1))
		Continue()
END

