IF 
	InParty(Myself)
	GlobalLT("XA_HostileHexxat", "LOCALS", 1)
	Global("XA_CorwinHexxatFight", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_HostileHexxat", "LOCALS", 1)
		Continue()
END

IF 
	Global("XA_HostileHexxat", "LOCALS", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		LeaveParty()
		SetLeavePartyDialogFile()
		ChangeAIScript("",DEFAULT)
		ChangeAIScript("useitem",GENERAL)
		ChangeAIScript("XACORHEX",SPECIFICS)
		SetGlobal("XA_HostileHexxat", "LOCALS", 2)
		
		SetInterrupt(TRUE)
END