IF
	True()
THEN
	RESPONSE #100
		StartCutSceneMode()
		CutSceneId(Player1)
		DisplayStringHead("LCINCUB", ~Come forth, my minions...~)
		CreateVisualEffect("SPPORTAL",[200.225])
		CreateVisualEffect("SPPORTAL",[430.235])
		Wait(2)
		CreateCreature("LCDEM01",[200.225],SE)  
		CreateCreature("LCDEM02",[430.235],SW)
		ActionOverride("LCINCUB", Enemy())
		SetGlobal("LCA_DemonSpawn", "GLOBAL", 2)
		EndCutSceneMode()
END