IF 
	InParty(Myself)
	GlobalLT("LCA_HostileHexxat", "LOCALS", 1)
	Global("LCA_Banter_CorwinHexxat", "GLOBAL", 7)
THEN
	RESPONSE #100
		SetGlobal("LCA_HostileHexxat", "LOCALS", 1)
		Continue()
END

IF 
	Global("LCA_HostileHexxat", "LOCALS", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		LeaveParty()
		ChangeAIScript("",DEFAULT)
		ChangeAIScript("bdfigh01",GENERAL)
		ChangeAIScript("LCKELHEX",SPECIFICS)
		SetGlobal("LCA_HostileHexxat", "LOCALS", 2)
		SetInterrupt(TRUE)
		Continue()
END