IF
	Global("XA_ArrivedInUndercity", "GLOBAL", 2)
	!Global("XA_SkieModActive", "GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("XA_ArrivedInUndercity", "GLOBAL", 3)
		Wait(1)
		ActionOverride("XASKIE", StartDialog("XASKIE", Player1))
END

IF
	Global("XA_ArrivedInUndercity", "GLOBAL", 2)
	Global("XA_SkieModActive", "GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("XA_ArrivedInUndercity", "GLOBAL", 3)
		Wait(1)
		ActionOverride("XAGLINT", StartDialog("XAGLINT", Player1))
END