IF
	True()
THEN
	RESPONSE #100
		CutSceneID(Player1)
		StorePartyLocations()
		FadeToColor([20.0],0)
		Wait(3)
		LeaveAreaLUA("XABEDR","",[267.308], NW) 
		Wait(1)
		SetGlobal("XA_LC_Workout", "GLOBAL", 1)
		CreateCreature("XACORWO", [370.383], NW)
		Wait(1)
		ActionOverride("XACORWO", SetSequence(SEQ_DIE))
		SetSequence(SEQ_DIE)
		Wait(2)
		FadeFromColor([20.0],0)
		EndCutSceneMode()
		Wait(1)
		ActionOverride("XACORWO", StartDialog("XACORWO", Player1))
END