PRINT @3000  /* ~Processing BG1 changes...~ */

COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/bg2/baf~
COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/bg2/d~

//{ Script Extensions
	EXTEND_TOP ~baldur.bcs~ 	~%MOD_FOLDER%/bg2/baf/xabalbg2.baf~
	EXTEND_TOP ~baldur.bcs~ 	~%MOD_FOLDER%/common/baf/xachfight.baf~
	EXTEND_TOP ~baldur.bcs~		~%MOD_FOLDER%/bg2/baf/xajrnbg2.baf~
	EXTEND_TOP ~player1d.bcs~ 	~%MOD_FOLDER%/bg2/baf/xap1d.baf~
//}

//{ are
	COPY ~%MOD_FOLDER%/bg2/are/xacs03.are~ ~override~
	COPY ~%MOD_FOLDER%/bg2/tis/xacs03.tis~ ~override~
	COPY ~%MOD_FOLDER%/bg2/wed/xacs03.wed~ ~override~
	COPY ~%MOD_FOLDER%/bg2/bmp/xacs03ht.bmp~ ~override~
	COPY ~%MOD_FOLDER%/bg2/bmp/xacs03lm.bmp~ ~override~
	COPY ~%MOD_FOLDER%/bg2/bmp/xacs03sr.bmp~ ~override~
	
	COPY ~%MOD_FOLDER%/bg2/are/xacs05.are~ ~override~
	COPY ~%MOD_FOLDER%/bg2/tis/xacs05.tis~ ~override~
	COPY ~%MOD_FOLDER%/bg2/wed/xacs05.wed~ ~override~
	COPY ~%MOD_FOLDER%/bg2/bmp/xacs05ht.bmp~ ~override~
	COPY ~%MOD_FOLDER%/bg2/bmp/xacs05lm.bmp~ ~override~
	COPY ~%MOD_FOLDER%/bg2/bmp/xacs05sr.bmp~ ~override~
	
	COPY ~%MOD_FOLDER%/bg2/are/xacs06.are~ ~override~
	COPY ~%MOD_FOLDER%/bg2/are/xacs12.are~ ~override~
	COPY ~%MOD_FOLDER%/bg2/are/xacs13.are~ ~override~
	COPY ~%MOD_FOLDER%/bg2/are/xapen.are~ ~override~
//}

//{ bam
	COPY ~%MOD_FOLDER%/bg2/bam/xacorbod.bam~ ~override~
	COPY ~%MOD_FOLDER%/bg2/bam/xagcorbd.bam~ ~override~
//}
//{ bmp
	COPY ~%MOD_FOLDER%/bg2/bmp/xacs12ht.bmp~ ~override~
	COPY ~%MOD_FOLDER%/bg2/bmp/xacs12lm.bmp~ ~override~
	COPY ~%MOD_FOLDER%/bg2/bmp/xacs12sr.bmp~ ~override~
	COPY ~%MOD_FOLDER%/bg2/bmp/xadingss.bmp~ ~override~
//}

//{ cre
	COPY ~%MOD_FOLDER%/bg2/cre/xaalig.cre~ ~override~
	SAY NAME1 @3053
	SAY NAME2 @3053
	
	COPY ~%MOD_FOLDER%/bg2/cre/xabltcut.cre~ ~override~
	SAY NAME1 @3050
	SAY NAME2 @3050
	
	COPY ~%MOD_FOLDER%/bg2/cre/xabowyer.cre~ ~override~
	SAY NAME1 @3055
	SAY NAME2 @3055
	
	COPY ~%MOD_FOLDER%/bg2/cre/xacc1.cre~ ~override~
	SAY NAME1 @3043
	SAY NAME2 @3043
	
	COPY ~%MOD_FOLDER%/bg2/cre/xacc2.cre~ ~override~
	SAY NAME1 @3043
	SAY NAME2 @3043

	COPY ~%MOD_FOLDER%/bg2/cre/xacorinv.cre~ ~override~
	
	COPY ~%MOD_FOLDER%/bg2/cre/xacorwin.cre~ ~override~
	SAY NAME1 					@3043 /*~Corwin~*/
	SAY NAME2 					@3043 /*~Corwin~*/
	SAY BIO						@400 /* ~When asked about her past, Schael Corwin reluctantly admits she ran wild as a child on the streets of Baldur's Gate. Her rebelliousness soon got her into trouble with the Flaming Fist. 

Left alone in a cell with nothing but her thoughts for company, she began to reflect on the decisions she'd made in the past and see where they would inevitably take her. When she was eventually freed, she decided to change the direction of her life. She enlisted in the Flaming Fist and rose quickly through the ranks.

You sense there is little Schael Corwin would not do for her family or for the Flaming Fist.~*/

	SAY MORALE 					@500 /* ~Rohma needs a mother!~ [XA100150]  */
	SAY HAPPY 					@501 /*= ~A team like this can't be beat.~ [XA100151]*/
	SAY UNHAPPY_ANNOYED 		@502 /* ~This isn't working. We need to do better.~ [XA100152] */
	SAY UNHAPPY_SERIOUS 		@503 /* ~Watch it. You're straying farther off the path than I'm ready to go.~ [XA100153] */
	
	SAY UNHAPPY_BREAKING_POINT 	@504 /* ~I can't support this effort, not anymore. Farewell.~ [XA100154] */
	
	SAY LEADER 					@505 /* ~I'm used to being in charge. I'll lead us to victory.~ [XA100155] */
	
	SAY TIRED 					@506 /* ~An army can't march forever. We've got to rest.~ [XA100156] */
	
	SAY BORED 					@507 /* ~We've work to do. Let's get moving.~ [XA100157] */
	SAY BATTLE_CRY1 			@508 /* ~To battle!~ [XA100158] */
	SAY BATTLE_CRY2 			@509 /* ~Let's see how long you last against me.~ [XA100159] */
	SAY BATTLE_CRY3 			@510 /* ~Fight if you must, but you're not winning this.~ [XA100160] */
	
	SAY BATTLE_CRY4 			@511 /* ~I'm looking forward to this.~ [XA100161] */
	SAY BATTLE_CRY5 			@512 /* ~Time to end you!~ [XA100162] */
	SAY DAMAGE 					@513 /*  ~Ow!~ [XA100163]*/
	SAY DYING 					@514 /* ~No... Rohma...~ [XA100164] */
	SAY HURT 					@515 /* ~Medic!~ [XA100165] */
	SAY AREA_FOREST				@516 /* ~The forest is so serene. I always catch myself watching for bandits, though.~ [XA100166]*/
	
	SAY AREA_CITY 				@517 /* ~Ah, noise and crowds. Feels like home.~ [XA100167]*/
	
	SAY AREA_DUNGEON 			@518 /*~Watch your step. Nothing good comes out of a place like this.~ [XA100168]*/
	SAY AREA_DAY 				@544 /*~Light and warmth. I'm glad for both.~ [XAA100194]*/
	
	SAY AREA_NIGHT 				@519 /*~In the city, you rarely see the stars. They're beautiful tonight.~ [XA100169]*/
	
	SAY SELECT_COMMON1 			@520 /* ~Yes?~ [XA100170] */
	SAY SELECT_COMMON2 			@521 /* ~Your orders?~ [XA100171] */
	SAY SELECT_COMMON3 			@522 /* ~Hm?~ [XA100172] */
	SAY SELECT_COMMON4 			@523 /* ~What?~ [XA100173] */
	SAY SELECT_COMMON5 			@524 /* ~Go ahead.~ [XA100174] */
	SAY SELECT_COMMON6 			@525 /* ~I'm listening.~ [XA100175] */
	SAY SELECT_ACTION1 			@526 /* ~Right.~ [XA100176]*/
	SAY SELECT_ACTION2 			@527 /* ~I understand.~ [XA100177] */
	SAY SELECT_ACTION3 			@528 /* ~Yes.~ [XA100178] */
	SAY SELECT_ACTION4 			@529 /* ~What are your orders, hero?~ [XA100179]*/
	SAY SELECT_ACTION5 			@530 /* ~I'm a ranger. I want to RANGE.~ [XA100180] */
	
	SAY SELECT_ACTION6 			@531 /* ~Do you think love can bloom even on a battlefield?~ [XA100181] */
	
	SAY SELECT_ACTION7 			@532 /* ~Sometimes I dream I'm a chaotic good elf.~ [XA100182] */
	
	SAY REACT_TO_DIE_GENERAL 	@533 /*~I won't forget you. Your sacrifice won't have been in vain.~ [XA100183]*/
	
	SAY REACT_TO_DIE_SPECIFIC 	@534 /*~We're better off without him.~ [XA100184]*/
	SAY SELECT_RARE1 			@529 /*~What are your orders, hero?~ [XA100179]*/
	SAY SELECT_RARE2			@530 /*~I'm a ranger. I want to RANGE.~ [XA100185]*/
	SAY CRITICAL_HIT 			@536 /* ~Hah! My aim is true.~ [XA100186] */
	SAY CRITICAL_MISS			@537 /*~I'll recover.~ [XA100187]*/
	SAY TARGET_IMMUNE 			@538 /* ~This isn't working! We have to try something else.~ [XA100188]*/
	
	SAY INVENTORY_FULL 			@539 /* ~I can't carry that too. I dropped it.~ [XA100189] */
	
	SAY PICKED_POCKET 			@540 /* ~I'll just take that...~ [XA100190] */
	SAY HIDDEN_IN_SHADOWS 		@541 /* ~Shhh. I'm hidden.~ [XA100191] */
	SAY SPELL_DISRUPTED 		@542 /* ~My spell! I lost it.~ [XA100192] */
	SAY SET_A_TRAP 				@543 /* ~Careful—I've put a trap down.~ [XA100193] */
		
	COPY ~%MOD_FOLDER%/bg2/cre/xadings.cre~ ~override~
	SAY NAME1 @3016
	SAY NAME2 @3016
		
	COPY ~%MOD_FOLDER%/bg2/cre/xaeltcut.cre~ ~override~
	SAY NAME1 @3034
	SAY NAME1 @3034
			
	COPY ~%MOD_FOLDER%/bg2/cre/xaentcut.cre~ ~override~
	SAY NAME1 @3035
	SAY NAME1 @3035
	
	COPY ~%MOD_FOLDER%/bg2/cre/xaesmith.cre~ ~override~
	SAY NAME1 @3036
	SAY NAME1 @3036
		
	COPY ~%MOD_FOLDER%/bg2/cre/xaffofcr.cre~ ~override~
	SAY NAME1 @3058
	SAY NAME2 @3058
	
	COPY ~%MOD_FOLDER%/bg2/cre/xaffwcut.cre~ ~override~
	SAY NAME1 @3079
	SAY NAME2 @3079
	
	COPY ~%MOD_FOLDER%/bg2/cre/xagolsto.cre~ ~override~
	SAY NAME1 @3062
	SAY NAME2 @3062
	
	COPY ~%MOD_FOLDER%/bg2/cre/xalchook.cre~ ~override~
	SAY NAME1 @3043
	SAY NAME2 @3043
	
	COPY ~%MOD_FOLDER%/bg2/cre/xaliacut.cre~ ~override~
	SAY NAME1 @3064
	SAY NAME2 @3064
	
	COPY ~%MOD_FOLDER%/bg2/cre/xaluxg.cre~ ~override~
	SAY NAME1 @3087
	SAY NAME2 @3087

	COPY ~%MOD_FOLDER%/bg2/cre/xaskcut1.cre~ ~override~
	SAY NAME1 @3070
	SAY NAME2 @3070
	
	COPY ~%MOD_FOLDER%/bg2/cre/xaskcut2.cre~ ~override~
	SAY NAME1 @3070
	SAY NAME2 @3070
	
	COPY ~%MOD_FOLDER%/bg2/cre/xatargol.cre~ ~override~
	SAY NAME1 @3071
	SAY NAME2 @3071
	
	COPY ~%MOD_FOLDER%/bg2/cre/xatmarsu.cre~ ~override~
	SAY NAME1 @3072
	SAY NAME2 @3072
//}

//{ itm
	COPY ~%MOD_FOLDER%/bg2/itm/xacorbod.itm~ ~override~
	COPY ~%MOD_FOLDER%/bg2/itm/xaldunc.itm~ ~override~
	COPY ~%MOD_FOLDER%/bg2/itm/xaldunca.itm~ ~override~
	COPY ~%MOD_FOLDER%/bg2/itm/xaorw1.itm~ ~override~
	COPY ~%MOD_FOLDER%/bg2/itm/xaorw1a.itm~ ~override~
	COPY ~%MOD_FOLDER%/bg2/itm/xaorw2.itm~ ~override~
	COPY ~%MOD_FOLDER%/bg2/itm/xaorw2a.itm~ ~override~
//}


