
IF
	Global("XA_LC_PartyRemovalProcessing", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_PartyRemovalProcessing", "GLOBAL", 2)
END

IF
	Global("XA_LC_PartyRemovalProcessing", "GLOBAL", 2)
	GlobalLT("XA_LC_TransitionRBG", "MYAREA", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_TransitionRBG", "MYAREA", 1)
		FadeToColor([30.0],0)
		HideGUI()
		Wait(2)
		ActionOverride(Player1,LeaveAreaLUA("XAPEN","",[1628.1456],NW))
		ActionOverride(Player2,LeaveAreaLUA("XAPEN","",[1664.1531],NW))
		ActionOverride(Player3,LeaveAreaLUA("XAPEN","",[1797.1452],NW))
		ActionOverride(Player4,LeaveAreaLUA("XAPEN","",[1719.1544],NW))
		ActionOverride(Player5,LeaveAreaLUA("XAPEN","",[1777.1510],NW))
		ActionOverride(Player6,LeaveAreaLUA("XAPEN","",[1770.1517],NW))
END