IF 
	GlobalLT("XA_LC_CreateNPC_BG0102", "MYAREA", 1)
	GlobalLT("XA_LC_SkieModActive", "GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_CreateNPC_BG0102", "MYAREA", 1)
		CreateCreature("XAMELKOR", [677.770], S)
		Continue()
END

IF
	GlobalLT("XA_LC_SkieModActive", "GLOBAL",1)
	GlobalLT("XA_LC_CreateSkie_BG0102", "MYAREA", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_CreateSkie_BG0102", "MYAREA", 1)
		CreateCreature("XASKIE", [710.1265], SW)
		Continue()
END





