IF 
	GlobalLT("XA_LC_CreateNPCs_0615", "MYAREA", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_CreateNPCs_0615", "MYAREA", 1)
		ActionOverride("Container 3", DestroyItem("SCRL1I"))
		ActionOverride("Container 3", DestroyItem("SCRL1K"))
		ActionOverride("Container 3", DestroyItem("SCRL3A"))
		ActionOverride("Container 3", DestroyItem("SCRL3C"))
		CreateCreature("XAWVMER2", [600.440], N)
		CreateCreature("XAWVMER1", [500.760], E)
		CreateCreature("XAA630", [770.415], W)
		Continue()
END

