IF 
	Global("XA_LC_PartyRemovalProcessing", "GLOBAL", 2)
	GlobalLT("XA_LC_900_Entry", "MYAREA", 1)
THEN 
	RESPONSE #100
		Explore()
		SetGlobal("XA_LC_900_Entry", "MYAREA", 1)
		SetGlobal("ThiefSecretQuestion","GLOBAL",0)
		Wait(2)
		ActionOverride("XANEDERL", Dialogue(Player1)) //XANEDERL
END

IF 
	Global("XA_LC_BenceWyrm", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_BenceWyrm", "GLOBAL", 2)
		ActionOverride("XARBNB01", MoveToPoint([3.827]))
		ActionOverride("XARBNB01", EscapeArea())
		SmallWait(2)
		ActionOverride("XARBNB02", MoveToPoint([3.827]))
		ActionOverride("XARBNB02", EscapeArea())
		SmallWait(2)
		ActionOverride("XAB147B", MoveToPoint([3.827]))
		ActionOverride("XAB147B", EscapeArea())
		SmallWait(2)
		ActionOverride("XAB149B", MoveToPoint([3.827]))
		ActionOverride("XAB149B", EscapeArea())
		SmallWait(2)
		ActionOverride("XANEDERL", MoveToPoint([3.827]))
		ActionOverride("XANEDERL", EscapeArea())
		Wait(3)
END

IF 
	Global("XA_LC_BenceWyrm", "GLOBAL", 2)
THEN
	RESPONSE #100
		ActionOverride("XABENCE",  Dialogue(Player1))
		Continue()
END

IF
	Global("XA_LC_BenceWyrm", "GLOBAL", 3)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_BenceWyrm", "GLOBAL", 4)
		ActionOverride("XABENCE", MoveToPoint([3.827]))
END

IF
	Global("XA_LC_BenceWyrm", "GLOBAL", 4)
	!TriggerOverride(Player1, See("XABENCE"))
THEN
	RESPONSE #100
		SetGlobal("XA_LC_BenceWyrm", "GLOBAL", 5)
		ActionOverride("XABENCE", DestroySelf()) 
END

IF 
	Global("XA_LC_ReturnToBG", "GLOBAL", 1)
	GlobalLT("XA_LC_NPCsDestroyed","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_NPCsDestroyed","GLOBAL",1)
		
		ActionOverride("XANEDERL", DestroySelf()) // Nederlok
		ActionOverride("XARBNB01", DestroySelf()) // City Official
		ActionOverride("XARBNB02", DestroySelf()) // City Official
		ActionOverride("XAB147B", DestroySelf()) // FF Officer
		ActionOverride("XAB149B", DestroySelf()) // FF Officer
		
END

//{ ShowGUI after transition from SoA
IF
	GlobalLT("XA_LC_ShowGUI", "MYAREA", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_ShowGUI", "MYAREA", 1)
		UnhideGUI()
		Continue()
END
//}

//{ See if the player already completed the Helm of Balduran quest
IF
	Global("XA_LC_PossessedHelm", "GLOBAL", 1)
	GlobalLT("XA_LC_BalduranCheck", "MYAREA", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_BalduranCheck", "MYAREA", 1)
		SetGlobal("XA_LC_HelmQuestAlreadyDone", "GLOBAL", 1)
		Continue()
END

IF
	GlobalLT("XA_LC_PossessedHelm", "GLOBAL", 1)
	GlobalLT("XA_LC_BalduranCheck", "MYAREA", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_BalduranCheck", "MYAREA", 1)
		Continue()
END
//}

//{ Mark Ellesime Dream as complete
IF
	GlobalLT("HadEllesimeDream1","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("HadEllesimeDream1","GLOBAL",1)
		Continue()
END
//}