IF
	Global("XA_ReturnToBG", "GLOBAL", 1)
	GlobalLT("XA_CellSpyCreated", "MYAREA", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_CellSpyCreated", "MYAREA", 1)
		CreateCreature("XACELL", [330.440], SEE)
		Continue()
END

IF 
	Global("XA_VirgilInCustody", "GLOBAL", 1)
	GlobalLT("XA_VirgiXAreated_0607", "MYAREA", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_VirgiXAreated_0607", "MYAREA", 1)
		CreateCreature("XAVIRGIL", [400.340], SSW)
		Continue()
END

