IF 
	Global("XA_LC_SavedAldeth", "GLOBAL", 1)
	GlobalLT("XA_CreateNPCs0128_Aldeth", "MYAREA", 1)
	!Dead("Aldeth")
THEN
	RESPONSE #100
		SetGlobal("XA_CreateNPCs0128_Aldeth", "MYAREA", 1)
		CreateCreature("ALDETH", [600.400], SW) 
		ActionOverride("Aldeth", SetDialog("XAALDETH"))
		ActionOverride("Aldeth", SetNumTimesTalkedTo(0))
		ActionOverride("Aldeth", ChangeAIScript("XAINITP1",CLASS))
		Continue()
END

