IF
	True()
THEN
	RESPONSE #100
		ClearAllActions()
		StartCutSceneMode()
		SetCutSceneLite(TRUE)
		SetGlobal("XA_LC_XACS15Cutscene", "GLOBAL", 2)
		CutSceneId("XACORWIN")
		ActionOverride("XANEOMA", FaceObject("XACORWIN"))
		SmallWait(5)
		DisplayStringHead("XANEOMA", @1)
		Wait(1)
		ActionOverride("XANEOMA", MoveToObject("XACORWIN"))
		Wait(1)
		ActionOverride("XACORWIN", FaceObject("XANEOMA"))
		Wait(1)
		DisplayStringHead("XACORWIN", @0)
		
		Wait(1)
		EndCutSceneMode()
END