IF
	True()
THEN
	RESPONSE #100
		StartCutSceneMode()
		CutSceneId(Player1)
		DisplayStringHead("XANARZU", @0)
		CreateVisualEffect("SPPORTAL",[475.460])
		CreateVisualEffect("SPPORTAL",[656.596])
		Wait(2)
		CreateCreature("xanarzs0",[475.460],SE)  // bdabibla
		CreateCreature("xanarzs1",[656.596],SW)  // bdabigre
		ActionOverride("XANARZU", Enemy())
		SetGlobal("XA_LC_DemonSpawn", "GLOBAL", 2)
		EndCutSceneMode()
END