IF
	Global("XA_StartTOB", "GLOBAL", 1)
THEN
	RESPONSE #100
		AdvanceTime(FOURTEEN_DAYS)
		DayNight(8)
		MoveToCampaign("ToB")
END
IF
	Global("XA_SkieModActive", "GLOBAL", 1)
	InMyArea("XASKIE")
THEN
	RESPONSE #100
		ActionOverride("XASKIE", DestroySelf())
		Continue()
END

IF
	GlobalLT("XA_RohmaCorwinCS", "XADUC3", 1)
	Global("XA_PrepareCSBGEND1", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_RohmaCorwinCS", "XADUC3", 1)
		StartCutSceneMode()
		StartCutScene("XABGEND1")
END
