IF
	AreaCheck("xauc")
	GlobalLT("XA_LC_SkieModActive", "GLOBAL",1)
THEN
	RESPONSE #100
		DestroySelf()
END
IF
	AreaCheck("XAA145") // ar1300
	See(Player1)
	!Range(Player1, 8)
	ActionListEmpty()
	GlobalLT("XA_LC_TalkedToGlint", "Global", 1)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	AreaCheck("XAA145") // ar1300
	See(Player1)
	Range(Player1, 8)
	GlobalLT("XA_LC_TalkedToGlint", "Global", 1)
THEN
	RESPONSE #100
		StartDialog("XAGLINT", Player1)
END