IF
	Global("XA_LC_ArrivedInUndercity", "GLOBAL", 2)
	GlobalLT("XA_LC_SkieModActive", "GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_ArrivedInUndercity", "GLOBAL", 3)
		Wait(1)
		ActionOverride("XASKIE2", StartDialog("XASKIE", Player1))
END

IF
	Global("XA_LC_ArrivedInUndercity", "GLOBAL", 2)
	Global("XA_LC_SkieModActive", "GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_ArrivedInUndercity", "GLOBAL", 3)
		Wait(1)
		ActionOverride("XAGLINT2", StartDialog("XAGLINT", Player1))
END