IF
	True() //cutscene conditions always evaluate as true
THEN
	RESPONSE #100
		CutSceneId(Player1)
		ActionOverride("CORWIN", EscapeArea())
		Wait(2)
		SetGlobalTimer("LCA_Ath","GLOBAL",FOUR_DAYS)
		SetGlobal("LCA_SkieSaved", "GLOBAL", 1)
		FadeToColor([30.0],0)
		Wait(3)
		ActionOverride("CORWIN",DestroySelf())
		ActionOverride("BDROHMA",DestroySelf())
		ActionOverride("BDAUDAM",DestroySelf())
		StartCutScene("LCAcsEx")
END