IF
	See(Player1)
	!Global("LCA_SavedElfsong", "GLOBAL", 1)
	OR(2)
		GlobalGT("LCA_SavedLyriel", "GLOBAL", 0)
		Global("LCA_ExitPrison", "GLOBAL", 1)
THEN
	RESPONSE #100
		StartDialog("LCALYTH", Player1)
END

IF
	See(Player1)
	!Global("LCA_AlythInit", "LOCALS", 1)
	!Global("LCA_SavedElfsong", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("LCA_AlythInit", "LOCALS", 1)
		StartDialog("LCALYTH", Player1)
END

