IF
	Global("LCA_ReturnToBG", "GLOBAL", 1)
	InMyArea("ivanne")
THEN
	RESPONSE #100
		ActionOverride("ivanne", DestroySelf())
		Continue()
END

IF
	Global("LCA_ReturnToBG", "GLOBAL", 1)
	InMyArea("VIVIENNE")
THEN
	RESPONSE #100
		ActionOverride("VIVIENNE", DestroySelf())
		Continue()
END

IF
	Global("LCA_ReturnToBG", "GLOBAL", 1)
	InMyArea("Detranion")
THEN
	RESPONSE #100
		ActionOverride("Detranion", DestroySelf())
		Continue()
END