IF
	Global("LCA_ReturnToBG", "GLOBAL", 1)
	!Global("LCA_NPCDestroy", "GLOBAL", 1)
THEN
	RESPONSE #100
		ActionOverride("NIKLOS", DestroySelf())
		ActionOverride("ELMIN5", DestroySelf())
		SetGlobal("LCA_NPCDestroy", "GLOBAL", 1)
		Continue()
END

IF 
	Global("LCA_ReturnToBG", "GLOBAL", 1)
	!Global("LCA_CreateMickNPC", "GLOBAL", 1)
	!InMyArea("MICK")
THEN
	RESPONSE #100
		CreateCreature("MICK", [510.2938], N)
		SetGlobal("LCA_CreateMickNPC", "GLOBAL", 1)
END