IF
	See("LCCORWIN")
	InParty("LCCORWIN")
	ActionListEmpty()
	GlobalLT("LCA_MagdaTalk", "GLOBAL", 1)
	OR(2)
		!InMyArea("BELAND")
		Global("BelandEntranceFee","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("LCA_MagdaTalk", "GLOBAL", 1)
		MoveToObject("LCCORWIN")
		Continue()
END

IF
	Global("LCA_MagdaTalk", "GLOBAL", 1)
	Range("LCCORWIN", 8)
THEN
	RESPONSE #100
		FaceObject("LCCORWIN")
		SmallWait(5)
		StartDialogNoSet(Player1)
END

