IF 
	InParty(Myself)
	GlobalLT("LCA_HostileHexxat", "LOCALS", 1)
	Global("LCA_CorwinHexxatFight", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("LCA_HostileHexxat", "LOCALS", 1)
		Continue()
END

IF 
	Global("LCA_HostileHexxat", "LOCALS", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		LeaveParty()
		SetLeavePartyDialogFile()
		ChangeAIScript("useitem",GENERAL)
		ChangeAIScript("LCCORHEX",SPECIFICS)
		SetGlobal("LCA_HostileHexxat", "LOCALS", 2)
		SetInterrupt(TRUE)
END