IF
	Clicked([ANYONE])
	Range(LastTrigger,6)
	PartyHasItem("AMUL27")
THEN
	RESPONSE #100
		SetGlobal("LCA_EnterPainting", "GLOBAL", 1)
		ActionOverride(Player1, StartDialog("PLAYER1", Player1))
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,6)
THEN
	RESPONSE #100
		DisplayString(Myself,~You are too far away to use that.~)
END

IF 
	Range(LastTrigger,6)
	!PartyHasItem("AMUL27")
THEN
	RESPONSE #100
		DisplayString(Myself,~The painting depicts three sailors playing a game of cards.~)
END
