IF
	Global("LCA_AmuletPainting", "GLOBAL", 4)
	PartyHasItem("AMUL27")
	See(Player1)	
THEN
	RESPONSE #100
		SetGlobal("LCA_AmuletPainting", "GLOBAL", 5)
		ActionOverride(Player1, StartDialog("PLAYER1", Player1))
END

IF
	Global("LCA_DoppleSpawn_0706", "GLOBAL", 1)
	Dead("LCDOPP01")
	Dead("LCDOPP02")
	Dead("LCDOPP03")
THEN
	RESPONSE #100
		SetGlobal("LCA_AmuletPainting", "GLOBAL", 7)
		SetGlobal("LCA_DoppleSpawn_0706", "GLOBAL", 2)
		ActionOverride(Player1, StartDialog("PLAYER1", Player1))
END
