IF
	True()
THEN
	RESPONSE #100
		CutSceneID("Vai")
		//[445.1100]
		CreateCreature("FLAMVAI2", [445.1100], N)
		Wait(1)
		ActionOverride("FLAMVAI2", FaceObject("Vai"))
		Wait(1)
		DisplayStringHead("FLAMVAI2", ~Officer Vai.~)
		Wait(2)
		DisplayStringHead("FLAMVAI2", ~New orders from Captain Corwin.~)
		Wait(2)
		ActionOverride("FLAMVAI2", MoveToObject("Vai"))
		Wait(3)
		ClearAllActions()
		SetGlobal("LCA_VaiExit", "GLOBAL", 1)
		StartDialog("VAI", Player1)
END