IF
	GlobalLT("XA_EnteredSaradush", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_EnteredSaradush", "GLOBAL", 1)
		Continue()
END

//{ Caelar Rescue Quest Timer Init
IF
	GlobalLT("XA_KanaDreamTimerSet", "GLOBAL",1)
	Global("XA_ClearedKanaglym", "GLOBAL",1)
	OR(2)
		Global("XA_IncubusDefeated", "GLOBAL", 1)
		GlobalGT("DemoGorgonIsDead","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("XA_KanaDreamTimerSet", "GLOBAL",1)
		SetGlobalTimer("XA_KanaDreamTimer", "GLOBAL", ONE_DAY)
		Continue()
END
//}