IF 
	Global("XA_ReturnToBG", "GLOBAL", 1)
	Global("XA_BelandDialogSwap", "LOCALS", 0)
THEN
	RESPONSE #100
		SetGlobal("BelandEntranceFee","GLOBAL",1)
		SetGlobal("XA_BelandDialogSwap", "LOCALS", 1)
		SetDialog("XABELAND")
END


IF
	Global("XA_ReturnToBG", "GLOBAL", 1)
	See([PC])
	!Allegiance(Myself,ENEMY)
	Global("BelandEntranceFee","GLOBAL",1)
THEN
	RESPONSE #100
		SmallWait(8)
		StartDialog("XABELAND",[PC])
END