IF 
	Global("XA_ReturnToBG", "GLOBAL", 1)
	!Global("XA_DestroyNPCs_0612", "BG0612", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_DestroyNPCs_0612", "BG0612", 1)
		ActionOverride("DRATAN", DestroySelf())
		ActionOverride("GREGOR", DestroySelf())
		ActionOverride("TRALITHAN", DestroySelf())
		CreateCreature("XAWVMER2", [300.410], N)
		CreateCreature("XAWVMER1", [960.517], E)
		CreateCreature("XAWVGRD2", [330.590], N)
		CreateCreature("XAWVGRD2", [890.400], N)
		Continue()
END