//{ Disable any reputation traps
	IF
		Global("XA_ReturnToBG", "GLOBAL", 1)
		GlobalLT("XA_DisableRepTraps", "MYAREA", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			TriggerActivation("REPTRAP",FALSE)
			SetGlobal("XA_DisableRepTraps", "MYAREA", 1)
			SetInterrupt(TRUE)
			Continue()
	END
//}

//{ Block all BG1 area scripting
	IF
		Global("XA_ReturnToBG", "GLOBAL", 1)
	THEN
		RESPONSE #100
			NoAction()
	END
//}