//Note: Variable Key Max Length Appears to be 32.

//{ Mark as In-Party in BG2 (For later summoning via the fate-spirit)
IF
	InParty(Myself)
	!Global("XA_CorwinInPartyBG2", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_CorwinInPartyBG2", "GLOBAL", 1)
		Continue()
END
//}

//{ Copy items from SoD Corwin
IF
	//InParty(Myself)
	!Global("XA_CopyCorwinItems", "GLOBAL", 1)
	//Global("XA_CopyItemTest", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		XEquipItem("", "Corwin", SLOT_AMULET,EQUIP) 
		XEquipItem("", "Corwin", SLOT_ARMOR,EQUIP)
		XEquipItem("", "Corwin", SLOT_BELT,EQUIP)
		XEquipItem("", "Corwin", SLOT_BOOTS,EQUIP)
		XEquipItem("", "Corwin", SLOT_CLOAK,EQUIP)     
		XEquipItem("", "Corwin", SLOT_GAUNTLETS,EQUIP) 
		XEquipItem("", "Corwin", SLOT_HELMET,EQUIP)    
		XEquipItem("", "Corwin", SLOT_RING_LEFT,EQUIP) 
		XEquipItem("", "Corwin", SLOT_RING_RIGHT,EQUIP)
		XEquipItem("", "Corwin", SLOT_SHIELD,EQUIP)
		XEquipItem("", "Corwin", SLOT_AMMO0,EQUIP)     
		XEquipItem("", "Corwin", SLOT_AMMO1,EQUIP)     
		XEquipItem("", "Corwin", SLOT_AMMO2,EQUIP)     
		XEquipItem("", "Corwin", SLOT_AMMO3,EQUIP)   
		XEquipItem("", "Corwin", SLOT_WEAPON0,EQUIP)   
		XEquipItem("", "Corwin", SLOT_WEAPON1,EQUIP)   
		XEquipItem("", "Corwin", SLOT_WEAPON2,EQUIP)   
		XEquipItem("", "Corwin", SLOT_WEAPON3,EQUIP) 

		TakeCreatureItems("Corwin", BACKPACK)
		SetGlobal("XA_CopyCorwinItems", "GLOBAL", 1)
		SetInterrupt(TRUE)
		Continue()
END
//}

//{ Determines if CorwinEET is Installed
IF 
	InParty(Myself)
	Global("XA_CorwinEETCheck", "GLOBAL", 0)
	GlobalGT("EECorwinBG1", "GLOBAL", 0) // this is set as part the CorwinEET mod.
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinEET", "GLOBAL", 1)
		SetGlobal("XA_CorwinEETCheck", "GLOBAL", 1)
		SetInterrupt(TRUE)
		Continue()
END

IF 
	InParty(Myself)
	Global("XA_CorwinEETCheck", "GLOBAL", 0)
	Global("EECorwinBG1", "GLOBAL", 0) // this is set as part the CorwinEET mod.
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinEET", "GLOBAL", 0)
		SetGlobal("XA_CorwinEETCheck", "GLOBAL", 1)
		SetInterrupt(TRUE)
		Continue()
END

IF 
	InParty(Myself)
	Global("XA_MetRohmaCheck", "GLOBAL", 0)
	OR(2)
		Global("bd_rohma_banter","bd0101",7)
		GlobalGT("EEMetRohma", "GLOBAL", 0)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_MetRohma", "GLOBAL", 1)
		SetGlobal("XA_MetRohmaCheck", "GLOBAL", 1)
		SetInterrupt(TRUE)
		Continue()
END
//}

//{ Checks if the Player met Rohma prior to the events of SoA
IF 
	InParty(Myself)
	Global("XA_MetRohmaCheck", "GLOBAL", 0)
	!Global("bd_rohma_banter","bd0101",7) //Met Rohma in SoD
	!GlobalGT("EEMetRohma", "GLOBAL", 0) //Met Rohma in CorwinEET
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_MetRohma", "GLOBAL", 0)
		SetGlobal("XA_MetRohmaCheck", "GLOBAL", 1)
		SetInterrupt(TRUE)
		Continue()
END
//}

//{	Rejoin processing - triggered in XACORWIN.D and XACORWIP.D
IF 
	!InParty(Myself)
	Global("XA_CorwinRejoinProcessed", "GLOBAL", 1)
THEN 
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinJoined","LOCALS",1)
		SetGlobal("XA_AskedToRejoin", "LOCALS", 0)
		SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
		SetGlobal("XA_ResetJoinChecks", "GLOBAL", 1)
		SetGlobal("XA_CorwinRepWarning", "GLOBAL", 0)
		SetGlobal("XA_CorwinRejoinProcessed", "GLOBAL", 2)
		SetInterrupt(TRUE)
		JoinParty()
END
//}

//{ Corwin Can Talk Check
IF 
	Global("XA_CorwinCanTalk", "GLOBAL", 1)
	ActionListEmpty()
	OR(3)
		!IsValidForPartyDialogue(Myself)
		!CombatCounter(0)
		GlobalGT("XA_ArrivedInUndercity", "GLOBAL", 0)
THEN
	RESPONSE #100
		SetGlobal("XA_CorwinCanTalk", "GLOBAL", 0)
		Continue()
END

IF
	!Global("XA_CorwinCanTalk", "GLOBAL", 1)
	ActionListEmpty()
	IsValidForPartyDialogue(Myself)
	CombatCounter(0)
THEN
	RESPONSE #100
		SetGlobal("XA_CorwinCanTalk", "GLOBAL", 1)
		Continue()
END
//}

//{ Corwin Can Talk to Player Check
IF 
	Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	ActionListEmpty()
	OR(3)
		!Global("XA_CorwinCanTalk", "GLOBAL", 1)
		!IsValidForPartyDialogue(Player1)
		!See(Player1)
THEN
	RESPONSE #100
		SetGlobal("XA_CorwinCanTalkToPlayer", "GLOBAL", 0)
		Continue()
END


IF
	!Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	Global("XA_CorwinCanTalk", "GLOBAL", 1)
	ActionListEmpty()
	IsValidForPartyDialogue(Player1)
	See(Player1)
THEN
	RESPONSE #100
		SetGlobal("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Continue()
END
//}

//{ Interactions concerning the Return to BG Mini Quest

	//{ Complimenting Corwin's Family
	IF
		AreaCheck("BG1300") //SE Baldur's Gate
		Global("XA_AVComplimentFamily", "GLOBAL", 1)
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IsValidForPartyDialogue("Aerie")
		
	THEN
		//Dialog B-66, B-79, B-82, B-83, B-84
		RESPONSE #100
			Interact("Aerie")
	END
	
	IF
		AreaCheck("BG1300") //SE Baldur's Gate
		Global("XA_AVComplimentFamily", "GLOBAL", 1)
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IsValidForPartyDialogue("Neera")
		
	THEN
		//Dialog B-66, B-79, B-82, B-83, B-84
		RESPONSE #100
			Interact("Neera")
	END
	
	IF
		AreaCheck("BG1300") //SE Baldur's Gate
		Global("XA_AVComplimentFamily", "GLOBAL", 1)
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IsValidForPartyDialogue("Valygar")
		
	THEN
		//Dialog B-66, B-79, B-82, B-83, B-84
		RESPONSE #100
			Interact("Valygar")
	END
	//}

	//{ Corwin Hall of Wonders Arrest
	IF 
		Global("XA_CorwinArrest", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	THEN
		RESPONSE #100
			//Dialog J-50
			StartDialog("XACORWIJ", Player1)
	END
	//}

	//{ Rohma Kidnapped
	IF 
		Global("XA_RohmaKidnapped", "GLOBAL", 2)
		See(Player1)
	THEN
		RESPONSE #100
			//Dialog J-68
			StartDialog("XACORWIJ", Player1)
	END
	//}

	//{ SoD Anxiety
	IF 
		Global("XA_SoDAnxiety", "GLOBAL", 1)
		GlobalTimerExpired("XA_SoDAnxietyTimer", "GLOBAL")
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_SoDAnxiety", "GLOBAL", 2)
			PlaySong(142)
			//Dialog J-39
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Corwin Leave for Family
	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_CorwinLeaveForFamily", "GLOBAL", 1)
	THEN
		RESPONSE #100
			//Dialogs J-19, J-20
			StartDialog("XACORWIJ", Player1)
	END
	//}
	
	//{ Corwin Need to See Family
	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_CorwinNeedSeeFamily", "GLOBAL", 1)
	THEN
		RESPONSE #100
			//Dialog J-18
			StartDialog("XACORWIJ", Player1)
	END
	//}	

	//{ Meet Tianna
	IF
		Global("XA_AskCorwinAboutTianna", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			Wait(1)
			//Dialog J-15
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Dialog init after Corwin / Neoma reunite
	IF 
		Global("XA_ReturnToBG", "GLOBAL", 1)
		Global("XA_XACS15Cutscene", "GLOBAL", 5)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		!See("XANEOMA")
		Range(Player1, 8)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			PlaySong(146)
			SetGlobal("XA_XACS15Cutscene", "GLOBAL", 6)
			//Dialog J-17
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Request Corwin ToB
	IF
		Global("XA_BGEND3", "GLOBAL", 1)
		Global("XA_DidNotRequestCorwin", "GLOBAL", 1)
		GlobalGT("XA_CorwinOpinionOfPlayer", "GLOBAL", 0)
		!Global("XA_CorwinRomanceActive", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			Wait(3)
			//Dialog J-2
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END

	IF
		Global("XA_BGEND3", "GLOBAL", 1)
		Global("XA_DidNotRequestCorwin", "GLOBAL", 1)
		GlobalGT("XA_CorwinOpinionOfPlayer", "GLOBAL", 0)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			Wait(3)
			PlaySong(146)
			//Dialog J-2
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END

	IF
		Global("XA_BGEND4", "GLOBAL", 1)
		Global("XA_DidRequestCorwin", "GLOBAL", 1)
		!Global("XA_CorwinRomanceActive", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			Wait(3)
			//Dialog J-2
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END

	IF
		Global("XA_BGEND4", "GLOBAL", 1)
		Global("XA_DidRequestCorwin", "GLOBAL", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			Wait(3)
			PlaySong(146)
			//Dialog J-2
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Kill Beno
	IF 
		OR(2)
			Global("XA_CorwinKillBeno", "GLOBAL", 1)
			Global("XA_CorwinBenoST", "GLOBAL", 1)
		ActionListEmpty()
		!Range("XABENO2", 4)
	THEN
		RESPONSE #100
			MoveToObject("XATRBENO")
			Continue()
	END

	IF 
		OR(2)
			Global("XA_CorwinKillBeno", "GLOBAL", 1)
			Global("XA_CorwinBenoST", "GLOBAL", 1)
		Range("XABENO2", 4)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("XACORWIN", FaceObject("XABENO2"))
			//Dialog J-5
			ActionOverride("XACORWIN", StartDialog("XACORWIJ", Player1))
			SetInterrupt(TRUE)
	END
	//}

//} BGMiniQuest Interaction End

//{ Event Checks on Join
/* If certain events occurred while Corwin was not in the party, remove the ability to enter states associated with those events (eg. events which will cause her to leave). */

IF
	Global("XA_ResetJoinChecks", "GLOBAL", 1)
	Global("OpenJonBedroom","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("XA_PlayerSoulStolen", "GLOBAL", 1)
		Continue()
END

IF 
	Global("XA_ResetJoinChecks", "GLOBAL", 1)
	Global("OHD_WEDDING_HOSTILE","OH5000",3)
THEN
	RESPONSE #100
		SetGlobal("XA_WeddingHostile", "GLOBAL", 1)
		Continue()
END

IF 
	Global("XA_ResetJoinChecks", "GLOBAL", 1)
	Global("OHD_sexreactions","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("XA_DornSex", "GLOBAL", 1)
		Continue()
END

IF
	Global("XA_ResetJoinChecks", "GLOBAL", 1)
	Global("BodhiDead","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("XA_BodhiDead", "GLOBAL", 1)
		Continue()
END

IF
	Global("XA_ResetJoinChecks", "GLOBAL", 1)
	Global("LadyMaria","GLOBAL",5) /* Keldorn reconciled with his wife */
THEN
	RESPONSE #100
		SetGlobal("XA_KeldornMaria", "GLOBAL", 1)
		Continue()
END

IF
	Global("XA_ResetJoinChecks", "GLOBAL", 1)
	GlobalGT("PhaereInnuendo","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("XA_AloneWithPhaere", "GLOBAL", 1)
		Continue()
END

IF
	Global("XA_ResetJoinChecks", "GLOBAL", 1)
	Global("BodhiJob","GLOBAL",2)
THEN
	RESPONSE #100
		SetGlobal("XA_BodhiDeal2", "GLOBAL", 1)
		Continue()
END

IF
	Global("XA_ResetJoinChecks", "GLOBAL", 1)
	Global("BodhiJob","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("XA_BodhiDeal3", "GLOBAL", 1)
		Continue()
END

IF
	Global("XA_ResetJoinChecks", "GLOBAL", 1)
	Global("BodhiJob","GLOBAL",4)
THEN
	RESPONSE #100
		SetGlobal("XA_BodhiDeal4", "GLOBAL", 1)
		Continue()
END

IF
	Global("XA_ResetJoinChecks", "GLOBAL", 1)
	Global("FirkraagDeal","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("XA_FirkraagDeal", "GLOBAL", 1)
		Continue()
END

/* Any join checks should be completed by this point. Set the XA_ResetJoinChecks to two to stop the checks from occurring in the future (unless she exits and rejoins the party). */
// Reset Join Checks is set back to 1 when Corwin rejoins the party.
IF
	Global("XA_ResetJoinChecks", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_ResetJoinChecks", "GLOBAL", 2)
		Continue()
END
//}

//{ Reputation Handling
IF
	InParty(Myself)
	ReputationLT(Player1,8)
	!Global("XA_CorwinRepWarning", "GLOBAL", 1)
THEN 
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("XA_CorwinRepWarningTimer", "GLOBAL", ONE_HOUR)
		SetGlobal("XA_CorwinRepWarning", "GLOBAL", 1)
		SetInterrupt(TRUE)
		Continue()
END

IF 
	Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	ReputationLT(Player1,8)
	GlobalTimerExpired("XA_CorwinRepWarningTimer", "GLOBAL")
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinRepWarning", "GLOBAL", 2)
		StartDialog("XACORWIJ", Player1)
		SetInterrupt(TRUE)
END

IF 
	Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	ReputationLT(Player1,7)
	Global("XA_CanLeaveParty", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinLeftPoorRep", "GLOBAL", 1)
		StartDialog("XACORWIJ", Player1)
		SetInterrupt(TRUE)
END
//}

//{ Corwin Can Leave Party Check
IF 
	InParty(Myself)
	!Global("XA_CanLeaveParty", "GLOBAL", 1)
	!OR(4)
		Global("XA_PlanarSphere", "GLOBAL", 1)
		Global("XA_PlanarPrison", "GLOBAL", 1)
		Global("XA_InUnderdark", "GLOBAL", 1)
		Global("XA_TrappedInDemonPrison", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_CanLeaveParty", "GLOBAL", 1)
		Continue()
END

IF 
	InParty(Myself)
	Global("XA_CanLeaveParty", "GLOBAL", 1)
	OR(4)
		Global("XA_PlanarSphere", "GLOBAL", 1)
		Global("XA_PlanarPrison", "GLOBAL", 1)
		Global("XA_InUnderdark", "GLOBAL", 1)
		Global("XA_TrappedInDemonPrison", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_CanLeaveParty", "GLOBAL", 0)
		Continue()
END
//}

//{ Check if the Player is in the Demon's Prison 
IF
	InParty(Myself)
	!Global("XA_TrappedInDemonPrison", "GLOBAL", 1)
	OR(5)
		AreaCheck("XADEMSAN")
		AreaCheck("XAG1")
		AreaCheck("XAG2A")
		AreaCheck("XAG3")
		AreaCheck("XAPAINT1")
THEN
	RESPONSE #100
		SetGlobal("XA_TrappedInDemonPrison", "GLOBAL", 1)
		Continue()
END

IF
	InParty(Myself)
	Global("XA_TrappedInDemonPrison", "GLOBAL", 1)
	!OR(5)
		AreaCheck("XADEMSAN")
		AreaCheck("XAG1")
		AreaCheck("XAG2A")
		AreaCheck("XAG3")
		AreaCheck("XAPAINT1")
THEN
	RESPONSE #100
		SetGlobal("XA_TrappedInDemonPrison", "GLOBAL", 0)
		Continue()
END
//}

//{ Check if the Player is in the Planar Sphere
IF 
	InParty(Myself)
	!Global("XA_PlanarSphere", "GLOBAL", 1)
	OR(5)
		AreaCheck("AR0410")
		AreaCheck("AR0411")
		AreaCheck("AR0412")
		AreaCheck("AR0413")
		AreaCheck("AR0414")
		AreaCheck("AR0415")
THEN 
	RESPONSE #100
		SetGlobal("XA_PlanarSphere", "GLOBAL", 1)
		Continue()
END

IF 
	InParty(Myself)
	Global("XA_PlanarSphere", "GLOBAL", 1)
	!OR(5)
		AreaCheck("AR0410")
		AreaCheck("AR0411")
		AreaCheck("AR0412")
		AreaCheck("AR0413")
		AreaCheck("AR0414")
		AreaCheck("AR0415")
THEN 
	RESPONSE #100
		SetGlobal("XA_PlanarSphere", "GLOBAL", 0)
		Continue()
END
//} End Planar Sphere Check

//{ Check if the Player is in the Planar Prison
IF 
	InParty(Myself)
	!Global("XA_PlanarPrison", "GLOBAL", 1)
	OR(6)
		AreaCheck("AR0516")
		AreaCheck("AR0517")
		AreaCheck("AR0518")
		AreaCheck("AR0519")
		AreaCheck("AR0520")
		AreaCheck("AR0521")
THEN 
	RESPONSE #100
		SetGlobal("XA_PlanarPrison", "GLOBAL", 1)
		Continue()
END

IF 
	InParty(Myself)
	Global("XA_PlanarPrison", "GLOBAL", 1)
	!OR(6)
		AreaCheck("AR0516")
		AreaCheck("AR0517")
		AreaCheck("AR0518")
		AreaCheck("AR0519")
		AreaCheck("AR0520")
		AreaCheck("AR0521")
THEN 
	RESPONSE #100
		SetGlobal("XA_PlanarPrison", "GLOBAL", 0)
		Continue()
END
//} End Planar Prison Check

//{ Check if the Player is in the Underdark
IF
	InParty(Myself)
	!Global("XA_InUnderdark", "GLOBAL", 1)
	OR(18)
		AreaCheck("AR2100") // Underdark
		AreaCheck("AR2101") // Beholder Cave in Underdark
		AreaCheck("AR2102") // Adalon's Cave
		AreaCheck("AR2200") // Ust Natha
		AreaCheck("AR2201") // Ust Natha Temple
		AreaCheck("AR2202") // Ust Natha Inn 1FL
		AreaCheck("AR2203") // Ust Natha Inn 2FL
		AreaCheck("AR2204") // Ust Natha House
		AreaCheck("AR2205") // Ust Natha House
		AreaCheck("AR2206") // Qilue's House
		AreaCheck("AR2207") // Deirex's Tower
		AreaCheck("AR2208") // Jarlaxle's House
		AreaCheck("AR2209") // Jarlaxle's House
		AreaCheck("AR2210") // Deirex's Cave
		AreaCheck("AR2300") // Sahuagin City
		AreaCheck("AR2400") // Mind Flayers
		AreaCheck("AR2401") // Cave to Exit
		AreaCheck("AR2402") // Kuo Toa
THEN 
	RESPONSE #100
		//DisplayStringHead(Myself, ~DEBUG_In Underdark~)
		SetGlobal("XA_InUnderdark", "GLOBAL", 1)
		Continue()
END

IF
	InParty(Myself)
	Global("XA_InUnderdark", "GLOBAL", 1)
	!OR(18)
		AreaCheck("AR2100") // Underdark
		AreaCheck("AR2101") // Beholder Cave in Underdark
		AreaCheck("AR2102") // Adalon's Cave
		AreaCheck("AR2200") // Ust Natha
		AreaCheck("AR2201") // Ust Natha Temple
		AreaCheck("AR2202") // Ust Natha Inn 1FL
		AreaCheck("AR2203") // Ust Natha Inn 2FL
		AreaCheck("AR2204") // Ust Natha House
		AreaCheck("AR2205") // Ust Natha House
		AreaCheck("AR2206") // Qilue's House
		AreaCheck("AR2207") // Deirex's Tower
		AreaCheck("AR2208") // Jarlaxle's House
		AreaCheck("AR2209") // Jarlaxle's House
		AreaCheck("AR2210") // Deirex's Cave
		AreaCheck("AR2300") // Sahuagin City
		AreaCheck("AR2400") // Mind Flayers
		AreaCheck("AR2401") // Cave to Exit
		AreaCheck("AR2402") // Kuo Toa
THEN 
	RESPONSE #100
		//DisplayStringHead(Myself, ~DEBUG_Not In Underdark~)
		SetGlobal("XA_InUnderdark", "GLOBAL", 0)
		Continue()
END
//} End Underdark Check

//{ Event Checks

	//{ Checks if Dorn's patrons are dead
	IF
		!Global("XA_DornPatronsDead", "GLOBAL", 1)
		Dead("ohdazoth")  // Azothet
		Dead("ohdugoth")  // Ur-Gothoz
	THEN
		RESPONSE #100
			SetGlobal("XA_DornPatronsDead", "GLOBAL", 1)
			Continue()
	END
	//}

	//{ Player gives soul fragment to Sarevok
	IF
		GlobalGT("SarevokAlive", "GLOBAL", 0)
		GlobalLT("ImoenGiveSoul","GLOBAL",2)
		Global("XA_CorwinRomanceActive","GLOBAL",2)
		!Global("XA_SarevokSoulTimerSet", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_SarevokSoulTimer", "GLOBAL",TWO_DAYS)
			SetGlobal("XA_SarevokSoulTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Wedding Hostile
	IF 
		Global("OHD_WEDDING_HOSTILE","OH5000",3)
		!Global("XA_WeddingHostile", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_WeddingHostile", "GLOBAL", 1)
			SetGlobal("XA_CorwinLeaveWedding", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
	
	//{ Entered Amkethran
	IF
		InParty(Myself)
		AreaCheck("AR5500")
		!Global("XA_AmkethranTimerSet", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_AmkethranTimer", "GLOBAL", ONE_ROUND)
			SetGlobal("XA_AmkethranTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	
	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		GlobalTimerExpired("XA_AmkethranTimer", "GLOBAL")
		GlobalLT("XA_MessageToBG", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			PlaySong(142)
			SetGlobal("XA_MessageToBG", "GLOBAL", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Aerie Pregnant Check
	IF
		GlobalGT("babytalk", "GLOBAL", 0)
		IsValidForPartyDialog("Aerie")
		!Global("XA_CorwinAerieBabyTimerSet", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinAerieBabyTimerSet", "GLOBAL", 1)
			SetGlobalTimer("XA_CorwinAerieBabyTimer", "GLOBAL", ONE_DAY)
			SetInterrupt(TRUE)
			Continue()
	END	
	//}
	
	//{ Left BG Romance Check
	IF
		Global("XA_ReturnToBG", "GLOBAL", 2)
		GlobalLT("XA_CheckInRomanceLeftBG", "GLOBAL", 1)
		Gender(Player1, MALE)
	THEN
		RESPONSE #100
			SetGlobal("XA_CheckInRomanceLeftBG", "GLOBAL", 1)
			Continue()
	END
	
	IF
		Global("XA_CheckInRomanceLeftBG", "GLOBAL", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		GlobalGT("XA_CorwinOpinionOfPlayer", "GLOBAL", 3)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinPregnant", "GLOBAL", 1)
			SetGlobalTimer("XA_CorwinPregnantTimer", "GLOBAL", THIRTY_DAYS)
			SetGlobal("XA_CheckInRomanceLeftBG", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		Global("XA_CheckInRomanceLeftBG", "GLOBAL", 1)
		OR(2)
			!Global("XA_CorwinRomanceActive", "GLOBAL", 2)
			GlobalLT("XA_CorwinOpinionOfPlayer", "GLOBAL", 4)
	THEN
		RESPONSE #100
			SetGlobal("XA_CheckInRomanceLeftBG", "GLOBAL", 2)
			Continue()
	END
	//}
	
	//{ Entered Yaga-Shura Camp
	IF
		!Global("XA_YagaTimerSet", "GLOBAL", 1)
		AreaCheck("AR5203")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_YagaTimer", "GLOBAL", ONE_ROUND)
			SetGlobal("XA_YagaTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		AreaCheck("AR5203")
		Gender(Player1, MALE)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		GlobalLT("XA_PregnantOverride", "GLOBAL", 1)
		Global("XA_CheckInRomanceLeftBG", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_PregnantOverride", "GLOBAL", 1)
			Continue()
	END
	//}
	
	//{ Sarevok Joined Party
	IF
		InParty("Sarevok")
		InParty(Myself)
		GlobalLT("XA_CorwinComplainSarevok", "GLOBAL", 0)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinComplainSarevokTimer", "GLOBAL", ONE_HOUR)
			SetGlobal("XA_CorwinComplainSarevok", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
	
	//{ Keldorn Wife Reconciled
	IF 
		Global("LadyMaria","GLOBAL",5)
		!Global("XA_KeldornMaria", "GLOBAL", 1)
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		GlobalLT("XA_Banter_CorwinKeldornOpt1", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_Banter_CorwinKeldornOpt1", "GLOBAL", 1)
			SetGlobal("XA_KeldornMaria", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
	
	//{ Svir Gnome Hostilities
	IF
		InParty(Myself)
		Global("SvirHostile", "GLOBAL", 1)
		!Global("XA_CorwinHostile", "GLOBAL", 1)
		!Global("XA_LeftPartySvir", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinHostile", "GLOBAL", 1)
			SetGlobal("XA_LeftPartySvir", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Met with Drizzt - Corwin vouched
	IF 
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		GlobalTimerExpired("XA_CorwinVouchedDrizzTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinVouchedDrizz", "GLOBAL", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Grove Poisoning
	IF
		InParty(Myself)
		Global("GrovePoisoned", "GLOBAL", 1)
		!Global("XA_CorwinHostile", "GLOBAL", 1)
		!Global("XA_LeftPartyGrove", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinHostle", "GLOBAL", 1)
			SetGlobal("XA_LeftPartyGrove", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Resurrection Gorge
	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("OHD_ritual_interjects","GLOBAL",0)
		!InParty("dorn")  // Dorn
		AreaCheck("oh5120")  // Dorn - Resurrection Gorge Tree Interior
		OR(2)
			Dead("ohdvern")  // Vernus
			!Exists("ohdvern")  // Vernus
		Range("RituaXAircle",20)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("OHD_ritual_interjects","GLOBAL",1)
			StartDialog("XACORWIJ",Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Slaver Stockade
	IF 
		Global("XA_BGSlaverPlot", "GLOBAL", 1)
		Global("XA_CorwinSlaverPlot", "GLOBAL", 1)
		AreaCheck("AR0405")
		!InMyArea("girl2")
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	THEN
		RESPONSE #100
			StartDialog("XACORWIJ", Player1)
	END
	//}

	//{ Player's Soul Stolen
	IF 
		Global("OpenJonBedroom","GLOBAL",1)
		!Global("XA_PlayerSoulStolen", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_PlayerSoulStolen", "GLOBAL", 1)
			SetGlobal("XA_PlayerSoulTalk", "GLOBAL", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Bodhi Killed
	/* Checks if Corwin was in the party when Bodhi was killed */
	IF 
		Global("BodhiDead","GLOBAL",1)
		IsValidForPartyDialogue("XACORWIN")
		!Global("XA_BodhiDead", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinImoenSoulTimer", "GLOBAL", ONE_HOUR)
			SetGlobal("XA_BodhiDead", "GLOBAL", 1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Phaere Alone With Player
	/* Checks if Corwin was in the party when the Player was alone with Phaere. */
	IF 
		GlobalGT("PhaereInnuendo","GLOBAL",1)
		!Global("XA_AloneWithPhaere", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AloneWithPhaere", "GLOBAL", 1)
			SetGlobal("XA_PhaereTalk", "GLOBAL", 1)
			PlaySong(142)
			StartDialogue("XACORWIJ", PLAYER1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Firkraag Deal
	/* Checks if Corwin was in the party when the deal with Firkraag was made. */
	IF 
		Global("FirkraagDeal","GLOBAL",1)
		!Global("XA_FirkraagDeal", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_FirkraagDeal", "GLOBAL", 1)
			SetGlobal("XA_CorwinFirkraagDeal", "GLOBAL", 1)
			//Dialog J-35
			StartDialogue("XACORWIJ", PLAYER1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Bodhi Job 2
	/* Checks if Corwin was in the party when the deal with Bodhi was made. Bodhi Job 2 */
	IF 
		Global("BodhiJob","GLOBAL",2)
		!Global("XA_BodhiDeal2", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_BodhiDeal2", "GLOBAL", 1)
			SetGlobal("XA_CorwinBodhiDeal", "GLOBAL", 1)
			StartDialogue("XACORWIJ", PLAYER1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Bodhi Job 3
	/* Checks if Corwin was in the party when the deal with Bodhi was made. Bodhi Job 3 */
	IF 
		Global("BodhiJob","GLOBAL",3)
		!Global("XA_BodhiDeal3", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_BodhiDeal3", "GLOBAL", 1)
			SetGlobal("XA_CorwinBodhiDeal", "GLOBAL", 1)
			StartDialogue("XACORWIJ", PLAYER1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Bodhi Job 4
	/* Checks if Corwin was in the party when the deal with Bodhi was made. Bodhi Job 4 */
	IF 
		Global("BodhiJob","GLOBAL",4)
		!Global("XA_BodhiDeal4", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_BodhiDeal4", "GLOBAL", 1)
			SetGlobal("XA_CorwinBodhiDeal", "GLOBAL", 1)
			StartDialogue("XACORWIJ", PLAYER1)
			SetInterrupt(TRUE)
	END
	//}

//} End Event Checks

//{ Corwin Turn Hostile
IF 
	InParty(Myself)
	Global("XA_CorwinHostile", "GLOBAL", 1)
THEN 
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinHostile", "GLOBAL", 2)
		DisplayStringHead(Myself, @11)
		SetLeavePartyDialogFile()
		ChangeAIScript("", DEFAULT)
		LeaveParty()
		Enemy()
		SetInterrupt(TRUE)
END
//}

//{ Corwin Sex Scripting

	//{ Checks is Corwin is Able
	IF
		!Global("XA_CorwinCanHaveSex", "GLOBAL", 1)
		!GlobalGT("XA_CorwinBit", "GLOBAL", 0)
		Gender(Player1, MALE)
		!HPPercentLT(Myself, 50)
		!HPPercentLT(Player1, 50)
		!Global("XA_RohmaKidnapped", "GLOBAL", 3)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		GlobalLT("XA_CorwinPregnant", "GLOBAL", 2)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinCanHaveSex", "GLOBAL", 1)
			Continue()
	END
	
	IF 
		Global("XA_CorwinCanHaveSex", "GLOBAL", 1)
		ActionListEmpty()
		OR(7)
			GlobalGT("XA_RohmaKidnapped", "GLOBAL", 0)
			GlobalGT("XA_CorwinBit", "GLOBAL", 0)
			!Gender(Player1, MALE)
			HPPercentLT(Myself, 50)
			HPPercentLT(Player1, 50)
			!Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
			GlobalGT("XA_CorwinPregnant", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinCanHaveSex", "GLOBAL", 0)
			Continue()
	END
	//}

	//{ Corwin Sex After Bodhi Experience
	/* If Corwin has not already had sex with CHARNAME, she will ask for sex after being healed / resurrected (Bodhi Bite) */
	IF 
		Global("XA_CorwinCleansed", "GLOBAL", 2) 
		GlobalLT("XA_TimesHadSex", "GLOBAL", 1)
		!Global("XA_CorwinSexAfterBodhiTimerSet", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinSexAfterBodhiTimer", "GLOBAL", ONE_DAY)
			SetGlobal("XA_CorwinSexAfterBodhiTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END

	IF 
		GlobalTimerExpired("XA_CorwinSexAfterBodhiTimer", "GLOBAL")
		GlobalLT("XA_TimesHadSex", "GLOBAL", 1)
		GlobalLT("XA_CorwinSexAfterBodhi", "GLOBAL", 1) //She has not asked for sex after Bodhi episode
		Global("XA_CorwinCanHaveSex", "GLOBAL", 1)
		ActionListEmpty()
	THEN 
		RESPONSE #100
			SetGlobal("XA_CorwinSexAfterBodhi", "GLOBAL", 1)
			Continue()
	END
		
	IF 
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_CorwinSexAfterBodhi", "GLOBAL", 1)
		Global("XA_CorwinCanHaveSex", "GLOBAL", 1)
		!Range(Player1, 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject(Player1)
			Continue()
	END

	IF 
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_CorwinSexAfterBodhi", "GLOBAL", 1)
		Global("XA_CorwinCanHaveSex", "GLOBAL", 1)
		Range(Player1, 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			PlaySong(146)
			//Dialog J-51
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Corwin After Sex Interaction 1
	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_CorwinSex_1", "GLOBAL", 3)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			Wait(1)
			//Dialog J-44
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ After Sex Party Banter
	IF 
		GlobalTimerExpired("XA_CorwinSexNoSleep", "GLOBAL")
		!Global("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
			Continue()
	END

	IF
		Global("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		IsValidForPartyDialog("Aerie")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Aerie", StartDialog("AERIEJ", Player1))
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		IsValidForPartyDialog("Imoen2")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Imoen2", StartDialog("IMOEN2J", Player1))
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		IsValidForPartyDialog("Nalia")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Nalia", StartDialog("NALIAJ", Player1))
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		IsValidForPartyDialog("Neera")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Neera", StartDialog("NEERAJ", Player1))
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		IsValidForPartyDialog("Jaheira")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Jaheira", StartDialog("JAHEIRAJ", Player1))
			SetInterrupt(TRUE)
	END
	
	IF 
		Global("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinSexNoSleepComplain", "GLOBAL", 2)
			Continue()
	END
	//}

	//{ After Sex HP Boost
	IF 
		Global("XA_CorwinSexBoost", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSexBoost", "GLOBAL", 0)
			SetGlobalTimer("XA_CorwinSexTimer", "GLOBAL", THREE_DAYS)
			IncrementGlobal("XA_CorwinOpinionOfPlayer", "GLOBAL", 1)
			ApplySpellRES("bdrejuve","XACORWIN")
			ApplySpellRES("bdrejuve",Player1)
			ChangeStat("XACORWIN", MINHITPOINTS, 5, ADD)
			ChangeStat(Player1, MINHITPOINTS, 5, ADD)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Corwin Sex Second Time
	IF
		GlobalGT("XA_TimesHadSex", "GLOBAL", 0)
		Global("XA_CorwinSex_2", "GLOBAL", 0)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinSex_2_Timer", "GLOBAL", THREE_DAYS)
			SetGlobal("XA_CorwinSex_2", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		GlobalTimerExpired("XA_CorwinSex_2_Timer", "GLOBAL")
		Global("XA_CorwinSex_2", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		GlobalLT("XA_CorwinSex2_Init", "GLOBAL", 1)
		Global("XA_CorwinCanHaveSex", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSex2_Init", "GLOBAL", 1)
			PlaySong(146)
			//Dialog J-46
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

//} End Corwin Sex Scripting

//{ Corwin Bite Disease Interactions

	//{ First Bit
	IF 
		Global("XA_CorwinBit", "GLOBAL", 1)
		CombatCounter(0)
		IsValidForPartyDialog(Player1)
	THEN
		RESPONSE #100
			//DisplayStringHead(Myself, ~DEBUG_018~)
			SetGlobal("XA_CorwinBit", "GLOBAL", 2)
			Continue()
	END

	IF 
		Global("XA_CorwinBit", "GLOBAL", 2)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		!Range(Player1, 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			//DisplayStringHead(Myself, ~DEBUG_019~)
			MoveToObject(Player1)
			Continue()
	END

	IF 
		Global("XA_CorwinBit", "GLOBAL", 2)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Range(Player1, 7)
	THEN
		RESPONSE #100
			//Dialog J-31
			StartDialog("XACORWIJ", Player1)
	END
	//}

	//{ Bite Death Warning 2
	IF 
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_CorwinBit", "GLOBAL", 3)
		GlobalTimerExpired("XA_CorwinBitTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinBit", "GLOBAL", 4)
			//Dialog J-32
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Bite Death Warning 3
	IF 
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_CorwinBit", "GLOBAL", 5)
		GlobalTimerExpired("XA_CorwinBitTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinBit", "GLOBAL", 6)
			//Dialog J-33
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Death from Bite
	IF 
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_CorwinBit", "GLOBAL", 7)
		GlobalTimerExpired("XA_CorwinBitTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinBit", "GLOBAL", 8)
			//Dialog J-34
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Reset Sounds to Original
	IF
		Global("XA_BiteSoundSet", "LOCALS", 1)
		Global("XA_CorwinBit", "GLOBAL", 0)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetPlayerSound(Myself,268296,MORALE)
			SetPlayerSound(Myself,268292,HAPPY)
			SetPlayerSound(Myself,268293,UNHAPPY_ANNOYED)
			SetPlayerSound(Myself,268294,UNHAPPY_SERIOUS)
			SetPlayerSound(Myself,268295,UNHAPPY_BREAKING_POINT)
			SetPlayerSound(Myself,268256,LEADER)
			SetPlayerSound(Myself,268257,TIRED)
			SetPlayerSound(Myself,268258,BORED)
			SetPlayerSound(Myself,268251,BATTLE_CRY1)
			SetPlayerSound(Myself,268252,BATTLE_CRY2)
			SetPlayerSound(Myself,268253,BATTLE_CRY3)
			SetPlayerSound(Myself,268254,BATTLE_CRY4)
			SetPlayerSound(Myself,268255,BATTLE_CRY5)
			SetPlayerSound(Myself,268273,DAMAGE)
			SetPlayerSound(Myself,268274,DYING)
			SetPlayerSound(Myself,268259,HURT)
			SetPlayerSound(Myself,268275,AREA_FOREST)
			SetPlayerSound(Myself,268276,AREA_CITY)
			SetPlayerSound(Myself,268277,AREA_DUNGEON)
			SetPlayerSound(Myself,268278,AREA_DAY)
			SetPlayerSound(Myself,268279,AREA_NIGHT)
			SetPlayerSound(Myself,268260,SELECT_COMMON1)
			SetPlayerSound(Myself,268261,SELECT_COMMON2)
			SetPlayerSound(Myself,268262,SELECT_COMMON3)
			SetPlayerSound(Myself,268263,SELECT_COMMON4)
			SetPlayerSound(Myself,268264,SELECT_COMMON5)
			SetPlayerSound(Myself,268265,SELECT_COMMON6)
			SetPlayerSound(Myself,268266,SELECT_ACTION1)
			SetPlayerSound(Myself,268267,SELECT_ACTION2)
			SetPlayerSound(Myself,268268,SELECT_ACTION3)
			SetPlayerSound(Myself,268280,SELECT_ACTION4)
			SetPlayerSound(Myself,268281,SELECT_ACTION5)
			SetPlayerSound(Myself,@9,SELECT_ACTION6) 
			SetPlayerSound(Myself,268283,SELECT_ACTION7)
			SetPlayerSound(Myself,268297,REACT_TO_DIE_GENERAL)
			SetPlayerSound(Myself,268298,REACT_TO_DIE_SPECIFIC)
			SetPlayerSound(Myself,268280,SELECT_RARE1)
			SetPlayerSound(Myself,268281,SELECT_RARE2)
			SetPlayerSound(Myself,268284,CRITICAL_HIT)
			SetPlayerSound(Myself,268285,CRITICAL_MISS)
			SetPlayerSound(Myself,268286,TARGET_IMMUNE)
			SetPlayerSound(Myself,268287,INVENTORY_FULL)
			SetPlayerSound(Myself,268288,PICKED_POCKET)
			SetPlayerSound(Myself,268289,HIDDEN_IN_SHADOWS)
			SetPlayerSound(Myself,268290,SPELL_DISRUPTED)
			SetPlayerSound(Myself,268291,SET_A_TRAP)
			SetGlobal("XA_BiteSoundSet", "LOCALS", 0)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Set Sickness Sounds

	IF
		GlobalGT("XA_CorwinBit", "GLOBAL", 2)
		!Global("XA_BiteSoundSet", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetPlayerSound(Myself,@12,MORALE)
			SetPlayerSound(Myself,@13,HAPPY)
			SetPlayerSound(Myself,@14,UNHAPPY_ANNOYED)
			SetPlayerSound(Myself,@12,UNHAPPY_SERIOUS)
			SetPlayerSound(Myself,@13,UNHAPPY_BREAKING_POINT)
			SetPlayerSound(Myself,@14,LEADER)
			SetPlayerSound(Myself,@12,TIRED)
			SetPlayerSound(Myself,@13,BORED)
			SetPlayerSound(Myself,@14,BATTLE_CRY1)
			SetPlayerSound(Myself,@12,BATTLE_CRY2)
			SetPlayerSound(Myself,@13,BATTLE_CRY3)
			SetPlayerSound(Myself,@14,BATTLE_CRY4)
			SetPlayerSound(Myself,@12,BATTLE_CRY5)
			SetPlayerSound(Myself,268273,DAMAGE)
			SetPlayerSound(Myself,268274,DYING)
			SetPlayerSound(Myself,@13,HURT)
			SetPlayerSound(Myself,@14,AREA_FOREST)
			SetPlayerSound(Myself,@12,AREA_CITY)
			SetPlayerSound(Myself,@13,AREA_DUNGEON)
			SetPlayerSound(Myself,@14,AREA_DAY)
			SetPlayerSound(Myself,@12,AREA_NIGHT)
			SetPlayerSound(Myself,@13,SELECT_COMMON1)
			SetPlayerSound(Myself,@14,SELECT_COMMON2)
			SetPlayerSound(Myself,@12,SELECT_COMMON3)
			SetPlayerSound(Myself,@13,SELECT_COMMON4)
			SetPlayerSound(Myself,@14,SELECT_COMMON5)
			SetPlayerSound(Myself,@12,SELECT_COMMON6)
			SetPlayerSound(Myself,@13,SELECT_ACTION1)
			SetPlayerSound(Myself,@14,SELECT_ACTION2)
			SetPlayerSound(Myself,@12,SELECT_ACTION3)
			SetPlayerSound(Myself,@13,SELECT_ACTION4)
			SetPlayerSound(Myself,@14,SELECT_ACTION5)
			SetPlayerSound(Myself,@12,SELECT_ACTION6) 
			SetPlayerSound(Myself,@13,SELECT_ACTION7)
			SetPlayerSound(Myself,@14,REACT_TO_DIE_GENERAL)
			SetPlayerSound(Myself,@12,REACT_TO_DIE_SPECIFIC)
			SetPlayerSound(Myself,@13,SELECT_RARE1)
			SetPlayerSound(Myself,@14,SELECT_RARE2)
			SetPlayerSound(Myself,@12,CRITICAL_HIT)
			SetPlayerSound(Myself,@13,CRITICAL_MISS)
			SetPlayerSound(Myself,@14,TARGET_IMMUNE)
			SetPlayerSound(Myself,@14,INVENTORY_FULL)
			SetPlayerSound(Myself,@12,PICKED_POCKET)
			SetPlayerSound(Myself,@13,SPELL_DISRUPTED)
			SetPlayerSound(Myself,@14,SET_A_TRAP)
			SetGlobal("XA_BiteSoundSet", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Corwin Resurrected At Shadow Temple
	IF 
		!InParty(Myself)
		Global("XA_CorwinCleansed", "GLOBAL", 1)
		GlobalGT("XA_CorwinBit", "GLOBAL", 0)
		See(Player1)
	THEN
		RESPONSE #100
			//Dialog P-6
			StartDialogNoSet(Player1)
	END
	//}

	//{ Corwin Bit - Apply Disease
	/* Corwin Bite Disease */
	/* This will reapply the disease while CorwinBit is greater than 0. CorwinBit is set to zero when Corwin is cleansed (or resurrected in the Shadow Temple). */

	IF 
		GlobalGT("XA_CorwinBit", "GLOBAL", 0)
		!CheckSpellState(Myself, DISEASED)
	THEN 
		RESPONSE #100
			//DisplayStringHead(Myself, ~DEBUG_016~)
			ForceSpellRES("bdisease",Myself)
			Continue()
	END
	//}

	//{ Corwin Cured from Bodhi Disease
	/* Corwin Disease Cured */
	// Might need to re-write this. Concerned that if the script is interrupted, stat gains could erroneously continue
	IF 
		Global("XA_CorwinCleansed", "GLOBAL", 2)
		!Global("XA_CorwinCured", "GLOBAL", 1)
	THEN 
		RESPONSE #100
			//ForceSpell("XACORWIN",CLERIC_CURE_DISEASE)
			//DisplayStringHead(Myself, ~DEBUG_017~)
			SetInterrupt(FALSE)
			ChangeStat(Myself,CON,1,ADD)
			ChangeStat(Myself,DEX,1,ADD)
			ChangeStat(Myself,STR,1,ADD)
			ChangeStat(Myself,CHR,1,ADD)
			SetGlobal("XA_CorwinCured", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END

	//}

	//{ Corwin Healed with Bodhi's Death
	/* This handles Bodhi's death when Corwin was bit, is still alive, and in the party. */
	IF
		InParty(Myself)
		GlobalGT("XA_CorwinBit", "GLOBAL", 0)
		Global("BodhiDead","GLOBAL",1)
		CombatCounter(0)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ClearAllActions()
			StartCutSceneMode()
			StartCutSceneEx("XAAcs09a", FALSE)
			SetInterrupt(TRUE)
	END
	//}

	//{ Party Concerned Corwin Sick
	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		GlobalGT("XA_CorwinBit", "GLOBAL", 0)
		GlobalTimerExpired("XA_CorwinSickPartyTimer", "GLOBAL")
		!Global("XA_CorwinPartySick", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinPartySick", "GLOBAL", 1)
			Continue()
	END
	
	IF
		Global("XA_CorwinPartySick", "GLOBAL", 1)
		IsValidForPartyDialogue("Jaheira")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSick_Jaheira", "GLOBAL", 1)
			//Dialog B-6
			ActionOverride("JAHEIRA", StartDialog("JAHEIRAJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CorwinPartySick", "GLOBAL", 1)
		IsValidForPartyDialogue("Aerie")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSick_Aerie", "GLOBAL", 1)
			//Dialog B-5
			ActionOverride("AERIE", StartDialog("AERIEJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END

	IF
		Global("XA_CorwinPartySick", "GLOBAL", 1)
		IsValidForPartyDialogue("Korgan")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSick_Korgan", "GLOBAL", 1)
			//Dialog B-7
			ActionOverride("KORGAN", StartDialog("KORGANJ", Player1))
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CorwinPartySick", "GLOBAL", 1)
		IsValidForPartyDialogue("Imoen2")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSick_Imoen", "GLOBAL", 1)
			//Dialog B-8
			ActionOverride("IMOEN2", StartDialog("IMOEN2J", "XACORWIN"))
			SetInterrupt(TRUE)
	END

	IF
		Global("XA_CorwinPartySick", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinPartySick", "GLOBAL", 2)
			Continue()
	END
	//}

//} End Corwin Disease Interactions

//{ Banter Initialization
/* Initialize Banters */

IF
	InParty(Myself)
	!Global("XA_BanterCountInit", "GLOBAL", 1)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself, ~DEBUG_025~)
		SetInterrupt(FALSE)
		SetGlobal("XA_BanterCountInit", "GLOBAL", 1)
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0) 
		SetGlobal("XA_Banter_CorwinAerie", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinAnomen", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinCernd", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinDorn", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinEdwin", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinHexxat", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinImoen", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinJaheira", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinJan", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinKeldorn", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinKorgan", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinNeera", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinPlayer", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinRasaad", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinValygar", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinViconia", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinYoshimo", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinMinsc", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinHaerDalis", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinNalia", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinMazzy", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinBanter", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinSarevok", "GLOBAL", 1)
		SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
		SetInterrupt(TRUE)
		Continue()
END

IF 
	InParty(Myself)
	Global("XA_ResetBanterTimer", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinMeetCC", "GLOBAL", 0)
		SetGlobal("XA_ResetBanterTimer", "GLOBAL", 0)
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0) 
		SetGlobalTimer("XA_CorwinBanter", "GLOBAL", ONE_DAY)
		SetInterrupt(TRUE)
		Continue()
END

IF
	InParty(Myself)
	GlobalTimerExpired("XA_CorwinBanter", "GLOBAL")	
	AreaType(DUNGEON)
THEN
	RESPONSE #100
		//DisplayStringHead(Myself, ~DEBUG_027~)
		SetGlobalTimer("XA_CorwinBanter", "GLOBAL", FORTY_MINUTES)
		Continue()
	RESPONSE #100
		//DisplayStringHead(Myself, ~DEBUG_028~)
		SetGlobalTimer("XA_CorwinBanter", "GLOBAL", THIRTY_MINUTES)
		Continue()
	RESPONSE #100
		//DisplayStringHead(Myself, ~DEBUG_029~)
		SetGlobalTimer("XA_CorwinBanter", "GLOBAL", TWENTY_MINUTES)
		Continue()
	RESPONSE #100
		//DisplayStringHead(Myself, ~DEBUG_030~)
		SetGlobalTimer("XA_CorwinBanter", "GLOBAL", TEN_MINUTES)
		Continue()
END
//} End Banter Initialization

//{ Banter Randomizer

/* Randomizes the next banter interaction */
IF
	InParty(Myself)
	Global("XA_BanterCountInit", "GLOBAL", 1)
	Global("XA_Banter_NextInteraction", "GLOBAL", 0)
	GlobalTimerExpired("XA_CorwinBanter", "GLOBAL")	
	GlobalLT("XA_CorwinBit", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 1) /* Aerie */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 2) /* Anomen */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 3) /* Dorn */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 4) /* Edwin */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 5) /* Imoen */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 6) /* Hexxat */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 7) /* Jaheira */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 8) /* Jan */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 9) /* Keldorn */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 10) /* Korgan */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 11) /* Neera */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 12) /* Player */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 13) /* Viconia */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 14) /* Valygar */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 15) /* Cernd */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 16) /* Yoshimo */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 17) /* Rasaad */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 18) /* Minsc */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 19) /* Haer Dalis */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 20) /* Nalia */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 21) /* Mazzy */
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 22) /* Sarevok */
		Continue()
END
//}

//{ Banter Reset to 0 is Subject is Unavailable
/* If the next subject of interaction is not valid, set the next subject to 0, which will re-run the randomizer the next time the script executes */
IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 1) /* Aerie */
	OR(2)
		!IfValidForPartyDialog("Aerie")
		!See("Aerie")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 2) /* Anomen */
	OR(2)
		!IfValidForPartyDialog("Anomen")
		!See("Anomen")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 3) /* Dorn */
	OR(2)
		!IfValidForPartyDialog("Dorn")
		!See("Dorn")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 4) /* Edwin */
	OR(2)
		!IfValidForPartyDialog("Edwin")
		!See("Edwin")
THEN
	RESPONSE #100	
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 5) /* Imoen2 */
	OR(2)
		!IfValidForPartyDialog("Imoen2")
		!See("Imoen2")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 6) /* Hexxat */
	OR(2)
		!IfValidForPartyDialog("Hexxat")
		!See("Hexxat")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 7) /* Jaheira */
	OR(2)
		!IfValidForPartyDialog("Jaheira")
		!See("Jaheira")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 8) /* Jan */
	OR(2)
		!IfValidForPartyDialog("Jan")
		!See("Jan")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 9) /* Keldorn */
	OR(2)
		!IfValidForPartyDialog("Keldorn")
		!See("Keldorn")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 10) /* Korgan */
	OR(2)
		!IfValidForPartyDialog("Korgan")
		!See("Korgan")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 11) /* Neera */
	OR(2)
		!IfValidForPartyDialog("Neera")
		!See("Neera")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 12) /* Player */
	OR(2)
		!IfValidForPartyDialog(Player1)
		!See(Player1)
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 13) /* Viconia */
	OR(2)
		!IfValidForPartyDialog("Viconia")
		!See("Viconia")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 14) /* Valygar */
	OR(2)
		!IfValidForPartyDialog("Valygar")
		!See("Valygar")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 15) /* Cernd */
	OR(2)
		!IfValidForPartyDialog("Cernd")
		!See("Cernd")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 16) /* Yoshimo */
	OR(2)
		!IfValidForPartyDialog("Yoshimo")
		!See("Yoshimo")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 17) /* Rasaad */
	OR(2)
		!IfValidForPartyDialog("Rasaad")
		!See("Rasaad")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 18) /* Minsc */
	OR(2)
		!IfValidForPartyDialog("Minsc")
		!See("Minsc")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 19) /* Haer Dalis */
	OR(2)
		!IfValidForPartyDialog("Haerdalis")
		!See("Haerdalis")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 20) /* Nalia */
	OR(2)
		!IfValidForPartyDialog("Nalia")
		!See("Nalia")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 21) /* Mazzy */
	OR(2)
		!IfValidForPartyDialog("Mazzy")
		!See("Mazzy")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

IF
	Global("XA_Banter_NextInteraction", "GLOBAL", 22) /* Sarevok */
	OR(2)
		!IfValidForPartyDialog("Sarevok")
		!See("Sarevok")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END
//} End Banter Resets

//{ Neb Killed While Corwin in Party 
IF
	Global("XA_NebFight", "GLOBAL", 1)
	Dead("Neb")
	Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_NebDead", "GLOBAL", 1)
		StartDialog("XACORWIJ", Player1)
		SetInterrupt(TRUE)
END
//}

//{ Mazzy Interactions

	//{ Mazzy First Interaction 

	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 21) /* Mazzy */
		Global("XA_Banter_CorwinMazzy", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinMazzy", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IfValidForPartyDialog("Mazzy")
		Global("XA_Banter_CorwinMazzy", "GLOBAL", 2)
		!Range("Mazzy", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Mazzy", MoveToObject("XACORWIN"))
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IfValidForPartyDialog("Mazzy")
		Global("XA_Banter_CorwinMazzy", "GLOBAL", 2)
		Range("Mazzy", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Mazzy")
			//Dialogs B-9, B-10
			Interact("Mazzy")
			SetInterrupt(TRUE)
	END
	//}

	//{ Mazzy Second Interaction 

	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 21) /* Mazzy */
		Global("XA_Banter_CorwinMazzy", "GLOBAL", 3)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinMazzy", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IfValidForPartyDialog("Mazzy")
		IfValidForPartyDialog(Player1)
		Global("XA_Banter_CorwinMazzy", "GLOBAL", 4)
		!Range("Mazzy", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Mazzy")
			Continue()
	END

	IF
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IfValidForPartyDialog("Mazzy")
		IfValidForPartyDialog(Player1)
		Global("XA_Banter_CorwinMazzy", "GLOBAL", 4)
		Range("Mazzy", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Mazzy")
			//Dialog B-4
			StartDialog("XACORWIB", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Trademeet Archery Competition Ended - Corwin Won 
	IF 
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		IfValidForPartyDialog("Mazzy")
		Global("XA_TM_ArcheryChallenge", "GLOBAL", 2)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		See("Mazzy")
	THEN
		RESPONSE #100
			//Dialog B-3A
			ActionOverride("Mazzy", StartDialog("MAZZYJ", Player1))
	END
	//}

	//{ Trademeet Archery Competition Ended - Mazzy Won
	IF 
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		IfValidForPartyDialog("Mazzy")
		Global("XA_TM_ArcheryChallenge", "GLOBAL", 2)
		!Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		See("Mazzy")
	THEN
		RESPONSE #100
			//Dialog B-3B
			StartDialog("XACORWIB", Player1)
	END
	//}

//} End Mazzy Interactions

//{ Nalia Interactions

	//{ Nalia First Interaction
	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 20) /* Nalia */
		Global("XA_Banter_CorwinNalia", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinNalia", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IfValidForPartyDialog("Nalia")
		Global("XA_Banter_CorwinNalia", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Nalia")
			//Dialog B-11, B-12
			Interact("Nalia")
			SetInterrupt(TRUE)
	END
	//}

	//{ Nalia Second Interaction
	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 20) /* Nalia */
		Global("XA_Banter_CorwinNalia", "GLOBAL", 3)
		CombatCounter(0)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinNalia", "GLOBAL", 4)
			DisplayStringHead("Nalia", @6) /*~Captain, do you have a moment?~ */
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IfValidForPartyDialog("Nalia")
		Global("XA_Banter_CorwinNalia", "GLOBAL", 4)
		!Range("Nalia", 6)
	THEN
		RESPONSE #100
			ActionOverride("Nalia", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IfValidForPartyDialog("Nalia")
		Global("XA_Banter_CorwinNalia", "GLOBAL", 4)
		Range("Nalia", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Nalia")
			//Dialog B-13
			Interact("Nalia")
			SetInterrupt(TRUE)
	END
	//}

	//{ Nalia Third Interaction
	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 20) /* Nalia */
		Global("XA_Banter_CorwinNalia", "GLOBAL", 5)
		CombatCounter(0)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinNalia", "GLOBAL", 6)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IfValidForPartyDialog("Nalia")
		Global("XA_Banter_CorwinNalia", "GLOBAL", 6)
		!Range("Nalia", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Nalia", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IfValidForPartyDialog("Nalia")
		Global("XA_Banter_CorwinNalia", "GLOBAL", 6)
		Range("Nalia", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Nalia")
			//Dialogs B-14, B-15
			Interact("Nalia")
			SetInterrupt(TRUE)
	END
	//}

//} End Nalia Interactions

//{ HaerDalis Interactions

	//{ HaerDalis First Interaction
	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 19) /* HaerDalis */
		Global("XA_Banter_CorwinHaerDalis", "GLOBAL", 1)
		CombatCounter(0)
		ActionListEmpty()
	THEN
		RESPONSE #100
			//DisplayStringHead(Myself, ~DEBUG_090~)
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinHaerDalis", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IfValidForPartyDialog("HaerDalis")
		Global("XA_Banter_CorwinHaerDalis", "GLOBAL", 2)
		!Range("HaerDalis", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("HaerDalis", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("HaerDalis")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinHaerDalis", "GLOBAL", 2)
		Range("HaerDalis", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("HaerDalis")
			//Dialog B-16
			ActionOverride("HaerDalis", StartDialog("HAERDAJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

	//{ HaerDalis Second Interaction
	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 19) /* HaerDalis */
		Global("XA_Banter_CorwinHaerDalis", "GLOBAL", 3)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinHaerDalis", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("HaerDalis")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinHaerDalis", "GLOBAL", 4)
		!Range("HaerDalis", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("HaerDalis", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("HaerDalis")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinHaerDalis", "GLOBAL", 4)
		Range("HaerDalis", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("HaerDalis")
			//Dialog B-18, B-19, B-20, B-21
			Interact("HaerDalis")
			SetInterrupt(TRUE)
	END
	//}
//} End HaerDalis Interactions

//{ Minsc Interactions

	//{ Minsc First Interaction

	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 18) /* Minsc */
		Global("XA_Banter_CorwinMinsc", "GLOBAL", 1)
		CombatCounter(0)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinMinsc", "GLOBAL", 2)
			DisplayStringHead("Minsc",@3)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Minsc")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinMinsc", "GLOBAL", 2)
		!Range("Minsc", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Minsc")
			Continue()
	END

	IF
		IfValidForPartyDialog("Minsc")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinMinsc", "GLOBAL", 2)
		Range("Minsc", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Minsc")
			//Dialogs B-2, B-22
			Interact("Minsc")
			SetInterrupt(TRUE)
	END
	//}

	//{ Minsc Second Interaction

	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 18) /* Minsc */
		Global("XA_Banter_CorwinMinsc", "GLOBAL", 3)
		ActionListEmpty()
	THEN
		RESPONSE #100
			//DisplayStringHead(Myself, ~DEBUG_099~)
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinMinsc", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Minsc")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinMinsc", "GLOBAL", 4)
		!Range("Minsc", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Minsc", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Minsc")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinMinsc", "GLOBAL", 4)
		Range("Minsc", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Minsc")
			//Dialog B-23
			Interact("Minsc")
			SetInterrupt(TRUE)
	END
	//}

	//{ Minsc Third Interaction

	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 18) /* Minsc */
		Global("XA_Banter_CorwinMinsc", "GLOBAL", 5)
		CombatCounter(0)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinMinsc", "GLOBAL", 6)
			DisplayStringHead(Myself, @4) /* ~Minsc! Come here!~ */
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Minsc")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinMinsc", "GLOBAL", 6)
		!Range("Minsc", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Minsc", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Minsc")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinMinsc", "GLOBAL", 6)
		Range("Minsc", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ClearActions("Minsc")
			FaceObject("Minsc")
			//Dialog B-24
			Interact("Minsc")
			SetInterrupt(TRUE)
	END
	//}

//} End Minsc Interactions

//{ Rasaad Interactions

	//{ Rasaad First Interaction

	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 17) /* Rasaad */
		Global("XA_Banter_CorwinRasaad", "GLOBAL", 1)
		CombatCounter(0)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinRasaad", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Rasaad")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinRasaad", "GLOBAL", 2)
		!Range("Rasaad", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Rasaad", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Rasaad")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinRasaad", "GLOBAL", 2)
		Range("Rasaad", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Rasaad")
			//Dialogs B-25, B-26
			ActionOverride("Rasaad", StartDialog("RASAADJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

	//{ Rasaad Second Interaction

	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 17) /* Rasaad */
		Global("XA_Banter_CorwinRasaad", "GLOBAL", 3)
		ActionListEmpty()
	THEN
		RESPONSE #100
			//DisplayStringHead(Myself, ~DEBUG_108~)
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinRasaad", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Rasaad")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinRasaad", "GLOBAL", 4)
		!Range("Rasaad", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Rasaad")
			Continue()
	END

	IF
		IfValidForPartyDialog("Rasaad")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinRasaad", "GLOBAL", 4)
		Range("Rasaad", 7)
	THEN
		RESPONSE #100
			//Dialog B-27
			Interact("Rasaad")
	END
	//}

	//{ Rasaad Third Interaction

	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 17) /* Rasaad */
		Global("XA_Banter_CorwinRasaad", "GLOBAL", 5)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinRasaad", "GLOBAL", 6)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Rasaad")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinRasaad", "GLOBAL", 6)
		!Range("Rasaad", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Rasaad")
			Continue()
	END

	IF
		IfValidForPartyDialog("Rasaad")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinRasaad", "GLOBAL", 6)
		Range("Rasaad", 7)
	THEN
		RESPONSE #100
			//Dialog B-28
			Interact("Rasaad")
	END
	//}

	//{ Rasaad Fourth Interaction

	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 17) /* Rasaad */
		Global("XA_Banter_CorwinRasaad", "GLOBAL", 7)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinRasaad", "GLOBAL", 8)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Rasaad")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinRasaad", "GLOBAL", 8)
		!Range("Rasaad", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Rasaad")
			Continue()
	END

	IF
		IfValidForPartyDialog("Rasaad")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinRasaad", "GLOBAL", 8)
		Range("Rasaad", 7)
	THEN
		RESPONSE #100
			//Dialogs B-29, B-30, B-31, B-32, B-33
			Interact("Rasaad")
	END
	//}

//} End Rasaad Interactions

//{ Yoshimo Interactions

	//{ Yoshimo First Interaction

	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 16) /* Yoshimo */
		Global("XA_Banter_CorwinYoshimo", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinYoshimo", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Yoshimo")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinYoshimo", "GLOBAL", 2)
		!Range("Yoshimo", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Yoshimo", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Yoshimo")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinYoshimo", "GLOBAL", 2)
		Range("Yoshimo", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Yoshimo")
			//Dialog B-34
			Interact("Yoshimo")
			SetInterrupt(TRUE)
	END
	//}

//} End Yoshimo Interactions

//{ Cernd Interactions

	//{ Cernd First Interaction
	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 15) /* Cernd */
		Global("XA_Banter_CorwinCernd", "GLOBAL", 1)
		Global("CerndBaby","GLOBAL",1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinCernd", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Cernd")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinCernd", "GLOBAL", 2)
		!Range("Cernd", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Cernd")
			Continue()
	END

	IF
		IfValidForPartyDialog("Cernd")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinCernd", "GLOBAL", 2)
		Range("Cernd", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Cernd", FaceObject("XACORWIN"))
			//Dialog B-35
			Interact("Cernd")
			SetInterrupt(TRUE)
	END
	//}

//} End Cernd Interactions

//{ Valygar Interactions

	//{ Valygar First Interaction 

	IF 
		Global("XA_Banter_NextInteraction", "GLOBAL", 14) /* Valygar */
		Global("XA_Banter_CorwinValygar", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinValygar", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Valygar")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinValygar", "GLOBAL", 2)
		!Range("Valygar", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Valygar")
			Continue()
	END

	IF
		IfValidForPartyDialog("Valygar")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinValygar", "GLOBAL", 2)
		Range("Valygar", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Valygar", FaceObject("XACORWIN"))
			//Dialogs B-37, B-38
			Interact("Valygar")
			SetInterrupt(TRUE)
	END
	//}

	//{ Valygar Second Interaction
	IF
		Global("LavokDead", "GLOBAL", 1)
		!Global("XA_CorwinLavokTimerSet", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinLavokTimer", "GLOBAL", ONE_HOUR)
			SetGlobal("XA_CorwinLavokTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END

	IF 
		IsValidForPartyDialog("Valygar")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		GlobalTimerExpired("XA_CorwinLavokTimer", "GLOBAL")
		GlobalLT("XA_CorwinValygarLavok", "GLOBAL", 1)
		GlobalLT("XA_ReturnToBG", "GLOBAL", 1)
		See("Valygar")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinValygarLavok", "GLOBAL", 1)
			//Dialog B-39
			Interact("Valygar")
			SetInterrupt(TRUE)
	END
	//}

	//{ Valygar Third Interaction
	IF
		GlobalTimerExpired("XA_CorwinValygarTimer", "GLOBAL")
		IsValidForPartyDialog("Valygar")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		GlobalLT("XA_ReturnToBG", "GLOBAL", 1)
		GlobalLT("XA_CorwinValygarBG", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinValygarBG", "GLOBAL", 1)
			Continue()
	END

	IF
		IsValidForPartyDialog("Valygar")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_CorwinValygarBG", "GLOBAL", 1)
		!Range("Valygar", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Valygar", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IsValidForPartyDialog("Valygar")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_CorwinValygarBG", "GLOBAL", 1)
		Range("Valygar", 7)
		See("Valygar")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinValygarBG", "GLOBAL", 1)
			//Dialog B-85
			ActionOverride("Valygar", StartDialog("VALYGARJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
		
	//}

//} End Valygar Interactions

//{ Hexxat Interactions

	//{ Hexxat - Corwin First Interaction 

	IF 
		InParty(Myself)
		IsValidForPartyDialogue("Hexxat")
		Global("XA_Banter_NextInteraction", "GLOBAL", 6) /* Hexxat */
		Global("XA_Banter_CorwinHexxat", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinHexxat", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_Banter_CorwinHexxat", "GLOBAL", 2)
		IsValidForPartyDialogue("Hexxat")
		!Range(Player1, 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject(Player1)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_Banter_CorwinHexxat", "GLOBAL", 2)
		IsValidForPartyDialogue("Hexxat")
		Range(Player1, 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride(Player1, FaceObject("XACORWIN"))
			//Dialog J-59
			StartDialogue("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Hexxat - Corwin Second Interaction 

	IF 
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 6) /* Hexxat */
		Global("XA_Banter_CorwinHexxat", "GLOBAL", 3)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinHexxat", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Hexxat")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinHexxat", "GLOBAL", 4)
		!Range("Hexxat", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Hexxat")
			Continue()
	END

	IF
		IfValidForPartyDialog("Hexxat")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinHexxat", "GLOBAL", 4)
		Range("Hexxat", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Hexxat", FaceObject("XACORWIN"))
			//Dialog B-42
			Interact("Hexxat")
			SetInterrupt(TRUE)
	END
	//}

	//{ Hexxat - Corwin Third Interaction 
	IF 
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 6) /* Hexxat */
		Global("XA_Banter_CorwinHexxat", "GLOBAL", 5)
		ActionListEmpty()
	THEN
		RESPONSE #100
			//DisplayStringHead(Myself, ~DEBUG_132~)
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinHexxat", "GLOBAL", 6)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Hexxat")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinHexxat", "GLOBAL", 6)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Hexxat", FaceObject("XACORWIN"))
			//Dialog J-57, Dialog J-58
			StartDialogue("XACORWIJ","Hexxat")
			SetInterrupt(TRUE)
	END
	//}

	//{ Hexxat Corwin Fight
	IF 
		InParty(Myself)
		IfValidForPartyDialog("Hexxat")
		Global("XA_CorwinHexxatFight", "GLOBAL", 1)
	THEN
		RESPONSE #100
			//DisplayStringHead(Myself, ~DEBUG_135~)
			SetInterrupt(FALSE)
			LeaveParty()
			SetLeavePartyDialogFile()
			ChangeAIScript("",DEFAULT)
			ChangeAIScript("",OVERRIDE)
			ChangeAIScript("XACORHEX",SPECIFICS)
			
			ActionOverride("Hexxat", LeaveParty())
			ActionOverride("Hexxat", SetLeavePartyDialogFile())
			ActionOverride("Hexxat", ChangeAIScript("",DEFAULT))
			ActionOverride("Hexxat", ChangeAIScript("useitem",GENERAL))
			ActionOverride("Hexxat", ChangeAIScript("XAHEXCOR",SPECIFICS))
			
			SetInterrupt(TRUE)
	END
	//}

//} End Hexxat Interaction

//{ Jaheira Interactions

	//{ Jaheira - Corwin First Interaction 

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 7)
		Global("XA_Banter_CorwinJaheira", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinJaheira", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Jaheira")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinJaheira", "GLOBAL", 2)
		!Range("Jaheira", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Jaheira")
			Continue()
	END

	IF
		IfValidForPartyDialog("Jaheira")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinJaheira", "GLOBAL", 2)
		Range("Jaheira", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Jaheira", FaceObject("XACORWIN"))
			//Dialogs B-68, B-69
			Interact("Jaheira")
			SetInterrupt(TRUE)
	END
	//}

	//{ Jaheira - Corwin Second Interaction

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 7)
		Global("XA_Banter_CorwinJaheira", "GLOBAL", 3)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinJaheira", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF 
		IfValidForPartyDialog("Jaheira")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinJaheira", "GLOBAL", 4)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself, @1)
			SetGlobal("XA_Banter_CorwinJaheira", "GLOBAL", 5)
			SetInterrupt(TRUE)
			Continue()
	END 

	IF
		IfValidForPartyDialog("Jaheira")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinJaheira", "GLOBAL", 5)
		!Range("Jaheira", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Jaheira", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Jaheira")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinJaheira", "GLOBAL", 5)
		Range("Jaheira", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Jaheira")
			//Dialog B-70
			Interact("Jaheira")
			SetInterrupt(TRUE)
	END
	//}

	//{ Jaheira - Corwin Third Interaction
	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 7)
		Global("XA_Banter_CorwinJaheira", "GLOBAL", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinJaheira", "GLOBAL", 7)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Jaheira")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinJaheira", "GLOBAL", 7)
		!Range("Jaheira", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Jaheira")
			Continue()
	END

	IF
		IfValidForPartyDialog("Jaheira")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinJaheira", "GLOBAL", 7)
		Range("Jaheira", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Jaheira", FaceObject("XACORWIN"))
			//Dialog B-71
			Interact("Jaheira")
			SetInterrupt(TRUE)
	END
	//}

//} End Jaheira Interactions

//{ Neera Interactions

	//{ Neera - Corwin First Interaction 

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 11)
		Global("XA_Banter_CorwinNeera", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinNeera", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Neera")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinNeera", "GLOBAL", 2)
		!Range("Neera", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Neera")
			Continue()
	END

	IF
		IfValidForPartyDialog("Neera")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinNeera", "GLOBAL", 2)
		Range("Neera", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			//Dialog B-40
			ActionOverride("Neera", FaceObject("XACORWIN"))
			Interact("Neera")
			SetInterrupt(TRUE)
	END
	//}

	//{ Neera - Corwin Second Interaction 

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 11)
		Global("XA_Banter_CorwinNeera", "GLOBAL", 3)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinNeera", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IsValidForPartyDialog("Neera")
		IsValidForPartyDialog("Imoen2")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinNeera", "GLOBAL", 4)
	THEN
		RESPONSE #100
			//Dialog B-41
			Interact("Neera")
	END
	//}

//} End Neera Interactions

//{ Dorn Interactions

	//{ Dorn / Corwin Love Conflict
	IF
		IfValidForPartyDialog("dorn")  // Dorn
		IfValidForPartyDialog("XACORWIN")  // corwin
		OR(2)
			Global("DornRomanceActive","GLOBAL",1)
			Global("DornRomanceActive","GLOBAL",2)
		GlobalGT("DornLovetalks","GLOBAL",9)
		OR(2)
			Global("XA_CorwinRomanceActive","GLOBAL",1)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
		Global("OHD_corwinconflict","GLOBAL",0)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			RealSetGlobalTimer("OHD_corwinconflict_timer","GLOBAL",NINE_HOURS)
			SetGlobal("OHD_corwinconflict","GLOBAL",1)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("dorn")  // Dorn
		IfValidForPartyDialog("XACORWIN")  // corwin
		OR(2)
			Global("DornRomanceActive","GLOBAL",1)
			Global("DornRomanceActive","GLOBAL",2)
		OR(2)
			Global("XA_CorwinRomanceActive","GLOBAL",1)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
		Global("OHD_corwinconflict","GLOBAL",1)
		RealGlobalTimerExpired("OHD_corwinconflict_timer","GLOBAL")
	THEN
		RESPONSE #100
			SetGlobal("OHD_corwinconflict","GLOBAL",2)
			Continue()
	END

	IF
		IfValidForPartyDialog("dorn")  // Dorn
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		!AreaType(DUNGEON)
		!See([ENEMY])
		Global("OHD_corwinconflict","GLOBAL",2)
		See("Dorn")
	THEN
		RESPONSE #100
			//Dialog B-0
			StartDialog("XACORWIB", Player1)
	END

	IF
		Global("OHD_sexreactions","GLOBAL",1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)  
		!Global("XA_DornSex", "GLOBAL", 1)
		OR(2)
			Global("XA_CorwinRomanceActive","GLOBAL",1)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_DornSex", "GLOBAL", 1)
			SetGlobal("XA_ComplainDornSex", "GLOBAL", 1)
			//Dialog J-25
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Dorn - Corwin First Interaction 

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 3)
		Global("XA_Banter_CorwinDorn", "GLOBAL", 1)
		ActionListEmpty()
		!Global("XA_DornPatronsDead", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinDorn", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Dorn")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinDorn", "GLOBAL", 2)
		!Range("Dorn", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Dorn")
			Continue()
	END

	IF
		IfValidForPartyDialog("Dorn")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinDorn", "GLOBAL", 2)
		Range("Dorn", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Dorn", FaceObject("XACORWIN"))
			//Dialog B-80
			Interact("Dorn")
			SetInterrupt(TRUE)
	END
	//}

	//{ Dorn - Corwin Second Interaction 

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 3)
		Global("XA_Banter_CorwinDorn", "GLOBAL", 3)
		!Global("XA_DornPatronsDead", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinDorn", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Dorn")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinDorn", "GLOBAL", 4)
		!Range("Dorn", 6)
		!Global("XA_DornPatronsDead", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Dorn")
			Continue()
	END

	IF
		IfValidForPartyDialog("Dorn")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinDorn", "GLOBAL", 4)
		!Global("XA_DornPatronsDead", "GLOBAL", 1)
		Range("Dorn", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Dorn", FaceObject("XACORWIN"))
			//Dialog B-81
			Interact("Dorn")
			SetInterrupt(TRUE)
	END
	//}

//} End Dorn Interactions

//{ Keldorn Interactions 

	//{ Corwin Mad at Keldorn - Underdark
	IF
		IsValidForPartyDialog("Keldorn")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		GlobalTimerExpired("XA_CorwinScoldKeldornTimer", "GLOBAL")
		Global("XA_InUnderdark", "GLOBAL", 1)
		See("Keldorn")
		Global("XA_CorwinAngryAtKeldorn", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinAngryAtKeldorn", "GLOBAL", 2)
			//Dialog B-61
			Interact("Keldorn")
			SetInterrupt(TRUE)
	END
	//}

	//{ Keldorn - Corwin Optional Interaction (Reconciled with Maria) 
	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 9)
		Global("XA_Banter_CorwinKeldornOpt1", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinKeldornOpt1", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Keldorn")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinKeldornOpt1", "GLOBAL", 2)
		!Range("Keldorn", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Keldorn", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Keldorn")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinKeldornOpt1", "GLOBAL", 2)
		Range("Keldorn", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Keldorn")
			//Dialog B-62
			Interact("Keldorn")
			SetInterrupt(TRUE)
	END
	//}

	//{ Keldorn - Corwin First Interaction 
	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 9)
		Global("XA_Banter_CorwinKeldorn", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinKeldorn", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Keldorn")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinKeldorn", "GLOBAL", 2)
		!Range("Keldorn", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Keldorn")
			Continue()
	END

	IF
		IfValidForPartyDialog("Keldorn")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinKeldorn", "GLOBAL", 2)
		Range("Keldorn", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Keldorn", FaceObject("XACORWIN"))
			//Dialog B-63
			Interact("Keldorn")
			SetInterrupt(TRUE)
	END
	//}

	//{ Keldorn - Corwin Second Interaction 
	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 9)
		Global("XA_Banter_CorwinKeldorn", "GLOBAL", 3)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinKeldorn", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Keldorn")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinKeldorn", "GLOBAL", 4)
		!Range("Keldorn", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Keldorn", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Keldorn")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinKeldorn", "GLOBAL", 4)
		Range("Keldorn", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Keldorn")
			//Dialogs B-64, B-65
			Interact("Keldorn")
			SetInterrupt(TRUE)
	END
	//}

//} End Keldorn Interactions

//{ Korgan Interactions

	//{ Korgan - Corwin First Interaction

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 10)
		Global("XA_Banter_CorwinKorgan", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinKorgan", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Korgan")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinKorgan", "GLOBAL", 2)
		!Range("Korgan", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Korgan", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Korgan")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinKorgan", "GLOBAL", 2)
		Range("Korgan", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Korgan")
			//Dialog B-43
			Interact("Korgan")
			SetInterrupt(TRUE)
	END
	//}

	//{ Korgan - Corwin Second Interaction

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 10)
		Global("XA_Banter_CorwinKorgan", "GLOBAL", 3)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinKorgan", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Korgan")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinKorgan", "GLOBAL", 4)
		!Range("Korgan", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Korgan", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Korgan")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinKorgan", "GLOBAL", 4)
		Range("Korgan", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Korgan")
			//Dialog B-44
			Interact("Korgan")
			SetInterrupt(TRUE)
	END
	//}

//} End Korgan Interactions

//{ Jan Interactions

	//{ Jan - Corwin First Interaction

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 8)
		Global("XA_Banter_CorwinJan", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinJan", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Jan")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinJan", "GLOBAL", 2)
		!Range("Jan", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Jan")
			Continue()
	END

	IF
		IfValidForPartyDialog("Jan")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinJan", "GLOBAL", 2)
		Range("Jan", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Jan", FaceObject("XACORWIN"))
			//Dialog B-59
			Interact("Jan")
			SetInterrupt(TRUE)
	END
	//}

	//{ Jan - Corwin Second Interaction

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 8)
		Global("XA_Banter_CorwinJan", "GLOBAL", 3)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinJan", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Jan")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinJan", "GLOBAL", 4)
		!Range("Jan", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Jan")
			Continue()
	END

	IF
		IfValidForPartyDialog("Jan")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinJan", "GLOBAL", 4)
		Range("Jan", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Jan", FaceObject("XACORWIN"))
			//Dialog B-60
			Interact("Jan")
			SetInterrupt(TRUE)
	END
	//}

//} End Jan Interactions

//{ Edwin Interactions

	//{ Edwin - Corwin Change to Female Interaction */

	IF
		InParty(Myself)
		InParty("Edwin")
		!Global("XA_EdwinWasMale", "GLOBAL", 1)
		Gender("Edwin",MALE)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetGlobal("XA_EdwinWasMale", "GLOBAL", 1)
			Continue()
	END

	IF 
		IfValidForPartyDialog("Edwin")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Gender("Edwin",FEMALE)
		Global("XA_EdwinWasMale", "GLOBAL", 1)
		GlobalLT("XA_CorwinEdwinFemale", "GLOBAL", 1)
		See("Edwin")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinEdwinFemale", "GLOBAL", 1)
			//Dialog B-55
			Interact("Edwin")
			SetInterrupt(TRUE)
	END
	//}

	//{ Edwin - Corwin First Interaction 

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 4)
		Global("XA_Banter_CorwinEdwin", "GLOBAL", 1)
		Gender("Edwin",MALE)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinEdwin", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Edwin")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinEdwin", "GLOBAL", 2)
		!Range("Edwin", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Edwin")
			Continue()
	END

	IF
		IfValidForPartyDialog("Edwin")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinEdwin", "GLOBAL", 2)
		Range("Edwin", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Edwin", FaceObject("XACORWIN"))
			//Dialog B-56
			Interact("Edwin")
			SetInterrupt(TRUE)
	END
	//}

	//{ Edwin - Corwin Second Interaction 

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 4)
		Global("XA_Banter_CorwinEdwin", "GLOBAL", 3)
		Gender("Edwin",MALE)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinEdwin", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Edwin")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinEdwin", "GLOBAL", 4)
		!Range("Edwin", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Edwin", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Edwin")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinEdwin", "GLOBAL", 4)
		Range("Edwin", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Edwin")
			//Dialog B-57
			Interact("Edwin")
			SetInterrupt(TRUE)
	END
	//}

	//{ Edwin - Corwin Third Interaction 

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 4)
		Global("XA_Banter_CorwinEdwin", "GLOBAL", 5)
		Gender("Edwin",MALE)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinEdwin", "GLOBAL", 6)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Edwin")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinEdwin", "GLOBAL", 6)
		!Range("Edwin", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Edwin", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Edwin")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinEdwin", "GLOBAL", 6)
		Range("Edwin", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Edwin")
			//Dialog B-58
			Interact("Edwin")
			SetInterrupt(TRUE)
	END
	//}

	//{ Corwin Edwin Thay Interaction

	IF
		GlobalTimerExpired("XA_CorwinEdwinThayTimer", "GLOBAL")
		GlobalLT("XA_CorwinEdwinThay", "GLOBAL", 1)
		IfValidForPartyDialog("Edwin")
		See("Edwin")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinEdwinThay", "GLOBAL", 1)
			//Dialog B-54
			Interact("Edwin")
			SetInterrupt(TRUE)
	END
	//}

//} End Edwin Interactions

//{ Aerie Interactions
	
	//{ Aerie - Corwin First Interaction 

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 1)
		Global("XA_Banter_CorwinAerie", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinAerie", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Aerie")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinAerie", "GLOBAL", 2)
		!Range("Aerie", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Aerie")
			Continue()
	END

	IF
		IfValidForPartyDialog("Aerie")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinAerie", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Aerie", FaceObject("XACORWIN"))
			//Dialog B-72
			Interact("Aerie")
			SetInterrupt(TRUE)
	END
	//}

	//{ Aerie - Corwin Second Interaction 

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 1)
		Global("XA_Banter_CorwinAerie", "GLOBAL", 3)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinAerie", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Aerie")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinAerie", "GLOBAL", 4)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself,@0)
			SetGlobal("XA_Banter_CorwinAerie", "GLOBAL", 5)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Aerie")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinAerie", "GLOBAL", 5)
		!Range("Aerie", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Aerie", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Aerie")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinAerie", "GLOBAL", 5)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Aerie")
			//Dialog B-74
			Interact("Aerie")
			SetInterrupt(TRUE)
	END
	//}

	//{ Aerie - Corwin Third Interaction 

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 1)
		Global("XA_Banter_CorwinAerie", "GLOBAL", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinAerie", "GLOBAL", 7)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Aerie")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinAerie", "GLOBAL", 7)
		!Range("Aerie", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Aerie")
			Continue()
	END

	IF
		IfValidForPartyDialog("Aerie")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinAerie", "GLOBAL", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Aerie", FaceObject("XACORWIN"))
			//Dialogs B-75, B-77
			Interact("Aerie")
			SetInterrupt(TRUE)
	END
	//}

	//{ Aerie - Corwin Fourth Interaction 

	IF
		Global("XA_Banter_NextInteraction", "GLOBAL", 1)
		Global("XA_Banter_CorwinAerie", "GLOBAL", 8)
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinAerie", "GLOBAL", 9)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Aerie")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinAerie", "GLOBAL", 9)
		!Range("Aerie", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Aerie", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Aerie")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinAerie", "GLOBAL", 9)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Aerie")
			//Dialogs B-76, B-78
			ActionOverride("Aerie", StartDialog("AERIEJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

//} End Aerie Interactions

//{ Anomen Interactions

	//{ Anomen - Corwin First Interaction*/

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 2)
		Global("XA_Banter_CorwinAnomen", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinAnomen", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Anomen")
		IfValidForPartyDialog(Player1)
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinAnomen", "GLOBAL", 2)
		!Range("Anomen", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Anomen")
			Continue()
	END

	IF
		IfValidForPartyDialog("Anomen")
		IfValidForPartyDialog(Player1)
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinAnomen", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Anomen", FaceObject("XACORWIN"))
			//Dialog B-1
			StartDialog("XACORWIB", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Anomen - Corwin Second Interaction*/

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 2)
		Global("XA_Banter_CorwinAnomen", "GLOBAL", 3)
		!Global("XA_CorwinHatesAnomen", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinAnomen", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Anomen")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinAnomen", "GLOBAL", 4)
		!Range("Anomen", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Anomen", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Anomen")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinAnomen", "GLOBAL", 4)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Anomen")
			//Dialog B-67
			Interact("Anomen")
			SetInterrupt(TRUE)
	END
	//}

//} End Anomen Interactions

//{ Viconia Interactions

	//{ Viconia - Corwin First Interaction*/
	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 13)
		Global("XA_Banter_CorwinViconia", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinViconia", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Viconia")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinViconia", "GLOBAL", 2)
		!Range("Viconia", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Viconia")
			Continue()
	END

	IF
		IfValidForPartyDialog("Viconia")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinViconia", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Viconia", FaceObject("XACORWIN"))
			//Dialog B-45
			Interact("Viconia")
			SetInterrupt(TRUE)
	END
	//}

	//{ Viconia - Corwin Second Interaction*/

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 13)
		Global("XA_Banter_CorwinViconia", "GLOBAL", 3)
		!TimeOfDay(NIGHT)
		!TimeOfDay(DUSK)
		AreaType(OUTDOOR)
		//Weather(NOWEATHER)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinViconia", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Viconia")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinViconia", "GLOBAL", 4)
	THEN
		RESPONSE #100
			//Dialog B-47
			Interact("Viconia")
	END
	//}

	//{ Viconia - Corwin Third Interaction*/

	IF
		Global("XA_Banter_NextInteraction", "GLOBAL", 13)
		Global("XA_Banter_CorwinViconia", "GLOBAL", 5)
		AreaType(CITY)
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinViconia", "GLOBAL", 6)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Viconia")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinViconia", "GLOBAL", 6)
	THEN
		RESPONSE #100
			//Dialog B-48
			ActionOverride("Viconia", StartDialog("VICONIJ", "XACORWIN"))
	END
	//}

//} End Viconia Corwin Interactions

//{ Imoen Interactions

	//{ Imoen Soul Returned
	IF 
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		IsValidForPartyDialogue("Imoen2")
		GlobalTimerExpired("XA_CorwinImoenSoulTimer", "GLOBAL")
		See("Imoen2")
		GlobalLT("XA_CorwinImoenSoulTalk", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinImoenSoulTalk", "GLOBAL", 1)
			//Dialogs B-50, B-51
			Interact("Imoen2")
			SetInterrupt(TRUE)
	END
	//}

	//{ Imoen - Corwin First Interaction
	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 5)
		Global("XA_Banter_CorwinImoen", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinImoen", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Imoen2")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinImoen", "GLOBAL", 2)
		!Range("Imoen2", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Imoen2", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Imoen2")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinImoen", "GLOBAL", 2)
		Range("Imoen2", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Imoen2")
			//Dialog B-49
			Interact("Imoen2")
			SetInterrupt(TRUE)
	END
	//}

	//{ Imoen - Corwin Second Interaction*/

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 5)
		Global("XA_Banter_CorwinImoen", "GLOBAL", 3)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinImoen", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		IfValidForPartyDialog("Imoen2")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinImoen", "GLOBAL", 4)
		!Range("Imoen2", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Imoen2")
			Continue()
	END

	IF
		IfValidForPartyDialog("Imoen2")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinImoen", "GLOBAL", 4)
		Range("Imoen2", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			FaceObject("Imoen2")
			//Dialog B-52
			Interact("Imoen2")
			SetInterrupt(TRUE)
	END
	//}

//} End Imoen Interactions

//{ Sarevok Interactions

	//{ Sarevok - <CHARNAME> Soul Interaction
	IF
		GlobalTimerExpired("XA_SarevokSoulTimer", "GLOBAL")
		GlobalLT("XA_SarevokSoul", "GLOBAL", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_SarevokSoul", "GLOBAL", 1)
			Interact("Sarevok")
			SetInterrupt(TRUE)
	END
	
	IF
		IfValidForPartyDialog("Sarevok")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_SarevokSoul", "GLOBAL", 1)
		!Range("Sarevok", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Sarevok")
			Continue()
	END

	IF
		IfValidForPartyDialog("Sarevok")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_SarevokSoul", "GLOBAL", 1)
		Range("Sarevok", 7)
		See("Sarevok")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_SarevokSoul", "GLOBAL", 2)
			//Dialog B-89A, B-89B
			Interact("Sarevok")
			SetInterrupt(TRUE)
	END
	//}

	//{ Sarevok First Interaction
	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 22)
		Global("XA_Banter_CorwinSarevok", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_CorwinSarevok", "GLOBAL", 2)
			Continue()
	END
	
	IF
		IfValidForPartyDialog("Sarevok")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinSarevok", "GLOBAL", 2)
		!Range("Sarevok", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Sarevok")
			Continue()
	END

	IF
		IfValidForPartyDialog("Sarevok")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinSarevok", "GLOBAL", 2)
		Range("Sarevok", 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Sarevok", FaceObject("XACORWIN"))
			//Dialog B-86
			Interact("Sarevok")
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Sarevok Second Interaction
	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 22)
		Global("XA_Banter_CorwinSarevok", "GLOBAL", 3)
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_CorwinSarevok", "GLOBAL", 4)
			Continue()
	END
	
	IF
		IfValidForPartyDialog("Sarevok")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinSarevok", "GLOBAL", 4)
		!Range("Sarevok", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			ActionOverride("Sarevok", MoveToObject("XACORWIN"))
			Continue()
	END

	IF
		IfValidForPartyDialog("Sarevok")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinSarevok", "GLOBAL", 4)
		Range("Sarevok", 7)
	THEN
		RESPONSE #100
			//Dialog B-87
			ActionOverride("Sarevok", StartDialog("SAREV25J", "XACORWIN"))
	END
	//}
	
	//{ Sarevok Third Interaction
	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 22)
		Global("XA_Banter_CorwinSarevok", "GLOBAL", 5)
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_CorwinSarevok", "GLOBAL", 6)
			Continue()
	END
	
	IF
		IfValidForPartyDialog("Sarevok")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinSarevok", "GLOBAL", 6)
		!Range("Sarevok", 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject("Sarevok")
			Continue()
	END

	IF
		IfValidForPartyDialog("Sarevok")
		Global("XA_CorwinCanTalk", "GLOBAL", 1)
		Global("XA_Banter_CorwinSarevok", "GLOBAL", 6)
		Range("Sarevok", 7)
	THEN
		RESPONSE #100
			//Dialog B-88
			Interact("Sarevok")
	END
	//}
	
//} End Sarevok Interactions

//{ Corwin / Player Interactions

	//{ Corwin Sees Player for the First Time Since SoD
	IF
		!Global("XA_CorwinReunited", "GLOBAL", 1)
		!Range(Player1, 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject(Player1)
			Continue()
	END
	
	IF
		!Global("XA_CorwinReunited", "GLOBAL", 1)
		See(Player1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride(Player1, FaceObject("XACORWIN"))
			PlaySong(146)
			// Dialog I-1
			StartDialog("XACORWIN", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ First Banter

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 12)
		Global("XA_Banter_CorwinPlayer", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinPlayer", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_Banter_CorwinPlayer", "GLOBAL", 2)
		!Range(Player1, 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject(Player1)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_Banter_CorwinPlayer", "GLOBAL", 2)
		Range(Player1, 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride(Player1, FaceObject("XACORWIN"))
			PlaySong(146)
			//Dialogs J-62, J-63
			StartDialogue("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Second Banter

	IF
		InParty(Myself)
		Global("XA_Banter_NextInteraction", "GLOBAL", 12)
		Global("XA_Banter_CorwinPlayer", "GLOBAL", 3)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinPlayer", "GLOBAL", 4)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_Banter_CorwinPlayer", "GLOBAL", 4)
		!Range(Player1, 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject(Player1)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_Banter_CorwinPlayer", "GLOBAL", 4)
		Range(Player1, 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride(Player1, FaceObject("XACORWIN"))
			//Dialogs J-60, J-61
			StartDialogue("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Optional Banter 1
	IF
		InParty(Myself)
		Global("XA_MetRohma", "GLOBAL", 1)
		GlobalGT("XA_Banter_CorwinPlayer", "GLOBAL", 2)
		Global("XA_Banter_NextInteraction", "GLOBAL", 12)
		GlobalLT("XA_Banter_CorwinPlayerOpt1", "GLOBAL", 1)
		ActionListEmpty()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "GLOBAL", 1)
			SetGlobal("XA_Banter_CorwinPlayerOpt1", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_Banter_CorwinPlayerOpt1", "GLOBAL", 1)
		!Range(Player1, 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject(Player1)
			Continue()
	END

	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_Banter_CorwinPlayerOpt1", "GLOBAL", 1)
		Range(Player1, 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_Banter_CorwinPlayerOpt1", "GLOBAL", 2)
			ActionOverride(Player1, FaceObject("XACORWIN"))
			PlaySong(146)
			//Dialogs J-40, J-41
			StartDialogue("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Corwin Complain about Sarevok
	IF
		InParty(Myself)
		InParty("Sarevok")
		GlobalTimerExpired("XA_CorwinComplainSarevokTimer", "GLOBAL")
		Global("XA_CorwinComplainSarevok", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinComplainSarevok", "GLOBAL", 2)
			Continue()
	END
	
	IF 
		Global("XA_CorwinComplainSarevok", "GLOBAL", 2)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		!Range(Player1, 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject(Player1)
			Continue()
	END
	
	IF 
		Global("XA_CorwinComplainSarevok", "GLOBAL", 2)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Range(Player1, 7)
	THEN
		RESPONSE #100
			//Dialog J-69
			StartDialog("XACORWIJ", Player1)
	END
	//}

	//{ Saradush Destruction
	IF 
		GlobalTimerExpired("XA_YagaTimer", "GLOBAL")
		GlobalLT("XA_SaradushDestroyed", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_SaradushDestroyed", "GLOBAL", 1)
			//Dialog J-70
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
//} End Player Interactions

//{ Corwin Pregnant Interactions
	
	//{ Aerie Baby Parent Advice
	IF 
		GlobalTimerExpired("XA_CorwinAerieBabyTimer", "GLOBAL")
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		IsValidForPartyDialogue("Aerie")
		GlobalLT("XA_CorwinParentAdvice", "GLOBAL", 1)
		GlobalGT("XA_CorwinOpinionOfPlayer", "GLOBAL", 3)
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinParentAdvice", "GLOBAL", 1)
			Continue()
	END
	
	IF
		Global("XA_CorwinParentAdvice", "GLOBAL", 1)
		!Range(Player1, 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject(Player1)
			Continue()
	END
	
	IF
		Global("XA_CorwinParentAdvice", "GLOBAL", 1)
		Range(Player1,7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinParentAdvice", "GLOBAL", 2)
			//Dialog J-76
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Initial Timer Expiration
	IF 
		!AreaCheck("AR5203") // Yaga-Shura Camp
		Global("XA_CorwinPregnant", "GLOBAL", 1)
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		OR(2)
			Global("XA_PregnantOverride", "GLOBAL", 1)
			GlobalTimerExpired("XA_CorwinPregnantTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_PregnantOverride", "GLOBAL", 2)
			SetGlobal("XA_CorwinPregnant", "GLOBAL", 2)
			PlaySong(142)
			//Dialog J-71
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Second Interaction
	IF
		Global("XA_CorwinPregnant", "GLOBAL", 3)
		GlobalTimerExpired("XA_CorwinPregnantTimer", "GLOBAL")
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinPregnant", "GLOBAL", 4)
			DisplayStringHead(Myself, @15)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		Global("XA_CorwinPregnant", "GLOBAL", 4)
		!Range(Player1,6)
		ActionListEmpty()
		
	THEN
		RESPONSE #100
			MoveToObject(Player1)
			Continue()
	END
	
	IF
		Global("XA_CorwinPregnant", "GLOBAL", 4)
		Range(Player1,7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			PlaySong(146)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Third Interaction
	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		Global("XA_CorwinPregnant", "GLOBAL", 5)
		GlobalTimerExpired("XA_CorwinPregnantTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinPregnant", "GLOBAL", 6)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		Global("XA_CorwinPregnant", "GLOBAL", 6)
		See(Player1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			PlaySong(142)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Fourth Interaction
	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		Global("XA_CorwinPregnant", "GLOBAL", 7)
		GlobalTimerExpired("XA_CorwinPregnantTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinPregnant", "GLOBAL", 8)
			Continue()
	END
	
	IF
		Global("XA_CorwinPregnant", "GLOBAL", 8)
		See(Player1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			PlaySong(142)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Final Interaction
	IF
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		Global("XA_CorwinPregnant", "GLOBAL", 9)
		GlobalTimerExpired("XA_CorwinPregnantTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinPregnant", "GLOBAL", 10)
			Continue()
	END
	
	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		Global("XA_CorwinPregnant", "GLOBAL", 10)
		AreaCheck("AR4500")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			PlaySong(146)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Baby Name Interaction Imoen
	IF
		GlobalTimerExpired("XA_CorwinPregnantImoenTimer", "GLOBAL")
		GlobalLT("XA_CorwinPregnantBabyName_Imoen", "GLOBAL", 1)
		IsValidForPartyDialog("Imoen2")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinPregnantBabyName_Imoen", "GLOBAL", 1)
			//DisplayStringHead(Myself, ~C~)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		Global("XA_CorwinPregnantBabyName_Imoen", "GLOBAL", 1)
		See("Imoen2")
		See(Player1)
	THEN
		RESPONSE #100
			//Dialog J-73
			SetInterrupt(FALSE)
			ActionOverride("Imoen2", StartDialog("IMOEN2J", Player1))
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Baby Name Interaction Aerie
	IF
		Global("XA_CorwinPregnant", "GLOBAL", 5)
		Global("XA_CorwinPregnantAerie", "GLOBAL", 1)
		!Global("XA_CorwinPregnantImoen", "GLOBAL", 1)
		!Global("XA_CorwinPregnantAerieTimerSet", "GLOBAL", 1)
		InParty("Aerie")
		InParty(Myself)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinPregnantAerieTimer", "GLOBAL", TWO_DAYS)
			SetGlobal("XA_CorwinPregnantAerieTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		GlobalTimerExpired("XA_CorwinPregnantAerieTimer", "GLOBAL")
		IsValidForPartyDialogue("Aerie")
		GlobalLT("XA_CorwinPregnantBabyName_Aerie", "GLOBAL", 1)
		See(Player1)
		See("Aerie")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinPregnantBabyName_Aerie", "GLOBAL", 1)
			//Dialog J-74
			ActionOverride("Aerie", StartDialog("AERIEJ", Player1))
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Baby Name Interaction Jaheira
	IF
		Global("XA_CorwinPregnant", "GLOBAL", 5)
		Global("XA_CorwinPregnantJaheira", "GLOBAL", 1)
		!Global("XA_CorwinPregnantImoen", "GLOBAL", 1)
		!Global("XA_CorwinPregnantJahTimerSet", "GLOBAL", 1)
		InParty("Jaheira")
		InParty(Myself)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinPregnantJahTimer", "GLOBAL", TWO_DAYS)
			SetGlobal("XA_CorwinPregnantJahTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		GlobalTimerExpired("XA_CorwinPregnantJahTimer", "GLOBAL")
		IsValidForPartyDialogue("Jaheira")
		GlobalLT("XA_CorwinPregnantBabyName_Jah", "GLOBAL", 1)
		See(Player1)
		See("Jaheira")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinPregnantBabyName_Jah", "GLOBAL", 1)
			//Dialog J-75
			ActionOverride("Jaheira", StartDialog("JAHEIRAJ", Player1))
			SetInterrupt(TRUE)
	END
	//}
//}

//{ Romance Conflicts

	//{ Other Romance == 2
	IF
		GlobalLT("XA_RomanceConflictTimerSet", "GLOBAL", 1)
		Global("XA_CorwinRomanceActive","GLOBAL",2)
		OR(8)
			Global("AerieRomanceActive","GLOBAL",2)
			Global("ViconiaRomanceActive","GLOBAL",2)
			Global("DornRomanceActive","GLOBAL",2)
			Global("NeeraRomanceActive","GLOBAL",2)
			Global("AnomenRomanceActive","GLOBAL",2)
			Global("JaheiraRomanceActive","GLOBAL",2)
			Global("HexxatRomanceActive","GLOBAL",2)
			Global("RasaadRomanceActive","GLOBAL",2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_RomanceConflictTimer", "GLOBAL", ONE_DAY)
			SetGlobal("XA_RomanceConflictTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CorwinCanTalkToPlayer", "GLOBAL", 1)
		GlobalTimerExpired("XA_RomanceConflictTimer", "GLOBAL")
		GlobalLT("XA_RomanceConflictTalk", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_RomanceConflictTalk", "GLOBAL", 1)
			//Dialog J-83
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Other Romance < 2
	
		//{ Aerie
		IF
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("AerieRomanceActive", "GLOBAL", 2)
		THEN
			RESPONSE #100
				SetGlobal("AerieRomanceActive","GLOBAL",3)
				Continue()
		END
		//}

		//{ Viconia
		IF
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("ViconiaRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("ViconiaRomanceActive","GLOBAL",3)
				Continue()
		END
		//}

		//{ Dorn
		IF
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("DornRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("DornRomanceActive","GLOBAL",3)
				Continue()
		END
		//}
		
		//{ Neera
		IF
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("NeeraRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("NeeraRomanceActive","GLOBAL",3)
				Continue()
		END
		//}

		//{ Anomen
		IF
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("AnomenRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("AnomenRomanceActive","GLOBAL",3)
				Continue()
		END
		//}

		//{ Jaheira
		IF
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("JaheiraRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("JaheiraRomanceActive","GLOBAL",3)
				Continue()
		END
		//}

		//{ Hexxat
		IF
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("HexxatRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("HexxatRomanceActive","GLOBAL",3)
				Continue()
		END
		//}
		
		//{ Rasaad
		IF
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("RasaadRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("RasaadRomanceActive","GLOBAL",3)
				Continue()
		END
		//}
		
	//}

//}

/* Reset the next interaction to zero; the current subject of the interaction has exhausted all of their banters */

IF 
	InParty(Myself)
	!Global("XA_Banter_NextInteraction", "GLOBAL", 0)
	ActionListEmpty()
	GlobalTimerExpired("XA_CorwinBanter", "GLOBAL") // not strictly necessary, but it is here to support debugging
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "GLOBAL", 0)
		Continue()
END

//{ Check for old SoD items
IF 
	InParty(Myself)
	OR(2)
		!Global("XA_SoDItemCheckTimerSet", "GLOBAL", 1)
		GlobalTimerExpired("XA_SoDItemCheckTimer", "GLOBAL")
	OR(2)
		PartyHasItem("BDBOW06") // Corwin's Bow (SoD)
		PartyHasItem("BDCHAN05") // Corwin's Armor (SoD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("XA_SoDItemCheckTimer", "GLOBAL", ONE_DAY)
		SetGlobal("XA_SoDItemCheckTimerSet", "GLOBAL", 1)
		
		ActionOverride(Player1, DestroyItem("BDBOW06"))
		ActionOverride(Player2, DestroyItem("BDBOW06"))
		ActionOverride(Player3, DestroyItem("BDBOW06"))
		ActionOverride(Player4, DestroyItem("BDBOW06"))
		ActionOverride(Player5, DestroyItem("BDBOW06"))
		ActionOverride(Player6, DestroyItem("BDBOW06"))
		
		ActionOverride(Player1, DestroyItem("BDCHAN05"))
		ActionOverride(Player2, DestroyItem("BDCHAN05"))
		ActionOverride(Player3, DestroyItem("BDCHAN05"))
		ActionOverride(Player4, DestroyItem("BDCHAN05"))
		ActionOverride(Player5, DestroyItem("BDCHAN05"))
		ActionOverride(Player6, DestroyItem("BDCHAN05"))
		SetInterrupt(TRUE)
		
		Continue()
END
//}

//{ Check Stats - SoD Corwin
IF
	!CheckStat("Corwin", 18, STR)
	GlobalLT("XA_Corwin_STR_Changed", "LOCALS", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 1)
		Continue()
END

IF
	!CheckStat("Corwin", 15, DEX)
	GlobalLT("XA_Corwin_DEX_Changed", "LOCALS", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 1)
		Continue()
END

IF
	!CheckStat("Corwin", 14, CON)
	GlobalLT("XA_Corwin_CON_Changed", "LOCALS", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 1)
		Continue()
END

IF
	!CheckStat("Corwin", 12, INT)
	GlobalLT("XA_Corwin_INT_Changed", "LOCALS", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 1)
		Continue()
END

IF
	!CheckStat("Corwin", 14, WIS)
	GlobalLT("XA_Corwin_WIS_Changed", "LOCALS", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 1)
		Continue()
END

IF
	!CheckStat("Corwin", 14, CHR)
	GlobalLT("XA_Corwin_CHR_Changed", "LOCALS", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 1)
		Continue()
END
//}

//{ Stat Adjustments to Match SoD Corwin

	//{ Adjust STR to Match SoD Corwin
	IF
		CheckStat("Corwin", 20, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 20, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 19, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 19, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 18, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 18, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 17, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 17, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 16, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 16, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 15, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 15, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 14, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 14, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 13, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 13, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 12, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 12, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 11, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 11, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 10, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 10, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Adjust DEX to Match SoD Corwin
	IF
		CheckStat("Corwin", 20, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 20, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 19, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 19, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 18, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 18, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 17, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 17, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 16, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 16, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 15, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 15, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 14, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 14, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 13, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 13, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 12, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 12, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 11, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 11, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 10, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 10, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Adjust WIS to Match SoD Corwin
	IF
		CheckStat("Corwin", 20, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 20, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 19, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 19, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 18, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 18, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 17, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 17, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 16, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 16, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 15, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 15, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 14, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 14, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 13, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 13, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 12, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 12, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 11, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 11, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 10, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 10, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Adjust CHR to Match SoD Corwin
	IF
		CheckStat("Corwin", 20, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 20, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 19, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 19, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 18, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 18, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 17, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 17, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 16, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 16, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 15, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 15, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 14, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 14, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 13, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 13, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 12, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 12, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 11, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 11, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 10, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 10, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Adjust CON to Match SoD Corwin
	IF
		CheckStat("Corwin", 20, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 20, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 19, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 19, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 18, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 18, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 17, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 17, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 16, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 16, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 15, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 15, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 14, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 14, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 13, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 13, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 12, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 12, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 11, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 11, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 10, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 10, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Adjust INT to Match SoD Corwin
	IF
		CheckStat("Corwin", 20, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 20, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 19, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 19, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 18, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 18, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 17, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 17, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 16, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 16, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 15, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 15, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 14, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 14, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 13, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 13, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 12, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 12, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 11, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 11, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 10, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 10, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

//}

//{ Exp Boosts on Join

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,249999)
  XPLT(Player1,500000)
  XPLT(Myself,500000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,250000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,499999)
  XPLT(Player1,750000)
  XPLT(Myself,750000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,500000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,749999)
  XPLT(Player1,1000000)
  XPLT(Myself,1000000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,750000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,999999)
  XPLT(Player1,1250000)
  XPLT(Myself,1250000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,1000000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,1249999)
  XPLT(Player1,1500000)
  XPLT(Myself,1500000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,1250000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,1499999)
  XPLT(Player1,1750000)
  XPLT(Myself,1750000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,1500000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,1749999)
  XPLT(Player1,2000000)
  XPLT(Myself,2000000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,1750000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,1999999)
  XPLT(Myself,2000000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,2000000,SET)
	Continue()
END

IF 
	Global("BD_JOINXP","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("BD_JOINXP","LOCALS",1)
		Continue()
END

//} End Exp Boosts on Join


