//Note: Variable Key Max Length Appears to be 32.

//{ 00: Blocking Actions
	IF
		Global("XA_CorwinIrenicus", "GLOBAL", 4)
	THEN
		RESPONSE #100
			////DisplayStringHead(Myself, ~CI4 Script Blocking~)
			NoAction()
	END
	
	IF
		Global("XA_ReturnToBG", "GLOBAL", 1)
		GlobalLT("XA_LC_BanterBlock_RBG", "LOCALS", 1)
		OR(4)
			AreaCheck("XAKIDNAP")
			AreaCheck("XADUCAL")
			AreaCheck("XADUCAL2")
			AreaCheck("XADUC3")
	THEN
		RESPONSE #100
			SetGlobal("XA_LC_BanterBlock_RBG", "LOCALS", 1)
	END
	
	IF
		Global("XA_ReturnToBG", "GLOBAL", 2)
		Global("XA_LC_BanterBlock_RBG", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_LC_BanterBlock_RBG", "LOCALS", 0)
	END
//}

//{ 01: Amulet / Letter on Party Join
	
	//{ Include the letter sent by the Player
	IF
		InParty(Myself)
		Global("XA_LetterSent", "GLOBAL", 1)
		GlobalLT("XA_CreatedLetterInventory", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			CreateItem("XAORW1",0,0,0)
			SetGlobal("XA_CreatedLetterInventory", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		InParty(Myself)
		Global("XA_LetterSent", "GLOBAL", 2)
		GlobalLT("XA_CreatedLetterInventory", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			CreateItem("XAORW2",0,0,0)
			SetGlobal("XA_CreatedLetterInventory", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Corwin Amulet 
	IF
		InParty(Myself)
		PartyHasItem("XAAMULET")	
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DestroyItem("XAAMULET")
			ActionOverride(Player1, DestroyItem("XAAMULET"))
			ActionOverride(Player2, DestroyItem("XAAMULET"))
			ActionOverride(Player3, DestroyItem("XAAMULET"))
			ActionOverride(Player4, DestroyItem("XAAMULET"))
			ActionOverride(Player5, DestroyItem("XAAMULET"))
			ActionOverride(Player6, DestroyItem("XAAMULET"))
			SetInterrupt(TRUE)
			Continue()
	END
	//}

//}

//{ 02: Corwin Opinion Baseline
IF
	GlobalLT("XA_CorwinOpinionBaselined", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinOpinionOfPlayer", "GLOBAL", 100)
		SetGlobal("XA_CorwinOpinionBaselined", "GLOBAL", 1)
		SetInterrupt(TRUE)
		Continue()
END
//}

//{ 03: Mark as In-Party in BG2 (For later summoning via the fate-spirit)
IF
	InParty(Myself)
	GlobalLT("XA_CorwinInPartyBG2", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_CorwinInPartyBG2", "GLOBAL", 1)
		Continue()
END
//}

//{ 05: Determines if CorwinEET is Installed
IF 
	InParty(Myself)
	Global("XA_CorwinEETCheck", "GLOBAL", 0)
	GlobalGT("EECorwinBG1", "GLOBAL", 0) // this is set as part the CorwinEET mod.
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinEET", "GLOBAL", 1)
		SetGlobal("XA_CorwinEETCheck", "GLOBAL", 1)
		SetInterrupt(TRUE)
		Continue()
END

IF 
	InParty(Myself)
	Global("XA_CorwinEETCheck", "GLOBAL", 0)
	Global("EECorwinBG1", "GLOBAL", 0) // this is set as part the CorwinEET mod.
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinEET", "GLOBAL", 0)
		SetGlobal("XA_CorwinEETCheck", "GLOBAL", 1)
		SetInterrupt(TRUE)
		Continue()
END

IF 
	InParty(Myself)
	Global("XA_MetRohmaCheck", "GLOBAL", 0)
	OR(2)
		GlobalGT("bd_rohma_banter","bd0101",6)
		GlobalGT("EEMetRohma", "GLOBAL", 0)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_MetRohma", "GLOBAL", 1)
		SetGlobal("XA_MetRohmaCheck", "GLOBAL", 1)
		SetInterrupt(TRUE)
		Continue()
END
//}

//{ 06: Checks if the Player met Rohma prior to the events of SoA
IF 
	InParty(Myself)
	Global("XA_MetRohmaCheck", "GLOBAL", 0)
	GlobalLT("bd_rohma_banter","bd0101",7) //Met Rohma in SoD
	Global("EEMetRohma", "GLOBAL", 0) //Met Rohma in CorwinEET
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_MetRohma", "GLOBAL", 0)
		SetGlobal("XA_MetRohmaCheck", "GLOBAL", 1)
		SetInterrupt(TRUE)
		Continue()
END
//}

//{	07: Rejoin processing - triggered in XACORWIN.D and XACORWIP.D
IF 
	//!InParty(Myself)
	ActionListEmpty()
	Global("XA_CorwinRejoinProcessed", "GLOBAL", 1)
THEN 
	RESPONSE #100
		SetInterrupt(FALSE)
		JoinParty()
		SetGlobal("XA_CorwinJoined","LOCALS",1)
		SetGlobal("XA_CorwinKickedOut", "LOCALS", 0)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
		SetGlobal("XA_CorwinRepWarning", "GLOBAL", 0)
		SetGlobal("XA_CorwinRejoinProcessed", "GLOBAL", 2)
		////DisplayStringHead(Myself, ~DEBUG: 07-00~)
		SetInterrupt(TRUE)
END
//}

//{ 08: Corwin Can Talk Check

	//{ Corwin Can Talk
	IF 
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		OR(6)
			!IsValidForPartyDialogue(Myself)
			ActuallyInCombat()
			GlobalGT("XA_ArrivedInUndercity", "GLOBAL", 0)
			!InParty(Myself)
			AreaCheck("XACS13")
			Global("XA_LCE_EXTalk", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CanTalk", "LOCALS", 0)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		ActionListEmpty()
		InParty(Myself)
		!Global("XA_CanTalk", "LOCALS", 1)
		IsValidForPartyDialogue(Myself)
		!ActuallyInCombat()
		GlobalLT("XA_LCE_EXTalk", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CanTalk", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
	
	//{ Corwin Can Talk to Player Check
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		OR(3)
			!Global("XA_CanTalk", "LOCALS", 1)
			!IsValidForPartyDialogue(Player1)
			!See(Player1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CanTalkToPlayer", "LOCALS", 0)
			////DisplayStringHead(Myself, ~DEBUG: 09-00~)
			SetInterrupt(TRUE)
			Continue()
	END


	IF
		ActionListEmpty()
		!Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
		IsValidForPartyDialogue(Player1)
		See(Player1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CanTalkToPlayer", "LOCALS", 1)
			////DisplayStringHead(Myself, ~DEBUG: 09-01~)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
	
	//{ Can Talk to Aerie
	IF
		ActionListEmpty()
		See("Aerie")
		IsValidForPartyDialogue("Aerie")
		!Global("XA_CanTalkToAerie", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToAerie", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToAerie", "LOCALS", 1)
		OR(3)	
			!See("Aerie")
			!IsValidForPartyDialogue("Aerie")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToAerie", "LOCALS", 0)
			Continue()
	END
	//}
	
	//{ Can Talk to Anomen
	IF
		ActionListEmpty()
		See("Anomen")
		IsValidForPartyDialogue("Anomen")
		!Global("XA_CanTalkToAnomen", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToAnomen", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToAnomen", "LOCALS", 1)
		OR(3)	
			!See("Anomen")
			!IsValidForPartyDialogue("Anomen")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToAnomen", "LOCALS", 0)
			Continue()
	END
	//}
	
	//{ Can Talk to Caelar
	IF
		ActionListEmpty()
		See("XACAELAR")
		IsValidForPartyDialogue("XACAELAR")
		!Global("XA_CanTalkToCaelar", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToCaelar", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToCaelar", "LOCALS", 1)
		OR(3)	
			!See("XACAELAR")
			!IsValidForPartyDialogue("XACAELAR")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToCaelar", "LOCALS", 0)
			Continue()
	END
	//}
	
	//{ Can Talk to Cernd
	IF
		ActionListEmpty()
		See("Cernd")
		IsValidForPartyDialogue("Cernd")
		!Global("XA_CanTalkToCernd", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToCernd", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToCernd", "LOCALS", 1)
		OR(3)	
			!See("Cernd")
			!IsValidForPartyDialogue("Cernd")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToCernd", "LOCALS", 0)
			Continue()
	END
	//}
	
	//{ Can Talk to Dorn
	IF
		ActionListEmpty()
		See("Dorn")
		IsValidForPartyDialogue("Dorn")
		!Global("XA_CanTalkToDorn", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToDorn", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToDorn", "LOCALS", 1)
		OR(3)	
			!See("Dorn")
			!IsValidForPartyDialogue("Dorn")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToDorn", "LOCALS", 0)
			Continue()
	END
	//}

	//{ Can Talk to Edwin
	IF
		ActionListEmpty()
		See("Edwin")
		IsValidForPartyDialogue("Edwin")
		!Global("XA_CanTalkToEdwin", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToEdwin", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToEdwin", "LOCALS", 1)
		OR(3)	
			!See("Edwin")
			!IsValidForPartyDialogue("Edwin")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToEdwin", "LOCALS", 0)
			Continue()
	END
	//}

	//{ Can Talk to HaerDalis
	IF
		ActionListEmpty()
		See("HaerDalis")
		IsValidForPartyDialogue("HaerDalis")
		!Global("XA_CanTalkToHaerDalis", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToHaerDalis", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToHaerDalis", "LOCALS", 1)
		OR(3)	
			!See("HaerDalis")
			!IsValidForPartyDialogue("HaerDalis")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToHaerDalis", "LOCALS", 0)
			Continue()
	END
	//}
		
	//{ Can Talk to Hexxat
	IF
		ActionListEmpty()
		See("Hexxat")
		IsValidForPartyDialogue("Hexxat")
		!Global("XA_CanTalkToHexxat", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToHexxat", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToHexxat", "LOCALS", 1)
		OR(3)	
			!See("Hexxat")
			!IsValidForPartyDialogue("Hexxat")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToHexxat", "LOCALS", 0)
			Continue()
	END
	//}
	
	//{ Can Talk to Imoen2
	IF
		ActionListEmpty()
		See("Imoen2")
		IsValidForPartyDialogue("Imoen2")
		!Global("XA_CanTalkToImoen2", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToImoen2", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToImoen2", "LOCALS", 1)
		OR(3)	
			!See("Imoen2")
			!IsValidForPartyDialogue("Imoen2")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToImoen2", "LOCALS", 0)
			Continue()
	END
	//}

	//{ Can Talk to Jaheira
	IF
		ActionListEmpty()
		See("Jaheira")
		IsValidForPartyDialogue("Jaheira")
		!Global("XA_CanTalkToJaheira", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToJaheira", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToJaheira", "LOCALS", 1)
		OR(3)	
			!See("Jaheira")
			!IsValidForPartyDialogue("Jaheira")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToJaheira", "LOCALS", 0)
			Continue()
	END
	//}
	
	//{ Can Talk to Jan
	IF
		ActionListEmpty()
		See("Jan")
		IsValidForPartyDialogue("Jan")
		!Global("XA_CanTalkToJan", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToJan", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToJan", "LOCALS", 1)
		OR(3)	
			!See("Jan")
			!IsValidForPartyDialogue("Jan")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToJan", "LOCALS", 0)
			Continue()
	END
	//}
		
	//{ Can Talk to Keldorn
	IF
		ActionListEmpty()
		See("Keldorn")
		IsValidForPartyDialogue("Keldorn")
		!Global("XA_CanTalkToKeldorn", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToKeldorn", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToKeldorn", "LOCALS", 1)
		OR(3)	
			!See("Keldorn")
			!IsValidForPartyDialogue("Keldorn")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToKeldorn", "LOCALS", 0)
			Continue()
	END
	//}
	
	//{ Can Talk to Korgan
	IF
		ActionListEmpty()
		See("Korgan")
		IsValidForPartyDialogue("Korgan")
		!Global("XA_CanTalkToKorgan", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToKorgan", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToKorgan", "LOCALS", 1)
		OR(3)	
			!See("Korgan")
			!IsValidForPartyDialogue("Korgan")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToKorgan", "LOCALS", 0)
			Continue()
	END
	//}

	//{ Can Talk to Mazzy
	IF
		ActionListEmpty()
		See("Mazzy")
		IsValidForPartyDialogue("Mazzy")
		!Global("XA_CanTalkToMazzy", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToMazzy", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToMazzy", "LOCALS", 1)
		OR(3)	
			!See("Mazzy")
			!IsValidForPartyDialogue("Mazzy")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToMazzy", "LOCALS", 0)
			Continue()
	END
	//}
	
	//{ Can Talk to Minsc
	IF	
		ActionListEmpty()
		See("Minsc")
		IsValidForPartyDialogue("Minsc")
		!Global("XA_CanTalkToMinsc", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToMinsc", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToMinsc", "LOCALS", 1)
		OR(3)	
			!See("Minsc")
			!IsValidForPartyDialogue("Minsc")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToMinsc", "LOCALS", 0)
			Continue()
	END
	//}
	
	//{ Can Talk to Nalia
	IF
		ActionListEmpty()
		See("Nalia")
		IsValidForPartyDialogue("Nalia")
		!Global("XA_CanTalkToNalia", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToNalia", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToNalia", "LOCALS", 1)
		OR(3)	
			!See("Nalia")
			!IsValidForPartyDialogue("Nalia")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToNalia", "LOCALS", 0)
			Continue()
	END
	//}
	
	//{ Can Talk to Neera
	IF
		ActionListEmpty()
		See("Neera")
		IsValidForPartyDialogue("Neera")
		!Global("XA_CanTalkToNeera", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToNeera", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToNeera", "LOCALS", 1)
		OR(3)	
			!See("Neera")
			!IsValidForPartyDialogue("Neera")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToNeera", "LOCALS", 0)
			Continue()
	END
	//}
	
	//{ Can Talk to Rasaad
	IF
		ActionListEmpty()
		See("Rasaad")
		IsValidForPartyDialogue("Rasaad")
		!Global("XA_CanTalkToRasaad", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToRasaad", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToRasaad", "LOCALS", 1)
		OR(3)	
			!See("Rasaad")
			!IsValidForPartyDialogue("Rasaad")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToRasaad", "LOCALS", 0)
			Continue()
	END
	//}
	
	//{ Can Talk to Sarevok
	IF
		ActionListEmpty()
		See("Sarevok")
		IsValidForPartyDialogue("Sarevok")
		!Global("XA_CanTalkToSarevok", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToSarevok", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToSarevok", "LOCALS", 1)
		OR(3)	
			!See("Sarevok")
			!IsValidForPartyDialogue("Sarevok")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToSarevok", "LOCALS", 0)
			Continue()
	END
	//}

	//{ Can Talk to Valygar
	IF
		ActionListEmpty()
		See("Valygar")
		IsValidForPartyDialogue("Valygar")
		!Global("XA_CanTalkToValygar", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToValygar", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToValygar", "LOCALS", 1)
		OR(3)	
			!See("Valygar")
			!IsValidForPartyDialogue("Valygar")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToValygar", "LOCALS", 0)
			Continue()
	END
	//}
	
	//{ Can Talk to Viconia
	IF
		ActionListEmpty()
		See("Viconia")
		IsValidForPartyDialogue("Viconia")
		!Global("XA_CanTalkToViconia", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToViconia", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToViconia", "LOCALS", 1)
		OR(3)	
			!See("Viconia")
			!IsValidForPartyDialogue("Viconia")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToViconia", "LOCALS", 0)
			Continue()
	END
	//}

	//{ Can Talk to Yoshimo
	IF
		ActionListEmpty()
		See("Yoshimo")
		IsValidForPartyDialogue("Yoshimo")
		!Global("XA_CanTalkToYoshimo", "LOCALS", 1)
		Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToYoshimo", "LOCALS", 1)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToYoshimo", "LOCALS", 1)
		OR(3)	
			!See("Yoshimo")
			!IsValidForPartyDialogue("Yoshimo")
			!Global("XA_CanTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CanTalkToYoshimo", "LOCALS", 0)
			Continue()
	END
	//}

//}

//{ 09: Sound Swap

/* If another mod is uninstalled, and LCA re-installed after Corwin has already joined, the sound swap may need to be performed again. This variable is accessible from the Debug Assistant. */

IF
	Global("XA_LC_ReapplySoundSwap", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_LC_ReapplySoundSwap", "GLOBAL", 0)
		SetGlobal("XA_LCASoundSwap", "LOCALS", 0)
		SetGlobal("XA_BiteSoundSet", "LOCALS", 0)
		SetInterrupt(TRUE)
		Continue()
END

IF
	Global("XA_CorwinRomanceActive", "GLOBAL", 2)
	GlobalLT("XA_LCASoundSwap", "LOCALS", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetPlayerSound(Myself,@9,SELECT_ACTION6) 
		SetGlobal("XA_LCASoundSwap", "LOCALS", 1)
		SetInterrupt(TRUE)
		Continue()
END

IF
	!Global("XA_CorwinRomanceActive", "GLOBAL", 2)
	Global("XA_LCASoundSwap", "LOCALS", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetPlayerSound(Myself,#268282,SELECT_ACTION6) 
		SetGlobal("XA_LCASoundSwap", "LOCALS", 0)
		SetInterrupt(TRUE)
		Continue()
END

//{ Reset Sounds to Original
	IF
		ActionListEmpty()
		Global("XA_BiteSoundSet", "LOCALS", 1)
		Global("XA_CorwinBit", "GLOBAL", 0)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetPlayerSound(Myself,268296,MORALE)
			SetPlayerSound(Myself,268292,HAPPY)
			SetPlayerSound(Myself,268293,UNHAPPY_ANNOYED)
			SetPlayerSound(Myself,268294,UNHAPPY_SERIOUS)
			SetPlayerSound(Myself,268295,UNHAPPY_BREAKING_POINT)
			SetPlayerSound(Myself,268256,LEADER)
			SetPlayerSound(Myself,268257,TIRED)
			SetPlayerSound(Myself,268258,BORED)
			SetPlayerSound(Myself,268251,BATTLE_CRY1)
			SetPlayerSound(Myself,268252,BATTLE_CRY2)
			SetPlayerSound(Myself,268253,BATTLE_CRY3)
			SetPlayerSound(Myself,268254,BATTLE_CRY4)
			SetPlayerSound(Myself,268255,BATTLE_CRY5)
			SetPlayerSound(Myself,268273,DAMAGE)
			SetPlayerSound(Myself,268274,DYING)
			SetPlayerSound(Myself,268259,HURT)
			SetPlayerSound(Myself,268275,AREA_FOREST)
			SetPlayerSound(Myself,268276,AREA_CITY)
			SetPlayerSound(Myself,268277,AREA_DUNGEON)
			SetPlayerSound(Myself,268278,AREA_DAY)
			SetPlayerSound(Myself,268279,AREA_NIGHT)
			SetPlayerSound(Myself,268260,SELECT_COMMON1)
			SetPlayerSound(Myself,268261,SELECT_COMMON2)
			SetPlayerSound(Myself,268262,SELECT_COMMON3)
			SetPlayerSound(Myself,268263,SELECT_COMMON4)
			SetPlayerSound(Myself,268264,SELECT_COMMON5)
			SetPlayerSound(Myself,268265,SELECT_COMMON6)
			SetPlayerSound(Myself,268266,SELECT_ACTION1)
			SetPlayerSound(Myself,268267,SELECT_ACTION2)
			SetPlayerSound(Myself,268268,SELECT_ACTION3)
			SetPlayerSound(Myself,268280,SELECT_ACTION4)
			SetPlayerSound(Myself,268281,SELECT_ACTION5)
			SetPlayerSound(Myself,268282,SELECT_ACTION6) 
			SetPlayerSound(Myself,268283,SELECT_ACTION7)
			SetPlayerSound(Myself,268297,REACT_TO_DIE_GENERAL)
			SetPlayerSound(Myself,268298,REACT_TO_DIE_SPECIFIC)
			SetPlayerSound(Myself,268280,SELECT_RARE1)
			SetPlayerSound(Myself,268281,SELECT_RARE2)
			SetPlayerSound(Myself,268284,CRITICAL_HIT)
			SetPlayerSound(Myself,268285,CRITICAL_MISS)
			SetPlayerSound(Myself,268286,TARGET_IMMUNE)
			SetPlayerSound(Myself,268287,INVENTORY_FULL)
			SetPlayerSound(Myself,268288,PICKED_POCKET)
			SetPlayerSound(Myself,268289,HIDDEN_IN_SHADOWS)
			SetPlayerSound(Myself,268290,SPELL_DISRUPTED)
			SetPlayerSound(Myself,268291,SET_A_TRAP)
			SetGlobal("XA_BiteSoundSet", "LOCALS", 0)
			SetGlobal("XA_LCASoundSwap", "LOCALS", 0)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Set Sickness Sounds

	IF
		ActionListEmpty()
		GlobalGT("XA_CorwinBit", "GLOBAL", 2)
		!Global("XA_BiteSoundSet", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetPlayerSound(Myself,@12,MORALE)
			SetPlayerSound(Myself,@13,HAPPY)
			SetPlayerSound(Myself,@14,UNHAPPY_ANNOYED)
			SetPlayerSound(Myself,@12,UNHAPPY_SERIOUS)
			SetPlayerSound(Myself,@13,UNHAPPY_BREAKING_POINT)
			SetPlayerSound(Myself,@14,LEADER)
			SetPlayerSound(Myself,@12,TIRED)
			SetPlayerSound(Myself,@13,BORED)
			SetPlayerSound(Myself,@14,BATTLE_CRY1)
			SetPlayerSound(Myself,@12,BATTLE_CRY2)
			SetPlayerSound(Myself,@13,BATTLE_CRY3)
			SetPlayerSound(Myself,@14,BATTLE_CRY4)
			SetPlayerSound(Myself,@12,BATTLE_CRY5)
			SetPlayerSound(Myself,268273,DAMAGE)
			SetPlayerSound(Myself,268274,DYING)
			SetPlayerSound(Myself,@13,HURT)
			SetPlayerSound(Myself,@14,AREA_FOREST)
			SetPlayerSound(Myself,@12,AREA_CITY)
			SetPlayerSound(Myself,@13,AREA_DUNGEON)
			SetPlayerSound(Myself,@14,AREA_DAY)
			SetPlayerSound(Myself,@12,AREA_NIGHT)
			SetPlayerSound(Myself,@13,SELECT_COMMON1)
			SetPlayerSound(Myself,@14,SELECT_COMMON2)
			SetPlayerSound(Myself,@12,SELECT_COMMON3)
			SetPlayerSound(Myself,@13,SELECT_COMMON4)
			SetPlayerSound(Myself,@14,SELECT_COMMON5)
			SetPlayerSound(Myself,@12,SELECT_COMMON6)
			SetPlayerSound(Myself,@13,SELECT_ACTION1)
			SetPlayerSound(Myself,@14,SELECT_ACTION2)
			SetPlayerSound(Myself,@12,SELECT_ACTION3)
			SetPlayerSound(Myself,@13,SELECT_ACTION4)
			SetPlayerSound(Myself,@14,SELECT_ACTION5)
			SetPlayerSound(Myself,@12,SELECT_ACTION6) 
			SetPlayerSound(Myself,@13,SELECT_ACTION7)
			SetPlayerSound(Myself,@14,REACT_TO_DIE_GENERAL)
			SetPlayerSound(Myself,@12,REACT_TO_DIE_SPECIFIC)
			SetPlayerSound(Myself,@13,SELECT_RARE1)
			SetPlayerSound(Myself,@14,SELECT_RARE2)
			SetPlayerSound(Myself,@12,CRITICAL_HIT)
			SetPlayerSound(Myself,@13,CRITICAL_MISS)
			SetPlayerSound(Myself,@14,TARGET_IMMUNE)
			SetPlayerSound(Myself,@14,INVENTORY_FULL)
			SetPlayerSound(Myself,@12,PICKED_POCKET)
			SetPlayerSound(Myself,@13,SPELL_DISRUPTED)
			SetPlayerSound(Myself,@14,SET_A_TRAP)
			SetGlobal("XA_BiteSoundSet", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
//}

//{ 10: Interactions concerning the Return to BG Mini Quest

	//{ Complimenting Corwin's Family
	IF
		AreaCheck("BG1300") //SE Baldur's Gate
		Global("XA_AVComplimentFamily", "GLOBAL", 1)
		Global("XA_CanTalk", "LOCALS", 1)
		IsValidForPartyDialogue("Aerie")
	THEN
		//Dialog B-66, B-79, B-82, B-83, B-84
		RESPONSE #100
			Interact("Aerie")
	END
	
	IF
		AreaCheck("BG1300") //SE Baldur's Gate
		Global("XA_AVComplimentFamily", "GLOBAL", 1)
		Global("XA_CanTalk", "LOCALS", 1)
		IsValidForPartyDialogue("Neera")
		
	THEN
		//Dialog B-66, B-79, B-82, B-83, B-84
		RESPONSE #100
			Interact("Neera")
	END
	
	IF
		AreaCheck("BG1300") //SE Baldur's Gate
		Global("XA_AVComplimentFamily", "GLOBAL", 1)
		Global("XA_CanTalk", "LOCALS", 1)
		IsValidForPartyDialogue("Valygar")
		
	THEN
		//Dialog B-66, B-79, B-82, B-83, B-84
		RESPONSE #100
			Interact("Valygar")
	END
	//}

	//{ Corwin Hall of Wonders Arrest
	IF 
		Global("XA_CorwinArrest", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			//Dialog J-50
			StartDialog("XACORWIJ", Player1)
	END
	//}

	//{ Rohma Kidnapped
	IF 
		Global("XA_RohmaKidnapped", "GLOBAL", 2)
		//See(Player1)
	THEN
		RESPONSE #100
			//Dialog J-68
			StartDialog("XACORWIJ", Player1)
	END
	//}

	//{ SoD Anxiety
	IF 
		Global("XA_SoDAnxiety", "GLOBAL", 1)
		GlobalTimerExpired("XA_SoDAnxietyTimer", "GLOBAL")
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_SoDAnxiety", "GLOBAL", 2)
			PlaySong(142)
			//Dialog J-39
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Corwin Leave for Family
	IF
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinLeaveForFamily", "GLOBAL", 1)
	THEN
		RESPONSE #100
			//Dialogs J-19, J-20
			StartDialog("XACORWIJ", Player1)
	END
	//}
	
	//{ Corwin Need to See Family
	IF
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinNeedSeeFamily", "GLOBAL", 1)
	THEN
		RESPONSE #100
			//Dialog J-18
			StartDialog("XACORWIJ", Player1)
	END
	//}	

	//{ Meet Tianna
	IF
		Global("XA_AskCorwinAboutTianna", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			Wait(1)
			//Dialog J-15
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Dialog init after Corwin / Neoma reunite
	IF 
		Global("XA_ReturnToBG", "GLOBAL", 1)
		Global("XA_XACS15Cutscene", "GLOBAL", 5)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		!See("XANEOMA")
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			PlaySong(146)
			SetGlobal("XA_XACS15Cutscene", "GLOBAL", 6)
			//Dialog J-17
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Request Corwin ToB
	IF
		Global("XA_BGEND3", "GLOBAL", 1)
		Global("XA_DidNotRequestCorwin", "GLOBAL", 1)
		GlobalGT("XA_CorwinOpinionOfPlayer", "GLOBAL", 99)
		!Global("XA_CorwinRomanceActive", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			Wait(3)
			//Dialog J-2
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END

	IF
		Global("XA_BGEND3", "GLOBAL", 1)
		Global("XA_DidNotRequestCorwin", "GLOBAL", 1)
		GlobalGT("XA_CorwinOpinionOfPlayer", "GLOBAL", 99)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			Wait(3)
			PlaySong(146)
			//Dialog J-2
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END

	IF
		Global("XA_BGEND4", "GLOBAL", 1)
		Global("XA_DidRequestCorwin", "GLOBAL", 1)
		!Global("XA_CorwinRomanceActive", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			Wait(3)
			//Dialog J-2
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END

	IF
		Global("XA_BGEND4", "GLOBAL", 1)
		Global("XA_DidRequestCorwin", "GLOBAL", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			Wait(3)
			PlaySong(146)
			//Dialog J-2
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Kill Beno
	IF 
		OR(2)
			Global("XA_CorwinKillBeno", "GLOBAL", 1)
			Global("XA_CorwinBenoST", "GLOBAL", 1)
		ActionListEmpty()
		!Range("XABENO2", 4)
	THEN
		RESPONSE #100
			MoveToObject("XATRBENO")
			Continue()
	END

	IF 
		OR(2)
			Global("XA_CorwinKillBeno", "GLOBAL", 1)
			Global("XA_CorwinBenoST", "GLOBAL", 1)
		Range("XABENO2", 4)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("XACORWIN", FaceObject("XABENO2"))
			//Dialog J-5
			ActionOverride("XACORWIN", StartDialog("XACORWIJ", Player1))
			SetInterrupt(TRUE)
	END
	//}

//} BGMiniQuest Interaction End

//{ 12: Reputation Handling
IF 
	Global("XA_CanTalkToPlayer", "LOCALS", 1)
	ReputationLT(Player1,7)
	Global("XA_CanLeaveParty", "LOCALS", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinLeftPoorRep", "GLOBAL", 1)
		StartDialog("XACORWIJ", Player1)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	InParty(Myself)
	ReputationLT(Player1,8)
	GlobalLT("XA_CorwinRepWarning", "GLOBAL", 1)
THEN 
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("XA_CorwinRepWarningTimer", "GLOBAL", ONE_ROUND)
		SetGlobal("XA_CorwinRepWarning", "GLOBAL", 1)
		SetInterrupt(TRUE)
		Continue()
END

IF 
	ActionListEmpty()
	Global("XA_CorwinRepWarning", "GLOBAL", 1)
	Global("XA_CanTalkToPlayer", "LOCALS", 1)
	ReputationLT(Player1,8)
	GlobalTimerExpired("XA_CorwinRepWarningTimer", "GLOBAL")
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinRepWarning", "GLOBAL", 2)
		StartDialog("XACORWIJ", Player1)
		SetInterrupt(TRUE)
END

IF 
	ActionListEmpty()
	GlobalGT("XA_CorwinRepWarning", "GLOBAL", 0)
	ReputationGT(Player1,7)
THEN
	RESPONSE #100
		SetGlobal("XA_CorwinRepWarning", "GLOBAL", 0)
		Continue()
END
//}

//{ 13: Corwin Can Leave Party Check
IF 
	ActionListEmpty()
	InParty(Myself)
	!Global("XA_CanLeaveParty", "LOCALS", 1)
	!Global("XA_PlanarSphere", "GLOBAL", 1)
	!Global("XA_PlanarPrison", "GLOBAL", 1)
	!Global("XA_InUnderdark", "GLOBAL", 1)
	!Global("XA_TrappedInDemonPrison", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_CanLeaveParty", "LOCALS", 1)
		Continue()
END

IF 
	ActionListEmpty()
	InParty(Myself)
	Global("XA_CanLeaveParty", "LOCALS", 1)
	OR(4)
		Global("XA_PlanarSphere", "GLOBAL", 1)
		Global("XA_PlanarPrison", "GLOBAL", 1)
		Global("XA_InUnderdark", "GLOBAL", 1)
		Global("XA_TrappedInDemonPrison", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_CanLeaveParty", "LOCALS", 0)
		Continue()
END
//}

//{ 14: Check if the Player is in the Demon's Prison 
IF
	ActionListEmpty()
	InParty(Myself)
	!Global("XA_TrappedInDemonPrison", "GLOBAL", 1)
	OR(5)
		AreaCheck("XADEMSAN")
		AreaCheck("XAG1")
		AreaCheck("XAG2A")
		AreaCheck("XAG3")
		AreaCheck("XAPAINT1")
THEN
	RESPONSE #100
		SetGlobal("XA_TrappedInDemonPrison", "GLOBAL", 1)
		Continue()
END

IF
	ActionListEmpty()
	InParty(Myself)
	Global("XA_TrappedInDemonPrison", "GLOBAL", 1)
	!AreaCheck("XADEMSAN")
	!AreaCheck("XAG1")
	!AreaCheck("XAG2A")
	!AreaCheck("XAG3")
	!AreaCheck("XAPAINT1")
THEN
	RESPONSE #100
		SetGlobal("XA_TrappedInDemonPrison", "GLOBAL", 0)
		Continue()
END
//}

//{ 15: Check if the Player is in the Planar Sphere
IF 
	ActionListEmpty()
	InParty(Myself)
	GlobalLT("XA_PlanarSphere", "GLOBAL", 1)
	OR(6)
		AreaCheck("AR0410")
		AreaCheck("AR0411")
		AreaCheck("AR0412")
		AreaCheck("AR0413")
		AreaCheck("AR0414")
		AreaCheck("AR0415")
THEN 
	RESPONSE #100
		SetGlobal("XA_PlanarSphere", "GLOBAL", 1)
		Continue()
END

IF 
	ActionListEmpty()
	InParty(Myself)
	Global("XA_PlanarSphere", "GLOBAL", 1)
	!AreaCheck("AR0410")
	!AreaCheck("AR0411")
	!AreaCheck("AR0412")
	!AreaCheck("AR0413")
	!AreaCheck("AR0414")
	!AreaCheck("AR0415")
THEN 
	RESPONSE #100
		SetGlobal("XA_PlanarSphere", "GLOBAL", 0)
		Continue()
END
//} End Planar Sphere Check

//{ 16: Check if the Player is in the Planar Prison
IF 
	ActionListEmpty()
	InParty(Myself)
	GlobalLT("XA_PlanarPrison", "GLOBAL", 1)
	OR(6)
		AreaCheck("AR0516")
		AreaCheck("AR0517")
		AreaCheck("AR0518")
		AreaCheck("AR0519")
		AreaCheck("AR0520")
		AreaCheck("AR0521")
THEN 
	RESPONSE #100
		SetGlobal("XA_PlanarPrison", "GLOBAL", 1)
		Continue()
END

IF 
	ActionListEmpty()
	InParty(Myself)
	Global("XA_PlanarPrison", "GLOBAL", 1)
	!AreaCheck("AR0516")
	!AreaCheck("AR0517")
	!AreaCheck("AR0518")
	!AreaCheck("AR0519")
	!AreaCheck("AR0520")
	!AreaCheck("AR0521")
THEN 
	RESPONSE #100
		SetGlobal("XA_PlanarPrison", "GLOBAL", 0)
		Continue()
END
//} End Planar Prison Check

//{ 17: Check if the Player is in the Underdark
IF
	ActionListEmpty()
	InParty(Myself)
	GlobalLT("XA_InUnderdark", "GLOBAL", 1)
	OR(18)
		AreaCheck("AR2100") // Underdark
		AreaCheck("AR2101") // Beholder Cave in Underdark
		AreaCheck("AR2102") // Adalon's Cave
		AreaCheck("AR2200") // Ust Natha
		AreaCheck("AR2201") // Ust Natha Temple
		AreaCheck("AR2202") // Ust Natha Inn 1FL
		AreaCheck("AR2203") // Ust Natha Inn 2FL
		AreaCheck("AR2204") // Ust Natha House
		AreaCheck("AR2205") // Ust Natha House
		AreaCheck("AR2206") // Qilue's House
		AreaCheck("AR2207") // Deirex's Tower
		AreaCheck("AR2208") // Jarlaxle's House
		AreaCheck("AR2209") // Jarlaxle's House
		AreaCheck("AR2210") // Deirex's Cave
		AreaCheck("AR2300") // Sahuagin City
		AreaCheck("AR2400") // Mind Flayers
		AreaCheck("AR2401") // Cave to Exit
		AreaCheck("AR2402") // Kuo Toa
THEN 
	RESPONSE #100
		////DisplayStringHead(Myself, ~DEBUG_In Underdark~)
		SetGlobal("XA_InUnderdark", "GLOBAL", 1)
		Continue()
END

IF
	ActionListEmpty()
	InParty(Myself)
	Global("XA_InUnderdark", "GLOBAL", 1)
	!AreaCheck("AR2100") // Underdark
	!AreaCheck("AR2101") // Beholder Cave in Underdark
	!AreaCheck("AR2102") // Adalon's Cave
	!AreaCheck("AR2200") // Ust Natha
	!AreaCheck("AR2201") // Ust Natha Temple
	!AreaCheck("AR2202") // Ust Natha Inn 1FL
	!AreaCheck("AR2203") // Ust Natha Inn 2FL
	!AreaCheck("AR2204") // Ust Natha House
	!AreaCheck("AR2205") // Ust Natha House
	!AreaCheck("AR2206") // Qilue's House
	!AreaCheck("AR2207") // Deirex's Tower
	!AreaCheck("AR2208") // Jarlaxle's House
	!AreaCheck("AR2209") // Jarlaxle's House
	!AreaCheck("AR2210") // Deirex's Cave
	!AreaCheck("AR2300") // Sahuagin City
	!AreaCheck("AR2400") // Mind Flayers
	!AreaCheck("AR2401") // Cave to Exit
	!AreaCheck("AR2402") // Kuo Toa
THEN 
	RESPONSE #100
		////DisplayStringHead(Myself, ~DEBUG_Not In Underdark~)
		SetGlobal("XA_InUnderdark", "GLOBAL", 0)
		Continue()
END
//} End Underdark Check

//{ 18: Event Checks

	//{ Player became a Lich
	IF
		Race(Player1, LICH)
		InParty(Myself)
		GlobalLT("XA_LC_CorwinLeaveLich", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_LC_CorwinLichTimer", "GLOBAL", THREE_DAYS)
			SetGlobal("XA_LC_CorwinLeaveLich", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		GlobalTimerExpired("XA_LC_CorwinLichTimer", "GLOBAL")
		Global("XA_LC_CorwinLeaveLich", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_LC_CorwinLeaveLich", "GLOBAL", 2)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Dings Joined
	IF
		GlobalLT("XA_LC_DingsCorwin", "GLOBAL", 1)
		InParty(Myself)
		PartyHasItem("OHNDINGS")
		GlobalLT("XA_ReturnToBG", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_LC_DingsCorwinTimer", "GLOBAL", THREE_DAYS)
			SetGlobal("XA_LC_DingsCorwin", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
	
	//{ Dings Interaction 1
	IF
		InParty(Myself)
		PartyHasItem("OHNDINGS")
		GlobalLT("XA_LC_DingsCorwin", "GLOBAL", 2)
		!AreaType(DUNGEON)
		OR(2)
			GlobalTimerExpired("XA_DingsCorwinTimer", "GLOBAL")
			Global("XA_LC_DingsDebug", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_LC_DingsDebug", "GLOBAL", 0)
			SetGlobal("XA_LC_DingsCorwin", "GLOBAL", 2)
			CreateCreature("XADINGS", [-1.-1], N)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Kalah Killed
	IF
		AreaCheck("AR0607")
		ActionListEmpty()
		Dead("Kalah")
		InParty(Myself)
		GlobalLT("XA_LC_CorwinKalah", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_LC_CorwinKalahTimer", "LOCALS", ONE_ROUND)
			SetGlobal("XA_LC_CorwinKalah", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		GlobalTimerExpired("XA_LC_CorwinKalahTimer", "LOCALS")
		GlobalLT("XA_LC_CorwinKalahRemark", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_LC_CorwinKalahRemark", "LOCALS", 1)
			DisplayStringHead( Myself, @27)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Corwin Larceny Talk
	IF
		ActionListEmpty()
		InParty(Myself)
		GlobalGT("MaeVarWork", "GLOBAL", 0)
		GlobalLT("XA_LC_CorwinLarceny", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_LC_CorwinLarcenyTimer", "LOCALS", ONE_ROUND)
			//DisplayStringHead(Myself, ~Timer started~)
			SetGlobal("XA_LC_CorwinLarceny", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		GlobalTimerExpired("XA_LC_CorwinLarcenyTimer", "LOCALS")
		GlobalLT("XA_LC_CorwinLarcenyTalk", "LOCALS", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		ReputationGT(Player1,9) //Amulet
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_LC_CorwinLarcenyTalk", "LOCALS", 1)
			//DisplayStringHead(Myself, ~Start Dialog~)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		GlobalTimerExpired("XA_LC_CorwinLarcenyTimer", "LOCALS")
		GlobalLT("XA_LC_CorwinLarcenyTalk", "LOCALS", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		ReputationLT(Player1,10) //Statue
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_LC_CorwinLarcenyTalk", "LOCALS", 2)
			//DisplayStringHead(Myself, ~Start Dialog~)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Completed Challenge 3
	IF
		InParty(Myself)
		Global("BeginChallenge3", "GLOBAL", 3)
		GlobalLT("XA_C3TimerSet", "LOCALS", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_C3TimerSet", "LOCALS", 1)
			SetGlobalTimer("XA_C3Timer", "LOCALS", ONE_HOUR)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Killed General
	IF
		Dead("amtgen01")
		GlobalLT("XA_GeneralDeadTalk", "LOCALS", 1)
		!ActuallyInCombat()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_GeneralDeadTalk", "LOCALS", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Killed Wraith
	IF
		Global("XA_RohmaWraith", "GLOBAL", 1)
		Dead("hgwra01")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_RohmaWraith", "GLOBAL", 2)
			SetGlobalTimer("XA_RohmaWraithTimer", "LOCALS", ONE_ROUND)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		!ActuallyInCombat()
		Global("XA_RohmaWraith", "GLOBAL", 2)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalTimerExpired("XA_RohmaWraithTimer", "LOCALS")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_RohmaWraith", "GLOBAL", 3)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Saved Father in Saradush
	IF
		AreaCheck("AR5000")
		Global("FatherKilled","AR5000",2)
		GlobalLT("XA_CommentOnFather", "LOCALS", 1)
		!InMyArea("orphan2")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CommentOnFather", "LOCALS", 1)
			DisplayStringHead(Myself, @22)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Gorge Tree Climb
	IF
		Global("OHD_GORGE_NTRJEX","OH5100",2)
		GlobalLT("XA_CorwinOH5100", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ForceTreeTalk", "GLOBAL", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Helped Ginia
	IF
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		Global("HelpGinia","GLOBAL",3)
		GlobalLT("XA_CorwinGinia", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			IncrementGlobal("XA_CorwinOpinionOfPlayer", "GLOBAL", 1)
			SetGlobal("XA_CorwinGinia", "GLOBAL", 1)
			DisplayStringHead(Myself, @22)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
	
	//{ See Statue
	IF
		GlobalLT("XA_CorwinStatueTalk", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		OR(6)
			See("statue01")
			See("statue02")
			See("statue03")
			See("statue04")
			See("statue05")
			See("statue06")
		OR(6)
			Range("statue01", 10)
			Range("statue02", 10)
			Range("statue03", 10)
			Range("statue04", 10)
			Range("statue05", 10)
			Range("statue06", 10)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinStatueTalk", "GLOBAL", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Slapped Delcia
	IF
		ActionListEmpty()
		GlobalGT("XA_SlappedDelcia", "GLOBAL", 0)
		GlobalLT("XA_SlapTalk", "LOCALS", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		!See("Delcia")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_SlapTalk", "LOCALS", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Entered Fire Temple 5204
	IF
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalLT("XA_AR5204TimerSet", "LOCALS", 1)
		AreaCheck("AR5204")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AR5204TimerSet", "LOCALS", 1)	
			SetGlobalTimer("XA_AR5204Timer", "LOCALS", ONE_ROUND)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalTimerExpired("XA_AR5204Timer", "LOCALS")
		GlobalLT("XA_AR5204_Talk", "LOCALS", 1)
		AreaCheck("AR5204")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself, @17)	
			SetGlobal("XA_AR5204_Talk", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Entered Sendai's Lair
	IF
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalLT("XA_AR6101TimerSet", "LOCALS", 1)
		AreaCheck("AR6101")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AR6101TimerSet", "LOCALS", 1)	
			SetGlobalTimer("XA_AR6101Timer", "LOCALS", ONE_ROUND)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalTimerExpired("XA_AR6101Timer", "LOCALS")
		GlobalLT("XA_AR6101_Talk", "LOCALS", 1)
		AreaCheck("AR6101")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself, @26)	
			SetGlobal("XA_AR6101_Talk", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Entered De'Arnise Keep
	IF
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalLT("XA_AR1300TimerSet", "LOCALS", 1)
		OR(6)
			AreaCheck("AR1301")
			AreaCheck("AR1302")
			AreaCheck("AR1303")
			AreaCheck("AR1305")
			AreaCheck("AR1306")
			AreaCheck("AR1307")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AR1300TimerSet", "LOCALS", 1)	
			SetGlobalTimer("XA_AR1300Timer", "LOCALS", ONE_ROUND)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalTimerExpired("XA_AR1300Timer", "LOCALS")
		GlobalLT("XA_AR1300_Talk", "LOCALS", 1)
		OR(6)
			AreaCheck("AR1301")
			AreaCheck("AR1302")
			AreaCheck("AR1303")
			AreaCheck("AR1305")
			AreaCheck("AR1306")
			AreaCheck("AR1307")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself, @21)	
			SetGlobal("XA_AR1300_Talk", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
	
	//{ Entered Troll Hill
	IF
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalLT("XA_AR1904TimerSet", "LOCALS", 1)
		AreaCheck("AR1904")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AR1904TimerSet", "LOCALS", 1)	
			SetGlobalTimer("XA_AR1904Timer", "LOCALS", ONE_ROUND)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalTimerExpired("XA_AR1904Timer", "LOCALS")
		GlobalLT("XA_AR1904_Talk", "LOCALS", 1)
		AreaCheck("AR1904")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself, @21)	
			SetGlobal("XA_AR1904_Talk", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
	
	//{ Entered Demon Plane (Planar Sphere)
	IF
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalLT("XA_AR0414TimerSet", "LOCALS", 1)
		AreaCheck("AR0414")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AR0414TimerSet", "LOCALS", 1)	
			SetGlobalTimer("XA_AR0414Timer", "LOCALS", ONE_ROUND)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalTimerExpired("XA_AR0414Timer", "LOCALS")
		GlobalLT("XA_AR0414_Talk", "LOCALS", 1)
		AreaCheck("AR0414")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself, @17)	
			SetGlobal("XA_AR0414_Talk", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
	
	//{ Entered Maze
	IF
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalLT("XA_AR1202TimerSet", "LOCALS", 1)
		AreaCheck("AR1202")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AR1202TimerSet", "LOCALS", 1)	
			SetGlobalTimer("XA_AR1202Timer", "LOCALS", ONE_ROUND)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalTimerExpired("XA_AR1202Timer", "LOCALS")
		GlobalLT("XA_AR1202_Talk", "LOCALS", 1)
		AreaCheck("AR1202")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself, @20)	
			SetGlobal("XA_AR1202_Talk", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Entered Illithid Lair
	IF
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalLT("XA_AR2400TimerSet", "LOCALS", 1)
		AreaCheck("AR2400")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AR2400TimerSet", "LOCALS", 1)	
			SetGlobalTimer("XA_AR2400Timer", "LOCALS", ONE_ROUND)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalTimerExpired("XA_AR2400Timer", "LOCALS")
		GlobalLT("XA_AR2400_Talk", "LOCALS", 1)
		AreaCheck("AR2400")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself, @20)	
			SetGlobal("XA_AR2400_Talk", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Entered Beholder's Lair
	IF
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalLT("XA_AR2101TimerSet", "LOCALS", 1)
		AreaCheck("AR2101")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AR2101TimerSet", "LOCALS", 1)	
			SetGlobalTimer("XA_AR2101Timer", "LOCALS", ONE_ROUND)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalTimerExpired("XA_AR2101Timer", "LOCALS")
		GlobalLT("XA_AR2101_Talk", "LOCALS", 1)
		AreaCheck("AR2101")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself, @17)	
			SetGlobal("XA_AR2101_Talk", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Entered Adventurer's Mart
	IF
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalLT("XA_AR0702TimerSet", "LOCALS", 1)
		AreaCheck("AR0702")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AR0702TimerSet", "LOCALS", 1)	
			SetGlobalTimer("XA_AR0702Timer", "LOCALS", ONE_ROUND)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalTimerExpired("XA_AR0702Timer", "LOCALS")
		GlobalLT("XA_AR0702_Talk", "LOCALS", 1)
		AreaCheck("AR0702")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself, @19)	
			SetGlobal("XA_AR0702_Talk", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Entered Sewers
	IF
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalLT("XA_AR0701TimerSet", "LOCALS", 1)
		AreaCheck("AR0701")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AR0701TimerSet", "LOCALS", 1)	
			SetGlobalTimer("XA_AR0701Timer", "LOCALS", ONE_ROUND)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalTimerExpired("XA_AR0701Timer", "LOCALS")
		GlobalLT("XA_AR0701_Talk", "LOCALS", 1)
		AreaCheck("AR0701")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself, @18)	
			SetGlobal("XA_AR0701_Talk", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Entered Planar Prison
	IF
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalLT("XA_AR0516TimerSet", "LOCALS", 1)
		AreaCheck("AR0516")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AR0516TimerSet", "LOCALS", 1)	
			SetGlobalTimer("XA_AR0516Timer", "LOCALS", ONE_ROUND)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalTimerExpired("XA_AR0516Timer", "LOCALS")
		GlobalLT("XA_AR0516_Talk", "LOCALS", 1)
		AreaCheck("AR0516")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself, @17)	
			SetGlobal("XA_AR0516_Talk", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Entered Circus Tent (Illusion)
	IF
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalLT("XA_AR0604TimerSet", "LOCALS", 1)
		AreaCheck("AR0604")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AR0604TimerSet", "LOCALS", 1)	
			SetGlobalTimer("XA_AR0604Timer", "LOCALS", ONE_ROUND)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalTimerExpired("XA_AR0604Timer", "LOCALS")
		GlobalLT("XA_AR0604_Talk", "LOCALS", 1)
		AreaCheck("AR0604")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			DisplayStringHead(Myself, @16)	
			SetGlobal("XA_AR0604_Talk", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Neb Killed While Corwin in Party 
	IF
		ActionListEmpty()
		!ActuallyInCombat()
		Global("XA_NebFight", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalLT("XA_NebDead", "GLOBAL", 1)
		OR(2)
			Dead("Neb")
			Dead("XANEB")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_NebDead", "GLOBAL", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Caelar Jailed
	IF 
		ActionListEmpty()
		Global("XA_CorwinCaelarJail", "GLOBAL", 1)
		GlobalLT("XA_CorwinCaelarJailTimerSet", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinCaelarJailTimer", "GLOBAL", TWO_ROUNDS)
			SetGlobal("XA_CorwinCaelarJailTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
	END
	
	IF
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalTimerExpired("XA_CorwinCaelarJailTimer", "GLOBAL")
		GlobalLT("XA_CorwinCaelarJailTalk", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinCaelarJailTalk", "GLOBAL", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Caelar Went Home
	IF 
		ActionListEmpty()
		Global("XA_CorwinCaelarHome", "GLOBAL", 1)
		GlobalLT("XA_CorwinCaelarHomeTimerSet", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinCaelarHomeTimer", "GLOBAL", TWO_ROUNDS)
			SetGlobal("XA_CorwinCaelarHomeTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
	END
	
	IF
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalTimerExpired("XA_CorwinCaelarHomeTimer", "GLOBAL")
		GlobalLT("XA_CorwinCaelarHomeTalk", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinCaelarHomeTalk", "GLOBAL", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Beno Exploded
	IF
		ActionListEmpty()
		InParty(Myself)
		GlobalTimerExpired("XA_CorwinBenoSoul", "GLOBAL")
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalLT("XA_CorwinBenoSoulTalk", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinBenoSoulTalk", "GLOBAL", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Checks if Dorn's patrons are dead
	IF
		ActionListEmpty()
		GlobalLT("XA_DornPatronsDead", "GLOBAL", 1)
		Dead("ohdazoth")  // Azothet
		Dead("ohdugoth")  // Ur-Gothoz
	THEN
		RESPONSE #100
			SetGlobal("XA_DornPatronsDead", "GLOBAL", 1)
			Continue()
	END
	//}

	//{ Player gives soul fragment to Sarevok
	IF
		ActionListEmpty()
		GlobalGT("SarevokAlive", "GLOBAL", 0)
		GlobalLT("ImoenGiveSoul","GLOBAL",2)
		Global("XA_CorwinRomanceActive","GLOBAL",2)
		!Global("XA_SarevokSoulTimerSet", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_SarevokSoulTimer", "GLOBAL",TWO_DAYS)
			SetGlobal("XA_SarevokSoulTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Wedding Hostile
	IF 
		ActionListEmpty()
		Global("OHD_WEDDING_HOSTILE","OH5000",3)
		GlobalLT("XA_WeddingHostile", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_WeddingHostile", "GLOBAL", 1)
			SetGlobal("XA_CorwinLeaveWedding", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
	
	//{ Entered Amkethran
	IF
		ActionListEmpty()
		InParty(Myself)
		AreaCheck("AR5500")
		!Global("XA_AmkethranTimerSet", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_AmkethranTimer", "GLOBAL", ONE_ROUND)
			SetGlobal("XA_AmkethranTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalTimerExpired("XA_AmkethranTimer", "GLOBAL")
		GlobalLT("XA_MessageToBG", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			PlaySong(142)
			SetGlobal("XA_MessageToBG", "GLOBAL", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Aerie Pregnant Check
	IF
		ActionListEmpty()
		GlobalGT("babytalk", "GLOBAL", 0)
		IsValidForPartyDialog("Aerie")
		!Global("XA_CorwinAerieBabyTimerSet", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinAerieBabyTimerSet", "GLOBAL", 1)
			SetGlobalTimer("XA_CorwinAerieBabyTimer", "GLOBAL", ONE_DAY)
			SetInterrupt(TRUE)
			Continue()
	END	
	//}
	
	//{ Entered Yaga-Shura Camp
	IF
		GlobalGT("YagaShuraHeart", "GLOBAL", 0)
		ActionListEmpty()
		GlobalLT("XA_YagaTimerSet", "GLOBAL", 1)
		AreaCheck("AR5203")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_YagaTimer", "GLOBAL", ONE_ROUND)
			SetGlobal("XA_YagaTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		AreaCheck("AR5203")
		Gender(Player1, MALE)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		GlobalGT("XA_CorwinPregnant", "GLOBAL", 0)
		GlobalLT("XA_PregnantOverride", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_PregnantOverride", "GLOBAL", 1)
			Continue()
	END
	//}
	
	//{ Sarevok Joined Party
	IF
		ActionListEmpty()
		InParty("Sarevok")
		InParty(Myself)
		GlobalLT("XA_CorwinComplainSarevok", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinComplainSarevokTimer", "GLOBAL", ONE_HOUR)
			SetGlobal("XA_CorwinComplainSarevok", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
	
	//{ Keldorn Wife Reconciled
	IF 
		ActionListEmpty()
		Global("LadyMaria","GLOBAL",5)
		!Global("XA_KeldornMaria", "GLOBAL", 1)
		Global("XA_CanTalk", "LOCALS", 1)
		GlobalLT("XA_Banter_CorwinKeldornOpt1", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_Banter_CorwinKeldornOpt1", "GLOBAL", 1)
			SetGlobal("XA_KeldornMaria", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}
	
	//{ Svir Gnome Hostilities
	IF
		ActionListEmpty()
		InParty(Myself)
		Global("SvirHostile", "GLOBAL", 1)
		!Global("XA_CorwinHostile", "GLOBAL", 1)
		!Global("XA_LeftPartySvir", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinHostile", "GLOBAL", 1)
			SetGlobal("XA_LeftPartySvir", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Met with Drizzt - Corwin vouched
	IF 
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinVouchedDrizz", "GLOBAL", 1)
		!InMyArea("C6DRIZZ")
		!Dead("C6DRIZZ")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinVouchedDrizz", "GLOBAL", 2)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Grove Poisoning
	IF
		ActionListEmpty()
		InParty(Myself)
		Global("GrovePoisoned", "GLOBAL", 1)
		!Global("XA_CorwinHostile", "GLOBAL", 1)
		!Global("XA_LeftPartyGrove", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinHostle", "GLOBAL", 1)
			SetGlobal("XA_LeftPartyGrove", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Resurrection Gorge
	IF
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("OHD_ritual_interjects","GLOBAL",0)
		!InParty("dorn")  // Dorn
		AreaCheck("oh5120")  // Dorn - Resurrection Gorge Tree Interior
		OR(2)
			Dead("ohdvern")  // Vernus
			!Exists("ohdvern")  // Vernus
		Range("RitualCircle",20)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("OHD_ritual_interjects","GLOBAL",1)
			StartDialog("XACORWIJ",Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Slaver Stockade
	IF 
		Global("XA_BGSlaverPlot", "GLOBAL", 1)
		Global("XA_CorwinSlaverPlot", "GLOBAL", 1)
		AreaCheck("AR0405")
		!InMyArea("girl2")
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			StartDialog("XACORWIJ", Player1)
	END
	//}

	//{ Player's Soul Stolen
	IF 
		ActionListEmpty()
		Global("OpenJonBedroom","GLOBAL",1)
		GlobalLT("XA_PlayerSoulStolen", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalLT("XA_CorwinIrenicus", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_PlayerSoulStolen", "GLOBAL", 1)
			SetGlobalTimer("XA_OBJTimer1", "LOCALS", TWO_ROUNDS)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		GlobalTimerExpired("XA_OBJTimer1", "LOCALS")
		GlobalLT("XA_PlayerSoulTalk", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_PlayerSoulTalk", "GLOBAL", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Player Rescued Corwin in Spellhold
	IF
		ActionListEmpty()
		Global("OpenJonBedroom","GLOBAL",1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalGT("XA_CorwinIrenicus", "GLOBAL", 1)
		GlobalLT("XA_OBJTimer2Set", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_OBJTimer2Set", "LOCALS", 1)
			SetGlobalTimer("XA_OBJTimer2", "LOCALS", TWO_ROUNDS)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		GlobalTimerExpired("XA_OBJTimer2", "LOCALS")
		GlobalLT("XA_PlayerRescueTalk", "LOCALS", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_PlayerRescueTalk", "LOCALS", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	
	IF 
		GlobalTimerExpired("XA_CorwinRejoinTimer", "LOCALS")
		GlobalLT("XA_CorwinIrenicusTalk", "LOCALS", 1)
		IsValidForPartyDialogue(Player1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinIrenicusTalk", "LOCALS", 1)
			StartDialog("XACORWIP", Player1)
			SetInterrupt(TRUE)
	END
	//}
	//{ Bodhi Killed
	/* Checks if Corwin was in the party when Bodhi was killed */
	IF 
		ActionListEmpty()
		Global("BodhiDead","GLOBAL",1)
		IsValidForPartyDialogue("XACORWIN")
		!Global("XA_BodhiDead", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinImoenSoulTimer", "GLOBAL", ONE_HOUR)
			SetGlobal("XA_BodhiDead", "GLOBAL", 1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Phaere Alone With Player
	/* Checks if Corwin was in the party when the Player was alone with Phaere. */
	IF 
		GlobalGT("PhaereInnuendo","GLOBAL",1)
		GlobalLT("XA_AloneWithPhaere", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		!InMyArea("Phaere")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_AloneWithPhaere", "GLOBAL", 1)
			SetGlobal("XA_PhaereTalk", "GLOBAL", 1)
			PlaySong(142)
			StartDialogue("XACORWIJ", PLAYER1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Firkraag Deal
	/* Checks if Corwin was in the party when the deal with Firkraag was made. */
	IF 
		Global("FirkraagDeal","GLOBAL",1)
		!Global("XA_FirkraagDeal", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_FirkraagDeal", "GLOBAL", 1)
			SetGlobal("XA_CorwinFirkraagDeal", "GLOBAL", 1)
			//Dialog J-35
			StartDialogue("XACORWIJ", PLAYER1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Bodhi Job 2
	/* Checks if Corwin was in the party when the deal with Bodhi was made. Bodhi Job 2 */
	IF 
		Global("BodhiJob","GLOBAL",2)
		!Global("XA_BodhiDeal2", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_BodhiDeal2", "GLOBAL", 1)
			SetGlobal("XA_CorwinBodhiDeal", "GLOBAL", 1)
			StartDialogue("XACORWIJ", PLAYER1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Bodhi Job 3
	/* Checks if Corwin was in the party when the deal with Bodhi was made. Bodhi Job 3 */
	IF 
		Global("BodhiJob","GLOBAL",3)
		!Global("XA_BodhiDeal3", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_BodhiDeal3", "GLOBAL", 1)
			SetGlobal("XA_CorwinBodhiDeal", "GLOBAL", 1)
			StartDialogue("XACORWIJ", PLAYER1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Bodhi Job 4
	/* Checks if Corwin was in the party when the deal with Bodhi was made. Bodhi Job 4 */
	IF 
		Global("BodhiJob","GLOBAL",4)
		!Global("XA_BodhiDeal4", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_BodhiDeal4", "GLOBAL", 1)
			SetGlobal("XA_CorwinBodhiDeal", "GLOBAL", 1)
			StartDialogue("XACORWIJ", PLAYER1)
			SetInterrupt(TRUE)
	END
	//}

//} End Event Checks

//{ 19: Corwin Turn Hostile
IF 
	InParty(Myself)
	Global("XA_CorwinHostile", "GLOBAL", 1)
THEN 
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinHostile", "GLOBAL", 2)
		DisplayStringHead(Myself, @11)
		SetLeavePartyDialogFile()
		ChangeAIScript("", DEFAULT)
		LeaveParty()
		Enemy()
		SetInterrupt(TRUE)
END
//}

//{ 20: Corwin Sex Scripting
	//{ Checks is Corwin is Able
	IF
		ActionListEmpty()
		!Global("XA_CorwinCanHaveSex", "GLOBAL", 1)
		GlobalLT("XA_CorwinBit", "GLOBAL", 1)
		Gender(Player1, MALE)
		!HPPercentLT(Myself, 50)
		!HPPercentLT(Player1, 50)
		Global("XA_RohmaKidnapped", "GLOBAL", 0)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalLT("XA_CorwinPregnant", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_OnlySleep", "GLOBAL", 0)
			SetGlobal("XA_CorwinCanHaveSex", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CorwinCanHaveSex", "GLOBAL", 1)
		OR(7)
			GlobalGT("XA_RohmaKidnapped", "GLOBAL", 0)
			GlobalGT("XA_CorwinBit", "GLOBAL", 0)
			!Gender(Player1, MALE)
			HPPercentLT(Myself, 50)
			HPPercentLT(Player1, 50)
			!Global("XA_CanTalkToPlayer", "LOCALS", 1)
			GlobalGT("XA_CorwinPregnant", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinCanHaveSex", "GLOBAL", 0)
			Continue()
	END
	//}

	//{ Corwin Sex After Bodhi Experience
	/* If Corwin has not already had sex with CHARNAME, she will ask for sex after being healed / resurrected (Bodhi Bite) */
	IF 
		ActionListEmpty()
		Global("XA_CorwinCleansed", "GLOBAL", 2) 
		GlobalLT("XA_TimesHadSex", "GLOBAL", 1)
		!Global("XA_CorwinSexAfterBodhiTimerSet", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinSexAfterBodhiTimer", "GLOBAL", ONE_DAY)
			SetGlobal("XA_CorwinSexAfterBodhiTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END

	IF 
		ActionListEmpty()
		GlobalTimerExpired("XA_CorwinSexAfterBodhiTimer", "GLOBAL")
		GlobalLT("XA_TimesHadSex", "GLOBAL", 1)
		GlobalLT("XA_CorwinSexAfterBodhi", "GLOBAL", 1) //She has not asked for sex after Bodhi episode
		Global("XA_CorwinCanHaveSex", "GLOBAL", 1)
	THEN 
		RESPONSE #100
			SetGlobal("XA_CorwinSexAfterBodhi", "GLOBAL", 1)
			Continue()
	END
		
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinSexAfterBodhi", "GLOBAL", 1)
		Global("XA_CorwinCanHaveSex", "GLOBAL", 1)
		!Range(Player1, 6)
	THEN
		RESPONSE #100
			MoveToObject(Player1)
			Continue()
	END

	IF 
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinSexAfterBodhi", "GLOBAL", 1)
		Global("XA_CorwinCanHaveSex", "GLOBAL", 1)
		Range(Player1, 7)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			PlaySong(146)
			//Dialog J-51
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Corwin After Sex Interaction 1
	IF
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinSex_1", "GLOBAL", 3)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			Wait(1)
			//Dialog J-44
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ After Sex Party Banter
	IF
		ActionListEmpty()
		Global("XA_CorwinSex_1", "GLOBAL", 4)
		GlobalLT("XA_CorwinSexNoSleepTimerSet", "GLOBAL", 1)
	THEN
		RESPONSE #100	
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinSexNoSleepTimer", "GLOBAL", ONE_ROUND)
			SetGlobal("XA_CorwinSexNoSleepTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		GlobalTimerExpired("XA_CorwinSexNoSleepTimer", "GLOBAL")
		GlobalLT("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
		OR(6)
			IsValidForPartyDialogue("Aerie")
			IsValidForPartyDialogue("Neera")
			IsValidForPartyDialogue("Nalia")
			IsValidForPartyDialogue("Imoen2")
			IsValidForPartyDialogue("Jaheira")
			IsValidForPartyDialogue("Viconia")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
			////DisplayStringHead(Myself, ~DEBUG: CSNC A~)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF 
		ActionListEmpty()
		GlobalTimerExpired("XA_CorwinSexNoSleepTimer", "GLOBAL")
		GlobalLT("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
		!IsValidForPartyDialogue("Aerie")
		!IsValidForPartyDialogue("Neera")
		!IsValidForPartyDialogue("Nalia")
		!IsValidForPartyDialogue("Imoen2")
		!IsValidForPartyDialogue("Jaheira")
		!IsValidForPartyDialogue("Viconia")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSexNoSleepComplain", "GLOBAL", 2)
			////DisplayStringHead(Myself, ~DEBUG: CSNC B~)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		Global("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		IsValidForPartyDialog("Aerie")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Aerie", StartDialog("AERIEJ", Player1))
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		IsValidForPartyDialog("Imoen2")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Imoen2", StartDialog("IMOEN2J", Player1))
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		IsValidForPartyDialog("Nalia")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Nalia", StartDialog("NALIAJ", Player1))
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		IsValidForPartyDialog("Neera")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Neera", StartDialog("NEERAJ", Player1))
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		IsValidForPartyDialog("Jaheira")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride("Jaheira", StartDialog("JAHEIRAJ", Player1))
			SetInterrupt(TRUE)
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CorwinSexNoSleepComplain", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinSexNoSleepComplain", "GLOBAL", 2)
			Continue()
	END
	//}

	//{ After Sex HP Boost
	IF 
		ActionListEmpty()
		Global("XA_CorwinSexBoost", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSexBoost", "GLOBAL", 0)
			SetGlobalTimer("XA_CorwinSexTimer", "GLOBAL", THREE_DAYS)
			IncrementGlobal("XA_CorwinOpinionOfPlayer", "GLOBAL", 1)
			ApplySpellRES("bdrejuve","XACORWIN")
			ApplySpellRES("bdrejuve",Player1)
			ChangeStat("XACORWIN", MINHITPOINTS, 5, ADD)
			ChangeStat(Player1, MINHITPOINTS, 5, ADD)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Corwin Sex Second Time
	IF
		ActionListEmpty()
		GlobalGT("XA_TimesHadSex", "GLOBAL", 0)
		GlobalLT("XA_Sex2TimerSet", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinSex_2_Timer", "GLOBAL", FOUR_DAYS)
			SetGlobal("XA_Sex2TimerSet", "LOCALS", 1)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		GlobalTimerExpired("XA_CorwinSex_2_Timer", "GLOBAL")
		GlobalLT("XA_CorwinSex_2", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalLT("XA_CorwinSex2_Init", "GLOBAL", 1)
		Global("XA_CorwinCanHaveSex", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSex2_Init", "GLOBAL", 1)
			PlaySong(146)
			//Dialog J-46
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

//} End Corwin Sex Scripting

//{ 21: Corwin Bite Disease Interactions

	//{ First Bit
	IF 
		ActionListEmpty()
		Global("XA_CorwinBit", "GLOBAL", 1)
		!ActuallyInCombat()
		IsValidForPartyDialog(Player1)
	THEN
		RESPONSE #100
			////DisplayStringHead(Myself, ~DEBUG_018~)
			SetGlobal("XA_CorwinBit", "GLOBAL", 2)
			Continue()
	END

	IF 
		ActionListEmpty()
		Global("XA_CorwinBit", "GLOBAL", 2)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		!Range(Player1, 6)
	THEN
		RESPONSE #100
			////DisplayStringHead(Myself, ~DEBUG_019~)
			MoveToObject(Player1)
			Continue()
	END

	IF 
		Global("XA_CorwinBit", "GLOBAL", 2)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Range(Player1, 7)
	THEN
		RESPONSE #100
			//Dialog J-31
			StartDialog("XACORWIJ", Player1)
	END
	//}

	//{ Bite Death Warning 2
	IF 
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinBit", "GLOBAL", 3)
		GlobalTimerExpired("XA_CorwinBitTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinBit", "GLOBAL", 4)
			//Dialog J-32
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Bite Death Warning 3
	IF 
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinBit", "GLOBAL", 5)
		GlobalTimerExpired("XA_CorwinBitTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinBit", "GLOBAL", 6)
			//Dialog J-33
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Death from Bite
	IF 
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinBit", "GLOBAL", 7)
		GlobalTimerExpired("XA_CorwinBitTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinBit", "GLOBAL", 8)
			//Dialog J-34
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	

	//{ Corwin Resurrected At Shadow Temple
	IF 
		!InParty(Myself)
		Global("XA_CorwinCleansed", "GLOBAL", 1)
		GlobalGT("XA_CorwinBit", "GLOBAL", 0)
		See(Player1)
	THEN
		RESPONSE #100
			//Dialog P-6
			SetInterrupt(FALSE)
			PlaySong(146)
			Wait(1)
			StartDialogNoSet(Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Corwin Bit - Apply Disease
	/* Corwin Bite Disease */
	/* This will reapply the disease while CorwinBit is greater than 0. CorwinBit is set to zero when Corwin is cleansed (or resurrected in the Shadow Temple). */

	IF 
		ActionListEmpty()
		GlobalGT("XA_CorwinBit", "GLOBAL", 0)
		!CheckSpellState(Myself, DISEASED)
	THEN 
		RESPONSE #100
			////DisplayStringHead(Myself, ~DEBUG_016~)
			ForceSpellRES("bdisease",Myself)
			Continue()
	END
	//}

	//{ Corwin Cured from Bodhi Disease
	/* Corwin Disease Cured */
	// Might need to re-write this. Concerned that if the script is interrupted, stat gains could erroneously continue
	IF 
		ActionListEmpty()
		Global("XA_CorwinCleansed", "GLOBAL", 2)
		GlobalLT("XA_CorwinCured", "GLOBAL", 1)
	THEN 
		RESPONSE #100
			//ForceSpell("XACORWIN",CLERIC_CURE_DISEASE)
			////DisplayStringHead(Myself, ~DEBUG_017~)
			SetInterrupt(FALSE)
			ChangeStat(Myself,CON,1,ADD)
			ChangeStat(Myself,DEX,1,ADD)
			ChangeStat(Myself,STR,1,ADD)
			ChangeStat(Myself,CHR,1,ADD)
			ReallyForceSpell(Myself,CLERIC_CURE_DISEASE)
			SetGlobal("XA_CorwinCured", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END

	//}

	//{ Corwin Healed with Bodhi's Death
	/* This handles Bodhi's death when Corwin was bit, is still alive, and in the party. */
	IF
		InParty(Myself)
		GlobalGT("XA_CorwinBit", "GLOBAL", 0)
		Global("BodhiDead","GLOBAL",1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ClearAllActions()
			StartCutSceneMode()
			StartCutSceneEx("XAAcs09a", FALSE)
			SetInterrupt(TRUE)
	END
	//}

	//{ Party Concerned Corwin Sick
	IF
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalGT("XA_CorwinBit", "GLOBAL", 0)
		GlobalTimerExpired("XA_CorwinSickPartyTimer", "GLOBAL")
		GlobalLT("XA_CorwinPartySick", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinPartySick", "GLOBAL", 1)
			Continue()
	END
	
	IF
		Global("XA_CorwinPartySick", "GLOBAL", 1)
		IsValidForPartyDialogue("Jaheira")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSick_Jaheira", "GLOBAL", 1)
			//Dialog B-6
			ActionOverride("JAHEIRA", StartDialog("JAHEIRAJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CorwinPartySick", "GLOBAL", 1)
		IsValidForPartyDialogue("Aerie")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSick_Aerie", "GLOBAL", 1)
			//Dialog B-5
			ActionOverride("AERIE", StartDialog("AERIEJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END

	IF
		Global("XA_CorwinPartySick", "GLOBAL", 1)
		IsValidForPartyDialogue("Korgan")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSick_Korgan", "GLOBAL", 1)
			//Dialog B-7
			ActionOverride("KORGAN", StartDialog("KORGANJ", Player1))
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CorwinPartySick", "GLOBAL", 1)
		IsValidForPartyDialogue("Imoen2")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinSick_Imoen", "GLOBAL", 1)
			//Dialog B-8
			ActionOverride("IMOEN2", StartDialog("IMOEN2J", "XACORWIN"))
			SetInterrupt(TRUE)
	END

	IF
		ActionListEmpty()
		Global("XA_CorwinPartySick", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinPartySick", "GLOBAL", 2)
			Continue()
	END
	//}

//} End Corwin Disease Interactions

//{ Romance Conflicts

	//{ Other Romance == 2
	IF
		ActionListEmpty()
		GlobalLT("XA_RomanceConflictTimerSet", "GLOBAL", 1)
		Global("XA_CorwinRomanceActive","GLOBAL",2)
		OR(8)
			Global("AerieRomanceActive","GLOBAL",2)
			Global("ViconiaRomanceActive","GLOBAL",2)
			Global("DornRomanceActive","GLOBAL",2)
			Global("NeeraRomanceActive","GLOBAL",2)
			Global("SarevokRomanceActive","GLOBAL",2)
			Global("JaheiraRomanceActive","GLOBAL",2)
			Global("HexxatRomanceActive","GLOBAL",2)
			Global("RasaadRomanceActive","GLOBAL",2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_RomanceConflictTimer", "GLOBAL", ONE_DAY)
			SetGlobal("XA_RomanceConflictTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
	END
	
	IF
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalTimerExpired("XA_RomanceConflictTimer", "GLOBAL")
		GlobalLT("XA_RomanceConflictTalk", "GLOBAL", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_RomanceConflictTalk", "GLOBAL", 1)
			//Dialog J-83
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Other Romance < 2
	
		//{ Aerie
		IF
			ActionListEmpty()
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("AerieRomanceActive", "GLOBAL", 2)
		THEN
			RESPONSE #100
				SetGlobal("AerieRomanceActive","GLOBAL",3)
				Continue()
		END
		//}

		//{ Viconia
		IF
			ActionListEmpty()
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("ViconiaRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("ViconiaRomanceActive","GLOBAL",3)
				Continue()
		END
		//}

		//{ Dorn
		IF
			ActionListEmpty()
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("DornRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("DornRomanceActive","GLOBAL",3)
				Continue()
		END
		//}
		
		//{ Neera
		IF
			ActionListEmpty()
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("NeeraRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("NeeraRomanceActive","GLOBAL",3)
				Continue()
		END
		//}

		//{ Sarevok
		IF
			ActionListEmpty()
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("AnomenRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("AnomenRomanceActive","GLOBAL",3)
				Continue()
		END
		//}

		//{ Jaheira
		IF
			ActionListEmpty()
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("JaheiraRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("JaheiraRomanceActive","GLOBAL",3)
				Continue()
		END
		//}

		//{ Hexxat
		IF
			ActionListEmpty()
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("HexxatRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("HexxatRomanceActive","GLOBAL",3)
				Continue()
		END
		//}
		
		//{ Rasaad
		IF
			ActionListEmpty()
			InParty(Myself)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
			GlobalLT("RasaadRomanceActive","GLOBAL",2)
		THEN
			RESPONSE #100
				SetGlobal("RasaadRomanceActive","GLOBAL",3)
				Continue()
		END
		//}
		
	//}

//}

//{ Check for old SoD items
IF 
	InParty(Myself)
	OR(2)
		GlobalLT("XA_SoDItemCheckTimerSet", "GLOBAL", 1)
		GlobalTimerExpired("XA_SoDItemCheckTimer", "GLOBAL")
	OR(2)
		PartyHasItem("BDBOW06") // Corwin's Bow (SoD)
		PartyHasItem("BDCHAN05") // Corwin's Armor (SoD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("XA_SoDItemCheckTimer", "GLOBAL", ONE_DAY)
		SetGlobal("XA_SoDItemCheckTimerSet", "GLOBAL", 1)
		
		ActionOverride(Player1, DestroyItem("BDBOW06"))
		ActionOverride(Player2, DestroyItem("BDBOW06"))
		ActionOverride(Player3, DestroyItem("BDBOW06"))
		ActionOverride(Player4, DestroyItem("BDBOW06"))
		ActionOverride(Player5, DestroyItem("BDBOW06"))
		ActionOverride(Player6, DestroyItem("BDBOW06"))
		
		ActionOverride(Player1, DestroyItem("BDCHAN05"))
		ActionOverride(Player2, DestroyItem("BDCHAN05"))
		ActionOverride(Player3, DestroyItem("BDCHAN05"))
		ActionOverride(Player4, DestroyItem("BDCHAN05"))
		ActionOverride(Player5, DestroyItem("BDCHAN05"))
		ActionOverride(Player6, DestroyItem("BDCHAN05"))
		SetInterrupt(TRUE)
		
		Continue()
END
//}

//{ Check Stats - SoD Corwin
IF
	!CheckStat("Corwin", 18, STR)
	GlobalLT("XA_Corwin_STR_Changed", "LOCALS", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 1)
		Continue()
END

IF
	!CheckStat("Corwin", 15, DEX)
	GlobalLT("XA_Corwin_DEX_Changed", "LOCALS", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 1)
		Continue()
END

IF
	!CheckStat("Corwin", 14, CON)
	GlobalLT("XA_Corwin_CON_Changed", "LOCALS", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 1)
		Continue()
END

IF
	!CheckStat("Corwin", 12, INT)
	GlobalLT("XA_Corwin_INT_Changed", "LOCALS", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 1)
		Continue()
END

IF
	!CheckStat("Corwin", 14, WIS)
	GlobalLT("XA_Corwin_WIS_Changed", "LOCALS", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 1)
		Continue()
END

IF
	!CheckStat("Corwin", 14, CHR)
	GlobalLT("XA_Corwin_CHR_Changed", "LOCALS", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 1)
		Continue()
END
//}

//{ Stat Adjustments to Match SoD Corwin

	//{ Adjust STR to Match SoD Corwin
	IF
		CheckStat("Corwin", 20, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 20, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 19, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 19, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 18, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 18, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 17, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 17, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 16, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 16, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 15, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 15, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 14, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 14, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 13, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 13, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 12, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 12, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 11, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 11, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 10, STR)
		Global("XA_Corwin_STR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, STR, 10, SET)
			SetGlobal("XA_Corwin_STR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Adjust DEX to Match SoD Corwin
	IF
		CheckStat("Corwin", 20, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 20, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 19, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 19, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 18, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 18, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 17, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 17, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 16, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 16, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 15, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 15, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 14, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 14, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 13, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 13, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 12, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 12, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 11, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 11, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 10, DEX)
		Global("XA_Corwin_DEX_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, DEX, 10, SET)
			SetGlobal("XA_Corwin_DEX_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Adjust WIS to Match SoD Corwin
	IF
		CheckStat("Corwin", 20, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 20, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 19, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 19, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 18, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 18, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 17, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 17, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 16, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 16, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 15, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 15, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 14, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 14, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 13, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 13, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 12, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 12, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 11, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 11, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 10, WIS)
		Global("XA_Corwin_WIS_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, WIS, 10, SET)
			SetGlobal("XA_Corwin_WIS_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Adjust CHR to Match SoD Corwin
	IF
		CheckStat("Corwin", 20, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 20, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 19, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 19, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 18, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 18, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 17, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 17, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 16, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 16, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 15, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 15, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 14, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 14, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 13, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 13, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 12, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 12, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 11, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 11, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 10, CHR)
		Global("XA_Corwin_CHR_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CHR, 10, SET)
			SetGlobal("XA_Corwin_CHR_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Adjust CON to Match SoD Corwin
	IF
		CheckStat("Corwin", 20, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 20, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 19, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 19, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 18, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 18, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 17, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 17, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 16, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 16, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 15, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 15, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 14, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 14, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 13, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 13, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 12, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 12, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 11, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 11, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 10, CON)
		Global("XA_Corwin_CON_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, CON, 10, SET)
			SetGlobal("XA_Corwin_CON_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

	//{ Adjust INT to Match SoD Corwin
	IF
		CheckStat("Corwin", 20, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 20, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 19, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 19, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 18, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 18, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 17, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 17, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 16, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 16, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 15, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 15, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 14, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 14, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 13, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 13, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 12, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 12, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 11, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 11, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		CheckStat("Corwin", 10, INT)
		Global("XA_Corwin_INT_Changed", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ChangeStat(Myself, INT, 10, SET)
			SetGlobal("XA_Corwin_INT_Changed", "LOCALS", 2)
			SetInterrupt(TRUE)
			Continue()
	END
	//}

//}

//{ Exp Boosts on Join

//{ Exp Boost after Re-Join in Spellhold
IF
	InParty(Myself)
	ActionListEmpty()
	!ActuallyInCombat()
	GlobalGT("XA_CorwinIrenicus", "GLOBAL", 4)
	GlobalLT("XA_CIExpBoost", "LOCALS", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CIExpBoost", "LOCALS", 1)
		ChangeStat(Myself,XP,35000,ADD)
		AddJournalEntry(@25, INFO)
		SetInterrupt(TRUE)
		Continue()
END
//}

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,249999)
  XPLT(Player1,500000)
  XPLT(Myself,500000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,250000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,499999)
  XPLT(Player1,750000)
  XPLT(Myself,750000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,500000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,749999)
  XPLT(Player1,1000000)
  XPLT(Myself,1000000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,750000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,999999)
  XPLT(Player1,1250000)
  XPLT(Myself,1250000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,1000000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,1249999)
  XPLT(Player1,1500000)
  XPLT(Myself,1500000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,1250000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,1499999)
  XPLT(Player1,1750000)
  XPLT(Myself,1750000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,1500000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,1749999)
  XPLT(Player1,2000000)
  XPLT(Myself,2000000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,1750000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,1999999)
  XPLT(Player1,2250000)
  XPLT(Myself,2250000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,2000000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,2249999)
  XPLT(Player1,2500000)
  XPLT(Myself,2500000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,2250000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,2499999)
  XPLT(Player1,2750000)
  XPLT(Myself,2750000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,2500000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,2749999)
  XPLT(Player1,3000000)
  XPLT(Myself,3000000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,2750000,SET)
	Continue()
END

IF
  Global("BD_JOINXP","LOCALS",0)
  InParty(Myself)
  XPGT(Player1,2999999)
  XPLT(Myself,3000000)
THEN
  RESPONSE #100
    ChangeStat(Myself,XP,3000000,SET)
	Continue()
END

IF 
	Global("BD_JOINXP","LOCALS",0)
	InParty(Myself)
THEN
	RESPONSE #100
		SetGlobal("BD_JOINXP","LOCALS",1)
		Continue()
END

//} End Exp Boosts on Join


//{ 22: Banter Initialization
/* Initialize Banters */

IF
	ActionListEmpty()
	InParty(Myself)
	OR(2)
		GlobalLT("XA_BanterCountInit", "LOCALS", 1)
		Global("XA_ResetCorwinBanters", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0) 
		SetGlobal("XA_Banter_CorwinAerie", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinAnomen", "GLOBAL", 1)
		//SetGlobal("XA_Banter_CorwinCernd", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinDorn", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinEdwin", "GLOBAL", 1)
		//SetGlobal("XA_Banter_CorwinHexxat", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinImoen", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinJaheira", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinJan", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinKeldorn", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinKorgan", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinNeera", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinPlayer", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinRasaad", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinValygar", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinViconia", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinYoshimo", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinMinsc", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinHaerDalis", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinNalia", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinMazzy", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinSarevok", "GLOBAL", 1)
		SetGlobal("XA_Banter_CorwinCaelar", "GLOBAL", 1)
		
		//{ Define Banter End States
			SetGlobal("XA_Banter_CorwinMazzyEnd", "GLOBAL", 5) 		//OK
			SetGlobal("XA_Banter_CorwinNaliaEnd", "GLOBAL", 7) 		//OK
			SetGlobal("XA_Banter_CorwinHaerDalisEnd", "GLOBAL", 5) 	//OK
			SetGlobal("XA_Banter_CorwinMinscEnd", "GLOBAL", 7) 		//OK
			SetGlobal("XA_Banter_CorwinRasaadEnd", "GLOBAL", 9)		//OK
			SetGlobal("XA_Banter_CorwinYoshimoEnd", "GLOBAL", 3)	//OK
			SetGlobal("XA_Banter_CorwinValygarEnd", "GLOBAL", 3)	//OK
			SetGlobal("XA_Banter_CorwinJaheiraEnd", "GLOBAL", 7)	//OK
			SetGlobal("XA_Banter_CorwinNeeraEnd", "GLOBAL", 3)		//OK
			SetGlobal("XA_Banter_CorwinDornEnd", "GLOBAL", 5)		//OK
			SetGlobal("XA_Banter_CorwinKeldornEnd", "GLOBAL", 5)	//OK
			SetGlobal("XA_Banter_CorwinKorganEnd", "GLOBAL", 5)		//OK
			SetGlobal("XA_Banter_CorwinJanEnd", "GLOBAL", 5)		//OK
			SetGlobal("XA_Banter_CorwinEdwinEnd", "GLOBAL", 7)		//OK
			SetGlobal("XA_Banter_CorwinAerieEnd", "GLOBAL", 9)		//OK
			SetGlobal("XA_Banter_CorwinAnomenEnd", "GLOBAL", 1)		//OK
			SetGlobal("XA_Banter_CorwinViconiaEnd", "GLOBAL", 3)	//OK
			SetGlobal("XA_Banter_CorwinImoenEnd", "GLOBAL", 5)		//OK
			SetGlobal("XA_Banter_CorwinSarevokEnd", "GLOBAL", 7)	//OK
			SetGlobal("XA_Banter_CorwinCaelarEnd", "GLOBAL", 3)		//OK
			SetGlobal("XA_Banter_CorwinPlayerEnd", "GLOBAL", 5)		//OK
		//}
		
		SetGlobal("XA_Banter_Pending", "LOCALS", 0)
		SetGlobal("XA_BanterCountInit", "LOCALS", 1)
		SetGlobal("XA_ResetCorwinBanters", "GLOBAL", 0)
		////DisplayStringHead(Myself, ~Banters reset!~)
		SetInterrupt(TRUE)
		Continue()
END

//{ Banter Interval

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterTimerReset", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_CorwinBanterTimerReset", "GLOBAL", 0)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
		////DisplayStringHead(Myself, ~DEBUG: 22-01~)
		SetInterrupt(TRUE)
		Continue()
END

IF 
	ActionListEmpty()
	InParty(Myself)
	Global("XA_ResetBanterTimer", "LOCALS", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 2)
		SetGlobal("XA_BanterPendingTimerSet", "LOCALS", 0)
		////DisplayStringHead(Myself, ~DEBUG: 22-02~)		
		SetInterrupt(TRUE)
END

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterInterval", "GLOBAL", 0) // Default
	Global("XA_ResetBanterTimer", "LOCALS", 2)
THEN
	RESPONSE #100
		SetGlobal("XA_CorwinBanterInterval", "GLOBAL", 10)
END

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterInterval", "GLOBAL", 1) 
	Global("XA_ResetBanterTimer", "LOCALS", 2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 0)
		SetGlobal("XA_Banter_Pending", "LOCALS", 0)
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", ONE_HOUR)
		////DisplayStringHead(Myself, ~DEBUG: 22-04~)	
		SetInterrupt(TRUE)
END

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterInterval", "GLOBAL", 2) 
	Global("XA_ResetBanterTimer", "LOCALS", 2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 0)
		SetGlobal("XA_Banter_Pending", "LOCALS", 0)
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", TWO_HOURS)
		////DisplayStringHead(Myself, ~DEBUG: 22-05~)	
		SetInterrupt(TRUE)
END

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterInterval", "GLOBAL", 3) 
	Global("XA_ResetBanterTimer", "LOCALS", 2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 0)
		SetGlobal("XA_Banter_Pending", "LOCALS", 0)
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", FOUR_HOURS)
		////DisplayStringHead(Myself, ~DEBUG: 22-06~)
		SetInterrupt(TRUE)
END

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterInterval", "GLOBAL", 4) 
	Global("XA_ResetBanterTimer", "LOCALS", 2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 0)
		SetGlobal("XA_Banter_Pending", "LOCALS", 0)
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", EIGHT_HOURS)
		////DisplayStringHead(Myself, ~DEBUG: 22-07~)
		SetInterrupt(TRUE)
END

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterInterval", "GLOBAL", 5) 
	Global("XA_ResetBanterTimer", "LOCALS", 2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 0)
		SetGlobal("XA_Banter_Pending", "LOCALS", 0)
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", TWELVE_HOURS)
		////DisplayStringHead(Myself, ~DEBUG: 22-08~)
		SetInterrupt(TRUE)
END

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterInterval", "GLOBAL", 6) 
	Global("XA_ResetBanterTimer", "LOCALS", 2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 0)
		SetGlobal("XA_Banter_Pending", "LOCALS", 0)
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", SIXTEEN_HOURS)
		////DisplayStringHead(Myself, ~DEBUG: 22-09~)
		SetInterrupt(TRUE)
END

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterInterval", "GLOBAL", 7) 
	Global("XA_ResetBanterTimer", "LOCALS", 2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 0)
		SetGlobal("XA_Banter_Pending", "LOCALS", 0)
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", TWENTY_HOURS)
		////DisplayStringHead(Myself, ~DEBUG: 22-12~)
		SetInterrupt(TRUE)
END

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterInterval", "GLOBAL", 8) 
	Global("XA_ResetBanterTimer", "LOCALS", 2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 0)
		SetGlobal("XA_Banter_Pending", "LOCALS", 0)
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", ONE_DAY)
		////DisplayStringHead(Myself, ~DEBUG: 22-10~)
		SetInterrupt(TRUE)
END

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterInterval", "GLOBAL", 9) 
	Global("XA_ResetBanterTimer", "LOCALS", 2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 0)
		SetGlobal("XA_Banter_Pending", "LOCALS", 0)
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", 10800)
		////DisplayStringHead(Myself, ~DEBUG: 22-10~)
		SetInterrupt(TRUE)
END

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterInterval", "GLOBAL", 10) 
	Global("XA_ResetBanterTimer", "LOCALS", 2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 0)
		SetGlobal("XA_Banter_Pending", "LOCALS", 0)
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", TWO_DAYS)
		////DisplayStringHead(Myself, ~DEBUG: 22-11~)
		SetInterrupt(TRUE)
END

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterInterval", "GLOBAL", 11) 
	Global("XA_ResetBanterTimer", "LOCALS", 2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 0)
		SetGlobal("XA_Banter_Pending", "LOCALS", 0)
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", 18000)
		////DisplayStringHead(Myself, ~DEBUG: 22-12~)
		SetInterrupt(TRUE)
END

IF 
	ActionListEmpty()
	Global("XA_CorwinBanterInterval", "GLOBAL", 12) 
	Global("XA_ResetBanterTimer", "LOCALS", 2)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 0)
		SetGlobal("XA_Banter_Pending", "LOCALS", 0)
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", THREE_DAYS)
		////DisplayStringHead(Myself, ~DEBUG: 22-12~)
		SetInterrupt(TRUE)
END


//}

//{ Postpone Banter by 10 minutes - in combat.
IF
	ActionListEmpty()
	InParty(Myself)
	GlobalTimerExpired("XA_BanterTimer", "LOCALS")
	ActuallyInCombat()
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", TEN_MINUTES)
		////DisplayStringHead(Myself, ~DEBUG: 22-13A~)
		SetInterrupt(TRUE)
END
//}

//{ Postpone Banter by One Hour - Bit
IF
	ActionListEmpty()
	InParty(Myself)
	GlobalTimerExpired("XA_BanterTimer", "LOCALS")
	GlobalGT("XA_CorwinBit", "GLOBAL", 0)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("XA_BanterTimer", "LOCALS", ONE_HOUR)
		////DisplayStringHead(Myself, ~DEBUG: 22-13A~)
		SetInterrupt(TRUE)
END
//}

//{ NBI Select
IF
	ActionListEmpty()
	GlobalLT("XA_LC_BanterBlock_RBG", "LOCALS", 0)
	Global("XA_CanTalk", "LOCALS", 1)
	GlobalTimerExpired("XA_BanterTimer", "LOCALS")
	Global("XA_Banter_NextInteraction", "LOCALS", 0)
	GlobalLT("XA_Banter_Pending", "LOCALS", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 1) //Aerie
		//DisplayStringHead(Myself, ~NBI Set to 1~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 2) //Anomen
		//DisplayStringHead(Myself, ~NBI Set to 2~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 3) //Dorn
		//DisplayStringHead(Myself, ~NBI Set to 3~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 4) //Edwin
		//DisplayStringHead(Myself, ~NBI Set to 4~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 5) //Imoen
		//DisplayStringHead(Myself, ~NBI Set to 5~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 7) //Jaheira
		//DisplayStringHead(Myself, ~NBI Set to 7~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 8) //Jan
		//DisplayStringHead(Myself, ~NBI Set to 8~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 9) //Keldorn
		//DisplayStringHead(Myself, ~NBI Set to 9~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 10) //Korgan
		//DisplayStringHead(Myself, ~NBI Set to 10~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 11) //Neera
		//DisplayStringHead(Myself, ~NBI Set to 11~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 12) //Player
		//DisplayStringHead(Myself, ~NBI Set to 12~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 13) //Viconia
		//DisplayStringHead(Myself, ~NBI Set to 13~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 14) //Valygar
		//DisplayStringHead(Myself, ~NBI Set to 14~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 16) //Yoshimo
		//DisplayStringHead(Myself, ~NBI Set to 16~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 17) //Rasaad
		//DisplayStringHead(Myself, ~NBI Set to 17~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 18) //Minsc
		//DisplayStringHead(Myself, ~NBI Set to 18~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 19) //HaerDalis
		//DisplayStringHead(Myself, ~NBI Set to 19~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 20) //Nalia
		//DisplayStringHead(Myself, ~NBI Set to 20~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 21) //Mazzy
		//DisplayStringHead(Myself, ~NBI Set to 21~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 22) //Sarevok
		//DisplayStringHead(Myself, ~NBI Set to 22~)
		Continue()
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 23) //Caelar
		//DisplayStringHead(Myself, ~NBI Set to 23~)
		Continue()
END
//}

//{ Check if NBI is a Valid Target
IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 1)
	OR(2)
		!Global("XA_CanTalkToAerie", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinAerieEnd", "XA_Banter_CorwinAerie")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 1~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 2)
	OR(2)
		!Global("XA_CanTalkToAnomen", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinAnomenEnd", "XA_Banter_CorwinAnomen")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 2~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 3)
	OR(2)
		!Global("XA_CanTalkToDorn", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinDornEnd", "XA_Banter_CorwinDorn")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 3~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 4)
	OR(2)
		!Global("XA_CanTalkToEdwin", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinEdwinEnd", "XA_Banter_CorwinEdwin")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 4~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 5)
	OR(2)
		!Global("XA_CanTalkToImoen2", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinImoenEnd", "XA_Banter_CorwinImoen")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 5~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 7)
	OR(2)
		!Global("XA_CanTalkToJaheira", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinJaheiraEnd", "XA_Banter_CorwinJaheira")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 7~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 8)
	OR(2)
		!Global("XA_CanTalkToJan", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinJanEnd", "XA_Banter_CorwinJan")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 8~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 9)
	OR(2)
		!Global("XA_CanTalkToKeldorn", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinKeldornEnd", "XA_Banter_CorwinKeldorn")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 9~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 10)
	OR(2)
		!Global("XA_CanTalkToKorgan", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinKorganEnd", "XA_Banter_CorwinKorgan")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 10~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 11)
	OR(2)
		!Global("XA_CanTalkToNeera", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinNeeraEnd", "XA_Banter_CorwinNeera")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 11~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 12)
	OR(2)
		!Global("XA_CanTalkToPlayer", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinPlayerEnd", "XA_Banter_CorwinPlayer")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 12~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 13)
	OR(2)
		!Global("XA_CanTalkToViconia", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinViconiaEnd", "XA_Banter_CorwinViconia")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 13~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 14)
	OR(2)
		!Global("XA_CanTalkToValygar", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinValygarEnd", "XA_Banter_CorwinValygar")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 14~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 16)
	OR(2)
		!Global("XA_CanTalkToYoshimo", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinYoshimoEnd", "XA_Banter_CorwinYoshimo")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 16~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 17)
	OR(2)
		!Global("XA_CanTalkToRasaad", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinRasaadEnd", "XA_Banter_CorwinRasaad")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 17~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 18)
	OR(2)
		!Global("XA_CanTalkToMinsc", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinMinscEnd", "XA_Banter_CorwinMinsc")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 18~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 19)
	OR(2)
		!Global("XA_CanTalkToHaerDalis", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinHaerDalisEnd", "XA_Banter_CorwinHaerDalis")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 19~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 20)
	OR(2)
		!Global("XA_CanTalkToNalia", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinNaliaEnd", "XA_Banter_CorwinNalia")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 20~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 21)
	OR(2)
		!Global("XA_CanTalkToMazzy", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinMazzyEnd", "XA_Banter_CorwinMazzy")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 21~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 22)
	OR(2)
		!Global("XA_CanTalkToSarevok", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinSarevokEnd", "XA_Banter_CorwinSarevok")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 22~)
		Continue()
END

IF
	ActionListEmpty()
	Global("XA_Banter_NextInteraction", "LOCALS", 23)
	OR(2)
		!Global("XA_CanTalkToCaelar", "LOCALS", 1)
		!GlobalsGT("XA_Banter_CorwinCaelarEnd", "XA_Banter_CorwinCaelar")
THEN
	RESPONSE #100
		SetGlobal("XA_Banter_NextInteraction", "LOCALS", 0)
		//DisplayStringHead(Myself, ~Cannot Talk to 23~)
		Continue()
END
//}

//} End Banter Initialization

//{ Mazzy Interactions
	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToMazzy", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 21) /* Mazzy */
		!Global("XA_Banter_Pending", "LOCALS", 21)
		GlobalsGT("XA_Banter_CorwinMazzyEnd", "XA_Banter_CorwinMazzy")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 21)
	END
	//}

	//{ Mazzy Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 21)
		Global("XA_CanTalkToMazzy", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinMazzy", "GLOBAL", 1)
			Interact("Mazzy")
			ActionOverride("Mazzy", StartDialog("MAZZYJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

	//{ Trademeet Archery Competition Ended - Corwin Won 
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CanTalkToMazzy", "LOCALS", 1)
		Global("XA_TM_ArcheryChallenge", "GLOBAL", 2)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			//Dialog B-3A
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			ActionOverride("Mazzy", StartDialog("MAZZYJ", Player1))
	END
	//}

	//{ Trademeet Archery Competition Ended - Mazzy Won
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CanTalkToMazzy", "LOCALS", 1)
		Global("XA_TM_ArcheryChallenge", "GLOBAL", 2)
		!Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			//Dialog B-3B
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			StartDialog("XACORWIB", Player1)
	END
	//}

//} End Mazzy Interactions

//{ Nalia Interactions
	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToNalia", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 20) /* Nalia */
		!Global("XA_Banter_Pending", "LOCALS", 20)
		GlobalsGT("XA_Banter_CorwinNaliaEnd", "XA_Banter_CorwinNalia")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 20)
	END
	//}
	
	//{ Nalia Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 20)
		Global("XA_CanTalkToNalia", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinNalia", "GLOBAL", 1)
			Interact("Nalia")
			ActionOverride("Nalia", StartDialog("NALIAJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

//} End Nalia Interactions

//{ HaerDalis Interactions
	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToHaerDalis", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 19) /* HaerDalis */
		!Global("XA_Banter_Pending", "LOCALS", 19)
		GlobalsGT("XA_Banter_CorwinHaerDalisEnd", "XA_Banter_CorwinHaerDalis")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 19)
	END
	//}

	//{ HaerDalis Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 19)
		Global("XA_CanTalkToHaerDalis", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinHaerDalis", "GLOBAL", 1)
			Interact("HaerDalis")
			ActionOverride("HaerDalis", StartDialog("HAERDAJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}
	
//} End HaerDalis Interactions

//{ Minsc Interactions

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToMinsc", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 18) /* Mazzy */
		!Global("XA_Banter_Pending", "LOCALS", 18)
		GlobalsGT("XA_Banter_CorwinMinscEnd", "XA_Banter_CorwinMinsc")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 18)
	END
	//}
	
	//{ Minsc Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 18)
		Global("XA_CanTalkToMinsc", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinMinsc", "GLOBAL", 1)
			Interact("Minsc")
			ActionOverride("Minsc", StartDialog("MINSCJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

//} End Minsc Interactions

//{ Rasaad Interactions

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToRasaad", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 17) /* Rasaad */
		!Global("XA_Banter_Pending", "LOCALS", 17)
		GlobalsGT("XA_Banter_CorwinRasaadEnd", "XA_Banter_CorwinRasaad")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 17)
	END
	//}

	//{ Rasaad Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 17)
		Global("XA_CanTalkToRasaad", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinRasaad", "GLOBAL", 1)
			Interact("Rasaad")
			ActionOverride("Rasaad", StartDialog("RASAADJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

//} End Rasaad Interactions

//{ Yoshimo Interactions

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToYoshimo", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 16) /* Yoshimo */
		!Global("XA_Banter_Pending", "LOCALS", 16)
		GlobalsGT("XA_Banter_CorwinYoshimoEnd", "XA_Banter_CorwinYoshimo")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 16)
	END
	//}
	
	//{ Yoshimo Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 16)
		Global("XA_CanTalkToYoshimo", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinYoshimo", "GLOBAL", 1)
			Interact("Yoshimo")
			ActionOverride("Yoshimo", StartDialog("YOSHJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

//} End Yoshimo Interactions

//{ Cernd Interactions

	//{ Compliment Child
	IF
		ActionListEmpty()
		Global("CerndBaby","GLOBAL",1)
		GlobalLT("XA_CorwinCerndBaby", "GLOBAL", 1)
		Global("XA_CanTalkToCernd", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinCerndBaby", "GLOBAL", 1)
			SetGlobalTimer("XA_CorwinCerndBabyTimer", "LOCALS", THREE_HOURS)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		ActionListEmpty()
		Global("CerndBaby","GLOBAL", 1)
		Global("XA_CorwinCerndBaby", "GLOBAL", 1)
		GlobalTimerExpired("XA_CorwinCerndBabyTimer", "LOCALS")
		Global("XA_CanTalkToCernd", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			SetGlobal("XA_CorwinCerndBaby", "GLOBAL", 2)
			Interact("Cernd")
			SetInterrupt(TRUE)
	END
	//}
//} End Cernd Interactions

//{ Valygar Interactions

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToValygar", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 14) /* Valygar */
		!Global("XA_Banter_Pending", "LOCALS", 14)
		GlobalsGT("XA_Banter_CorwinValygarEnd", "XA_Banter_CorwinValygar")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 14)
	END
	//}

	//{ Valygar Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 14)
		Global("XA_CanTalkToValygar", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinValygar", "GLOBAL", 1)
			Interact("Valygar")
			ActionOverride("Valygar", StartDialog("VALYGARJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Lavok Dead
	IF
		ActionListEmpty()
		//GlobalTimerExpired("XA_PauseBeforeBanterTimer", "LOCALS")
		Global("XA_CanTalkToValygar", "LOCALS", 1)
		Global("LavokDead", "GLOBAL", 1)
		!Global("XA_CorwinLavokTimerSet", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinLavokTimer", "GLOBAL", ONE_HOUR)
			SetGlobal("XA_CorwinLavokTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
	END
	
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToValygar", "LOCALS", 1)
		GlobalTimerExpired("XA_CorwinLavokTimer", "GLOBAL")
		GlobalLT("XA_CorwinValygarLavok", "GLOBAL", 1)
		GlobalLT("XA_ReturnToBG", "GLOBAL", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinValygarLavok", "GLOBAL", 1)
			//Dialog B-39
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinValygar", "GLOBAL", 1)
			Interact("Valygar")
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Valygar Return BG
	IF
		ActionListEmpty()
		GlobalTimerExpired("XA_CorwinValygarTimer", "GLOBAL")
		Global("XA_CanTalkToValygar", "LOCALS", 1)
		GlobalLT("XA_ReturnToBG", "GLOBAL", 1)
		GlobalLT("XA_CorwinValygarBG", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinValygarBG", "GLOBAL", 1)
			ActionOverride("Valygar", StartDialog("VALYGARJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}
	
//} End Valygar Interactions

//{ Hexxat Interactions
	
	//{ First Interaction
	IF
		ActionListEmpty()
		Global("XA_CanTalkToHexxat", "LOCALS", 1)
		Global("XA_CorwinHexxat", "GLOBAL", 2)
		GlobalTimerExpired("XA_CorwinHexxatTimer", "LOCALS")
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			SetGlobal("XA_CorwinHexxat", "GLOBAL", 3)
			Interact("Hexxat")
			SetInterrupt(TRUE)
	END
	//}

	//{ Second Interaction
	IF
		ActionListEmpty()
		Global("XA_CanTalkToHexxat", "LOCALS", 1)
		Global("XA_CorwinHexxat", "GLOBAL", 4)
		GlobalTimerExpired("XA_CorwinHexxatTimer", "LOCALS")
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			SetGlobal("XA_CorwinHexxat", "GLOBAL", 5)
			StartDialogue("XACORWIJ","Hexxat")
			SetInterrupt(TRUE)
	END
	//}

//} End Hexxat Interaction

//{ Jaheira Interactions

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToJaheira", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 7) /* Jaheira */
		!Global("XA_Banter_Pending", "LOCALS", 7)
		GlobalsGT("XA_Banter_CorwinJaheiraEnd", "XA_Banter_CorwinJaheira")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 7)
	END
	//}

	//{ Jaheira Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 7)
		Global("XA_CanTalkToJaheira", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinJaheira", "GLOBAL", 1)
			Interact("Jaheira")
			ActionOverride("Jaheira", StartDialog("JAHEIRAJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

//} End Jaheira Interactions

//{ Neera Interactions

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToNeera", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 11) /* Neera */
		!Global("XA_Banter_Pending", "LOCALS", 11)
		GlobalsGT("XA_Banter_CorwinNeeraEnd", "XA_Banter_CorwinNeera")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 11)
	END
	//}

	//{ Neera Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 11)
		Global("XA_CanTalkToNeera", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinNeera", "GLOBAL", 1)
			Interact("Neera")
			ActionOverride("Neera", StartDialog("NEERAJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

	//{ Neera - Corwin Second Interaction 
	IF
		ActionListEmpty()
		Global("XA_CanTalkToNeera", "LOCALS", 1)
		Global("XA_CanTalkToImoen2", "LOCALS", 1)
		GlobalGT("XA_Banter_CorwinNeera", "GLOBAL", 2)
		GlobalLT("XA_NeeraBanterBump", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_NeeraBanterBump", "LOCALS", 1)
			SetGlobalTimer("XA_CorwinNeeraImoenTimer", "LOCALS", ONE_DAY)
			SetInterrupt(TRUE)
	END
	
	IF
		ActionListEmpty()
		GlobalTimerExpired("XA_CorwinNeeraImoenTimer", "LOCALS")
		Global("XA_CanTalkToNeera", "LOCALS", 1)
		Global("XA_CanTalkToImoen2", "LOCALS", 1)
		GlobalLT("XA_CorwinNeeraImoen", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinNeeraImoen", "GLOBAL", 1)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			Interact("Neera")
			SetInterrupt(TRUE)
	END
	//}

//} End Neera Interactions

//{ Dorn Interactions

	//{ Dorn / Corwin Love Conflict
	IF
		ActionListEmpty()
		Global("XA_CanTalkToDorn", "LOCALS", 1)
		OR(2)
			Global("DornRomanceActive","GLOBAL",1)
			Global("DornRomanceActive","GLOBAL",2)
		GlobalGT("DornLovetalks","GLOBAL",9)
		OR(2)
			Global("XA_CorwinRomanceActive","GLOBAL",1)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
		Global("OHD_corwinconflict","GLOBAL",0)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			RealSetGlobalTimer("OHD_corwinconflict_timer","GLOBAL",NINE_HOURS)
			SetGlobal("OHD_corwinconflict","GLOBAL",1)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToDorn", "LOCALS", 1)
		OR(2)
			Global("DornRomanceActive","GLOBAL",1)
			Global("DornRomanceActive","GLOBAL",2)
		OR(2)
			Global("XA_CorwinRomanceActive","GLOBAL",1)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
		Global("OHD_corwinconflict","GLOBAL",1)
		RealGlobalTimerExpired("OHD_corwinconflict_timer","GLOBAL")
	THEN
		RESPONSE #100
			SetGlobal("OHD_corwinconflict","GLOBAL",2)
			Continue()
	END

	IF
		Global("XA_CanTalkToDorn", "LOCALS", 1)
		!AreaType(DUNGEON)
		!See([ENEMY])
		Global("OHD_corwinconflict","GLOBAL",2)
		See("Dorn")
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			//Dialog B-0
			StartDialog("XACORWIB", Player1)
	END

	IF
		Global("OHD_sexreactions","GLOBAL",1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)  
		!Global("XA_DornSex", "GLOBAL", 1)
		!ActuallyInCombat()
		OR(2)
			Global("XA_CorwinRomanceActive","GLOBAL",1)
			Global("XA_CorwinRomanceActive","GLOBAL",2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_DornSex", "GLOBAL", 1)
			SetGlobal("XA_ComplainDornSex", "GLOBAL", 1)
			//Dialog J-25
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Dorn - Corwin First Interaction 
	
	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToDorn", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 3) /* Dorn */
		!Global("XA_Banter_Pending", "LOCALS", 3)
		GlobalsGT("XA_Banter_CorwinDornEnd", "XA_Banter_CorwinDorn")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 3)
	END
	//}
	
	//{ Dorn Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 3)
		Global("XA_CanTalkToDorn", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinDorn", "GLOBAL", 1)
			Interact("Dorn")
			ActionOverride("Dorn", StartDialog("DORNJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}
	
//} End Dorn Interactions
//}

//{ Keldorn Interactions 

	//{ Keldorn Audamar
	IF
		ActionListEmpty()
		Global("XA_CanTalkToKeldorn", "LOCALS", 1)
		GlobalLT("XA_KeldornAudamarTimerSet", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_KeldornAudamarTimerSet", "GLOBAL", 1)
			SetGlobalTimer("XA_KeldornAudamarTimer", "GLOBAL", SIX_HOURS)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		ActionListEmpty()
		Global("XA_CanTalkToKeldorn", "LOCALS", 1)
		GlobalTimerExpired("XA_KeldornAudamarTimer", "GLOBAL")
		GlobalLT("XA_Banter_CorwinKeldornInitial", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_Banter_CorwinKeldornInitial", "GLOBAL", 1)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			ActionOverride("Keldorn", StartDialog("KELDORJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

	//{ Corwin Mad at Keldorn - Underdark
	IF
		ActionListEmpty()
		Global("XA_CanTalkToKeldorn", "LOCALS", 1)
		GlobalTimerExpired("XA_CorwinScoldKeldornTimer", "LOCALS")
		Global("XA_CorwinCoverUD", "GLOBAL", 1)
		GlobalLT("DrowCityHostile","GLOBAL",1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinCoverUD", "GLOBAL", 2)
			//Dialog B-61
			Interact("Keldorn")
			SetInterrupt(TRUE)
	END
	//}

	//{ Keldorn - Corwin Optional Interaction (Reconciled with Maria) 
	IF
		ActionListEmpty()
		Global("XA_CanTalkToKeldorn", "LOCALS", 1)
		Global("XA_Banter_CorwinKeldornOpt1", "GLOBAL", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_Banter_CorwinKeldornOpt1", "GLOBAL", 2)
			SetGlobalTimer("XA_Banter_CorwinKeldornOpt1", "LOCALS", ONE_HOUR)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToKeldorn", "LOCALS", 1)
		Global("XA_Banter_CorwinKeldornOpt1", "GLOBAL", 2)
		GlobalTimerExpired("XA_Banter_CorwinKeldornOpt1", "LOCALS")
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			//Dialog B-62
			SetGlobal("XA_Banter_CorwinKeldornOpt1", "GLOBAL", 3)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			Interact("Keldorn")
			SetInterrupt(TRUE)
	END
	//}

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToKeldorn", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 9) /* Keldorn */
		!Global("XA_Banter_Pending", "LOCALS", 9)
		GlobalsGT("XA_Banter_CorwinKeldornEnd", "XA_Banter_CorwinKeldorn")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 9)
	END
	//}

	//{ Keldorn Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 9)
		Global("XA_CanTalkToKeldorn", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinKeldorn", "GLOBAL", 1)
			Interact("Keldorn")
			ActionOverride("Keldorn", StartDialog("KELDORJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

//} End Keldorn Interactions

//{ Korgan Interactions

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToKorgan", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 10) /* Korgan */
		!Global("XA_Banter_Pending", "LOCALS", 10)
		GlobalsGT("XA_Banter_CorwinKorganEnd", "XA_Banter_CorwinKorgan")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 10)
	END
	//}

	//{ Korgan Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 10)
		Global("XA_CanTalkToKorgan", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinKorgan", "GLOBAL", 1)
			Interact("Korgan")
			ActionOverride("Korgan", StartDialog("KORGANJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

//} End Korgan Interactions

//{ Jan Interactions

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToJan", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 8) /* Korgan */
		!Global("XA_Banter_Pending", "LOCALS", 8)
		GlobalsGT("XA_Banter_CorwinJanEnd", "XA_Banter_CorwinJan")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 8)
	END
	//}

	//{ Jan Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 8)
		Global("XA_CanTalkToJan", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinJan", "GLOBAL", 1)
			Interact("Jan")
			ActionOverride("Jan", StartDialog("JANJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

//} End Jan Interactions

//{ Edwin Interactions

	//{ Edwin - Corwin Change to Female Interaction */

	IF
		ActionListEmpty()
		InParty(Myself)
		InParty("Edwin")
		GlobalLT("XA_EdwinWasMale", "LOCALS", 1)
		Gender("Edwin",MALE)
	THEN
		RESPONSE #100
			SetGlobal("XA_EdwinWasMale", "LOCALS", 1)
			Continue()
	END

	IF 
		Global("XA_CanTalkToEdwin", "LOCALS", 1)
		Gender("Edwin",FEMALE)
		Global("XA_EdwinWasMale", "LOCALS", 1)
		GlobalLT("XA_CorwinEdwinFemale", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinEdwinFemale", "LOCALS", 1)
			//Dialog B-55
			Interact("Edwin")
			SetInterrupt(TRUE)
	END
	//}

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToEdwin", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 4) /* Edwin */
		!Global("XA_Banter_Pending", "LOCALS", 4)
		GlobalsGT("XA_Banter_CorwinEdwinEnd", "XA_Banter_CorwinEdwin")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 4)
	END
	//}

	//{ Edwin Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 4)
		Global("XA_CanTalkToEdwin", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinEdwin", "GLOBAL", 1)
			Interact("Edwin")
			ActionOverride("Edwin", StartDialog("EDWINJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

	//{ Corwin Edwin Thay Interaction

	IF
		ActionListEmpty()
		GlobalTimerExpired("XA_CorwinEdwinThayTimer", "GLOBAL")
		GlobalLT("XA_CorwinEdwinThay", "GLOBAL", 1)
		Global("XA_CanTalkToEdwin", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinEdwinThay", "GLOBAL", 1)
			//Dialog B-54
			Interact("Edwin")
			SetInterrupt(TRUE)
	END
	//}

//} End Edwin Interactions

//{ Aerie Interactions
	
	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToAerie", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 1) /* Aerie */
		!Global("XA_Banter_Pending", "LOCALS", 1)
		GlobalsGT("XA_Banter_CorwinAerieEnd", "XA_Banter_CorwinAerie")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 1)
	END
	//}

	//{ Aerie Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 1)
		Global("XA_CanTalkToAerie", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinAerie", "GLOBAL", 1)
			Interact("Aerie")
			ActionOverride("Aerie", StartDialog("AERIEJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}
	

//} End Aerie Interactions

//{ Anomen Interactions
	IF
		ActionListEmpty()
		Global("XA_CanTalkToAnomen", "LOCALS", 1)
		GlobalLT("XA_CorwinAnomenTimerSet", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinAnomenTimerSet", "LOCALS", 1)
			SetGlobalTimer("XA_CorwinAnomenTimer", "LOCALS", TWO_DAYS)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		ActionListEmpty()
		Global("XA_CanTalkToAnomen", "LOCALS", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalTimerExpired("XA_CorwinAnomenTimer", "LOCALS")
		GlobalLT("XA_CorwinAnomenTalk", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			SetGlobal("XA_CorwinAnomenTalk", "LOCALS", 1)
			Interact(Player1)
			SetInterrupt(TRUE)
	END

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToAnomen", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 2) /* Anomen */
		!Global("XA_Banter_Pending", "LOCALS", 2)
		GlobalsGT("XA_Banter_CorwinAnomenEnd", "XA_Banter_CorwinAnomen")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 2)
	END
	//}

	//{ Anomen Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 2)
		Global("XA_CanTalkToAnomen", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinAnomen", "GLOBAL", 1)
			Interact("Anomen")
			ActionOverride("Anomen", StartDialog("ANOMENJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

//} End Anomen Interactions

//{ Viconia Interactions

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToViconia", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 13) /* Viconia */
		!Global("XA_Banter_Pending", "LOCALS", 13)
		GlobalsGT("XA_Banter_CorwinViconiaEnd", "XA_Banter_CorwinViconia")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 13)
	END
	//}

	//{ Viconia Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 13)
		Global("XA_CanTalkToViconia", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinViconia", "GLOBAL", 1)
			Interact("Viconia")
			SetInterrupt(TRUE)
	END

	//{ Viconia - Corwin Second Interaction*/

	IF
		ActionListEmpty()
		!ActuallyInCombat()
		GlobalTimerExpired("XA_ViconiaBanter2Timer", "LOCALS")
		Global("XA_CanTalkToViconia", "LOCALS", 1)
		GlobalGT("XA_Banter_CorwinViconia", "GLOBAL", 2)
		GlobalLT("XA_Banter_CorwinViconiaDay", "LOCALS", 1)
		!TimeOfDay(NIGHT)
		!TimeOfDay(DUSK)
		AreaType(OUTDOOR)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_ViconiaBanter3Timer", "LOCALS", ONE_DAY)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			SetGlobal("XA_Banter_CorwinViconiaDay", "LOCALS", 1)
			Interact("Viconia")
			SetInterrupt(TRUE)
	END
	//}

	//{ Viconia - Corwin Third Interaction*/
	IF
		ActionListEmpty()
		!ActuallyInCombat()
		GlobalTimerExpired("XA_ViconiaBanter3Timer", "LOCALS")
		Global("XA_CanTalkToViconia", "LOCALS", 1)
		Global("XA_Banter_CorwinViconiaDay", "LOCALS", 2)
		GlobalLT("XA_Banter_CorwinViconiaCity", "GLOBAL", 1)
		AreaType(CITY)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			SetGlobal("XA_Banter_CorwinViconiaCity", "GLOBAL", 1)
			ActionOverride("Viconia", StartDialog("VICONIJ", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}
//} End Viconia Corwin Interactions
//}

//{ Imoen Interactions

	//{ Imoen Soul Returned
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToImoen2", "LOCALS", 1)
		GlobalTimerExpired("XA_CorwinImoenSoulTimer", "GLOBAL")
		GlobalLT("XA_CorwinImoenSoulTalk", "GLOBAL", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinImoenSoulTalk", "GLOBAL", 1)
			//Dialogs B-50, B-51
			Interact("Imoen2")
			SetInterrupt(TRUE)
	END
	//}

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToImoen2", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 5) /* Imoen2 */
		!Global("XA_Banter_Pending", "LOCALS", 5)
		GlobalsGT("XA_Banter_CorwinImoenEnd", "XA_Banter_CorwinImoen")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 5)
	END
	//}

	//{ Imoen Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 5)
		Global("XA_CanTalkToImoen2", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinImoen", "GLOBAL", 1)
			Interact("Imoen2")
			ActionOverride("Imoen2", StartDialog("IMOEN2J", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

//} End Imoen Interactions

//{ Sarevok Interactions

	//{ Sarevok - <CHARNAME> Soul Interaction
	IF
		ActionListEmpty()
		Global("XA_CanTalkToSarevok", "LOCALS", 1)
		GlobalTimerExpired("XA_SarevokSoulTimer", "GLOBAL")
		GlobalLT("XA_SarevokSoul", "GLOBAL", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_SarevokSoul", "GLOBAL", 1)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			Interact("Sarevok")
			SetInterrupt(TRUE)
	END
	//}

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToSarevok", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 22) /* Sarevok */
		!Global("XA_Banter_Pending", "LOCALS", 22)
		GlobalsGT("XA_Banter_CorwinSarevokEnd", "XA_Banter_CorwinSarevok")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 22)
	END
	//}

	//{ Sarevok Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 22)
		Global("XA_CanTalkToSarevok", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinSarevok", "GLOBAL", 1)
			Interact("Sarevok")
			ActionOverride("Sarevok", StartDialog("SAREV25J", "XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}
//} End Sarevok Interactions

//{ Caelar Interactions

	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToCaelar", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 23) /* Caelar */
		!Global("XA_Banter_Pending", "LOCALS", 23)
		GlobalsGT("XA_Banter_CorwinCaelarEnd", "XA_Banter_CorwinCaelar")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 23)
	END
	//}

	//{ Caelar Banters
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 23)
		Global("XA_CanTalkToCaelar", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinCaelar", "GLOBAL", 1)
			Interact("XACAELAR")
			ActionOverride("XACAELAR", Interact("XACORWIN"))
			SetInterrupt(TRUE)
	END
	//}

//}

//{ Corwin / Player Interactions

	//{ Hexxat in Party
	IF
		ActionListEmpty()
		InParty(Myself)
		InPartyAllowDead("Hexxat")
		GlobalLT("XA_CorwinHexxatTimerSet", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinHexxatTimerSet", "LOCALS", 1)
			SetGlobalTimer("XA_CorwinHexxatTimer", "LOCALS", FOUR_HOURS)
			SetInterrupt(TRUE)
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinHexxatTimerSet", "LOCALS", 1)
			SetGlobalTimer("XA_CorwinHexxatTimer", "LOCALS", EIGHT_HOURS)
			SetInterrupt(TRUE)
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinHexxatTimerSet", "LOCALS", 1)
			SetGlobalTimer("XA_CorwinHexxatTimer", "LOCALS", TWELVE_HOURS)
			SetInterrupt(TRUE)
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinHexxatTimerSet", "LOCALS", 1)
			SetGlobalTimer("XA_CorwinHexxatTimer", "LOCALS", SIXTEEN_HOURS)
			SetInterrupt(TRUE)
	END
	
	IF
		ActionListEmpty()
		InParty(Myself)
		InPartyAllowDead("Hexxat")
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalTimerExpired("XA_CorwinHexxatTimer", "LOCALS")
		GlobalLT("XA_CorwinHexxat", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinHexxat", "GLOBAL", 1)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Corwin Sees Player for the First Time Since SoD
	IF
		GlobalLT("XA_CorwinReunited", "GLOBAL", 1)
		!Range(Player1, 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject(Player1)
			Continue()
	END
	
	IF
		GlobalLT("XA_CorwinReunited", "GLOBAL", 1)
		See(Player1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			ActionOverride(Player1, FaceObject("XACORWIN"))
			PlaySong(146)
			// Dialog I-1
			StartDialog("XACORWIN", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Scold Player UD - Party
	IF
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalTimerExpired("XA_CorwinScoldPartyTimer", "LOCALS")
		Global("XA_CorwinCoverUD_Party", "GLOBAL", 1)
		GlobalLT("DrowCityHostile","GLOBAL",1)
		!InMyArea("Phaere")
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinCoverUD_Party", "GLOBAL", 2)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Scold Player UD
	IF
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalTimerExpired("XA_CorwinScoldPlayerTimer", "LOCALS")
		Global("XA_CorwinCoverUD_Player", "GLOBAL", 1)
		GlobalLT("DrowCityHostile","GLOBAL",1)
		!InMyArea("Phaere")
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinCoverUD_Player", "GLOBAL", 2)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Banter Primer
	IF 
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_Banter_NextInteraction", "LOCALS", 12) /* Player */
		!Global("XA_Banter_Pending", "LOCALS", 12)
		GlobalsGT("XA_Banter_CorwinPlayerEnd", "XA_Banter_CorwinPlayer")
	THEN
		RESPONSE #100
			SetGlobal("XA_Banter_Pending", "LOCALS", 12)
	END
	//}

	//{ Player Banters - Romance
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 12)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinPlayer", "GLOBAL", 1)
			PlaySong(146)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Player Banters - Non-Romance
	IF
		ActionListEmpty()
		Global("XA_Banter_Pending", "LOCALS", 12)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		!Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			IncrementGlobal("XA_Banter_CorwinPlayer", "GLOBAL", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Optional Banter 1
	IF
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_MetRohma", "GLOBAL", 1)
		GlobalGT("XA_Banter_CorwinPlayer", "GLOBAL", 2)
		GlobalLT("XA_Banter_CorwinPlayerOpt1", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_PlayerOpt1BanterTimer", "LOCALS", THREE_DAYS)
			SetGlobal("XA_Banter_CorwinPlayerOpt1", "GLOBAL", 1)
			SetInterrupt(TRUE)
	END

	IF
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_Banter_CorwinPlayerOpt1", "GLOBAL", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		GlobalTimerExpired("XA_PlayerOpt1BanterTimer", "LOCALS")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_Banter_CorwinPlayerOpt1", "GLOBAL", 2)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			PlaySong(146)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	
	IF
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_Banter_CorwinPlayerOpt1", "GLOBAL", 1)
		!Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		GlobalTimerExpired("XA_PlayerOpt1BanterTimer", "LOCALS")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_Banter_CorwinPlayerOpt1", "GLOBAL", 2)
			SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Optional Banter 1A
	IF
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalLT("XA_Banter_CorwinPlayerOpt1", "GLOBAL", 1)
		Global("XA_ReturnToBG", "GLOBAL", 2)
		GlobalGT("GavePocketPlane","GLOBAL",0)
		GlobalLT("XA_1ATimerSet", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_1ATimerSet", "LOCALS", 1)
			SetGlobalTimer("XA_PlayerOpt1ABanterTimer", "LOCALS", THREE_DAYS)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		ActionListEmpty()
		GlobalTimerExpired("XA_PlayerOpt1ABanterTimer", "LOCALS")
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		GlobalLT("XA_Banter_CorwinPlayerOpt1A", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_Banter_CorwinPlayerOpt1A", "GLOBAL", 1)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}

	//{ Corwin Complain about Sarevok
	IF
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		InParty("Sarevok")
		GlobalTimerExpired("XA_CorwinComplainSarevokTimer", "GLOBAL")
		Global("XA_CorwinComplainSarevok", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinComplainSarevok", "GLOBAL", 2)
			StartDialog("XACORWIJ", Player1)
			Continue()
	END
	//}

	//{ Saradush Destruction
	IF 
		ActionListEmpty()
		GlobalTimerExpired("XA_YagaTimer", "GLOBAL")
		GlobalLT("XA_SaradushDestroyed", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_SaradushDestroyed", "GLOBAL", 1)
			//Dialog J-70
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
//} End Player Interactions

//{ Corwin Pregnant Interactions
	
	//{ Aerie Baby Parent Advice
	IF 
		ActionListEmpty()
		GlobalTimerExpired("XA_CorwinAerieBabyTimer", "GLOBAL")
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		IsValidForPartyDialogue("Aerie")
		GlobalLT("XA_CorwinParentAdvice", "GLOBAL", 1)
		GlobalGT("XA_CorwinOpinionOfPlayer", "GLOBAL", 97)
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinParentAdvice", "GLOBAL", 1)
			Continue()
	END
	
	IF
		Global("XA_CorwinParentAdvice", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		!Range(Player1, 6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject(Player1)
			Continue()
	END
	
	IF
		Global("XA_CorwinParentAdvice", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Range(Player1,7)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinParentAdvice", "GLOBAL", 2)
			//Dialog J-76
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Initial Timer Expiration
	IF 
		!AreaCheck("AR5203") // Yaga-Shura Camp
		Global("XA_CorwinPregnant", "GLOBAL", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		!ActuallyInCombat()
		OR(2)
			Global("XA_PregnantOverride", "GLOBAL", 1)
			GlobalTimerExpired("XA_CorwinPregnantTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_PregnantOverride", "GLOBAL", 2)
			SetGlobalTimer("XA_OneRoundTimer", "LOCALS", ONE_ROUND)
			SetGlobal("XA_CorwinPregnant", "GLOBAL", 2)
			SetInterrupt(TRUE)
			Continue()
	END

	IF
		GlobalTimerExpired("XA_OneRoundTimer", "LOCALS")
		Global("XA_CorwinPregnant", "GLOBAL", 2)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			PlaySong(142)
			//Dialog J-71
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Second Interaction
	IF
		ActionListEmpty()
		Global("XA_CorwinPregnant", "GLOBAL", 3)
		GlobalTimerExpired("XA_CorwinPregnantTimer", "GLOBAL")
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinPregnant", "GLOBAL", 4)
			DisplayStringHead(Myself, @15)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		Global("XA_CorwinPregnant", "GLOBAL", 4)
		!Range(Player1,6)
		ActionListEmpty()
	THEN
		RESPONSE #100
			MoveToObject(Player1)
			Continue()
	END
	
	IF
		Global("XA_CorwinPregnant", "GLOBAL", 4)
		Range(Player1,7)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			PlaySong(146)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Third Interaction
	IF
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		Global("XA_CorwinPregnant", "GLOBAL", 5)
		OR(2)
			GlobalTimerExpired("XA_CorwinPregnantTimer", "GLOBAL")
			GlobalTimerExpired("XA_C3Timer", "LOCALS")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinPregnant", "GLOBAL", 6)
			PlaySong(142)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	

	//}
	
	//{ Fourth Interaction
	IF
		ActionListEmpty()
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		Global("XA_CorwinPregnant", "GLOBAL", 7)
		GlobalTimerExpired("XA_CorwinPregnantTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinPregnant", "GLOBAL", 8)
			PlaySong(142)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Final Interaction - Corwin Leaves
	IF
		ActionListEmpty()
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		Global("XA_CorwinPregnant", "GLOBAL", 9)
		GlobalTimerExpired("XA_CorwinPregnantTimer", "GLOBAL")
	THEN
		RESPONSE #100
			SetGlobal("XA_CorwinPregnant", "GLOBAL", 10)
			Continue()
	END
	
	IF
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		Global("XA_CorwinRomanceActive", "GLOBAL", 2)
		Global("XA_CorwinPregnant", "GLOBAL", 10)
		AreaCheck("AR4500")
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			PlaySong(146)
			StartDialog("XACORWIJ", Player1)
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Baby Name Interaction Imoen
	IF
		ActionListEmpty()
		GlobalTimerExpired("XA_CorwinPregnantImoenTimer", "GLOBAL")
		GlobalLT("XA_CorwinPregnantBabyName_Imoen", "GLOBAL", 1)
		Global("XA_CanTalkToImoen2", "LOCALS", 1)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinPregnantBabyName_Imoen", "GLOBAL", 1)
			////DisplayStringHead(Myself, ~C~)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		Global("XA_CorwinPregnantBabyName_Imoen", "GLOBAL", 1)
		Global("XA_CanTalkToImoen2", "LOCALS", 1)
		Global("XA_CanTalkToPlayer", "LOCALS", 1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			//Dialog J-73
			SetInterrupt(FALSE)
			ActionOverride("Imoen2", StartDialog("IMOEN2J", Player1))
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Baby Name Interaction Aerie
	IF
		ActionListEmpty()
		Global("XA_CorwinPregnant", "GLOBAL", 5)
		Global("XA_CorwinPregnantAerie", "GLOBAL", 1)
		!Global("XA_CorwinPregnantImoen", "GLOBAL", 1)
		!Global("XA_CorwinPregnantAerieTimerSet", "GLOBAL", 1)
		InParty("Aerie")
		InParty(Myself)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinPregnantAerieTimer", "GLOBAL", TWO_DAYS)
			SetGlobal("XA_CorwinPregnantAerieTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		GlobalTimerExpired("XA_CorwinPregnantAerieTimer", "GLOBAL")
		Global("XA_CanTalkToAerie", "LOCALS", 1)
		GlobalLT("XA_CorwinPregnantBabyName_Aerie", "GLOBAL", 1)
		See(Player1)
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinPregnantBabyName_Aerie", "GLOBAL", 1)
			//Dialog J-74
			ActionOverride("Aerie", StartDialog("AERIEJ", Player1))
			SetInterrupt(TRUE)
	END
	//}
	
	//{ Baby Name Interaction Jaheira
	IF
		ActionListEmpty()
		Global("XA_CorwinPregnant", "GLOBAL", 5)
		Global("XA_CorwinPregnantJaheira", "GLOBAL", 1)
		!Global("XA_CorwinPregnantImoen", "GLOBAL", 1)
		!Global("XA_CorwinPregnantJahTimerSet", "GLOBAL", 1)
		InParty("Jaheira")
		InParty(Myself)
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobalTimer("XA_CorwinPregnantJahTimer", "GLOBAL", TWO_DAYS)
			SetGlobal("XA_CorwinPregnantJahTimerSet", "GLOBAL", 1)
			SetInterrupt(TRUE)
			Continue()
	END
	
	IF
		GlobalTimerExpired("XA_CorwinPregnantJahTimer", "GLOBAL")
		IsValidForPartyDialogue("Jaheira")
		GlobalLT("XA_CorwinPregnantBabyName_Jah", "GLOBAL", 1)
		See(Player1)
		See("Jaheira")
		!ActuallyInCombat()
	THEN
		RESPONSE #100
			SetInterrupt(FALSE)
			SetGlobal("XA_CorwinPregnantBabyName_Jah", "GLOBAL", 1)
			//Dialog J-75
			ActionOverride("Jaheira", StartDialog("JAHEIRAJ", Player1))
			SetInterrupt(TRUE)
	END
	//}
//}

//{ Banter Error - if NBI and Pending are greater than zero for more than 10 cycles, something is wrong. Reset the timer in this case.

IF 
	ActionListEmpty()
	InParty(Myself)
	GlobalGT("XA_Banter_NextInteraction", "LOCALS", 0)
	GlobalGT("XA_Banter_Pending", "LOCALS", 0)
	GlobalLT("XA_BanterProblemTick", "LOCALS", 10)
THEN
	RESPONSE #100
		IncrementGlobal("XA_BanterProblemTick", "LOCALS", 1)
		Continue()
END

IF 
	ActionListEmpty()
	InParty(Myself)
	GlobalGT("XA_Banter_NextInteraction", "LOCALS", 0)
	GlobalGT("XA_Banter_Pending", "LOCALS", 0)
	GlobalGT("XA_BanterProblemTick", "LOCALS", 9)
THEN
	RESPONSE #100
		SetGlobal("XA_BanterProblemTick", "LOCALS", 0)
		SetGlobal("XA_ResetBanterTimer", "LOCALS", 1)
		////DisplayStringHead(Myself, ~Error. Resetting Banter Timer.~)
		Continue()
END
//}
