IF
	Clicked([ANYONE])
	GlobalLT("XA_CorwinStatueTalk", "GLOBAL", 2)
	Global("XA_CorwinStatue5", "GLOBAL", 1)
	IsValidForPartyDialogue("XACORWIN")
	InMyArea(Player1)
	InMyArea("XACORWIN")
THEN
	RESPONSE #100
		SetGlobal("XA_CorwinStatueTalk", "GLOBAL", 1)
		ActionOverride("XACORWIN", StartDialog("XACORWIJ", Player1))
		DisplayString(Myself, @0)
END

IF
	Clicked([ANYONE])
THEN
	RESPONSE #100
		DisplayString(Myself, @0)
		//DisplayString(Myself, ~CLICK~)
END