IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
	!Global("XA_CompletedG3", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_EnterG3", "GLOBAL", 1)
		ActionOverride(Player1, StartDialog("PLAYER1", Player1))
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,10)
THEN
	RESPONSE #100
		DisplayString(Myself,@0)
END

IF 
	Clicked([ANYONE])
	Range(LastTrigger,10)
	Global("XA_CompletedG3", "GLOBAL", 1)
THEN
	RESPONSE #100
		DisplayString(Myself,@1)
END
