PRINT @900  /* ~Processing common components...~ */

COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/common/baf~
COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/common/d~


ACTION_IF (isEET = 1) THEN BEGIN
	EXTEND_BOTTOM ~BALDUR.BCS~ ~%MOD_FOLDER%/common/baf/xalcasst.baf~
END


	
//{ bam
	COPY ~%MOD_FOLDER%/common/bam/xaamulet.bam~ ~override~
	COPY ~%MOD_FOLDER%/common/bam/xaassist.bam~ ~override~
	COPY ~%MOD_FOLDER%/common/bam/xabenohd.bam~ ~override~
		
	COPY ~%MOD_FOLDER%/common/bam/xaibenoh.bam~ ~override~
	
	
	COPY ~%MOD_FOLDER%/common/bam/xaiegg.bam~ ~override~
	COPY ~%MOD_FOLDER%/common/bam/xaimsrin.bam~ ~override~
	COPY ~%MOD_FOLDER%/common/bam/xairing.bam~ ~override~
	
	COPY ~%MOD_FOLDER%/common/bam/xamsring.bam~ ~override~
	COPY ~%MOD_FOLDER%/common/bam/xaring.bam~ ~override~
//}

//{ cre
	COPY ~%MOD_FOLDER%/common/cre/xalcdbg.cre~ ~override~
	SAY NAME1 @919
	SAY NAME2 @919
	
	COPY ~%MOD_FOLDER%/common/cre/xadummy.cre~ ~override~
	SAY NAME1 @918
	SAY NAME2 @918
	
	COPY ~%MOD_FOLDER%/common/cre/xavoidf.cre~ ~override~
	SAY NAME1 @916
	SAY NAME2 @916
	
	COPY ~%MOD_FOLDER%/common/cre/xavoidfa.cre~ ~override~
	SAY NAME1 @916
	SAY NAME2 @916
	
	COPY ~%MOD_FOLDER%/common/cre/xavoidfe.cre~ ~override~
	SAY NAME1 @916
	SAY NAME2 @916
	
	COPY ~%MOD_FOLDER%/common/cre/xavoidl.cre~ ~override~
	SAY NAME1 @917
	SAY NAME2 @917
	
	COPY ~%MOD_FOLDER%/common/cre/xavoidla.cre~ ~override~
	SAY NAME1 @917
	SAY NAME2 @917
	
	COPY ~%MOD_FOLDER%/common/cre/xavoidle.cre~ ~override~
	SAY NAME1 @917
	SAY NAME2 @917
	
	COPY ~%MOD_FOLDER%/common/cre/xavoidw.cre~ ~override~
	SAY NAME1 @915
	SAY NAME2 @915
	
	COPY ~%MOD_FOLDER%/common/cre/xavoidwa.cre~ ~override~
	SAY NAME1 @915
	SAY NAME2 @915
	
	COPY ~%MOD_FOLDER%/common/cre/xavoidwe.cre~ ~override~
	SAY NAME1 @915
	SAY NAME2 @915
//}

//{ Narzugon
	COPY ~%MOD_FOLDER%/common/bmp/xanarzus.bmp~ ~override~
//}

//{ itm

	COPY ~%MOD_FOLDER%/common/itm/xacorbo4.itm~ ~override~
	SAY NAME1 @972
	SAY NAME2 @972
	SAY UNIDENTIFIED_DESC @973
	SAY DESC @973
	

	COPY ~%MOD_FOLDER%/common/itm/xacorch4.itm~ ~override~
	SAY NAME1 @968
	SAY NAME2 @968
	SAY UNIDENTIFIED_DESC @969
	SAY DESC @969
	
	
	
	COPY ~%MOD_FOLDER%/common/itm/xastdagd.itm~ ~override~
	SAY NAME1 @943 							
	SAY NAME2 @944
	SAY UNIDENTIFIED_DESC @958
	SAY DESC @958	
	
	COPY ~%MOD_FOLDER%/common/itm/xasword.itm~ ~override~
	SAY NAME1 @964
	SAY NAME2 @964
	SAY UNIDENTIFIED_DESC @965
	SAY DESC @965
	
	COPY ~%MOD_FOLDER%/common/itm/xasword2.itm~ ~override~
//}
