//{ Script Reporter
IF
	!Global("XA_LC_ActiveScript", "GLOBAL", 4)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_ActiveScript", "GLOBAL", 4)
		Continue()
END
//}

//{ Kanaglym Dream
	IF
		GlobalLT("XA_LC_KanaDreamTimerSet", "GLOBAL",1)
		Global("XA_LC_ClearedKanaglym", "GLOBAL",1)
		Global("XA_LC_EnteredSaradush", "GLOBAL", 1)
		Global("XA_LC_IncubusDefeated", "GLOBAL", 1)
	THEN
		RESPONSE #100
			SetGlobal("XA_LC_KanaDreamTimerSet", "GLOBAL",1)
			Continue()
	END
//}