//{ Longbow Training
IF
	InParty("Corwin")
	TriggerOverride("Corwin", See(Player1))
	TriggerOverride("Corwin", See("BDBELEGA"))
	IsValidForPartyDialog("Corwin")
	IsValidForPartyDialog(Player1)
	GlobalTimerExpired("XA_LC_A_ProficiencyTimer", "GLOBAL")
	TimeOfDay(DAY)
	GlobalLT("XA_LC_A_ProficiencyTalk", "GLOBAL", 1)
	OR(2)
		IsWeaponRanged(Player1)
		TriggerOverride(Player1, CanEquipRanged())
THEN
	RESPONSE #100
		SetGlobal("XA_LC_A_ProficiencyTalk", "GLOBAL", 1)
		
END
//}