IF 
	InPartyAllowDead("Corwin")
	!Global("XA_LC_CorwinAvernus", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_CorwinAvernus", "GLOBAL", 1)
		Continue()
END

IF
	Global("bd_asha_duel","global",3)
	GlobalLT("XA_LC_HonorableDuel", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_HonorableDuel", "GLOBAL", 1)
		Continue()
END

IF
	Dead("bdkherr")
	GlobalLT("XA_LC_ClearedKanaglym", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_ClearedKanaglym", "GLOBAL", 1)
		Continue()
END