IF
	Global("XA_LC_TLR_LeftPartyFight", "LOCALS", 1)
	Dead("lrirenic")
THEN
	RESPONSE #100
		SetGlobal("XA_LC_TLR_LeftPartyFight", "LOCALS", 3)
		SetGlobal("XA_LC_TLR_CorwinIrenicusFight", "GLOBAL", 3)
		JoinParty()
END

IF
	Global("XA_LC_TLR_LeftPartyFight", "LOCALS", 2)
	Dead("xacorwin")
THEN
	RESPONSE #100
		SetGlobal("XA_LC_TLR_LeftPartyFight", "LOCALS", 3)
		SetGlobal("XA_LC_TLR_CorwinIrenicusFight", "GLOBAL", 3)
		JoinParty()
END