IF
	Global("XA_Cromwell_CorwinBow", "GLOBAL", 1)
	Global("ForgeStuff", "GLOBAL" , 1)
THEN
	RESPONSE #100
		SetGlobal("XA_Cromwell_CorwinBow", "GLOBAL", 0)
		SetGlobal("ForgeStuff", "GLOBAL" , 0)
		SetGlobal("ForgeItem", "GLOBAL", 1)
		TakePartyItem("XACORBOW")  // Corwin's Bow + 2
		TakePartyItem("BOW19B") // Gesen String
		GiveItemCreate("XACORBG3", Player1, 0,0,0) // Corwin's Bow + 3 (Gesen)
		ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END