PRINT @4000  /* ~Processing Return to Baldur's Gate Changes...~ */

SILENT

OUTER_SET xa_regenerate = 0 // set to 1 to regenerate areas, 0 (default) to copy pre-generated areas

//{ WAV
	COPY ~%MOD_FOLDER%/rbg/wav~ ~override~
//}

//{ BAM
	COPY ~%MOD_FOLDER%/rbg/bam~ ~override~
//}

//{ Narzugon, Hephernaan and Dragon Animations
	ACTION_IF (isEET = 0) THEN BEGIN
		COPY ~%MOD_FOLDER%/rbg/anim~ ~override~

		APPEND ~animate.ids~ ~0x7D04 HARLOT_FIGHTER~
		APPEND ~animate.ids~ ~0x7F5A ABISHAI_RED~
		APPEND ~animate.ids~ ~0x7F5B ABISHAI_BLUE~
		APPEND ~animate.ids~ ~0x7F58 ABISHAI_BLACK~
		APPEND ~animate.ids~ ~0x7F59 ABISHAI_GREEN~
		APPEND ~animate.ids~ ~0xE258 HERPHERNAAN~
		APPEND ~animate.ids~ ~0xE279 OROG_SHAMAN~
		APPEND ~animate.ids~ ~0xEA10 SHADOW_SMALL~
		
		// The hashes of these bams are the same. No sense in including them in the download.
		COPY_EXISTING ~mbe2dee.bam~ ~override/mbe2gue.bam~
		COPY_EXISTING ~mbe2dee.bam~ ~override/mbe2sce.bam~
		COPY_EXISTING ~mbe2dee.bam~ ~override/mbe2sle.bam~
		
		COPY_EXISTING ~mbe2de.bam~ ~override/mbe2gu.bam~
		COPY_EXISTING ~mbe2de.bam~ ~override/mbe2sc.bam~
		COPY_EXISTING ~mbe2de.bam~ ~override/mbe2sl.bam~
	END
	
//}

PRINT @4172 /*  ~Processing conversion blocks...~ */
PRINT @4164 /* ~Please be patient. This may take a while.~ */
SILENT

INCLUDE ~%MOD_FOLDER%/generated/a/generated.tph~
INCLUDE ~%MOD_FOLDER%/generated/c/generated.tph~
INCLUDE ~%MOD_FOLDER%/generated/f/generated.tph~
INCLUDE ~%MOD_FOLDER%/generated/g/generated.tph~

//{ Worldmap
	COPY ~%MOD_FOLDER%/rbg/mos/xamaprbg.mos~ ~override~
	COPY ~%MOD_FOLDER%/rbg/wmp/xamaprbg.wmp~ ~override~
	WRITE_LONG 0x24 RESOLVE_STR_REF(@4136) // Map Name
	WRITE_LONG 0x978 RESOLVE_STR_REF(@4137) // Wyrm Crossing Label
		
	//{ Wyrm's Crossing (0900) <--> E Baldur's Gate (0800) xaa100 <--> xaa104
		LPF xa_mapdoublelink
			STR_VAR
				xa_area_a = ~xaa100~
				xa_area_a_entry = ~Exit0800~
				xa_area_a_exit_node = ~w~
				xa_area_b = ~xaa104~
				xa_area_b_entry = ~Ext0800e~
				xa_area_b_exit_node = ~e~
		END
	//}
	
	//{ NW Baldur's Gate (0100) <--> N Baldur's Gate (0200) xaa233 <--> xaa134
		LPF xa_mapdoublelink
			STR_VAR
				xa_area_a = ~xaa233~
				xa_area_a_entry = ~Ext0100e~
				xa_area_a_exit_node = ~e~
				xa_area_b = ~xaa134~
				xa_area_b_entry = ~Ext0200w~
				xa_area_b_exit_node = ~w~
		END
	//}
	
	//{ NW Baldur's Gate (0100) <--> W Baldur's Gate (0600) xaa233 <--> xaa168
		LPF xa_mapdoublelink
			STR_VAR
				xa_area_a = ~xaa233~
				xa_area_a_entry = ~Ext0100s~
				xa_area_a_exit_node = ~s~
				xa_area_b = ~xaa168~
				xa_area_b_entry = ~Ext0600n~
				xa_area_b_exit_node = ~n~
		END
	//}
	
	//{ N Baldur's Gate (0200) <--> NE Baldur's Gate (0300) xaa134 <--> xaa107
		LPF xa_mapdoublelink
			STR_VAR
				xa_area_a = ~xaa134~
				xa_area_a_entry = ~Ext0200e~
				xa_area_a_exit_node = ~e~
				xa_area_b = ~xaa107~
				xa_area_b_entry = ~Ext0300w~
				xa_area_b_exit_node = ~w~
		END
	//}
		
	//{ N Baldur's Gate (0200) <--> C Baldur's Gate (0700) xaa134 <--> xaa109
		LPF xa_mapdoublelink
			STR_VAR
				xa_area_a = ~xaa134~
				xa_area_a_entry = ~Ext0200s~
				xa_area_a_exit_node = ~s~
				xa_area_b = ~xaa109~
				xa_area_b_entry = ~Ext0700n~
				xa_area_b_exit_node = ~n~
		END
	//}
	
	//{ NE Baldur's Gate (0300) <--> E Baldur's Gate (0800) xaa107 <--> xaa104
		LPF xa_mapdoublelink
			STR_VAR
				xa_area_a = ~xaa107~
				xa_area_a_entry = ~Ext0300s~
				xa_area_a_exit_node = ~s~
				xa_area_b = ~xaa104~
				xa_area_b_entry = ~Ext0800n~
				xa_area_b_exit_node = ~n~
		END
	//}
	
	//{ W Baldur's Gate (0600) <--> C Baldur's Gate (0700) xaa168 <--> xaa109
		LPF xa_mapdoublelink
			STR_VAR
				xa_area_a = ~xaa168~
				xa_area_a_entry = ~Ext0600e~
				xa_area_a_exit_node = ~e~
				xa_area_b = ~xaa109~
				xa_area_b_entry = ~Ext0700w~
				xa_area_b_exit_node = ~w~
		END
	//}
	
	//{ W Baldur's Gate (0600) <--> SW Baldur's Gate (1100) xaa168 <--> xaa146
		LPF xa_mapdoublelink
			STR_VAR
				xa_area_a = ~xaa168~
				xa_area_a_entry = ~Ext0600s~
				xa_area_a_exit_node = ~s~
				xa_area_b = ~xaa146~
				xa_area_b_entry = ~Ext1100n~
				xa_area_b_exit_node = ~n~
		END
	//}
	
	//{ C Baldur's Gate (0700) <--> E Baldur's Gate (0800) xaa109 <--> xaa104
		LPF xa_mapdoublelink
			STR_VAR
				xa_area_a = ~xaa109~
				xa_area_a_entry = ~Ext0700e~
				xa_area_a_exit_node = ~e~
				xa_area_b = ~xaa104~
				xa_area_b_entry = ~Ext0800w~
				xa_area_b_exit_node = ~w~
		END
	//}
	
	//{ C Baldur's Gate (0700) <--> S Baldur's Gate (Docks) (1200)  xaa107 <--> xaa108
		LPF xa_mapdoublelink
			STR_VAR
				xa_area_a = ~xaa109~
				xa_area_a_entry = ~Ext0700s~
				xa_area_a_exit_node = ~s~
				xa_area_b = ~xaa108~
				xa_area_b_entry = ~Ext1200n~
				xa_area_b_exit_node = ~n~
		END
	//}
	
	//{ E Baldur's Gate (0800) <--> SE Baldur's Gate (1300) xaa104 <--> xaa145
		LPF xa_mapdoublelink
			STR_VAR
				xa_area_a = ~xaa104~
				xa_area_a_entry = ~Ext0800s~
				xa_area_a_exit_node = ~s~
				xa_area_b = ~xaa145~
				xa_area_b_entry = ~Ext1300n~
				xa_area_b_exit_node = ~n~
		END
	//}
	
	//{ SW Baldur's Gate (1100) <--> S Baldur's Gate (1200) xaa146 <--> xaa108
		LPF xa_mapdoublelink
			STR_VAR
				xa_area_a = ~xaa146~
				xa_area_a_entry = ~Ext1100e~
				xa_area_a_exit_node = ~e~
				xa_area_b = ~xaa108~
				xa_area_b_entry = ~Ext1200w~
				xa_area_b_exit_node = ~w~
		END
	//}
		
	//{ S Baldur's Gate (1200) <--> SE Baldur's Gate (1300) xaa108 <--> xaa145
		LPF xa_mapdoublelink
			STR_VAR
				xa_area_a = ~xaa108~
				xa_area_a_entry = ~Ext1200e~
				xa_area_a_exit_node = ~e~
				xa_area_b = ~xaa145~
				xa_area_b_entry = ~Ext1300w~
				xa_area_b_exit_node = ~w~
		END
	//}
//}

COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/rbg/d~
COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/rbg/baf~

//{ Record who was in BG
	ACTION_DEFINE_ARRAY xa_replacements
	BEGIN
		Aerie
		Anomen
		Dorn
		Edwin
		HaerDalis
		Imoen2
		Jaheira
		Jan
		Keldorn
		Korgan
		Nalia
		Rasaad
		Valygar
		Viconia
	END
	
	LAF xa_replaceIn
		STR_VAR
			xa_copyFrom = ~xabgrec~
			xa_extendTarget = ~xaar0900~
			xa_fileextension = ~bcs~
			xa_strToReplace = ~TO_REPLACE~
	END
//}

//{ Replace Rumors
	COPY_EXISTING_REGEXP GLOB ~xaa.+\.sto$~ ~override~ 
	WRITE_ASCII 0x44 ~xarumor~ #8
	BUT_ONLY
//}

//{ Script Extensions
	/* Explore BG1 Areas, and cause Bence to spawn when the debriefing timer expires. */
	EXTEND_TOP_REGEXP ~xaas.+\.bcs$~ ~%MOD_FOLDER%/rbg/baf/xalcbg1a.baf~

	EXTEND_TOP ~player1d.bcs~ 	~%MOD_FOLDER%/rbg/baf/xap1d.baf~
	EXTEND_TOP ~xabalrbg.bcs~ 	~%MOD_FOLDER%/rbg/baf/xabalegg.baf~
	EXTEND_TOP ~xabalrbg.bcs~ 	~%MOD_FOLDER%/rbg/baf/xabalamu.baf~
	EXTEND_TOP ~baldur.bcs~ 	~%MOD_FOLDER%/rbg/baf/xabalrbg.baf~	
//}

//{ BMP
	COPY ~%MOD_FOLDER%/rbg/bmp~ ~override~
//}

PRINT @4173 /*  ~Processing creatures...*/
SILENT
	
//{ CRE
	//{ Pause / Rewind
		COPY_EXISTING ~xalcspy.cre~ ~override/xapause.cre~
		WRITE_ASCII 0x248 ~xapause~ #8 
		OUTER_SET xa_hour = 0
		OUTER_WHILE(xa_hour < 24)
		BEGIN
			COPY_EXISTING ~xapause24.bcs~ ~override/xapause%xa_hour%.bcs~
			DECOMPILE_AND_PATCH BEGIN
				REPLACE_TEXTUALLY ~24~ ~%xa_hour%~
			END
			EXTEND_TOP ~xapause.bcs~ 	~override/xapause%xa_hour%.bcs~
			xa_hour = xa_hour + 1
		END
		
		COPY_EXISTING ~xalcspy.cre~ ~override/xarewind.cre~
		WRITE_ASCII 0x248 ~xarewind~ #8 
		OUTER_SET xa_hour = 0
		OUTER_WHILE(xa_hour < 24)
		BEGIN
			COPY_EXISTING ~xarewind24.bcs~ ~override/xarewind%xa_hour%.bcs~
			DECOMPILE_AND_PATCH BEGIN
				REPLACE_TEXTUALLY ~24~ ~%xa_hour%~
			END
			EXTEND_TOP ~xarewind.bcs~ 	~override/xarewind%xa_hour%.bcs~
			xa_hour = xa_hour + 1
		END
	//}
	//{ Block A Base
		COPY_EXISTING ~xaa100.cre~ ~override/xasarevo.cre~ // sarevo
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xasarevo~
				xa_scriptName = ~xasarevo~
				xa_override = ~xasarevo~
				xa_race = ~wtasight~
		END
		ADD_CRE_ITEM ~xasdiary~ #0 #0 #0 ~identified&unstealable~ ~INV1~
		
		COPY_EXISTING ~xaa966.cre~ ~override~
		LPF xa_reset_cre
			STR_VAR
				xa_override = ~xafigh01~
				xa_general = ~xalcwalk~
				xa_dialog = ~xafergus~
		END
		
		COPY_EXISTING ~xaa947.cre~ ~override/xag2dop0.cre~ // dopmer
		WRITE_ASCII 0x250 ~xag2dop~ #8 // class script
		WRITE_ASCII 0x268 ~xafigh01~ #8 // race script
		WRITE_ASCII 0x280 ~xag2dop0~ #8 // script name
		WRITE_LONG 0x14 3500 // xp
		WRITE_SHORT 0x24 85 // hp
		WRITE_SHORT 0x26 85 // hp		
		
		COPY_EXISTING ~xag2dop0.cre~ ~override/xag2dop1.cre~
		WRITE_ASCII 0x280 ~xag2dop1~ #8 // script name
		WRITE_LONG 0x28 0xC810 // Fat woman
		WRITE_BYTE 0x275 2 // Female
		
		COPY_EXISTING ~xag2dop0.cre~ ~override/xag2dop2.cre~
		WRITE_ASCII 0x280 ~xag2dop2~ #8 // script name
		
		COPY_EXISTING ~xag2dop1.cre~ ~override/xag2dop3.cre~
		WRITE_ASCII 0x280 ~xag2dop3~ #8 // script name
		
		//{ Male Townspeople
			ACTION_DEFINE_ARRAY maleTownspeople
			BEGIN
				xaa731		// mtob2
				xaa1190		// mtob3
				xaa849		// mtob6
				xaa694		// mtob7
				xaa877		// mtob8
				xaa695		// mtob9
				xaa463		// mtowba
				xaa151		// mtowba_a
				xaa166		// mtowba_b
				xaa180		// mtowba_c
				xaa172		// mtowba_d
				xaa250		// mtowba_e
				xaa170		// mtowbasc
				xaa132		// mtowbasn
				xaa452		// mtowbast
				xaa583		// mtowbax
				xaa498		// mtowbesn
				xaa1207		// mtowwon1
				xaa1208		// mtowwon2
				xaa1209		// mtowwon3
				xaa123		// mtwbax_a
				xaa124		// mtwbax_b
				xaa128		// mtwbax_c
				xaa126		// mtwbax_d
				xaa131		// mtwbax_e
				xaa952		// mtwslim
				xaa953		// mtwslim2
				xaa954		// mtwslim3
			END
			
			ACTION_PHP_EACH maleTownspeople AS _ => maleTownsperson
			BEGIN
				COPY_EXISTING ~%maleTownsperson%.cre~ ~override~
				LPF xa_reset_cre
					STR_VAR
						xa_dialog = ~xatownm~
						xa_override = ~xalcflee~
						xa_class = ~xalcwalk~
				END
			END
		//}
		
		//{ Female Townspeople
			ACTION_DEFINE_ARRAY femaleTownspeople
			BEGIN
				xaa548	// ftowb5
				xaa981	// ftowb6
				xaa696	// ftowb7
				xaa560	// ftowba
				xaa167	// ftowba_a
				xaa375	// ftowba_b
				xaa251	// ftowba_c
				xaa130	// ftowba_d
				xaa134	// ftowba_e
				xaa129	// ftowbasc
				xaa291	// ftowbasn
				xaa605	// ftowbax
				xaa127	// ftwbax_a
				xaa140	// ftwbax_b
				xaa163	// ftwbax_c
				xaa135	// ftwbax_d
				xaa168	// ftwbax_e
			END
			
			ACTION_PHP_EACH femaleTownspeople AS _ => femaleTownsperson
			BEGIN
				COPY_EXISTING ~%femaleTownsperson%.cre~ ~override~
				LPF xa_reset_cre
					STR_VAR
						xa_dialog = ~xatownf~
						xa_override = ~xalcflee~
						xa_class = ~xalcwalk~
				END
			END
		//}
			
		//{ Noblemen
			ACTION_DEFINE_ARRAY noblemen
			BEGIN
				xaa257 	// nobbax_a
				xaa200 	// nobbax_b
				xaa524 	// nobbax_c
				xaa372 	// nobbax_d
				xaa396 	// nobbax_e
				xaa730 	// nobl11
				xaa1035 // nobl12
				xaa932 	// nobl14
				xaa359 	// noblba_a
				xaa767 	// noblba_b
				xaa532 	// noblba_c
				xaa521 	// noblba_d
				xaa755 	// noblba_e
			END
			
			ACTION_PHP_EACH noblemen AS _ => nobleman
			BEGIN
				COPY_EXISTING ~%nobleman%.cre~ ~override~
				LPF xa_reset_cre
					STR_VAR
						xa_dialog = ~xanoblm~
						xa_override = ~xalcflee~
						xa_class = ~xalcwalk~
				END
			END
		//}
		
		//{ Noblewomen
			ACTION_DEFINE_ARRAY noblewomen
			BEGIN
				xaa1033	// nobw5
				xaa1353 // nobw7
				xaa1334 // nobw8
				xaa728	// nobw9
				xaa360	// nobwba
				xaa1072 // nobwba_a
				xaa514	// nobwba_d
				xaa1084 // nobwba_e
				xaa361	// nowbax_a
				xaa397	// nowbax_b
				xaa402	// nowbax_c
				xaa369	// nowbax_d
				xaa370	// nowbax_e
			END
			
			ACTION_PHP_EACH noblewomen AS _ => noblewoman
			BEGIN
				COPY_EXISTING ~%noblewoman%.cre~ ~override~
				LPF xa_reset_cre
					STR_VAR
						xa_dialog = ~xanoblw~
						xa_override = ~xalcflee~
						xa_class = ~xalcwalk~
				END
			END
		//}
		
		COPY_EXISTING ~xaa274.cre~ ~override/xabrielb.cre~ // Brielbara brielb
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xabrielb~
				xa_scriptName = ~xabrielb~
				xa_override = ~xainitp1~
		END
		
		COPY_EXISTING ~xaa463.cre~ ~override/xa800m.cre~ // mtowba
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xa800m~
				xa_scriptName = ~xa800m~
		END
		
		COPY_EXISTING ~xaa465.cre~ ~override/xabrevlk.cre~ // Brevlik brevli
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xabrevlk~
				xa_scriptName = ~xabrevlk~
				xa_override = ~xabrevlk~
		END
		
		COPY_EXISTING ~xaa552.cre~ ~override/xalarze.cre~ // Larze larze
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xalarze~
				xa_scriptName = ~xalarze~
				xa_override = ~xainitp1~
				xa_general = ~xafigh01~
		END
		
		COPY_EXISTING ~xaa560.cre~ ~override/xamom.cre~ // ftowba
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xamom~
				xa_scriptName = ~xamom~
				xa_override = ~xamom~
		END
		SAY NAME1 @4154 /*~Anguished Mother~ */
		SAY NAME2 @4154 /* */
		
		COPY_EXISTING ~xaa560.cre~ ~override/xa800w.cre~ // ftowba
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xa800w~
				xa_scriptName = ~xa800w~
		END
		
		COPY_EXISTING ~xaa687.cre~ ~override~ // WV Guard 1 iron13
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xawvgrd1~
				xa_override = ~xaguard~
		END
		
		COPY_EXISTING ~xaa688.cre~ ~override~ // WV Merchant ironme
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xawvmer~
				xa_override = ~xalcflee~
				xa_class = ~xalcwalk~
		END
		
		COPY_EXISTING ~xaa1179.cre~ ~override/xawvgrd.cre~ // WV Guard 2 iron12
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xawvgrd2~
				xa_override = ~xaguard~
		END
		
		COPY_EXISTING ~xaa702.cre~ ~override~ // Umberlee Priestess pumber1
		WRITE_ASCII 0x2CC ~xaumberl~ #8
		
		COPY_EXISTING ~xaa730.cre~ ~override/xavirgil.cre~ // Virgil nobl11
		SAY NAME1 @4082
		SAY NAME2 @4082
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xavirgil~
				xa_scriptName = ~xavirgil~
				xa_default = ~xavirgil~
		END
		
		COPY_EXISTING ~xaa874.cre~ ~override~ // Nadine nadine
		WRITE_ASCII 0x2CC ~xanadine~ #8 	// Dialogue
		
		COPY_EXISTING ~xaa904.cre~ ~override/xaalyth.cre~ // Alyth alyth
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xaalyth~
				xa_scriptName = ~xaalyth~
				xa_override = ~xainitp1~
		END
		
		COPY_EXISTING ~xaa1105.cre~ ~override/xamerchj.cre~ // Seven Suns Merchant merlea
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xamerch~
				xa_override = ~xamerchj~
		END
		
		COPY_EXISTING ~xaa1360.cre~ ~override/xawvmer1.cre~ // WV Merchant ironm3
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xawvmer~
				xa_override = ~xalcflee~
				xa_class = ~xalcwalk~
		END
		
		COPY_EXISTING ~xawvmer1.cre~ ~override/xawvmer2.cre~ // WV Merchant ironm3
		
		COPY_EXISTING ~xaa1105.cre~ ~override/xamerlea.cre~ // Merchant's League Merchant
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xamerlea~
				xa_override = ~shout~
				xa_class = ~runenemy~
				xa_race = ~wtrunsgt~
				xa_general = ~xamerlea~
		END
		
		COPY_EXISTING ~xaa1000.cre~ ~override~ // Euric
		WRITE_ASCII 0x2CC ~xaeuric~ #8 	// Dialogue
		
		COPY_EXISTING ~xaa1359.cre~ ~override~ // Merchant's League Bartender bart6
		LPF xa_reset_cre
			STR_VAR
				xa_override = ~xalcflee~
				xa_dialog = ~xabartml~
		END
		
		COPY_EXISTING ~xaa1322.cre~ ~override/xajhasso.cre~ // Jhasso jhasso
		LPF xa_reset_cre
			STR_VAR
				xa_scriptName = ~xajhasso~
				xa_override = ~xainitp1~
				xa_dialog = ~xajhasso~
				xa_general = ~xalcflee~
				xa_class = ~xalcwalk~
		END
		WRITE_BYTE 0xA4 255 // set initial greeting str ref to -1
		WRITE_BYTE 0xA5 255
		WRITE_BYTE 0xA6 255
		WRITE_BYTE 0xA7 255
		
		WRITE_BYTE 0x10C 255 // set common select str ref to -1
		WRITE_BYTE 0x10D 255
		WRITE_BYTE 0x10E 255
		WRITE_BYTE 0x10F 255
		
		COPY_EXISTING ~xaa108.cre~ ~override/xasemaj.cre~ // Semaj semaj
		LPF xa_reset_cre
			STR_VAR
				xa_scriptName = ~xasemaj~
				xa_override = ~shout~
				xa_race = ~mage12d~
				xa_general = ~wtasight~
		END
		
		COPY_EXISTING ~xaa1033.cre~ ~override/xacurato.cre~ // Curator Magda nobw5
		SAY NAME1 @4048 /* Curator Magda */
		SAY NAME2 @4048
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xacurato~
				xa_scriptName = ~xacurato~
				xa_override = ~xacurato~
		END
		
		COPY_EXISTING ~xaa1366.cre~ ~override/xazhalim.cre~ // Zhalimar zhalim
		LPF xa_reset_cre
			STR_VAR
				xa_scriptName = ~xazhalim~
				xa_override = ~shout~
				xa_default = ~wtasight~
		END
		
		COPY_EXISTING ~xaa1368.cre~ ~override/xaaasim.cre~ // Aasim aasim
		LPF xa_reset_cre
			STR_VAR
				xa_scriptName = ~xaaasim~
				xa_override = ~shout~
				xa_class = ~priest5~
				xa_default = ~wtasight~
		END
		
		COPY_EXISTING ~xaa1369.cre~ ~override/xadiyab.cre~ // Diyab diyab
		LPF xa_reset_cre
			STR_VAR
				xa_scriptName = ~xadiyab~
				xa_override = ~shout~
				xa_class = ~priest5~
				xa_default = ~wtasight~
		END
		
		COPY_EXISTING ~xaa1370.cre~ ~override/xagardus.cre~ // Gardus gardus
		LPF xa_reset_cre
			STR_VAR
				xa_scriptName = ~xagardus~
				xa_override = ~shout~
				xa_default = ~wtasight~
		END
		
		COPY_EXISTING ~xaa130.sto~ ~override/xabartml.sto~ // Merchants' League Bar tav0705
		WRITE_LONG 0xC RESOLVE_STR_REF(@4149)
	//}
	
	//{ Block C Base
		COPY_EXISTING ~xac100.cre~ ~override/xaglint.cre~ // Glint glint7
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xaglint~
				xa_override = ~xaglint~
				xa_scriptName = ~xaglint~
		END
		
		COPY_EXISTING ~xac101.cre~ ~override/xarohma.cre~ // Rohma bdrohma
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xarohma~
				xa_override = ~xarohma1~
				xa_scriptName = ~xarohma~
		END
		
		COPY_EXISTING ~xac102.cre~ ~override/xaaudam.cre~ // Audamar bdaudam
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xaaudam~
				xa_override = ~xaaudam~
				xa_scriptName = ~xaaudam~
		END
		
		COPY_EXISTING ~xac103.cre~ ~override/xanederl.cre~ // Nederlok bdnederl
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xanederl~
				xa_override = ~xafigh01~
				xa_scriptName = ~xanederl~
		END
		
		COPY_EXISTING ~xac104.cre~ ~override/xaaldeth.cre~ // Aldeth aldeth
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xaaldeth~
				xa_override = ~xainitp1~
				xa_scriptName = ~xaaldeth~
		END
		
		COPY_EXISTING ~xac105.cre~ ~override/xakent.cre~ // Kent kent
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xakent~
				xa_override = ~xafigh01~
				xa_scriptName = ~xakent~
		END
		
		COPY_EXISTING ~xac106.cre~ ~override/xabeno.cre~ // Beno bdfamari
		ADD_CRE_ITEM ~xbow04~ #0 #0 #0 ~IDENTIFIED~ ~WEAPON2~
		ADD_CRE_ITEM ~bolt01~ #20 #0 #0 ~IDENTIFIED~ ~QUIVER1~
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xabeno~
				xa_override = ~xabenof~
				xa_scriptName = ~xabeno~
		END
		
		COPY_EXISTING ~xac107.cre~ ~override/xaskie.cre~ // Skie bdskie
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xaskie~
				xa_override = ~xaskie~
				xa_scriptName = ~xaskie~
		END
		
		//{ Evil Caelar
			COPY_EXISTING ~xac108.cre~ ~override~ // bdcaela2
			WRITE_BYTE 0x270 255
			LPF xa_reset_cre
				STR_VAR
					xa_override = ~xag1crus~
					xa_scriptName = ~xac108~
					xa_general = ~xacaelac~
					xa_default = ~xac130~ // bdfmcl01
			END
			COPY_EXISTING ~xac109.cre~ ~override~
			WRITE_BYTE 0x270 255
			LPF xa_reset_cre
				STR_VAR
					xa_override = ~xag1crus~
					xa_scriptName = ~xac109~
					xa_general = ~xacaelac~
					xa_default = ~xac130~ // bdfmcl01
			END
			
		//}
		EXTEND_BOTTOM ~xag1coal.bcs~ ~%MOD_FOLDER%/rbg/baf/xacrtyrd.baf~
		EXTEND_BOTTOM ~xag1crus.bcs~ ~%MOD_FOLDER%/rbg/baf/xacrtyrd.baf~
		
		//{ Coalition Respawns
			COPY_EXISTING ~xac121.cre~ ~override/xacoal0.cre~ // bddagf35
			COPY_EXISTING ~xac122.cre~ ~override/xacoal1.cre~ // bddagf36
			COPY_EXISTING ~xac123.cre~ ~override/xacoal2.cre~ // bddagf37
			COPY_EXISTING ~xac124.cre~ ~override/xacoal3.cre~ // bddagf38
			COPY_EXISTING ~xac125.cre~ ~override/xacoal4.cre~ // bdfist35
			COPY_EXISTING ~xac126.cre~ ~override/xacoal5.cre~ // bdfist36
			COPY_EXISTING ~xac127.cre~ ~override/xacoal6.cre~ // bdfist37
			COPY_EXISTING ~xac128.cre~ ~override/xacoal7.cre~ // bdfist38
			COPY_EXISTING ~xac129.cre~ ~override/xacoal8.cre~ // bdfist40
			COPY_EXISTING ~xac130.cre~ ~override/xacoal9.cre~ // bdfist41
			COPY_EXISTING ~xac131.cre~ ~override/xacoal10.cre~ // bdfist42
			COPY_EXISTING ~xac132.cre~ ~override/xacoal11.cre~ // bdwtr35
			COPY_EXISTING ~xac133.cre~ ~override/xacoal12.cre~ // bdwtr36
			COPY_EXISTING ~xac134.cre~ ~override/xacoal13.cre~ // bdwtr37
			COPY_EXISTING ~xac135.cre~ ~override/xacoal14.cre~ // bdwtr38

			COPY_EXISTING_REGEXP GLOB ~xacoal.+\.cre$~ ~override~ 
				LPF xa_reset_cre
					STR_VAR
						xa_override = ~xag1coal~
						xa_general = ~xac130~ // bdfmcl01
				END
			BUT_ONLY
		//}
		
		//{ Crusader Respawns
			COPY_EXISTING ~xac136.cre~ ~override/xacrus0.cre~ //bdcru40
			COPY_EXISTING ~xac137.cre~ ~override/xacrus1.cre~ //bdcru41
			COPY_EXISTING ~xac138.cre~ ~override/xacrus2.cre~ //bdcru42
			COPY_EXISTING ~xac139.cre~ ~override/xacrus3.cre~ //bdcru43
			COPY_EXISTING ~xac140.cre~ ~override/xacrus4.cre~ //bdcru44
			COPY_EXISTING ~xac141.cre~ ~override/xacrus5.cre~ //bdcru45
			COPY_EXISTING ~xac142.cre~ ~override/xacrus6.cre~ //bdcru46
			COPY_EXISTING ~xac143.cre~ ~override/xacrus7.cre~ //bdcru47
			COPY_EXISTING ~xac144.cre~ ~override/xacrus8.cre~ //bdcru51
			COPY_EXISTING ~xac145.cre~ ~override/xacrus9.cre~ //bdcru52
			COPY_EXISTING ~xac146.cre~ ~override/xacrus10.cre~ //bdcru53
			COPY_EXISTING ~xac147.cre~ ~override/xacrus11.cre~ //bdcru54
			COPY_EXISTING ~xac148.cre~ ~override/xacrus12.cre~ //bdcru55
			COPY_EXISTING ~xac149.cre~ ~override/xacrus13.cre~ //bdcru56
			COPY_EXISTING ~xac150.cre~ ~override/xacrus14.cre~ //bdcru57
			COPY_EXISTING ~xac151.cre~ ~override/xacrus15.cre~ //bdcru58
			COPY_EXISTING ~xac167.cre~ ~override/xacrus16.cre~ //bdcru118
			COPY_EXISTING ~xac171.cre~ ~override/xacrus17.cre~ //bdcru117
			COPY_EXISTING ~xac175.cre~ ~override/xacrus18.cre~ //bdcrum31
			COPY_EXISTING ~xac176.cre~ ~override/xacrus19.cre~ //bdcrum32
			COPY_EXISTING ~xac177.cre~ ~override/xacrus20.cre~ //bdcrum30
			COPY_EXISTING ~xac190.cre~ ~override/xacrus21.cre~ //bdcrus36
			COPY_EXISTING ~xac192.cre~ ~override/xacrus22.cre~ //bdcrus35
			COPY_EXISTING ~xac200.cre~ ~override/xacrus23.cre~ //bdcrus29
			COPY_EXISTING ~xac202.cre~ ~override/xacrus24.cre~ //bdcrus39
			COPY_EXISTING ~xac204.cre~ ~override/xacrus25.cre~ //bdcrux31
			COPY_EXISTING ~xac205.cre~ ~override/xacrus26.cre~ //bdcrue30
			COPY_EXISTING ~xac206.cre~ ~override/xacrus27.cre~ //bdcrux30
			COPY_EXISTING ~xac207.cre~ ~override/xacrus28.cre~ //bdcrue33
			COPY_EXISTING ~xac209.cre~ ~override/xacrus29.cre~ //bdcrur30
			COPY_EXISTING ~xac213.cre~ ~override/xacrus30.cre~ //bdcrus38
			COPY_EXISTING ~xac214.cre~ ~override/xacrus31.cre~ //bdcrus20
			COPY_EXISTING ~xac219.cre~ ~override/xacrus32.cre~ //bdcrur33
			COPY_EXISTING ~xac221.cre~ ~override/xacrus33.cre~ //bdcrur31
			COPY_EXISTING ~xac222.cre~ ~override/xacrus34.cre~ //bdcrur34
			COPY_EXISTING ~xac223.cre~ ~override/xacrus35.cre~ //bdcru101
			COPY_EXISTING ~xac224.cre~ ~override/xacrus36.cre~ //bdcrur32
			COPY_EXISTING ~xac227.cre~ ~override/xacrus37.cre~ //bdcrur29
			COPY_EXISTING ~xac228.cre~ ~override/xacrus38.cre~ //bdcrus33
			COPY_EXISTING ~xac230.cre~ ~override/xacrus39.cre~ //bdcru111
			COPY_EXISTING ~xac231.cre~ ~override/xacrus40.cre~ //bdcrus95
			COPY_EXISTING ~xac233.cre~ ~override/xacrus41.cre~ //bdcrur27
			COPY_EXISTING ~xac235.cre~ ~override/xacrus42.cre~ //bdcrur28
			COPY_EXISTING ~xac236.cre~ ~override/xacrus43.cre~ //bdcru100
			COPY_EXISTING ~xac237.cre~ ~override/xacrus44.cre~ //bdcrur26
			COPY_EXISTING ~xac238.cre~ ~override/xacrus45.cre~ //bdcrus98
			COPY_EXISTING ~xac240.cre~ ~override/xacrus46.cre~ //bdcrue32
			COPY_EXISTING ~xac241.cre~ ~override/xacrus47.cre~ //bdcrue31
			COPY_EXISTING ~xac243.cre~ ~override/xacrus48.cre~ //bdcru112
			COPY_EXISTING ~xac246.cre~ ~override/xacrus49.cre~ //bdcru103
			COPY_EXISTING ~xac247.cre~ ~override/xacrus50.cre~ //bdcru104
			COPY_EXISTING ~xac250.cre~ ~override/xacrus51.cre~ //bdcru115
			COPY_EXISTING ~xac251.cre~ ~override/xacrus52.cre~ //bdcru116
			COPY_EXISTING ~xac254.cre~ ~override/xacrus53.cre~ //bdcrus90
			COPY_EXISTING ~xac255.cre~ ~override/xacrus54.cre~ //bdcrus97
			COPY_EXISTING ~xac256.cre~ ~override/xacrus55.cre~ //bdcrus93
			COPY_EXISTING ~xac257.cre~ ~override/xacrus56.cre~ //bdcrus96
			COPY_EXISTING ~xac272.cre~ ~override/xacrus57.cre~ //bdcrus32

			COPY_EXISTING_REGEXP GLOB ~xacrus.+\.cre$~ ~override~ 
				LPF xa_reset_cre
					STR_VAR
						xa_override = ~xag1crus~
						xa_general = ~xac130~ // bdfmcl01
				END
			BUT_ONLY
		//}
	//}
	
	//{ Block D Base
		COPY_EXISTING ~xad123.cre~ ~override/xaff1248.cre~ // Flaming Fist bdfistcc Enforcer
		LPF xa_reset_cre
			STR_VAR
				xa_scriptName = ~XAFF1248~
				xa_override = ~XAFIGH01~
		END
		
		COPY_EXISTING ~xad123.cre~ ~override/xaff1271.cre~ // Flaming Fist bdfistcc Enforcer
		LPF xa_reset_cre
			STR_VAR
				xa_scriptName = ~XAFF1271~
				xa_override = ~XAFIGH01~
		END
		
		COPY_EXISTING ~xad123.cre~ ~override/xaff1272.cre~ // Flaming Fist bdfistcc Enforcer
		LPF xa_reset_cre
			STR_VAR
				xa_scriptName = ~XAFF1272~
				xa_override = ~XAFIGH01~
		END
		
		COPY_EXISTING ~xaff1271.cre~ ~override/xab147b.cre~
		SAY NAME1 @3058
		SAY NAME2 @3058
		WRITE_ASCII 0x280 ~XAB147B~ #20  	// Script Name
		
		COPY_EXISTING ~xaff1272.cre~ ~override/xab149b.cre~
		SAY NAME1 @3058
		SAY NAME2 @3058
		WRITE_ASCII 0x280 ~XAB149B~ #20  	// Script Name
		
		COPY_EXISTING ~xaff1248.cre~ ~override/xab144a.cre~
		SAY NAME1 @4151
		SAY NAME2 @4151
		WRITE_ASCII 0x2CC ~xabridge~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~XAB144A~ #20  	// Script Name
		
		COPY_EXISTING ~xaff1271.cre~ ~override/xab145a.cre~
		SAY NAME1 @4151
		SAY NAME2 @4151
		WRITE_ASCII 0x2CC ~xabridge~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~XAB145A~ #20  	// Script Name
		
		COPY_EXISTING ~xaff1272.cre~ ~override/xab147a.cre~
		SAY NAME1 @4151
		SAY NAME2 @4151
		WRITE_ASCII 0x2CC ~xabridge~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~XAB147A~ #20  	// Script Name
		
		COPY_EXISTING ~xac105.cre~ ~override/xab149a.cre~ // kent
		SAY NAME1 @4151
		SAY NAME2 @4151
		WRITE_ASCII 0x2CC ~xabridge~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~XAB149A~ #20  	// Script Name
		WRITE_ASCII 0x250 ~xalcnull~ #8		// Class Script
	//}
	
	//{ Block F Base
		COPY_EXISTING ~xaf100.cre~ ~override/xaangelo.cre~ // Angelo angelo
		LPF xa_reset_cre
			STR_VAR
				xa_scriptName = ~xaangelo~
				xa_override = ~shout~
				xa_class = ~mage3~
				xa_default = ~wtasight~
		END
		
		//{ Drakes
			COPY_EXISTING ~xaf102.cre~ ~override/xadrake0.cre~ // bdwyrmli
			SAY NAME1 @4161 /* Alabaster Drake */
			SAY NAME2 @4161 /* Alabaster Drake */
			WRITE_LONG 0x14 6000 // XP
			WRITE_BYTE 0x52 3 // THAC0
			WRITE_LONG 0x28 0xA000
			
			WRITE_SHORT 0x24 80 // HP
			WRITE_SHORT 0x26 80 // HP
			
			WRITE_BYTE 0x54 8 // Saves Death
			WRITE_BYTE 0x55 8 // Saves Wand
			WRITE_BYTE 0x56 8 // Saves Polymorph
			WRITE_BYTE 0x57 8 // Saves Breath
			WRITE_BYTE 0x58 8 // Saves Spell
			
			WRITE_BYTE 0x59 20 // Resist Fire
			WRITE_BYTE 0x5A 20 // Resist Cold
			WRITE_BYTE 0x5B 20 // Resist Elec
			WRITE_BYTE 0x5C 20 // Resist Acid
			WRITE_BYTE 0x5D 20 // Resist Magic
			WRITE_BYTE 0x5E 20 // Resist Magic Fire
			WRITE_BYTE 0x5F 20 // Resist Magic Cold
			
			WRITE_BYTE 0x234 14 // Level
			WRITE_ASCII 0xB1C ~S3-8~ #8 // 3d8 (3 to 24) damage
			WRITE_ASCII 0x280 ~xadrake0~ #8 // script name
			WRITE_ASCII 0x258 ~xadrake~ #8 // race script
			REMOVE_CRE_ITEM ~bdsw1hda~ ~bddagg05~
			LPF ADD_CRE_EFFECT
				INT_VAR
					opcode = 52
					target = 1
					timing = 9
					parameter1 = 16909056 // r = 3, b = 2, g = 1
					parameter2 = 2
			END
			
			COPY_EXISTING ~xadrake0.cre~ ~override/xadrake1.cre~
			WRITE_ASCII 0x280 ~xadrake1~ #8
			
			COPY_EXISTING ~xadrake0.cre~ ~override/xadrake2.cre~
			WRITE_ASCII 0x280 ~xadrake2~ #8
		//}
		
		//{ Dragon
			COPY ~%MOD_FOLDER%/rbg/cre/xadragon.cre~ ~override~ // bdhalat2
			SAY NAME1 @4162 /* Auburn Dragon */
			SAY NAME2 @4162 /* Auburn Dragon */
			WRITE_ASCII 0x850 ~dragring~ #8
			WRITE_ASCII 0x280 ~xadragon~ #8
			WRITE_LONG 0x14 55000
			WRITE_LONG 0x28 0x1206
		//}
	//}
	
	//{ BG2 Base
		COPY_EXISTING ~bonebld.cre~ ~override/xabondag.cre~ // Bone Dagger
		SAY NAME1 @4159 /* ~Bone Dagger~ */
		SAY NAME2 @4159 /* ~Bone Dagger~ */
		WRITE_ASCII 0x248 ~xaucspwn~ #8		// Override Script
		WRITE_LONG 0x14 200	// Exp
		WRITE_SHORT 0x24 10		// Current HP
		WRITE_SHORT 0x26 10 	// Max HP
		WRITE_SHORT 0x46 0		// Natural AC
		WRITE_SHORT 0x48 0		// Effective AC
		
		COPY_EXISTING ~telpit2.cre~ ~override/xasarev2.cre~ 
		WRITE_ASCII 0x280 ~xasarev2~ #20  	// Script Name
		ADD_CRE_ITEM ~xasdiary~ #0 #0 #0 ~identified&unstealable~ ~INV1~
		
		COPY_EXISTING ~ankheg01.cre~ ~override/xamutank.cre~ // Mutated Ankheg
		SAY NAME1 @4077
		SAY NAME2 @4077
		WRITE_LONG 0x14 2000	// Exp
		WRITE_SHORT 0x24 72		// Current HP
		WRITE_SHORT 0x24 72 	// Max HP
		WRITE_BYTE 0x52 8 		// THAC0
		WRITE_SHORT 0x46 0		// Natural AC
		WRITE_SHORT 0x48 0		// Effective AC
	
		COPY_EXISTING ~boy1.cre~ ~override/xapercy.cre~
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xapercy~
				xa_scriptName = ~xapercy~
				xa_override = ~xapercy~
		END
		SAY NAME1 @4155/*~Percy~ */
		SAY NAME2 @4155
		
		COPY_EXISTING ~xapercy.cre~ ~override/xatimoty.cre~
		WRITE_ASCII 0x2CC ~xatimoty~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xatimoty~ #20  	// Script Name
		SAY NAME1 @4156/* ~Timotey~*/
		SAY NAME2 @4156
		WRITE_LONG 0x20 128 // Stone Death
	
		COPY_EXISTING ~chicke.cre~ ~override/xachick.cre~ // Chicken
		WRITE_ASCII 0x2CC ~xachick~ #8 	// Dialogue
		WRITE_ASCII 0x250 ~xachick~ #8		// Class Script
		SAY NAME1 @5031 /* Hen */
		SAY NAME2 @5031 /* Hen */
		
		COPY_EXISTING ~neb.cre~ ~override/xaneb.cre~ // Flaming Fist Enforcer
		REMOVE_CRE_ITEM ~MISC5K~
		WRITE_LONG 0x14 7000	// XP Value
		WRITE_SHORT 0x24 145	// Current HP
		WRITE_SHORT 0x26 145	// Max HP
		WRITE_ASCII 0x2CC ~xaneb~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xaneb~ #20  	// Script Name
		WRITE_ASCII 0x250 ~xaneb~ #8		// Class Script
		
		COPY_EXISTING ~CHWRAITH.CRE~ ~override/xachwrai.cre~
		WRITE_LONG 0x14 3333 // XP Value
		WRITE_SHORT 0x24 33
		WRITE_SHORT 0x26 33
		WRITE_SHORT 0x46 3
		WRITE_SHORT 0x48 3
		WRITE_BYTE 0x52 7
		LPF xa_reset_cre
			STR_VAR
				xa_scriptName = ~xachwrai~
				xa_override = ~xachwrai~
				xa_default = ~wtasight~
		END
		
		COPY_EXISTING ~dopgre01.cre~ ~override/xagdop00.cre~
		WRITE_ASCII 0x280 ~xagdop00~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xadopsp~ #8
		WRITE_SHORT 0x24 85 // Current HP
		WRITE_SHORT 0x26 85 // Max HP
		WRITE_BYTE 0x52 5 // THAC0
		WRITE_LONG 0x14 5000 // Exp
		
		COPY_EXISTING ~xagdop00.cre~ ~override/xagdop01.cre~
		WRITE_ASCII 0x280 ~xagdop01~ #20  	// Script Name
		
		COPY_EXISTING ~xagdop00.cre~ ~override/xagdop02.cre~
		WRITE_ASCII 0x280 ~xagdop02~ #20  	// Script Name
		
		COPY_EXISTING ~xagdop00.cre~ ~override/xagdop03.cre~
		WRITE_ASCII 0x280 ~xagdop03~ #20  	// Script Name
		
		COPY_EXISTING ~amcust02.cre~ ~override/xarbnb01.cre~
		SAY NAME1 @4140
		SAY NAME2 @4140
		LPF xa_reset_cre
			STR_VAR
				xa_scriptName = ~xarbnb01~
		END
		
		COPY_EXISTING ~xarbnb01.cre~ ~override/xarbnb02.cre~
		WRITE_ASCII 0x280 ~xarbnb02~ #20  	// Script Name
		
		COPY_EXISTING ~xaschael.cre~ ~override/xacc3.cre~ // Corwin
		LPF xa_reset_cre
			STR_VAR
				xa_dialog = ~xacc3~
				xa_scriptName = ~xacc3~
				xa_override = ~xacc3~
				xa_race = ~shout~
				xa_general = ~xafigh01~
		END
	//}
	
	//{ ToB Base
		COPY_EXISTING ~illasera.cre~ ~override/xaillase.cre~ // Illasera
		WRITE_ASCII 0x2CC ~xaillase~ #8 	// Dialogue
		WRITE_ASCII 0x250 ~xaillase~ #8	// Class Script
		WRITE_ASCII 0x260 ~xailadlg~ #8	// General Script
	//}
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xahowspy.cre~ // Hall of Wonders Spy
	WRITE_ASCII 0x248 ~xahowspy~ #8		// Override Script
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xacell.cre~ // Cell Spy
	WRITE_ASCII 0x248 ~xacell~ #8		// Override Script
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xaskie2.cre~ // Skie invisible
	SAY NAME1 @3070 /* Skie */
	SAY NAME2 @3070
	WRITE_ASCII 0x34 ~xaskies~ #8 // Portrait
	WRITE_ASCII 0x2CC ~xaskie~ #8 	// Dialogue
	WRITE_ASCII 0x280 ~xaskie2~ #20  	// Script Name
	WRITE_ASCII 0x248 ~xaskie~ #8		// Override Script
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xabeno2.cre~ // Beno invisible
	SAY NAME1 @4064 /* Beno Famari */
	SAY NAME2 @4064
	WRITE_ASCII 0x2CC ~xabeno2~ #8 	// Dialogue
	WRITE_ASCII 0x280 ~xabeno2~ #20  	// Script Name
	WRITE_ASCII 0x248 ~xabeno2~ #8		// Override Script
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xaglint2.cre~ // Glint invisible
	SAY NAME1 @4074 /* Glint */
	SAY NAME2 @4074
	WRITE_ASCII 0x34 ~xac100~ #8 // Portrait
	WRITE_ASCII 0x280 ~xaglint2~ #20  	// Script Name
	WRITE_ASCII 0x248 ~xaglint~ #8		// Override Script
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xarohma3.cre~ // Rohma invisible
	SAY NAME1 @4079 /* Rohma */
	SAY NAME2 @4079 /* Rohma */
	WRITE_ASCII 0x280 ~xarohma3~ #20  	// Script Name
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xapspy.cre~ // Paint Spy
	WRITE_ASCII 0x248 ~xapaint~ #8		// Override Script
	
	COPY_EXISTING ~xaffval1.cre~ ~override/xaffexec.cre~ // Flaming Fist Executioner
	SAY NAME1 @4072
	SAY NAME2 @4072
	WRITE_ASCII 0x280 ~xaffexec~ #20  	// Script Name
	WRITE_ASCII 0x2CC ~xaffexec~ #8 	// Dialogue
	
	//{ New CRE
		COPY ~%MOD_FOLDER%/rbg/cre/xaaudam2.cre~ ~override~
		SAY NAME1 @4067
		SAY NAME2 @4067
		
		COPY ~%MOD_FOLDER%/rbg/cre/xagorion.cre~ ~override~
		WRITE_ASCII 0x250 ~mage14a~ #8		// Class Script
		
		COPY ~%MOD_FOLDER%/rbg/cre/xajasper.cre~ ~override~
		SAY NAME1 @4092
		SAY NAME2 @4092
		
		COPY ~%MOD_FOLDER%/rbg/cre/xalyriel.cre~ ~override~
		SAY NAME1 @4049
		SAY NAME2 @4049
			
		COPY ~%MOD_FOLDER%/rbg/cre/xanarzu.cre~ ~override~
		WRITE_LONG 0x28 0xE279 // expressed as a hexadecimal
		SAY NAME1 @4050
		SAY NAME2 @4050
		ADD_CRE_ITEM ~xasword~ #0 #0 #0 ~identified&unstealable&undroppable~ ~INV1~
		ADD_CRE_ITEM ~xamsring~ #0 #0 #0 ~identified&unstealable&undroppable~ ~INV1~
		ADD_CRE_ITEM ~xaquiver~ #0 #0 #0 ~identified&unstealable&undroppable~ ~INV2~
		
		COPY ~%MOD_FOLDER%/rbg/cre/xaneoma.cre~ ~override~
		SAY NAME1 @4046
		SAY NAME2 @4046
		
		COPY ~%MOD_FOLDER%/rbg/cre/xarohma2.cre~ ~override~
		SAY NAME1 @3067
		SAY NAME2 @3067
		
		COPY ~%MOD_FOLDER%/rbg/cre/xatianna.cre~ ~override~
		SAY NAME1 @4078
		SAY NAME2 @4078
		
		COPY ~%MOD_FOLDER%/rbg/cre/xavoidfe.cre~ ~override~
		SAY NAME1 @4147
		SAY NAME2 @4147
		
		COPY ~%MOD_FOLDER%/rbg/cre/xavoidle.cre~ ~override~
		SAY NAME1 @4148
		SAY NAME2 @4148	
		
		COPY ~%MOD_FOLDER%/rbg/cre/xavoidwe.cre~ ~override~
		SAY NAME1 @4146
		SAY NAME2 @4146
	//}
//}

//{ MOS, Text Screens
	COPY ~%MOD_FOLDER%/rbg/mos~ ~override~
//}

//{ 2da
	COPY ~%MOD_FOLDER%/rbg/2da/xabad1.2da~ ~override~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4098)
	SET_2DA_ENTRY 2 1 3 RESOLVE_STR_REF(@4097)
	SET_2DA_ENTRY 2 2 3 RESOLVE_STR_REF(@4097)
	
	COPY_EXISTING ~xabad1.2da~ ~override/xabad2.2da~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4099)
	
	COPY_EXISTING ~xabad1.2da~ ~override/xabad3.2da~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4100)
	
	COPY ~%MOD_FOLDER%/rbg/2da/xabg.2da~ ~override~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4103)
	SET_2DA_ENTRY 2 1 3 RESOLVE_STR_REF(@4101)
	SET_2DA_ENTRY 2 2 3 RESOLVE_STR_REF(@4101)
	
	COPY_EXISTING ~xabg.2da~ ~override/xabgrom.2da~ 
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4102)
	
	COPY ~%MOD_FOLDER%/rbg/2da/xadinner.2da~ ~override~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4104)
	SET_2DA_ENTRY 2 1 3 RESOLVE_STR_REF(@4105)
	SET_2DA_ENTRY 2 2 3 RESOLVE_STR_REF(@4105)
	
	COPY_EXISTING ~xadinner.2da~ ~override/xadinrom.2da~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4106)
	
	COPY ~%MOD_FOLDER%/rbg/2da/xasara1.2da~ ~override~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4108)
	SET_2DA_ENTRY 2 1 3 RESOLVE_STR_REF(@4107)
	SET_2DA_ENTRY 2 2 3 RESOLVE_STR_REF(@4107)
	
	COPY_EXISTING ~xasara1.2da~ ~override/xasara2.2da~ 
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4109)
	
	COPY_EXISTING ~xasara1.2da~ ~override/xasara3.2da~ 
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4110)
	
	COPY_EXISTING ~xasara1.2da~ ~override/xasara4.2da~ 
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4111)
//}

//{ New Items
	
	//{ Diary of Sarevok
		COPY_EXISTING ~ohnnote5.itm~ ~override/xasdiary.itm~
		WRITE_LONG 0x8 RESOLVE_STR_REF(@5030)
		WRITE_LONG 0xC RESOLVE_STR_REF(@5030)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@5029)
		WRITE_LONG 0x18 44 // item flags
	//}
	
	//{ Basilisk Figurine
		COPY_EXISTING ~figspid.eff~ ~override/xabasfig.eff~
		WRITE_ASCII 0x30 ~xabasgrt~ #8
		
		COPY_EXISTING ~misc3e.itm~ ~override/xabasfig.itm~
		WRITE_ASCII 0x3A ~xaibas~ #8
		WRITE_LONG 0x34 6000
		WRITE_LONG 0xC RESOLVE_STR_REF(@4152)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4153)
		WRITE_ASCII 0x58 ~xacbas~ #8
		WRITE_ASCII 0xEE ~xabasfig~ #8
		WRITE_ASCII 0x76 ~xaibas~ #8
	//}

	//{ Farseer
		COPY_EXISTING ~misc64.itm~ ~override/xafarsee.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4117)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4117)
	//}
	
	//{ Ledger
		COPY_EXISTING ~book71.itm~ ~override/xaledger.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4119)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4119)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4120)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4120)
	//}
	
	//{ Manifest 1
		COPY_EXISTING ~scrl3d.itm~ ~override/xamanfst.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4121)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4121)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4122)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4122)
	//}
	
	//{ Manifest 2
		COPY_EXISTING ~scrl3d.itm~ ~override/xamanfs2.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4123)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4123)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4124)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4124)
	//}
	
	//{ Manifest 3
		COPY_EXISTING ~scrl3d.itm~ ~override/xamanfs3.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4125)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4125)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4126)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4126)
	//}
	
	//{ Beno's Head
		COPY_EXISTING ~misc9h.itm~ ~override/xabenohd.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4013)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4013)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4014)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4014)
	//}
	
	//{ Soultaker Dagger (Beno)
		COPY_EXISTING ~dagg10.itm~ ~override/xastdagb.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@3158)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@3158)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4015)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4015)
	//}
	
	//{ Soultaker Dagger (Fake)
		COPY_EXISTING ~dagg10.itm~ ~override/xastdagf.itm~
		WRITE_LONG 0x34 50 // gold
		WRITE_LONG 0x08 RESOLVE_STR_REF(@3158)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@3158)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4016)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4016)
	//}
	
	//{ Rohma's Doll
		COPY_EXISTING ~misc1g.itm~ ~override/xardoll.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4115)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4115)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4116)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4116)
	//}
	
	//{ Hen that Laid the Golden Egg
		COPY ~%MOD_FOLDER%/rbg/itm/xachick.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4001)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4001)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4002)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4002)
	//}
	
	//{ Lyriel's Gratitude
		COPY ~%MOD_FOLDER%/rbg/itm/xalyamul.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4003)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4003)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4004)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4004)
	//}
	
	//{ Dragonspear Medallion
		COPY ~%MOD_FOLDER%/rbg/itm/xamedal.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4005)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4005)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4006)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4006)
	//}
	
	//{ Aureate Egg
		COPY ~%MOD_FOLDER%/rbg/itm/xaegg.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4007)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4007)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4008)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4008)
	//}
	
	//{ Quiver + 4
		COPY ~%MOD_FOLDER%/rbg/itm/xaquiver.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4009)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4009)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4010)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4010)
	//}
	
	//{ Mindshield Ring
		COPY ~%MOD_FOLDER%/rbg/itm/xamsring.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4011)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4011)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4012)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4012)
	//}
	
	//{ Baatezu's Gift
		COPY ~%MOD_FOLDER%/rbg/itm/xasword.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4039)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4039)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4040)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4040)
	//}
	
	//{ Dragon Armor
		COPY ~%MOD_FOLDER%/rbg/itm/xadarmor.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4179)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4179)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4180)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4180)
	//}
	
	//{ Dragon Robe
		COPY ~%MOD_FOLDER%/rbg/itm/xadrobe.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4175)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4175)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4176)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4176)
	//}
	
	//{ Dragon Shield
		COPY ~%MOD_FOLDER%/rbg/itm/xadshld.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4177)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4177)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4178)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4178)
		WRITE_LONG 0x30E RESOLVE_STR_REF(@4181)
		WRITE_ASCII 0x58 ~xac100~ #8
	//}
	
	//{ Engagement Rings
		//Refer to ringabilities.txt and ringbits.xlsx
		COPY ~%MOD_FOLDER%/rbg/itm/xaring99.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4017)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4017)
		WRITE_LONG 0x54E RESOLVE_STR_REF(@2010)
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring07.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4018)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4018)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring11.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4019)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4019)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring13.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4020)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4020)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring14.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4021)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4021)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring19.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4022)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4022)
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring21.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4023)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4023)
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring22.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4024)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4024)
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring25.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4025)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4025)
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring26.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4026)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4026)
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring28.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4027)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4027)
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY ~%MOD_FOLDER%/rbg/itm/xarng99a.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4017)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4017)
		WRITE_LONG 0x54E RESOLVE_STR_REF(@2010)
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng07a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4028)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4028)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng11a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4029)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4029)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0

		COPY_EXISTING ~xarng99a.itm~ ~override/xarng13a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4030)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4030)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng14a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4031)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4031)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng19a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4032)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4032)
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng21a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4033)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4033)
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng22a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4034)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4034)
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng25a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4035)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4035)
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng26a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4036)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4036)
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng28a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4037)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4037)
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
	//}
//}

//{ Music

	//{ Kidnap Music
		ADD_MUSIC xamu04	~%MOD_FOLDER%/rbg/mus/xamu04.mus~
		COPY ~%MOD_FOLDER%/rbg/mus/xamu04a.acm~ ~MUSIC/xamu04/xamu04a.acm~	
	//}

	//{ Sanctum Music
		ADD_MUSIC xamu05	~%MOD_FOLDER%/rbg/mus/xamu05.mus~
		COPY ~%MOD_FOLDER%/rbg/mus/xamu05a.acm~ ~MUSIC/xamu05/xamu05a.acm~	
	//}

	//{ Kidnap Quest End Music
		ADD_MUSIC xamu06	~%MOD_FOLDER%/rbg/mus/xamu06.mus~
		COPY ~%MOD_FOLDER%/rbg/mus/xamu06a.acm~ ~MUSIC/xamu06/xamu06a.acm~	
	//}

	//{ Preparations Music
		ADD_MUSIC xamu07	~%MOD_FOLDER%/rbg/mus/xamu07.mus~
		COPY ~%MOD_FOLDER%/rbg/mus/xamu07a.acm~ ~MUSIC/xamu07/xamu07a.acm~	

		COPY_EXISTING ~xad101.are~ ~override~
		WRITE_LONG 0x630B %xamu07%
		WRITE_LONG 0x630F %xamu07%
	//}

	//{ Triumphant Music
		ADD_MUSIC xamu08	~%MOD_FOLDER%/rbg/mus/xamu08.mus~
		COPY ~%MOD_FOLDER%/rbg/mus/xamu08a.acm~ ~MUSIC/xamu08/xamu08a.acm~	
	//}
	
	//{ SoD Fight Music
		ADD_MUSIC xabb		~%MOD_FOLDER%/rbg/mus/xabb.mus~
		COPY ~%MOD_FOLDER%/rbg/mus/xabb/~ ~MUSIC/xabb/~	
	//}

	//{ Adjust Script & Dialogue Music
		COPY_EXISTING ~xanarzu.dlg~ ~override~
		
		COPY_EXISTING ~player1.dlg~ ~override~
		DECOMPILE_AND_PATCH BEGIN
			REPLACE_TEXTUALLY ~PlaySong(1008)~ ~PlaySong(%xamu08%)~
		END
	//}
//}

//{ New Potion Case
	COPY_EXISTING ~bag06.itm~ ~override/xapotion.itm~
	COPY_EXISTING ~bag06.sto~ ~override/xapotion.sto~
//}

//{ Stores
	COPY_EXISTING ~xaa101.sto~ ~override/xahalbaz.sto~ // sto0703
	ADD_STORE_ITEM ~potn52~ AFTER ~potn08~ #1 #0 #0 ~IDENTIFIED~ #3
	ADD_STORE_ITEM ~potn55~ AFTER ~potn52~ #1 #0 #0 ~IDENTIFIED~ #3
	
	COPY_EXISTING ~xaa137.sto~ ~override~ // sto1115
	ADD_STORE_ITEM ~potn52~ AFTER ~potn08~ #1 #0 #0 ~IDENTIFIED~ #5
	ADD_STORE_ITEM ~potn55~ AFTER ~potn52~ #1 #0 #0 ~IDENTIFIED~ #2
	ADD_STORE_ITEM "xapotion" #0 #0 #0 ~IDENTIFIED~ #1
			
	COPY ~%MOD_FOLDER%/rbg/sto/xamelkor.sto~ ~override~
	WRITE_LONG 0xc RESOLVE_STR_REF(@4158)
	
	COPY ~%MOD_FOLDER%/rbg/sto/xawvbar.sto~ ~override~
	WRITE_LONG 0xc RESOLVE_STR_REF(@4138)
	WRITE_ASCII 0x44 ~xarumor~ #8
//}

PRINT @4171 /* ~Processing area modifications: Blocks A and C...~ */
PRINT @4164 /* ~Please be patient. This may take a while.~ */
SILENT

//{ Block A Area Modifications
	//{ Places where Brevlik can spawn
		ACTION_DEFINE_ARRAY brevSpawns
		BEGIN
			xaas137 // ar0114
			xaas138 // ar0103
			xaas159 // ar0133
			xaas242 // ar0119
			xaas478 // ar0116
		END

		ACTION_PHP_EACH brevSpawns AS _ => spawnArea
		BEGIN
			EXTEND_TOP ~%spawnArea%.bcs~ ~%MOD_FOLDER%/rbg/baf/xabrvspw.baf~
		END
	//}
	
	//{ ar0004 xaa243 Bheren's Home
		COPY_EXISTING ~xaa243.are~ ~override~
		WRITE_ASCII 0x19C ~xaa359~ #8
	//}
	
	//{ ar0010 xaa245 Jardak's Home L1
		COPY_EXISTING ~xaa235.are~ ~override~
		WRITE_ASCII 0x19C ~xaa877~ #8
	//}
	
	//{ ar0011 xaa468 Jardak's Home L2
		COPY_EXISTING ~xaa235.are~ ~override~
		WRITE_ASCII 0x19C ~xaa981~ #8
	//}
	
	//{ ar0100 xaa233 NW Baldur's Gate
		COPY_EXISTING ~xaa233.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x3E7C 256
		WRITE_LONG 0x3F40 256
		WRITE_LONG 0x4004 256
		WRITE_LONG 0x40C8 256
		WRITE_LONG 0x418C 256
		WRITE_LONG 0x4250 256
		WRITE_LONG 0x4314 256
		
		// Remove Ocellis
		WRITE_LONG 0x2BD4 0
		
		// Unlock Silvershield Door
		WRITE_LONG 0x64C8 64
	//}
	
	//{ ar0101 xaa472 Silvershield Estate L1
		COPY_EXISTING ~xaa472.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x990 256
		
		// Change Servant Dialog
		WRITE_ASCII 0x164 ~xaserva2~ #8 
		WRITE_ASCII 0x164 ~xaserva2~ #8
	//}
	
	//{ ar0102 xaa596 Silvershield Estate L2
		EXTEND_TOP ~xaas596.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0102.baf~
	
		COPY_EXISTING ~xaa596.are~ ~override~

		// Replace Dialogues
		WRITE_ASCII 0x164 ~xabrilla~ #8 // Brilla
		WRITE_ASCII 0x384 ~xacook~ #8 // Cook
				
		// Disable NPCs
		WRITE_LONG 0x484 0 // Entar
	//}
	
	//{ ar0103 xaa138 Splurging Sturgeon L1
		EXTEND_TOP ~xaas138.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0103.baf~
		
		COPY_EXISTING ~xaa138.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0xDA4 256
		
		// Disable NPCs
		WRITE_LONG 0x594 0 // Lusselyn
		
		// Replace Lantanara Dialogue
		WRITE_ASCII 0x6B4 ~xalantan~ #8
	//}
	
	//{ ar0104 xaa260 Splurging Sturgeon L2
		COPY_EXISTING ~xaa260.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x264 0 // Mr. Shade
		WRITE_LONG 0x374 0 // Mustard Jelly
	//}
	
	//{ ar0105 xaa268 Blade & Stars L1
		EXTEND_TOP ~xaas268.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0105.baf~
	
		COPY_EXISTING ~xaa268.are~ ~override~
		
		// Replace Actors with Commoners
		WRITE_ASCII 0x2AC ~xaa694~ #8 
		WRITE_ASCII 0x3BC ~xaa695~ #8 
		WRITE_ASCII 0x4CC ~xaa696~ #8 
		
		// Disable Reptrap
		WRITE_LONG 0x808 256
	//}
	
	//{ ar0112 xaa228 Undercellar
		COPY_EXISTING ~xaa228.are~ ~override~
		
		// Disable NPCs
		//WRITE_LONG 0x2024 0 // Quenash
		
		WRITE_ASCII 0x2054 ~xadegrod~ #8 // Update Quenash Script
		
		//{ Add Jasper NPC (Tianna's Problem Quest)
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 420
				fj_loc_y = 1542
				fj_orientation = 15 // SSE 
			STR_VAR
				fj_structure_type = actor
				fj_name = xajasper
				fj_cre_resref = xajasper
		END
		//}
		
	//}
	
	//{ ar0114 xaa137 Blushing Mermaid
		COPY_EXISTING ~xaa137.are~ ~override~
		
		// Replace NPCs
		WRITE_ASCII 0x3BC ~xaa694~ #8
		WRITE_ASCII 0x4CC ~xaa695~ #8
	//}
	
	//{ ar0116 xaa478 Helm and Cloak Level 1
		EXTEND_TOP ~xaas478.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0116.baf~
		
		COPY_EXISTING ~xaa478.are~ ~override~
		WRITE_ASCII 0x94 ~xaas478 ~#8 // the area script wasn't attached to the area, for some reason
		
		// Replace NPCs
		WRITE_ASCII 0x2AC ~xaa166~ #8
		WRITE_ASCII 0x3BC ~xaa167~ #8
		WRITE_ASCII 0x4CC ~xaa168~ #8
		WRITE_ASCII 0x5DC ~xaa250~ #8
	//}
	
	//{ ar0117 xaa584 Helm and Cloak L2 - Restricted Area
		COPY_EXISTING ~xaa584.are~ ~override~
		
		// Replace NPCs
		WRITE_ASCII 0x19C ~xaa372~ #8
		WRITE_ASCII 0x2AC ~xaa396~ #8
		WRITE_ASCII 0x3BC ~xaa361~ #8
	//}
	
	//{ ar0118 xaa586 Helm and Cloak L2 - Balduran Helm Area
		EXTEND_TOP ~xaas586.bcs~ ~%MOD_FOLDER%/rbg/baf/xaar0118.baf~
	//}
	
	//{ ar0119 xaa242
		COPY_EXISTING ~xaa242.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0xDA4 256
		
		// Replace NPCs
		WRITE_ASCII 0x19C ~xaa694~ #8
		WRITE_ASCII 0xB2C ~xaa695~ #8
	//}
	
	//{ ar0120 xaa454
		COPY_EXISTING ~xaa454.are~ ~override~
		
		// Replace Ithtyl Dialogue
		WRITE_ASCII 0x164 ~xaithtyl~ #8
		
		// Remove Skull of Kereph
		WRITE_ASCII 0x654 ~misc07~ #8
		WRITE_SHORT 0x65E 621
	//}
	
	//{ ar0121 xaa609
		COPY_EXISTING ~xaa609.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Areana
	//}
	
	//{ Update Shadowed Soul Script to use correct spells
		COPY_EXISTING ~xac158.cre~ ~override~
		WRITE_ASCII 0x268 ~xashsoul~ #8
	//}
	
	//{ ar0123 xaa106 Undercity
		EXTEND_TOP ~xaas106.bcs~ 	~%MOD_FOLDER%/rbg/baf/xauc.baf~
	
		COPY_EXISTING ~xaa106.are~ ~override/xauc.are~
		
		// Deactivate Exit Back to Maze
		WRITE_LONG 0x1560 256
		
		// Replace Ambush Party with Shadows
		WRITE_ASCII 0x2AC ~SHADFI01~ #8
		WRITE_ASCII 0x3BC ~SHADOW01~ #8
		WRITE_ASCII 0x4CC ~xac158~ #8 // bdshsoul Shadowed Soul
		WRITE_ASCII 0x5DC ~xac162~ #8 // bdwrai02 Wraith
		WRITE_ASCII 0x6EC ~SHADFI01~ #8
		WRITE_ASCII 0x7FC ~SHADOW01~ #8
		
		// Replace Magma Bulwark with Healing Potions
		WRITE_ASCII 0x1FEC ~POTN55~ #8
		WRITE_SHORT 0x1FF6 2
		
		
		
		// Replace Area Triggers
		WRITE_ASCII 0x1474 ~xauctemp~ #8
		
		LPF xa_delete_are_spawns END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 4600
				fj_loc_y = 975
				fj_orientation = 0 // S
			STR_VAR
				fj_structure_type = actor
				fj_name = xaskie2
				fj_cre_resref = xaskie2
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 4610
				fj_loc_y = 985
				fj_orientation = 0 // S
			STR_VAR
				fj_structure_type = actor
				fj_name = xaglint2
				fj_cre_resref = xaglint2
		END
		
		// Replace Battle Song
		WRITE_LONG 0x1DC0 xaf3
		
		// Replace Area Song
		WRITE_LONG 0x1DB4 xag0
		WRITE_LONG 0x1DB8 xag0
	//}
	
	//{ ar0126 xaa361 Ragefast's Home
		COPY_EXISTING ~xaa361.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Ragefast
		WRITE_LONG 0x264 0 // Abela	
	//}
	
	//{ ar0127 xaa291 Merchant's League L1
		COPY_EXISTING ~xaa291.are~ ~override~
		
		// Replace Doppelgangers
		WRITE_ASCII 0x3BC ~xamerlea~ #8
		WRITE_ASCII 0x4CC ~xamerlea~ #8
		WRITE_ASCII 0x5DC ~xamerlea~ #8
		WRITE_ASCII 0x6EC ~xamerlea~ #8
		
		// Replace Guard Dialogs & Race Scripts
		WRITE_ASCII 0x164 ~xamerchg~ #8
		WRITE_ASCII 0x184 ~xamerchg~ #8
		WRITE_ASCII 0x274 ~xamerchg~ #8
		WRITE_ASCII 0x294 ~xamerchg~ #8
	//}
	
	//{ ar0128 xaa492 Merchant's League L2
		EXTEND_TOP ~xaas492.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0128.baf~
	
		COPY_EXISTING ~xaa492.are~ ~override~
		
		// Adjust script for cook
		WRITE_ASCII 0x17C ~xalcflee~ #8
		
		// Replace Zorl
		WRITE_ASCII 0x6EC ~xamerlea~ #8
		
		// Replace Bartender Dialog
		WRITE_ASCII 0x274 ~xabartml~ #8
		
		// Replace Brandilar Dialog
		WRITE_ASCII 0x5A4 ~xabrandi~ #8
		
		// Replace Merchants
		WRITE_ASCII 0x3BC ~xamerlea~ #8
		WRITE_ASCII 0x4CC ~xamerlea~ #8
		
		// Gold
		WRITE_SHORT 0xDCA 322
		
		//Replace BG1 storyline items
		WRITE_ASCII 0xDD4 ~scrl03~ #8
		WRITE_ASCII 0xDE8 ~scrl04~ #8
		WRITE_ASCII 0xDFC ~scrl05~ #8
		
		LPF xa_rescript_actors
			STR_VAR
				xa_race = ~xamerchg~
		END
	//}
	
	//{ ar0130 xaa363 Hall of Wonders
		EXTEND_TOP ~xaas363.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0130.baf~
		
		COPY_EXISTING ~xaa363.are~ ~override~
		
		// Disable Brathlen
		WRITE_LONG 0x264 0 
		
		// Change Beland Dialog & Race Script
		WRITE_ASCII 0x164 ~xabeland~ #8
		WRITE_ASCII 0x184 ~xainitp1~ #8
		
		// Disable rep traps
		WRITE_LONG 0xB84 256
		WRITE_LONG 0xC48 256
	//}
	
	//{ ar0131 xaa362 High Hall of Wonders
		COPY_EXISTING ~xaa363.are~ ~override~
		WRITE_ASCII 0x274 ~xaforthe~ #8
	//}
	
	//{ ar0134 xaa330 Low Lantern B1
		COPY_EXISTING ~xaa330.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x374 0 // Desreta
		WRITE_LONG 0x484 0 // Vay-ya
		
		//{ Create Tianna NPC (Tianna's Problem Quest)
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 832
				fj_loc_y = 622
				fj_orientation = 6 // NW 
			STR_VAR
				fj_structure_type = actor
				fj_name = xatianna
				fj_cre_resref = xatianna
		END
		//}
	//}
	
	//{ ar0135 xaa540 Low Lantern B2
		COPY_EXISTING ~xaa540.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Yago
	//}
	
	//{ ar0138 xaa670 Ramazith L5
		COPY_EXISTING ~basgrt01.cre~ ~override/xabasgrt.cre~
		REMOVE_CRE_ITEM ~rndtre05~
	
		EXTEND_TOP ~xaas670.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0138.baf~
	
		COPY_EXISTING ~xaa670.are~ ~override~
		
		// Disable Containers
		WRITE_LONG 0x270 32
		WRITE_LONG 0x330 32
		WRITE_LONG 0x3F0 32
		WRITE_LONG 0x4B0 32
		WRITE_LONG 0x570 32
		WRITE_LONG 0x630 32
		WRITE_LONG 0x6F0 32
		WRITE_LONG 0x7B0 32
		WRITE_LONG 0x870 32
		
		//{ Tower Trouble Quest
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 170
					fj_loc_y = 138
					fj_orientation = 14 
				STR_VAR
					fj_structure_type = actor
					fj_name = xatimoty
					fj_cre_resref = xatimoty
			END
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 193
					fj_loc_y = 176
					fj_orientation = 14 
				STR_VAR
					fj_structure_type = actor
					fj_name = xabasgrt
					fj_cre_resref = xabasgrt
					fj_bcs_general = xabasil
			END
		//}
	//}
	
	//{ ar0139 xaa458 Ramazith L2
		COPY_EXISTING ~xaa458.are~ ~override~
		LPF xa_delete_are_actors END
	//}
	
	//{ ar0140 xaa607 Ramazith L3
		COPY_EXISTING ~xaa607.are~ ~override~
		LPF xa_delete_are_actors END
	//}
	
	//{ ar0141 xaa644 Ramazith L4
		COPY_EXISTING ~xaa644.are~ ~override~
		LPF xa_delete_are_actors END
	//}
	
	//{ ar0142 xaa668 Ramazith L5
		COPY_EXISTING ~xaa668.are~ ~override~
		LPF xa_delete_are_actors END
	//}

	//{ ar0153 xaa192 Thieves' Guild
		COPY_EXISTING ~xaa192.are~ ~override~
		
		// Replace Dialog
		WRITE_ASCII 0x494 ~xaalatos~ #8
		
		// Replace NPCs
		WRITE_ASCII 0x19C ~xaa475~ #8 // Husam
		WRITE_ASCII 0x2AC ~xaa475~ #8 // Resar
		WRITE_ASCII 0x3BC ~xaa475~ #8 // Narlen
	//}
	
	//{ ar0157 xaa476 Quinn's Home L1
		COPY_EXISTING ~xaa476.are~ ~override~
		LPF xa_delete_are_actors END
	//}
	
	//{ ar0161 xaa479 Degrodel's Home
		COPY_EXISTING ~xaa479.are~ ~override~
		
		WRITE_ASCII 0x17C ~xadegrod~ #8
		WRITE_ASCII 0x27C ~xadegrod~ #8
		WRITE_ASCII 0x38C ~xadegrod~ #8
		WRITE_ASCII 0x49C ~xadegrod~ #8
		WRITE_ASCII 0x5AC ~xadegrod~ #8
		WRITE_ASCII 0x6BC ~xadegrod~ #8
		WRITE_ASCII 0x7CC ~xadegrod~ #8
		WRITE_ASCII 0x8DC ~xadegrod~ #8
		
	//}
	
	//{ ar0162 xaa475 Louise and Laerta's Home
		COPY_EXISTING ~xaa475.are~ ~override~
		LPF xa_delete_are_actors END
	//}
	
	//{ ar0165 xaa474 Tavern
		EXTEND_TOP ~xaas474.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0165.baf~

		COPY_EXISTING ~xaa474.are~ ~override~
		
		// Replace Dialog
		WRITE_ASCII 0x164 ~xaconnol~ #8
	//}
	
	//{ ar0166 xaa593 Tavern L2		
		COPY_EXISTING ~xaa593.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x264 0 // Borinole
	//}
	
	//{ ar0167 xaa480 Pheirkas Home
		EXTEND_TOP ~xaas480.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0116.baf~
		
		COPY_EXISTING ~xaa480.are~ ~override~
		
		// Change Creatures
		WRITE_ASCII 0x154 ~xaa548~ #8 // ftowb5
	//}
	
	//{ ar0200 xaa134 N Baldur's Gate
		EXTEND_TOP ~xaas134.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0200.baf~
	
		COPY_EXISTING ~xaa134.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x4574 256
		WRITE_LONG 0x4638 256
		WRITE_LONG 0x46FC 256
		WRITE_LONG 0x47C0 256
		WRITE_LONG 0x4884 256
		WRITE_LONG 0x4948 256
		WRITE_LONG 0x4A0C 256
		
		// Disable NPCs
		WRITE_LONG 0x3014 0 // Petrine
		WRITE_LONG 0x2F04 0 // Ramazith
		WRITE_LONG 0x3674 0 // Rodnim
		WRITE_LONG 0x3564 0 // Tartusse
		WRITE_LONG 0x3454 0 // Tick
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 3765
				fj_loc_y = 1640
				fj_orientation = 7 
			STR_VAR
				fj_structure_type = actor
				fj_name = xamom
				fj_cre_resref = xamom
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 3820
				fj_loc_y = 1620
				fj_orientation = 7 
			STR_VAR
				fj_structure_type = actor
				fj_name = xapercy
				fj_cre_resref = xapercy
		END
		
		WRITE_LONG 0x4610 RESOLVE_STR_REF(@4157) // update info trigger for Ramazith's Tower
		
		WRITE_ASCII 0x768C ~~ #8 // remove door closing script for Ramazith's Tower
		WRITE_LONG 0x7634 1 // Set door flag to open (and nothing else)
		WRITE_LONG 0x3E64 0 // Remove travel trigger connection to door
		WRITE_LONG 0x8C60 RESOLVE_STR_REF(@4157) // update map note text for Ramazith's Tower
	//}
	
	//{ ar0224 xaa301 BG Sewers (Sewerfolk)
		COPY_EXISTING ~xaa301.are~ ~override~
		
		// Change Spiders to BG2 assets
		WRITE_ASCII 0x19C ~spidgi01~ #8
		WRITE_ASCII 0x2AC ~spidhu01~ #8
		
		// Change Sewerfolk to Carrion Crawlers
		WRITE_ASCII 0x3BC ~carcra01~ #8
		WRITE_ASCII 0x4CC ~carcra01~ #8
		WRITE_ASCII 0x5DC ~carcra01~ #8
		WRITE_ASCII 0x6EC ~carcra01~ #8
		WRITE_ASCII 0x7FC ~carcra01~ #8
		WRITE_ASCII 0x90C ~carcra01~ #8
		WRITE_ASCII 0x3BC ~carcra01~ #8
		WRITE_ASCII 0xA1C ~carcra01~ #8
		
		// Sleep Creatures
		WRITE_ASCII 0x37B8 ~spidgi01~ #8 // use the BG2 asset
		
		//{ Update spawn points to use BG2 assets
			//{ Spawn Point 0
				WRITE_ASCII 0x1C8C ~ghoul01~ #8
				WRITE_ASCII 0x1C94 ~ghast01~ #8
			//}
			
			//{ Spawn Point 1
				WRITE_ASCII 0x1D54 ~spidsm01~ #8
			//}
			
			//{ Spawn Point 2
				WRITE_ASCII 0x1E1C ~spidsm01~ #8
				WRITE_ASCII 0x1E24 ~spidph01~ #8
			//}
			
			//{ Spawn Point 3
				WRITE_ASCII 0x1EE4 ~spidwr01~ #8
			//}
		//}
	//}
	
	//{ ar0225 xaa160 BG Sewers (Ratchild)
		EXTEND_TOP ~xaas160.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0225.baf~
	
		COPY_EXISTING ~xaa160.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x374 0 // Ratchild
		
		//{ Update spawn points to use BG2 assets
			//{ Spawn Point 0
				WRITE_ASCII 0x1CB8 ~jellgr~ #8
				WRITE_ASCII 0x1CC0 ~jellmu~ #8
				WRITE_ASCII 0x1CC8 ~jelloc~ #8
			//}
			
			//{ Spawn Point 1
				WRITE_ASCII 0x1D80 ~jellygr~ #8
				WRITE_ASCII 0x1D88 ~jellgr~ #8
			//}
			
			//{ Spawn Point 2
				WRITE_ASCII 0x1E48 ~jellygr~ #8
				WRITE_ASCII 0x1E50 ~jelloc~ #8
				WRITE_ASCII 0x1E58 ~slfis01~ #8
			//}
		//}
	//}
	
	//{ ar0226 xaa123 BG Sewers (Ogre Mage)
		COPY_EXISTING ~xaa123.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x374 0 // Ogre Mage
		
		//{ Change Creatures - use BG2 assets
			WRITE_ASCII 0x19C ~spidph01~ #8
			WRITE_ASCII 0x2AC ~spidph01~ #8
			WRITE_ASCII 0x4CC ~carcra01~ #8
			WRITE_ASCII 0x5DC ~carcra01~ #8
			WRITE_ASCII 0x6EC ~carcra01~ #8
			WRITE_ASCII 0x7FC ~carcra01~ #8
			WRITE_ASCII 0x90C ~carcra01~ #8
		//}
		
		//{ Update Spawn Points to use BG2 assets
			//{ Spawn Point 0
				WRITE_ASCII 0x18B8 ~carcra01~ #8
			//}
			
			//{ Spawn Point 1
				WRITE_ASCII 0x1980 ~carcra01~ #8
			//}
			
			//{ Spawn Point 2
				WRITE_ASCII 0x1A48 ~carcra01~ #8
			//}
		//}
	//}
	
	//{ ar0300 xaa107
		COPY_EXISTING ~xaa107.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x2ECC 256
		WRITE_LONG 0x2F90 256
		WRITE_LONG 0x3054 256
		WRITE_LONG 0x3118 256
		
		// Disable NPCs
		WRITE_LONG 0x2244 0 // Brielbara 
		WRITE_LONG 0x1E04 0 // Lothander
		WRITE_LONG 0x1F14 0 // Marek
	//}
	
	//{ ar0308 xaa263 Merchant's League Counting House
		COPY_EXISTING ~xaa263.are~ ~override~
		
		// Disable NPC
		WRITE_LONG 0x154 0 // Jacil
	//}
	
	
	//{ ar0600 xaa168
		COPY_EXISTING ~xaa168.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x493C 256
		WRITE_LONG 0x4A00 256
		WRITE_LONG 0x4AC4 256
		WRITE_LONG 0x4B88 256
		WRITE_LONG 0x4C4C 256
		
		// Disable NPCs
		WRITE_LONG 0x3AB4 0 // Dun 
		WRITE_LONG 0x3BC4 0 // Varci 
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 4254
				fj_loc_y = 909 
				fj_orientation = 6 // NW
			STR_VAR
				fj_structure_type = actor
				fj_name = xahowspy1
				fj_cre_resref = xahowspy
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 1580
				fj_loc_y = 2424
				fj_orientation = 6 // NW
			STR_VAR
				fj_structure_type = actor
				fj_name = xahowspy2
				fj_cre_resref = xahowspy
		END
	//}
	
	//{ ar0601 xaa290 - Seven Suns L1
		COPY_EXISTING ~xaa290.are~ ~override~
		
		WRITE_ASCII 0x19C ~xamerchj~ #8
		WRITE_ASCII 0x2AC ~xamerchj~ #8
		WRITE_ASCII 0x3BC ~xamerchj~ #8
	//}
	
	//{ ar0602 xaa406 - Seven Suns L2
		EXTEND_TOP ~xaas406.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0602.baf~
		
		COPY_EXISTING ~xaa406.are~ ~override~
		
		// Replace Doppelgangers
		WRITE_ASCII 0x19C ~xamerchj~ #8
		WRITE_ASCII 0x2AC ~xamerchj~ #8
	//}
	
	//{ ar0603 xaa407 - Seven Suns Cellar
		COPY_EXISTING ~xaa407.are~ ~override~
		LPF xa_delete_are_actors END	
	//}
	
	//{ ar0607 xaa287	// FF HQ Level 1
		EXTEND_TOP ~xaas287.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0607.baf~
		
		COPY_EXISTING ~xaa287.are~ ~override~
		WRITE_LONG 0x264 0 // Disable Neb
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 330
				fj_loc_y = 440
				fj_orientation = 13 // ESE 
			STR_VAR
				fj_structure_type = actor
				fj_name = cellspy
				fj_cre_resref = xacell
		END
	//}
	
	//{ ar0608 xaa413	// FF HQ Level 2
		EXTEND_TOP ~xaas413.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0608.baf~
		COPY_EXISTING ~xaa413.are~ ~override~
		LPF xa_delete_are_actors END
		
		LPF fj_are_structure // Rest Encounter Offset Bug Fix
			INT_VAR
				fj_enable = 0
			STR_VAR
				fj_structure_type = interrupts
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 380
				fj_loc_y = 309
				fj_orientation = 4 // W 
			STR_VAR
				fj_structure_type = actor
				fj_name = Kent
				fj_cre_resref = xakent
		END

		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 233
				fj_loc_y = 399
				fj_orientation = 11 // ENE 
			STR_VAR
				fj_structure_type = actor
				fj_name = Nederlok
				fj_cre_resref = xanederl
		END
	//}
	
	//{ ar0611 xaa311 Iron Throne Basement
		COPY_EXISTING ~xaa311.are~ ~override~
		
	//}
	
	//{ ar0612 xaa309 Iron Throne Second Floor
		COPY_EXISTING ~xaa309.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Dra'tan
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 300
				fj_loc_y = 410
				fj_orientation = 8 // N 
			STR_VAR
				fj_structure_type = actor
				fj_name = Merchant
				fj_cre_resref = xawvmer1
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 960
				fj_loc_y = 517
				fj_orientation = 12 // E 
			STR_VAR
				fj_structure_type = actor
				fj_name = Merchant
				fj_cre_resref = xawvmer1
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 330
				fj_loc_y = 590
				fj_orientation = 8 // N 
			STR_VAR
				fj_structure_type = actor
				fj_name = Guard
				fj_cre_resref = xawvgrd
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 890
				fj_loc_y = 400
				fj_orientation = 8 // N 
			STR_VAR
				fj_structure_type = actor
				fj_name = Guard
				fj_cre_resref = xawvgrd
		END
	//}
	
	//{ ar0613 xaa529 Iron Throne Third Floor
		COPY_EXISTING ~xaa529.are~ ~override~
	
		LPF xa_delete_are_actors END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 850
				fj_loc_y = 420
				fj_orientation = 8 // N 
			STR_VAR
				fj_structure_type = actor
				fj_name = Merchant
				fj_cre_resref = xawvmer2
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 910
				fj_loc_y = 460
				fj_orientation = 12 // E 
			STR_VAR
				fj_structure_type = actor
				fj_name = Merchant
				fj_cre_resref = xawvmer1
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 380
				fj_loc_y = 640
				fj_orientation = 8 // N 
			STR_VAR
				fj_structure_type = actor
				fj_name = Guard
				fj_cre_resref = xawvgrd
		END
	//}
	
	//{ ar0614 xaa563 Iron Throne Fourth Floor
		EXTEND_TOP ~xaas563.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0614.baf~
		COPY_EXISTING ~xaa563.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x6A4 0 // Destus
		
		WRITE_ASCII 0x164 ~xawvbart~ #8 // change bartender dialog
		
		// Change Merchants
		WRITE_ASCII 0x2AC ~xawvmer1~ #8
		WRITE_ASCII 0x3BC ~xawvmer1~ #8
		WRITE_ASCII 0x4CC ~xawvmer1~ #8
		WRITE_ASCII 0x5DC ~xawvmer1~ #8
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 850
				fj_loc_y = 500
				fj_orientation = 0 // S 
			STR_VAR
				fj_structure_type = actor
				fj_name = Virgil
				fj_cre_resref = xavirgil
		END
	//}
	PRINT @4182 /* ~Still working... please be patient.~*/
	SILENT
	//{ ar0615 xaa662 Iron Throne Fifth Floor
		COPY_EXISTING ~xaa662.are~ ~override~	
		//{ Change scrolls in container 3
			WRITE_ASCII 0x1130 ~SCRL56~ #8
			WRITE_ASCII 0x1144 ~SCRL59~ #8
			WRITE_ASCII 0x1158 ~SCRL63~ #8
			WRITE_ASCII 0x116C ~SCRL15~ #8
		//}
		LPF xa_delete_are_actors END
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 2
				fj_box_left		= 724
				fj_box_top		= 779
				fj_box_right	= 791
				fj_box_bottom	= 861
				fj_cursor_idx	= 22
				fj_alt_x		= 760
				fj_alt_y		= 822
				fj_flags		= 1024
				fj_vertex_0     = 724 + (807 << 16)
				fj_vertex_1     = 791 + (779 << 16)
				fj_vertex_2     = 791 + (834 << 16)
				fj_vertex_3     = 724 + (861 << 16)
			STR_VAR
				fj_structure_type = region
				fj_name = ~XAP0615~
				fj_reg_script = ~XAP0615~
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 600
				fj_loc_y = 440
				fj_orientation = 8 // N 
			STR_VAR
				fj_structure_type = actor
				fj_name = Merchant
				fj_cre_resref = xawvmer2
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 500
				fj_loc_y = 760
				fj_orientation = 12 // E 
			STR_VAR
				fj_structure_type = actor
				fj_name = Merchant
				fj_cre_resref = xawvmer1
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 770
				fj_loc_y = 415
				fj_orientation = 4 // W 
			STR_VAR
				fj_structure_type = actor
				fj_name = Guard
				fj_cre_resref = xawvgrd
		END
	//}
	
	//{ ar0616 xaa147 Iron Throne Lobby
		COPY_EXISTING ~xaa147.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x484 0 // Triadore
	//}
	
	//{ ar0619 xaa364
		COPY_EXISTING ~xaa364.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Fenten 
	//}
	
	//{ ar0700 xaa109
		COPY_EXISTING ~xaa109.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x7440 256
		WRITE_LONG 0x7504 256
		WRITE_LONG 0x75C8 256
		
		// Disable NPCs
		WRITE_LONG 0x5FE4 0 // Lady Hannah
		
		// Lock Doors 
		WRITE_LONG 0x9E40 100 // Set pick difficulty for Oberan's door
		WRITE_ASCII 0x9E2C ~abazring~ #8
	//}
	
	//{ ar0702 xaa152 Harbor Master's Building
		EXTEND_TOP ~xaas152.bcs~	~%MOD_FOLDER%/rbg/baf/xaar0702.baf~
		COPY_EXISTING ~xaa152.are~ ~override~
		WRITE_ASCII 0x164 ~xaharbor~ #8 // change harbor master's dialog
	//}
	
	//{ ar0703 xaa115 Halbazzer's Shop L1
		COPY_EXISTING ~xaa115.are~ ~override~
		WRITE_ASCII 0x274 ~xahalbaz~ #8 // change halbazzer's dialog
		// Disable NPCs
		WRITE_LONG 0x154 0 // Ordulinian
	//}
	
	//{ ar0704 xaa202 Halbazzer's Shop L2
		COPY_EXISTING ~xaa202.are~ ~override~
		LPF xa_delete_are_actors END
	//}
	
	//{ ar0705 xaa119 // Elfsong L1
		EXTEND_TOP ~xaas119.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0705.baf~
		
		COPY_EXISTING ~xaa119.are~ ~override~
		// Replace NPCs
		WRITE_ASCII 0x4CC ~xaa695~ #8 // Cauternus
		WRITE_ASCII 0x3BC ~xaa696~ #8 // Brevlik
		
		WRITE_LONG 0x1378 4 // Disable Lyriel's Song
	//}
	
	//{ ar0706 xaa210 // Elfsong L2
		EXTEND_TOP ~xaas210.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0706.baf~
		
		COPY_EXISTING ~xaa210.are~ ~override~
		WRITE_LONG 0xB4C 4 // Disable Lyriel's Song
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 2
				fj_box_left		= 215
				fj_box_top		= 447
				fj_box_right	= 271
				fj_box_bottom	= 510
				fj_cursor_idx	= 22
				fj_alt_x		= 270
				fj_alt_y		= 527
				fj_flags		= 1024
				fj_vertex_0     = 215 + (479 << 16)
				fj_vertex_1     = 270 + (447 << 16)
				fj_vertex_2     = 271 + (475 << 16)
				fj_vertex_3     = 217 + (510 << 16)
			STR_VAR
				fj_structure_type = region
				fj_name = ~XAP0706~
				fj_reg_script = ~XAP0706~
		END
		LPF xa_delete_are_actors END
		
	//}
	
	//{ ar0715 xaa179 Nadine & Euric's House
		COPY_EXISTING ~xaa179.are~ ~override~
		
		// Add Euric to the area
		LPF fj_are_structure 
			INT_VAR
				fj_loc_x = 345
				fj_loc_y = 300
				fj_orientation = 12 // E 
			STR_VAR
				fj_structure_type = actor
				fj_name = Neoma
				fj_cre_resref = xaa1006 // euric
		END
	//}
	
	//{ ar0719 xaa173 Felonius Gist House
		COPY_EXISTING ~xaa173.are~ ~override~
		LPF xa_rescript_actors
			STR_VAR
				xa_override = ~xadegrod~
				xa_general = ~xaa123~
				xa_class = ~xaa349~
				xa_default = ~xaa102~
		END
	//}
	
	//{ ar0724 xaa176 Games Tent
		COPY_EXISTING ~xaa176.are~ ~override~
		WRITE_ASCII 0x6B4 ~xagames2~ #8
	//}
	
	//{ ar0725 xaa177 Games Tent
		COPY_EXISTING ~xaa177.are~ ~override~
		WRITE_ASCII 0x644 ~xagames2~ #8
	//}
	
	//{ ar0726 xaa175 Diviner's Tent
		COPY_EXISTING ~xaa175.are~ ~override~
		
		// Diviner Dialogue
		WRITE_ASCII 0x164 ~xadivine~ #8
	//}
	
	//{ ar0800 xaa104
		EXTEND_TOP ~xaas104.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0800.baf~
	
		COPY_EXISTING ~xaa104.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x6534 256
		WRITE_LONG 0x65F8 256
		WRITE_LONG 0x66BC 256
		WRITE_LONG 0x6780 256
		WRITE_LONG 0x6844 256
		WRITE_LONG 0x6908 256
		WRITE_LONG 0x69CC 256
		WRITE_LONG 0x6A90 256
		
		// Disable NPCs
		WRITE_LONG 0x4FF4 0 // Elminster
		WRITE_LONG 0x4DD4 0 // Niklos
		
		//{ Add Neoma NPC
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 3075
				fj_loc_y = 1390
				fj_orientation = 12 // E 
			STR_VAR
				fj_structure_type = actor
				fj_name = Neoma
				fj_cre_resref = xaneoma
		END
		//}
		
		//{ Elfsong Trouble Intro NPCs
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 3150
				fj_loc_y = 1260
				fj_orientation = 0 // S 
			STR_VAR
				fj_structure_type = actor
				fj_name = xa800w
				fj_cre_resref = xa800m
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 3100
				fj_loc_y = 1260
				fj_orientation = 0 // S 
			STR_VAR
				fj_structure_type = actor
				fj_name = xa800w
				fj_cre_resref = xa800w
		END
		//}
	//}
	
	//{ ar0900 xaa100
		EXTEND_TOP ~xaas100.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0900.baf~
		//EXTEND_TOP ~xaas100.bcs~	~%MOD_FOLDER%/rbg/baf/xamaprbg.baf~
		
		COPY_EXISTING ~xaa100.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x9B0 256
		
		// Disable Ankheg, Tenya and Original Bridge Guards
		WRITE_LONG 0x6A4 0
		WRITE_LONG 0x154 0
		WRITE_LONG 0x264 0
		WRITE_LONG 0x7B4 0
		
		// Close Drawbridge
		//WRITE_LONG 0x2BFC 97
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 1553
				fj_loc_y = 1370
				fj_orientation = 14 // SE 
			STR_VAR
				fj_structure_type = actor
				fj_name = Nederlok
				fj_cre_resref = xanederl
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 1500
				fj_loc_y = 1396
				fj_orientation = 14 // SE 
			STR_VAR
				fj_structure_type = actor
				fj_name = Bence
				fj_cre_resref = xabence
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 1400
				fj_loc_y = 1300
				fj_orientation = 14 // SE 
			STR_VAR
				fj_structure_type = actor
				fj_name = Official
				fj_cre_resref = xarbnb01
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 1466
				fj_loc_y = 1263
				fj_orientation = 14 // SE 
			STR_VAR
				fj_structure_type = actor
				fj_name = Official
				fj_cre_resref = xarbnb02
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 1415
				fj_loc_y = 1385
				fj_orientation = 14 // SE 
			STR_VAR
				fj_structure_type = actor
				fj_name = FFOfficer
				fj_cre_resref = xab147b
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 1566
				fj_loc_y = 1288
				fj_orientation = 14 // SE 
			STR_VAR
				fj_structure_type = actor
				fj_name = FFOfficer
				fj_cre_resref = xab149b
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 4038
				fj_loc_y = 3160
				fj_orientation = 14 // SE 
			STR_VAR
				fj_structure_type = actor
				fj_name = BridgeGuard
				fj_cre_resref = xab149a
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 3916
				fj_loc_y = 3244
				fj_orientation = 14 // SE 
			STR_VAR
				fj_structure_type = actor
				fj_name = BridgeGuard
				fj_cre_resref = xab145a
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 2634
				fj_loc_y = 2404
				fj_orientation = 14 // SE 
			STR_VAR
				fj_structure_type = actor
				fj_name = BridgeGuard
				fj_cre_resref = xab144a
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 2891
				fj_loc_y = 2217
				fj_orientation = 14 // SE 
			STR_VAR
				fj_structure_type = actor
				fj_name = BridgeGuard
				fj_cre_resref = xab147a
		END
	//}
	
	//{ ar1100 xaa146
		COPY_EXISTING ~xaa146.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x5460 256
		WRITE_LONG 0x5524 256
		WRITE_LONG 0x55E8 256
		WRITE_LONG 0x56AC 256
		WRITE_LONG 0x5770 256
		WRITE_LONG 0x5834 256
		WRITE_LONG 0x58F8 256
		
		// Unlock Merchant's League Door
		WRITE_LONG 0x7B84 64
	//}
	
	//{ ar1109 xaa294 Inn (Phandalyn)
		EXTEND_TOP ~xaas294.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar1109.baf~
		COPY_EXISTING ~xaa294.are~ ~override~
		
		WRITE_ASCII 0x118C ~xaa696~ #8
	//}
	
	//{ ar1111 xaa293 Sunin's Home
		COPY_EXISTING ~xaa293.are~ ~override~
		
		// Change Actor to Nobleman
		WRITE_ASCII 0x19C ~xaa730~ #8
	//}
	
	//{ ar1113 xaa288 Slime Inn / Ye Olde Inn
		COPY_EXISTING ~xaa132.sto~ ~override/xasto00.sto~
		WRITE_LONG 0xC RESOLVE_STR_REF(@4150)
	
		COPY_EXISTING ~xaa288.are~ ~override~
		WRITE_ASCII 0x19C ~xaa832~ #8 // change cre to bartender 
		WRITE_ASCII 0x164 ~xabartyo~ #8 // change bartender dialog
		
		// Disable NPCs
		WRITE_LONG 0x6A4 0 // Slime
		WRITE_LONG 0x7B4 0 // Slime
		WRITE_LONG 0xAE4 0 // Slime
		WRITE_LONG 0xBF4 0 // Slime
		WRITE_LONG 0xD04 0 // Slime
		
		// Replace Dialogue
		WRITE_ASCII 0x274 ~xatownm~ #8
		WRITE_ASCII 0x384 ~xatownm~ #8
		WRITE_ASCII 0x494 ~xatownm~ #8
		WRITE_ASCII 0x5A4 ~xatownm~ #8
		WRITE_ASCII 0x8D4 ~xatownm~ #8
		WRITE_ASCII 0x9E4 ~xatownm~ #8
		WRITE_ASCII 0xE24 ~xatownm~ #8
	//}
	
	//{ ar1200 xaa108
		COPY_EXISTING ~xaa108.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x6708 256
		WRITE_LONG 0x67CC 256
		WRITE_LONG 0x6890 256
		WRITE_LONG 0x6954 256
		WRITE_LONG 0x6A18 256
		WRITE_LONG 0x6ADC 256
		
		// Disable NPCs
		WRITE_LONG 0x5324 0 // Entillis Fulsom
		
		WRITE_ASCII 0x5114 ~xakerrac~ #8 // kerrachus dialog
		
		// Change Iron Throne to WV (Info Triggers)
		WRITE_LONG 0x61B0 RESOLVE_STR_REF(@4138)
		WRITE_LONG 0x6BA4 RESOLVE_STR_REF(@4138)
		
		// Change Iron Throne to WV (Map Note)
		WRITE_LONG 0xB2A8 RESOLVE_STR_REF(@4138)
	//}
	
	//{ ar1201 xaa150 Ogre Mage Ambush House
		COPY_EXISTING ~xaa150.are~ ~override~
		
		LPF xa_delete_are_actors END
	//}
	
	//{ ar1207 xaa155
		COPY_EXISTING ~xaa155.are~ ~override~
		
		LPF xa_delete_are_actors END
	//}
	
	//{ ar1208 xaa156
		COPY_EXISTING ~xaa156.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x6A4 0 // Noralee
	//}
	
	//{ ar1209 xaa157
		COPY_EXISTING ~xaa157.are~ ~override~
		LPF xa_delete_are_actors END
	//}
	
	//{ ar1210 xaa326
		COPY_EXISTING ~xaa326.are~ ~override~
		LPF xa_delete_are_actors END
	//}
	
	//{ ar1211 xaa158
		COPY_EXISTING ~xaa158.are~ ~override~
		LPF xa_delete_are_actors END
	//}
	
	//{ ar1213 xaa154
		COPY_EXISTING ~xaa154.are~ ~override~
		LPF xa_delete_are_actors END
	//}
	
	
	//{ ar1300 xaa145
		EXTEND_TOP ~xaas145.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar1300.baf~
		
		COPY_EXISTING ~xaa145.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x48A4 256
		WRITE_LONG 0x4968 256
		WRITE_LONG 0x4A2C 256
		WRITE_LONG 0x4AF0 256
		WRITE_LONG 0x4BB4 256
		WRITE_LONG 0x4C78 256
		WRITE_LONG 0x4D3C 256
		
		// Disable NPCs
		WRITE_LONG 0x3674 0 // Nikolai
		
		// Corwin's Home Map Note
		ADD_MAP_NOTE #1732 #1126 ~violet~ @4160 
		
		// Change Travel Trigger to Point to Corwin's Home
		WRITE_ASCII 0x3DC4 ~xahome~ #8
		
		//{ Add Glint NPC
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 1900
				fj_loc_y = 1240
				fj_orientation = 6 // NW 
			STR_VAR
				fj_structure_type = actor
				fj_name = Glint
				fj_cre_resref = xaglint
		END
		//}
	//}
	
	//{ ar1306 xaa274
		COPY_EXISTING ~xaa274.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x7B4 0 // Euric
	//}
	
	//{ ar1307 xaa425
		COPY_EXISTING ~xaa425.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x6A4 0 // Sanadal
	//}
	
	//{ ar1313 xaa434 Gantolandan's Home
		COPY_EXISTING ~xaa434.are~ ~override~
		LPF xa_delete_are_actors END
	//}
	
	//{ Hall of Wonders Cutscene Area ar0131
		LAF xa_copy_area_music
			STR_VAR
				xa_sourcearea = ~xaa362.are~
				xa_destinationarea = ~%MOD_FOLDER%/rbg/are/xacshow.are~
		END
		COPY_EXISTING ~xacshow.are~ ~override~
		WRITE_LONG 0x7E0 0
	//}
	
	//{ Ducal Palace 1FL (Kidnap) ar0108 xaa246
		COPY_EXISTING ~xaa246.are~ ~override/xaducal.are~ 
			WRITE_LONG 0x1624 xamu07
			WRITE_LONG 0x1628 xamu07
			
			LPF xa_delete_are_triggers END			
			LPF xa_delete_are_actors END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 620
					fj_loc_y = 460
					fj_orientation = 10 
				STR_VAR
					fj_structure_type = actor
					fj_name = Belt
					fj_cre_resref = xabelt
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 740
					fj_loc_y = 350
					fj_orientation = 2 
				STR_VAR
					fj_structure_type = actor
					fj_name = Eltan
					fj_cre_resref = xaeltan
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 800
					fj_loc_y = 365
					fj_orientation = 2 
				STR_VAR
					fj_structure_type = actor
					fj_name = Kent
					fj_cre_resref = xakent
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 619
					fj_loc_y = 337
					fj_orientation = 14 
				STR_VAR
					fj_structure_type = actor
					fj_name = Liia
					fj_cre_resref = xaliia
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 550
					fj_loc_y = 400
					fj_orientation = 14 
				STR_VAR
					fj_structure_type = actor
					fj_name = Melkor
					fj_cre_resref = xamelkor
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 740
					fj_loc_y = 321
					fj_orientation = 2 
				STR_VAR
					fj_structure_type = actor
					fj_name = Nederlok
					fj_cre_resref = xanederl
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 860
					fj_loc_y = 470
					fj_orientation = 6 
				STR_VAR
					fj_structure_type = actor
					fj_name = Valiant
					fj_cre_resref = xaffval1
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 780
					fj_loc_y = 512
					fj_orientation = 6 
				STR_VAR
					fj_structure_type = actor
					fj_name = Valiant
					fj_cre_resref = xaffval2
			END
		
	//}
	
	//{ Ducal Palace 2FL (Debrief) ar0109
		ACTION_IF(xa_regenerate = 1) THEN BEGIN
			COPY_EXISTING ~xaa444.are~ ~override/xaducal2.are~
			WRITE_LONG 0xA34 xaa12
			WRITE_LONG 0xA38 xaa13
			
			LPF xa_delete_are_actors END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 872
					fj_loc_y = 437
					fj_orientation = 2 
				STR_VAR
					fj_structure_type = actor
					fj_name = Belt
					fj_cre_resref = xabelt
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 552
					fj_loc_y = 376
					fj_orientation = 14 
				STR_VAR
					fj_structure_type = actor
					fj_name = Bence
					fj_cre_resref = xabence
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 792
					fj_loc_y = 390
					fj_orientation = 2 
				STR_VAR
					fj_structure_type = actor
					fj_name = Eltan
					fj_cre_resref = xaeltan
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 900
					fj_loc_y = 467
					fj_orientation = 2 
				STR_VAR
					fj_structure_type = actor
					fj_name = Entar
					fj_cre_resref = xaentar
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 720
					fj_loc_y = 260
					fj_orientation = 2 
				STR_VAR
					fj_structure_type = actor
					fj_name = Kent
					fj_cre_resref = xakent
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 830
					fj_loc_y = 412
					fj_orientation = 2 
				STR_VAR
					fj_structure_type = actor
					fj_name = Liia
					fj_cre_resref = xaliia
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 761
					fj_loc_y = 292
					fj_orientation = 2 
				STR_VAR
					fj_structure_type = actor
					fj_name = Nederlok
					fj_cre_resref = xanederl
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 986
					fj_loc_y = 466
					fj_orientation = 2 
				STR_VAR
					fj_structure_type = actor
					fj_name = Skie
					fj_cre_resref = xaskie
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 880
					fj_loc_y = 600
					fj_orientation = 6 
				STR_VAR
					fj_structure_type = actor
					fj_name = Valiant
					fj_cre_resref = xaffval1
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 570
					fj_loc_y = 307
					fj_orientation = 14 
				STR_VAR
					fj_structure_type = actor
					fj_name = Valiant
					fj_cre_resref = xaffval2
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 620
					fj_loc_y = 275
					fj_orientation = 14 
				STR_VAR
					fj_structure_type = actor
					fj_name = Valiant
					fj_cre_resref = xaffval3
			END
			
			LPF fj_are_structure
				INT_VAR
				fj_type 		= 0
				fj_box_left		= 360
				fj_box_top		= 454
				fj_box_right	= 364
				fj_box_bottom	= 450
				fj_cursor_idx	= 0
				fj_flags		= 0
				fj_vertex_0     = 360 + (450 << 16)
				fj_vertex_1     = 360 + (454 << 16)
				fj_vertex_2     = 364 + (450 << 16)
				fj_vertex_3     = 364 + (454 << 16)
				STR_VAR
				fj_structure_type = region
				fj_name = ~TrigCC~
			END
			
			LPF fj_are_structure
				INT_VAR
				fj_type 		= 0
				fj_box_left		= 750
				fj_box_top		= 500
				fj_box_right	= 752
				fj_box_bottom	= 498
				fj_cursor_idx	= 0
				fj_flags		= 0
				fj_vertex_0     = 752 + (498 << 16)
				fj_vertex_1     = 752 + (500 << 16)
				fj_vertex_2     = 750 + (498 << 16)
				fj_vertex_3     = 750 + (500 << 16)
				STR_VAR
				fj_structure_type = region
				fj_name = ~TrigCC2~
			END
			
			LPF fj_are_structure
				INT_VAR
				fj_type 		= 0
				fj_box_left		= 600
				fj_box_top		= 150
				fj_box_right	= 600
				fj_box_bottom	= 150
				fj_cursor_idx	= 0
				fj_flags		= 0
				fj_vertex_0     = 600 + (150 << 16)
				STR_VAR
				fj_structure_type = region
				fj_name = ~TrigExit~
			END
			
			LPF fj_are_structure
				INT_VAR
				fj_type 		= 0
				fj_box_left		= 360
				fj_box_top		= 504
				fj_box_right	= 364
				fj_box_bottom	= 500
				fj_cursor_idx	= 0
				fj_flags		= 0
				fj_vertex_0     = 360 + (500 << 16)
				fj_vertex_1     = 360 + (504 << 16)
				fj_vertex_2     = 364 + (500 << 16)
				fj_vertex_3     = 364 + (504 << 16)
				STR_VAR
				fj_structure_type = region
				fj_name = ~TrigP1~
			END
			
			LPF fj_are_structure
				INT_VAR
				fj_type 		= 0
				fj_box_left		= 700
				fj_box_top		= 465
				fj_box_right	= 702
				fj_box_bottom	= 463
				fj_cursor_idx	= 0
				fj_flags		= 0
				fj_vertex_0     = 702 + (463 << 16)
				fj_vertex_1     = 702 + (465 << 16)
				fj_vertex_2     = 700 + (463 << 16)
				fj_vertex_3     = 700 + (465 << 16)
				STR_VAR
				fj_structure_type = region
				fj_name = ~TrigP12~
			END
			
			LPF fj_are_structure
				INT_VAR
				fj_type 		= 0
				fj_box_left		= 800
				fj_box_top		= 530
				fj_box_right	= 802
				fj_box_bottom	= 528
				fj_cursor_idx	= 0
				fj_flags		= 0
				fj_vertex_0     = 800 + (530 << 16)
				fj_vertex_1     = 800 + (528 << 16)
				fj_vertex_2     = 802 + (530 << 16)
				fj_vertex_3     = 802 + (528 << 16)
				STR_VAR
				fj_structure_type = region
				fj_name = ~TrigSS~
			END
		END ELSE BEGIN
			LAF xa_copy_area_music
				STR_VAR
					xa_sourcearea = ~xaa444.are~
					xa_destinationarea = ~%MOD_FOLDER%/rbg/are/xaducal2.are~
			END
			COPY_EXISTING ~xaducal2.are~ ~override~
			WRITE_LONG 0xA34 xaa12
			WRITE_LONG 0xA38 xaa13
		END
		
	//}
	
	//{ Ducal Palace 3FL ar0110	Post-Kidnap
		
		COPY_EXISTING ~xaa614.are~ ~override/xaduc3.are~ 
		WRITE_LONG 0xEF8 xamu06
		WRITE_LONG 0xEFC xamu06
		WRITE_ASCII 0x94 ~xaduc3~ #8
		
		LPF xa_delete_are_actors END
		LPF xa_delete_are_triggers END
		
		//{ Add NPCs
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 331
				fj_loc_y = 311
				fj_orientation = 14 // SE 
			STR_VAR
				fj_structure_type = actor
				fj_name = Valiant
				fj_cre_resref = xaffval2
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 650
				fj_loc_y = 590
				fj_orientation = 10 // NE 
			STR_VAR
				fj_structure_type = actor
				fj_name = Belt
				fj_cre_resref = xabelt
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 730
				fj_loc_y = 550
				fj_orientation = 2 // SW 
			STR_VAR
				fj_structure_type = actor
				fj_name = Eltan
				fj_cre_resref = xaeltan
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 718
				fj_loc_y = 622
				fj_orientation = 8 // N 
			STR_VAR
				fj_structure_type = actor
				fj_name = Nederlok
				fj_cre_resref = xanederl
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 400
				fj_loc_y = 385
				fj_orientation = 2 // SW 
			STR_VAR
				fj_structure_type = actor
				fj_name = Skie
				fj_cre_resref = xaskie
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 370
				fj_loc_y = 370
				fj_orientation = 2 // SW 
			STR_VAR
				fj_structure_type = actor
				fj_name = Rohma
				fj_cre_resref = xarohma
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 400
				fj_loc_y = 460
				fj_orientation = 10 // NE
			STR_VAR
				fj_structure_type = actor
				fj_name = Liia
				fj_cre_resref = xaliia
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 630
				fj_loc_y = 455
				fj_orientation = 14 // SE 
			STR_VAR
				fj_structure_type = actor
				fj_name = Valiant
				fj_cre_resref = xaffval3
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 666		
				fj_loc_y = 210
				fj_orientation = 2 // SW 
			STR_VAR
				fj_structure_type = actor
				fj_name = Valiant
				fj_cre_resref = xaffval1
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 790
				fj_loc_y = 580
				fj_orientation = 4 // W 
			STR_VAR
				fj_structure_type = actor
				fj_name = Entar
				fj_cre_resref = xaentar
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 216
				fj_loc_y = 399
				fj_orientation = 4 // W 
			STR_VAR
				fj_structure_type = actor
				fj_name = Audamar
				fj_cre_resref = xaaudam2
		END
		//}
		
		//{ Add Triggers
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 0
				fj_box_left		= 454
				fj_box_top		= 313
				fj_box_right	= 456
				fj_box_bottom	= 311
				fj_cursor_idx	= 0
				fj_vertex_0     = 454 + (311 << 16)
				fj_vertex_1     = 454 + (313 << 16)
				fj_vertex_2     = 456 + (313 << 16)
				fj_vertex_3     = 456 + (311<< 16)
			STR_VAR
				fj_structure_type = region
				fj_name = ~TrigRom~
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 0
				fj_box_left		= 485
				fj_box_top		= 292
				fj_box_right	= 487
				fj_box_bottom	= 290
				fj_cursor_idx	= 0
				fj_vertex_0     = 487 + (292 << 16)
				fj_vertex_1     = 487 + (290 << 16)
				fj_vertex_2     = 485 + (290 << 16)
				fj_vertex_3     = 485 + (292 << 16)
			STR_VAR
				fj_structure_type = region
				fj_name = ~TrigCor~
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 0
				fj_box_left		= 585
				fj_box_top		= 200
				fj_box_right	= 587
				fj_box_bottom	= 198
				fj_cursor_idx	= 0
				fj_vertex_0     = 587 + (200 << 16)
				fj_vertex_1     = 587 + (198 << 16)
				fj_vertex_2     = 585 + (198 << 16)
				fj_vertex_3     = 585 + (200 << 16)
			STR_VAR
				fj_structure_type = region
				fj_name = ~TrigP1~
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 0
				fj_box_left		= 545
				fj_box_top		= 285
				fj_box_right	= 547
				fj_box_bottom	= 287
				fj_cursor_idx	= 0
				fj_vertex_0     = 545 + (285 << 16)
				fj_vertex_1     = 545 + (287 << 16)
				fj_vertex_2     = 547 + (287 << 16)
				fj_vertex_3     = 547 + (285 << 16)
			STR_VAR
				fj_structure_type = region
				fj_name = ~TrigExit~
		END
		//}

		
	//}
	
	//{ Painting One - Dragonspear Revisit
		EXTEND_TOP ~xacs101.bcs~ ~%MOD_FOLDER%/rbg/baf/xag1.baf~
		
		COPY_EXISTING ~xac111.cre~ ~override~ // bdashati
		REMOVE_CRE_ITEM ~minhp1~
		
		COPY_EXISTING ~xac112.cre~ ~override~ // bdhepher
		REMOVE_CRE_ITEM ~minhp1~
		
		ACTION_IF(xa_regenerate = 1) THEN BEGIN
			COPY_EXISTING ~xac101.are~ ~override/xag1.are~
			LPF xa_delete_are_actors END
			LPF xa_delete_are_triggers END
			LPF fj_are_structure
				INT_VAR
					fj_type 		= 0
					fj_box_left		= 1976
					fj_box_top		= 2049
					fj_box_right	= 2297
					fj_box_bottom	= 2232
					fj_cursor_idx	= 0
					fj_alt_x		= 0
					fj_alt_y		= 0
					fj_flags		= 0
					fj_vertex_0     = 1976 + (2120 << 16)
					fj_vertex_1     = 2112 + (2049 << 16)
					fj_vertex_2     = 2297 + (2115 << 16)
					fj_vertex_3     = 2232 + (2232 << 16)
				STR_VAR
					fj_structure_type = region
					fj_name = ~CYARD~
			END
			//{ Add Drakes
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 1600
						fj_loc_y = 900
						fj_orientation = 0 // S 
					STR_VAR
						fj_structure_type = actor
						fj_name = Drake
						fj_cre_resref = xadrake0
				END
				
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 1740
						fj_loc_y = 600
						fj_orientation = 0 // S 
					STR_VAR
						fj_structure_type = actor
						fj_name = Drake
						fj_cre_resref = xadrake1
				END
				
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 2170
						fj_loc_y = 300
						fj_orientation = 2 // SW 
					STR_VAR
						fj_structure_type = actor
						fj_name = Drake
						fj_cre_resref = xadrake2
				END
				
			//}
			
			//{ Add Caelar Lieutenants
				PATCH_DEFINE_ARRAY xa_extras
				BEGIN
					xac152 // bdsindr2
					xac114 // bdeiner
					xac115 // bdbertor
					xac111 // bdashati
					xac112 // bdhepher
					xac113 // bdbarghe
					xac120 // bdferrus
				END
				LPF xa_add_extras_rescript
					INT_VAR
						xa_minX = 2060
						xa_minY = 1800
						xa_maxX = 2350
						xa_maxY = 2040
						xa_numToGenerate = 7
						xa_orientation = 2 // SW
					STR_VAR 
						xa_override = ~xag1crus~
						xa_general = ~xac130~ // bdfmcl01
				END
			//}
			
			//{ Ferrusk
				PATCH_DEFINE_ARRAY xa_extras
				BEGIN
					xamutank 
					xamutank 
					xamutank 
					trolgi01 
					hgtrl01 
					hgtrl01 
					troll01
					troll01
				END
				LPF xa_add_extras
					INT_VAR
						xa_minX = 2060
						xa_minY = 1800
						xa_maxX = 2350
						xa_maxY = 2040
						xa_numToGenerate = 9
						xa_orientation = 16 // random
				END
			//}
			//{ Add Coalition
				PATCH_DEFINE_ARRAY xa_extras
				BEGIN
					xac125 // bdfist35
					xac126 // bdfist36
					xac127 // bdfist37
					xac128 // bdfist38
					xac129 // bdfist40
					xac130 // bdfist41
					xac131 // bdfist42
					xac121 // bddagf35
					xac122 // bddagf36
					xac123 // bddagf37
					xac124 // bddagf38
					xac132 // bdwtr35
					xac133 // bdwtr36
					xac134 // bdwtr37
					xac135 // bdwtr38
				END
				
				LPF xa_add_extras_rescript
					INT_VAR
						xa_minX = 962
						xa_maxX = 2163
						xa_minY = 2446
						xa_maxY = 2782
						xa_numToGenerate = 30
						xa_orientation = 16 // random
					STR_VAR 
						xa_override = ~xag1coal~
						xa_general = ~xac130~ // bdfmcl01
				END
				
				LPF xa_add_extras_rescript
					INT_VAR
						xa_minX = 984
						xa_maxX = 1110
						xa_minY = 1298
						xa_maxY = 1990
						xa_numToGenerate = 10
						xa_orientation = 16 // random
					STR_VAR 
						xa_override = ~xag1coal~
						xa_general = ~xac130~ // bdfmcl01
				END
				
				LPF xa_add_extras_rescript
					INT_VAR
						xa_minX = 1668
						xa_maxX = 1987
						xa_minY = 1588
						xa_maxY = 1728
						xa_numToGenerate = 10
						xa_orientation = 16 // random
					STR_VAR 
						xa_override = ~xag1coal~
						xa_general = ~xac130~ // bdfmcl01
				END
				
				LPF xa_add_extras_rescript
					INT_VAR
						xa_minX = 2771
						xa_maxX = 3279
						xa_minY = 2747
						xa_maxY = 3021
						xa_numToGenerate = 10
						xa_orientation = 16 // random
					STR_VAR 
						xa_override = ~xag1coal~
						xa_general = ~xac130~ // bdfmcl01
				END
				
				LPF xa_add_extras_rescript
					INT_VAR
						xa_minX = 1894
						xa_maxX = 2153
						xa_minY = 2128
						xa_maxY = 2378
						xa_numToGenerate = 12
						xa_orientation = 16 // random
					STR_VAR 
						xa_override = ~xag1coal~
						xa_general = ~xac130~ // bdfmcl01
				END
			//}
			//{ Add Crusaders
				PATCH_DEFINE_ARRAY xa_extras
				BEGIN
					xac236 // bdcru100
					xac223 // bdcru101
					xac246 // bdcru103
					xac247 // bdcru104
					xac230 // bdcru111
					xac243 // bdcru112
					xac250 // bdcru115
					xac251 // bdcru116
					xac171 // bdcru117
					xac167 // bdcru118
					xac136 // bdcru40
					xac137 // bdcru41
					xac138 // bdcru42
					xac139 // bdcru43
					xac140 // bdcru44
					xac141 // bdcru45
					xac142 // bdcru46
					xac143 // bdcru47
					xac144 // bdcru51
					xac145 // bdcru52
					xac146 // bdcru53
					xac147 // bdcru54
					xac148 // bdcru55
					xac149 // bdcru56
					xac150 // bdcru57
					xac151 // bdcru58
					xac205 // bdcrue30
					xac241 // bdcrue31
					xac240 // bdcrue32
					xac207 // bdcrue33
					xag131 // bdcrue50
					xag135 // bdcrue51
					xag124 // bdcrue52
					xag126 // bdcrue53
					xag127 // bdcrue54
					xac177 // bdcrum30
					xac175 // bdcrum31
					xac176 // bdcrum32
					xac237 // bdcrur26
					xac233 // bdcrur27
					xac235 // bdcrur28
					xac227 // bdcrur29
					xac209 // bdcrur30
					xac221 // bdcrur31
					xac224 // bdcrur32
					xac219 // bdcrur33
					xac222 // bdcrur34
					xac214 // bdcrus20
					xac200 // bdcrus29
					xac272 // bdcrus32
					xac228 // bdcrus33
					xac192 // bdcrus35
					xac190 // bdcrus36
					xac213 // bdcrus38
					xac202 // bdcrus39
					xac254 // bdcrus90
					xac256 // bdcrus93
					xac231 // bdcrus95
					xac257 // bdcrus96
					xac255 // bdcrus97
					xac238 // bdcrus98
				END
				
				LPF xa_add_extras_rescript
					INT_VAR
						xa_minX = 962
						xa_maxX = 2163
						xa_minY = 2446
						xa_maxY = 2782
						xa_numToGenerate = 40
						xa_orientation = 16 // random
					STR_VAR 
						xa_override = ~xag1crus~
						xa_general = ~xac130~ // bdfmcl01
				END
				
				LPF xa_add_extras_rescript
					INT_VAR
						xa_minX = 984
						xa_maxX = 1110
						xa_minY = 1298
						xa_maxY = 1990
						xa_numToGenerate = 10
						xa_orientation = 16 // random
					STR_VAR 
						xa_override = ~xag1crus~
						xa_general = ~xac130~ // bdfmcl01
				END
				
				LPF xa_add_extras_rescript
					INT_VAR
						xa_minX = 1668
						xa_maxX = 1987
						xa_minY = 1588
						xa_maxY = 1728
						xa_numToGenerate = 10
						xa_orientation = 16 // random
					STR_VAR 
						xa_override = ~xag1crus~
						xa_general = ~xac130~ // bdfmcl01
				END
				
				LPF xa_add_extras_rescript
					INT_VAR
						xa_minX = 2771
						xa_maxX = 3279
						xa_minY = 2747
						xa_maxY = 3021
						xa_numToGenerate = 10
						xa_orientation = 16 // random
					STR_VAR 
						xa_override = ~xag1crus~
						xa_general = ~xac130~ // bdfmcl01
				END
				
				LPF xa_add_extras_rescript
					INT_VAR
						xa_minX = 1894
						xa_maxX = 2153
						xa_minY = 2128
						xa_maxY = 2378
						xa_numToGenerate = 12
						xa_orientation = 16 // random
					STR_VAR 
						xa_override = ~xag1crus~
						xa_general = ~xac130~ // bdfmcl01
				END
				LPF xa_replacesongs
					INT_VAR
						xa_day = xac2
						xa_night = xac2
						xa_battle = xac2
				END
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 2230
						fj_loc_y = 1930
					STR_VAR
						fj_structure_type = ~actor~
						fj_name = ~Caelar~
						fj_cre_resref = ~xac109~
				END
			//}
		END ELSE BEGIN
			LAF xa_copy_area_music
				STR_VAR
					xa_sourcearea = ~xac101.are~
					xa_destinationarea = ~%MOD_FOLDER%/rbg/are/xag1.are~
			END
			COPY_EXISTING ~xag1.are~ ~override~
			LPF xa_replacesongs
				INT_VAR
					xa_day = xac2
					xa_night = xac2
					xa_battle = xac2
			END
		END
		
		
	//}
	
	PRINT @4174 /* ~Almost done...~ */
	SILENT
	//{ Painting Two - Grand Duke Savevok ar1100
		ACTION_IF (xa_regenerate = 1) THEN BEGIN
			COPY_EXISTING ~xaa146.are~ ~override/xag2.are~
			WRITE_ASCII 0x94 ~xag2~ #8 // Area Script
			
			LPF xa_delete_are_actors END
			LPF xa_delete_are_triggers END
			//{ Add Doppelgangers
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 925
						fj_loc_y = 1605
						fj_orientation = 12 // E 
					STR_VAR
						fj_structure_type = actor
						fj_name = xag2dop0
						fj_cre_resref = xag2dop0
				END
				
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 1520
						fj_loc_y = 1620
						fj_orientation = 4 // W 
					STR_VAR
						fj_structure_type = actor
						fj_name = xag2dop1
						fj_cre_resref = xag2dop1
				END
				
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 1510
						fj_loc_y = 1470
						fj_orientation = 4 // W 
					STR_VAR
						fj_structure_type = actor
						fj_name = xag2dop2
						fj_cre_resref = xag2dop2
				END
				
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 990
						fj_loc_y = 1690
						fj_orientation = 10 // NE 
					STR_VAR
						fj_structure_type = actor
						fj_name = xag2dop3
						fj_cre_resref = xag2dop3
				END
			//}
			
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 1175
					fj_loc_y = 1635
					fj_orientation = 12 // E 
				STR_VAR
					fj_structure_type = actor
					fj_name = xaffexec
					fj_cre_resref = xaffexec
			END
			
			//{ Sarevok & Followers
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 1227
						fj_loc_y = 1557
						fj_orientation = 12 // E 
					STR_VAR
						fj_structure_type = actor
						fj_name = xasarevo
						fj_cre_resref = xasarevo
				END
				
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 1380
						fj_loc_y = 1560
						fj_orientation = 11 // ENE 
					STR_VAR
						fj_structure_type = actor
						fj_name = xazhalim
						fj_cre_resref = xazhalim
				END
				
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 1030
						fj_loc_y = 1530
						fj_orientation = 6 // NW 
					STR_VAR
						fj_structure_type = actor
						fj_name = xadiyab
						fj_cre_resref = xadiyab
				END
				
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 1400
						fj_loc_y = 1650
						fj_orientation = 10 // NE 
					STR_VAR
						fj_structure_type = actor
						fj_name = xaaasim
						fj_cre_resref = xaaasim
				END
				
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 1300
						fj_loc_y = 1715
						fj_orientation = 14 // SE 
					STR_VAR
						fj_structure_type = actor
						fj_name = xagardus
						fj_cre_resref = xagardus
				END
				
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 1100
						fj_loc_y = 1550
						fj_orientation = 14 // SE 
					STR_VAR
						fj_structure_type = actor
						fj_name = xasemaj
						fj_cre_resref = xasemaj
				END
				
				LPF fj_are_structure
					INT_VAR
						fj_loc_x = 1090
						fj_loc_y = 1650
						fj_orientation = 14 // SE 
					STR_VAR
						fj_structure_type = actor
						fj_name = xaangelo
						fj_cre_resref = xaangelo
				END
			//}
			
			//{ Add Crowds
			PATCH_DEFINE_ARRAY xa_extras
				BEGIN
					xaa432 // boyba1
					xaa175 // boyba1_a
					xaa519 // boyba1_c
					xaa548 // ftowb5
					xaa981 // ftowb6
					xaa696 // ftowb7
					xaa560 // ftowba
					xaa167 // ftowba_a
					xaa375 // ftowba_b
					xaa251 // ftowba_c
					xaa130 // ftowba_d
					xaa134 // ftowba_e
					xaa605 // ftowbax
					xaa127 // ftwbax_a
					xaa140 // ftwbax_b
					xaa163 // ftwbax_c
					xaa135 // ftwbax_d
					xaa168 // ftwbax_e
					xaa459 // girba1
					xaa880 // girba2
					xaa624 // girba3
					xaa731 // mtob2
					xaa1190 // mtob3
					xaa849 // mtob6
					xaa694 // mtob7
					xaa877 // mtob8
					xaa695 // mtob9
					xaa463 // mtowba
					xaa151 // mtowba_a
					xaa166 // mtowba_b
					xaa180 // mtowba_c
					xaa172 // mtowba_d
					xaa250 // mtowba_e
					xaa583 // mtowbax
					xaa498 // mtowbesn
					xaa1207 // mtowwon1
					xaa1208 // mtowwon2
					xaa1209 // mtowwon3
					xaa123 // mtwbax_a
					xaa124 // mtwbax_b
					xaa128 // mtwbax_c
					xaa126 // mtwbax_d
					xaa131 // mtwbax_e
					xaa952 // mtwslim
					xaa953 // mtwslim2
					xaa954 // mtwslim3
					xaa257 // nobbax_a
					xaa200 // nobbax_b
					xaa524 // nobbax_c
					xaa372 // nobbax_d
					xaa396 // nobbax_e
					xaa730 // nobl11
					xaa1035 // nobl12
					xaa932 // nobl14
					xaa359 // noblba_a
					xaa767 // noblba_b
					xaa532 // noblba_c
					xaa521 // noblba_d
					xaa755 // noblba_e
					xaa1033 // nobw5
					xaa1353 // nobw7
					xaa1334 // nobw8
					xaa728 // nobw9
					xaa360 // nobwba
					xaa1072 // nobwba_a
					xaa514 // nobwba_d
					xaa1084 // nobwba_e
					xaa361 // nowbax_a
					xaa397 // nowbax_b
					xaa402 // nowbax_c
					xaa369 // nowbax_d
					xaa370 // nowbax_e
				END
				LPF xa_add_extras_rescript
					INT_VAR
						xa_minX = 700
						xa_minY = 1400
						xa_maxX = 1000
						xa_maxY = 2000
						xa_numToGenerate = 72
						xa_orientation = 12 // E
					STR_VAR 
						xa_override = ~xarun~
				END
			
				LPF xa_add_extras_rescript
					INT_VAR
						xa_minX = 1420
						xa_minY = 1410
						xa_maxX = 1750
						xa_maxY = 1650
						xa_numToGenerate = 51
						xa_orientation = 4 // W
					STR_VAR 
						xa_override = ~xarun~
				END
			//}
			LPF fj_are_structure
				INT_VAR
					fj_type 		= 0
					fj_box_left		= 1300
					fj_box_top		= 1760
					fj_box_right	= 1305
					fj_box_bottom	= 1765
					fj_cursor_idx	= 22
					fj_vertex_0     = 1300 + (1760 << 16)
					fj_vertex_1     = 1300 + (1765 << 16)
					fj_vertex_2     = 1305 + (1760 << 16)
					fj_vertex_3     = 1305 + (1765 << 16)
				STR_VAR
					fj_reg_script = ~trigff3~
					fj_structure_type = region
					fj_name = ~trigff3~
			END
			LPF fj_are_structure
				INT_VAR
					fj_type 		= 0
					fj_box_left		= 1250
					fj_box_top		= 1790
					fj_box_right	= 1250
					fj_box_bottom	= 1790
					fj_cursor_idx	= 22
					fj_vertex_0     = 1250 + (1790 << 16)
					fj_vertex_1     = 1250 + (1795 << 16)
					fj_vertex_2     = 1255 + (1790 << 16)
					fj_vertex_3     = 1255 + (1795 << 16)
				STR_VAR
					fj_reg_script = ~trigff1~
					fj_structure_type = region
					fj_name = ~trigff1~
			END
			LPF fj_are_structure
				INT_VAR
					fj_type 		= 0
					fj_box_left		= 1355
					fj_box_top		= 1775
					fj_box_right	= 1360
					fj_box_bottom	= 1780
					fj_cursor_idx	= 22
					fj_vertex_0     = 1355 + (1775 << 16)
					fj_vertex_1     = 1355 + (1780 << 16)
					fj_vertex_2     = 1360 + (1775 << 16)
					fj_vertex_3     = 1360 + (1780 << 16)
				STR_VAR
					fj_reg_script = ~trigff2~
					fj_structure_type = region
					fj_name = ~trigff2~
			END
			LPF fj_are_structure
				INT_VAR
					fj_type 		= 0
					fj_box_left		= 1340
					fj_box_top		= 1830
					fj_box_right	= 1345
					fj_box_bottom	= 1835
					fj_cursor_idx	= 22
					fj_vertex_0     = 1340 + (1830 << 16)
					fj_vertex_1     = 1340 + (1835 << 16)
					fj_vertex_2     = 1345 + (1830 << 16)
					fj_vertex_3     = 1345 + (1835 << 16)
				STR_VAR
					fj_reg_script = ~trigliia~
					fj_structure_type = region
					fj_name = ~trigliia~
			END
			LPF fj_are_structure
				INT_VAR
					fj_type 		= 0
					fj_box_left		= 1285
					fj_box_top		= 1835
					fj_box_right	= 1290
					fj_box_bottom	= 1840
					fj_cursor_idx	= 22
					fj_vertex_0     = 1285 + (1835 << 16)
					fj_vertex_1     = 1285 + (1840 << 16)
					fj_vertex_2     = 1290 + (1835 << 16)
					fj_vertex_3     = 1290 + (1840 << 16)
				STR_VAR
					fj_reg_script = ~trigbelt~
					fj_structure_type = region
					fj_name = ~trigbelt~
			END
			LPF fj_are_structure
				INT_VAR
					fj_type 		= 0
					fj_box_left		= 1312
					fj_box_top		= 1800
					fj_box_right	= 1317
					fj_box_bottom	= 1805
					fj_cursor_idx	= 22
					fj_vertex_0     = 1312 + (1800 << 16)
					fj_vertex_1     = 1312 + (1805 << 16)
					fj_vertex_2     = 1317 + (1800 << 16)
					fj_vertex_3     = 1317 + (1805 << 16)
				STR_VAR
					fj_reg_script = ~trigcor~
					fj_structure_type = region
					fj_name = ~trigcor~
			END
			LPF xa_replacesongs
				INT_VAR
					xa_day = xaa6
					xa_night = xaa6
					xa_battle = xabb
			END
		END ELSE BEGIN
			LAF xa_copy_area_music
				STR_VAR
					xa_sourcearea = ~xaa146.are~
					xa_destinationarea = ~%MOD_FOLDER%/rbg/are/xag2.are~
			END
			COPY_EXISTING ~xag2.are~ ~override~
			LPF xa_replacesongs
				INT_VAR
					xa_day = xaa6
					xa_night = xaa6
					xa_battle = xabb
			END
		END
		
	//}
	
	//{ Corwin's Home, L1 ar1316
		EXTEND_TOP ~xaas272.bcs~ ~override/xahome.bcs~
		
		COPY_EXISTING ~xaa272.are~ ~override/xahome.are~ 
		WRITE_ASCII 0x438 ~xahom2~ #8
		WRITE_LONG 0x688 xamu02
		WRITE_LONG 0x68C xamu02
		
		LPF xa_delete_are_actors END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 440
				fj_loc_y = 164
				fj_orientation = 14 
			STR_VAR
				fj_structure_type = actor
				fj_name = Audamar
				fj_cre_resref = xaaudam
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 160
				fj_loc_y = 300
				fj_orientation = 14 
			STR_VAR
				fj_structure_type = actor
				fj_name = Rohma
				fj_cre_resref = xarohma
		END
	//}	
		
	//{ Corwin's Home, L2 ar1317	
		COPY_EXISTING ~xaa428.are~ ~override/xahom2.are~
		WRITE_LONG 0x784 xamu02
		WRITE_LONG 0x788 xamu02
		WRITE_ASCII 0x374 ~xahome~ #8
		
		LPF xa_delete_are_actors END
	//}
	
	//{ Corwin's Home, Rohma Kidnapped ar1316	
		COPY_EXISTING ~xaa272.are~ ~override/xakidnap.are~
		WRITE_ASCII 0x94 ~xahomek~ #8
		
		WRITE_LONG 0x688 xamu04
		WRITE_LONG 0x68C xamu04
		
		LPF xa_delete_are_actors END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 389
				fj_loc_y = 257
				fj_orientation = 8 
			STR_VAR
				fj_structure_type = actor
				fj_name = Audamar
				fj_cre_resref = xaaudam2
		END
	//}
	
	//{ Demon's Sanctum
		COPY_EXISTING ~xaf100.are~ ~override/xademsan.are~
		
		WRITE_LONG 0x5EC 1 // Disable Ambient

		// Add Music
		WRITE_LONG 0x630 xamu05
		WRITE_LONG 0x634 xamu05
		WRITE_LONG 0x63C xag3

		// Add Area Script
		WRITE_ASCII 0x94 ~xademsan~ #8
		
		LPF xa_delete_are_actors END
		
		//{ Add Narzugon NPC
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 327
				fj_loc_y = 180
				fj_orientation = 0 // S 
			STR_VAR
				fj_structure_type = actor
				fj_name = xanarzu
				fj_cre_resref = xanarzu
		END
		//}
	//}
	
	//{ Lyriel Painting
		COPY_EXISTING ~ar0407.are~ ~override/xapaint1.are~
		WRITE_ASCII 0x94 ~xapaint1~ // area script
		
		LPF xa_delete_are_actors END
		LPF xa_delete_are_triggers END		
		
		//{ Painting Entry Triggers
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 2
				fj_box_left		= 265
				fj_box_top		= 216
				fj_box_right	= 290
				fj_box_bottom	= 247
				fj_cursor_idx	= 22
				fj_vertex_0     = 267 + (247 << 16)
				fj_vertex_1     = 290 + (233 << 16)
				fj_vertex_2     = 287 + (216 << 16)
				fj_vertex_3     = 265 + (228 << 16)
			STR_VAR
				fj_reg_script = ~xatrigg3~
				fj_structure_type = region
				fj_name = ~xatrigg3~
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 2
				fj_box_left		= 334
				fj_box_top		= 170
				fj_box_right	= 366
				fj_box_bottom	= 197
				fj_cursor_idx	= 22
				fj_vertex_0     = 334 + (182 << 16)
				fj_vertex_1     = 360 + (170 << 16)
				fj_vertex_2     = 366 + (181 << 16)
				fj_vertex_3     = 335 + (197 << 16)
			STR_VAR
				fj_reg_script = ~xatrigg2~
				fj_structure_type = region
				fj_name = ~xatrigg2~
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 2
				fj_box_left		= 190
				fj_box_top		= 263
				fj_box_right	= 224
				fj_box_bottom	= 300
				fj_cursor_idx	= 22
				fj_vertex_0     = 219 + (263 << 16)
				fj_vertex_1     = 224 + (285 << 16)
				fj_vertex_2     = 193 + (300 << 16)
				fj_vertex_3     = 190 + (283 << 16)
			STR_VAR
				fj_reg_script = ~xatrigg1~
				fj_structure_type = region
				fj_name = ~xatrigg1~
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 2
				fj_box_left		= 600
				fj_box_top		= 128
				fj_box_right	= 630
				fj_box_bottom	= 170
				fj_cursor_idx	= 22
				fj_vertex_0     = 600 + (150 << 16)
				fj_vertex_1     = 600 + (130 << 16)
				fj_vertex_2     = 630 + (150 << 16)
				fj_vertex_3     = 630 + (175 << 16)
			STR_VAR
				fj_reg_script = ~xatrigs~
				fj_structure_type = region
				fj_name = ~xatrigs~
		END
		//}
		
		//{ Add Lyriel NPC
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 465
				fj_loc_y = 300
				fj_orientation = 10 // NE 
			STR_VAR
				fj_structure_type = actor
				fj_name = Audamar
				fj_cre_resref = xalyriel
		END
		//}
	//}
	
	//{ Walk Home Cutscene Area // ar1300
		ACTION_IF(xa_regenerate = 1) THEN BEGIN
			COPY_EXISTING ~xaa145.are~ ~override/xawlkhom.are~
			LPF xa_delete_are_actors END
			LPF xa_delete_are_triggers END
			
			LPF fj_are_structure
				INT_VAR
					fj_type 		= 0
					fj_box_left		= 1706
					fj_box_top		= 1050
					fj_box_right	= 1746
					fj_box_bottom	= 1127
					fj_cursor_idx	= 0
					fj_vertex_0     = 1706 + (1127 << 16)
					fj_vertex_1     = 1746 + (1107 << 16)
					fj_vertex_2     = 1746 + (1050 << 16)
					fj_vertex_3     = 1706 + (1069 << 16)
				STR_VAR
					fj_structure_type = region
					fj_name = ~Door1316~
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_type 		= 0
					fj_box_left		= 2083
					fj_box_top		= 1128
					fj_box_right	= 2107
					fj_box_bottom	= 1107
					fj_cursor_idx	= 0
					fj_vertex_0     = 2083 + (1112 << 16)
					fj_vertex_1     = 2100 + (1107 << 16)
					fj_vertex_2     = 2107 + (1121 << 16)
					fj_vertex_3     = 2094 + (1128 << 16)
				STR_VAR
					fj_structure_type = region
					fj_name = ~CSTrigger2~
			END
			
			LPF fj_are_structure
				INT_VAR
					fj_type 		= 0
					fj_box_left		= 2013
					fj_box_top		= 1081
					fj_box_right	= 2040
					fj_box_bottom	= 1066
					fj_cursor_idx	= 0
					fj_vertex_0     = 2013 + (1072 << 16)
					fj_vertex_1     = 2027 + (1066 << 16)
					fj_vertex_2     = 2040 + (1075 << 16)
					fj_vertex_3     = 2025 + (1081 << 16)
				STR_VAR
					fj_structure_type = region
					fj_name = ~CSTrigger~
			END
			WRITE_LONG 0x2614 65 // open door to Corwin's Home
		END ELSE BEGIN
			LAF xa_copy_area_music
				STR_VAR
					xa_sourcearea = ~xaa145.are~
					xa_destinationarea = ~%MOD_FOLDER%/rbg/are/xawlkhom.are~
			END
		END
		
		
	//}
	
	//{ Undercity Temple ar0125
		COPY_EXISTING ~xaa101.are~ ~override/xauctemp.are~		
		WRITE_ASCII 0x94 ~xauctemp~ #8 // Area Script

		LPF xa_delete_are_triggers END
		
		LPF xa_delete_are_actors
			INT_VAR 
				xa_component_count = 3
		END
		
		//{ Add New Components (Rohma Rescue)
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 755
				fj_loc_y = 660
				fj_orientation = 0 
			STR_VAR
				fj_structure_type = actor
				fj_name = Beno
				fj_cre_resref = xabeno
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 610
				fj_loc_y = 690
				fj_orientation = 15 
			STR_VAR
				fj_structure_type = actor
				fj_name = Illasera
				fj_cre_resref = xaillase
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 740
				fj_loc_y = 780
				fj_orientation = 0 
			STR_VAR
				fj_structure_type = actor
				fj_name = Rohma
				fj_cre_resref = xarohma2
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 750
				fj_loc_y = 790
				fj_orientation = 0 
			STR_VAR
				fj_structure_type = actor
				fj_name = Rohma
				fj_cre_resref = xarohma3
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 0
				fj_box_left		= 730
				fj_box_top		= 670
				fj_box_right	= 740
				fj_box_bottom	= 680
				fj_cursor_idx	= 0
				fj_vertex_0     = 740 + (670 << 16)
				fj_vertex_1     = 730 + (670 << 16)
				fj_vertex_2     = 730 + (680 << 16)
				fj_vertex_3     = 740 + (680 << 16)
			STR_VAR
				fj_structure_type = region
				fj_name = ~xatrbeno~
		END
		WRITE_LONG 0x1358 xag0 // Day
		WRITE_LONG 0x135C xag0 // Night
		WRITE_LONG 0x1364 xaa22 // Battle Music
		//}
	//}
	
	//{ Dinner Cutscene - Three Old Kegs ar0119
		COPY_EXISTING ~xaa242.are~ ~override/xatok.are~
		WRITE_ASCII 0x94 ~xatok~ #8
		// Disable NPCs
		WRITE_LONG 0xAE4 0
		
		// Deactivate Triggers
		WRITE_LONG 0xCE0 256
		WRITE_LONG 0xC1C 256
	//}
	
	//{ Proposal Area ar0900
		COPY_EXISTING ~xaa100.are~ ~override/xawyrm.are~
		LPF xa_delete_are_actors END
		WRITE_LONG 0x3E48 xamu02
		WRITE_LONG 0x3E4C xamu02
		WRITE_ASCII 0x94 ~xawyrm~ #8 // area script
		WRITE_ASCII 0x3C ~~ #8 // area west
	//}
//}

//{ Block C Area Modifications
	//{ Painting Three - ar2612 xac100 Candlekeep - Gorion's Quarters
		COPY_EXISTING ~xac100.are~ ~override/xag3.are~
		
		// Change Area Script
		WRITE_ASCII 0x94 ~xag3~ #8 
		
		// Disable Triggers
		WRITE_LONG 0x460 256
		WRITE_LONG 0x39C 256
		
		LPF xa_delete_are_actors END
		LPF xa_delete_are_containers END
		
		//{ Add Gorion NPC
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 740
				fj_loc_y = 1025
				fj_orientation = 14 // SE
			STR_VAR
				fj_structure_type = actor
				fj_name = xagorion
				fj_cre_resref = xagorion
		END
		//}
	//}
//}



