PRINT @4000  /* ~Processing Return to Baldur's Gate Changes...~ */

SILENT

//{ BAM
	COPY ~%MOD_FOLDER%/rbg/bam/xabenohd.bam~ ~override~
	COPY ~%MOD_FOLDER%/rbg/bam/xacbas.bam~ ~override~
	COPY ~%MOD_FOLDER%/rbg/bam/xaegg.bam~ ~override~
	COPY ~%MOD_FOLDER%/rbg/bam/xaibenoh.bam~ ~override~
	COPY ~%MOD_FOLDER%/rbg/bam/xaiegg.bam~ ~override~
	COPY ~%MOD_FOLDER%/rbg/bam/xaimsrin.bam~ ~override~
	COPY ~%MOD_FOLDER%/rbg/bam/xairing.bam~ ~override~
	COPY ~%MOD_FOLDER%/rbg/bam/xamedal.bam~ ~override~
	COPY ~%MOD_FOLDER%/rbg/bam/xamsring.bam~ ~override~
	COPY ~%MOD_FOLDER%/rbg/bam/xaring.bam~ ~override~
	COPY ~%MOD_FOLDER%/rbg/bam/xaswordd.bam~ ~override~
	COPY ~%MOD_FOLDER%/rbg/bam/xaswordi.bam~ ~override~
//}

//{ Narzugon & Hephernan Animations
	ACTION_IF (isEET = 0) THEN BEGIN
		COPY ~%MOD_FOLDER%/rbg/anim/e258.INI~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/e279.INI~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1a1.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1a1e.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1a2.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1a2e.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1ca.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1cae.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1de.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1dee.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1gh.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1ghe.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1gu.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1gue.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1sc.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1sce.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1sd.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1sde.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1sl.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1sle.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1sp.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1spe.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1tw.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1twe.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1wk.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mbe1wke.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnosa1.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnosa1e.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnosa2.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnosa2e.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnosca.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnoscae.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnosde.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnosdee.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnosgh.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnosghe.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnosgu.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnosgue.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnossc.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnossce.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnossd.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnossde.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnossl.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnossle.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnossp.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnosspe.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnostw.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnostwe.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnoswk.BAM~ ~override~
		COPY ~%MOD_FOLDER%/rbg/anim/mnoswke.BAM~ ~override~

		APPEND ~animate.ids~ ~0xE279 OROG_SHAMAN~
		APPEND ~animate.ids~ ~0xE258 HERPHERNAAN~
	END
	
//}
INCLUDE ~%MOD_FOLDER%/generated/a/generated.tph~
INCLUDE ~%MOD_FOLDER%/generated/c/generated.tph~
INCLUDE ~%MOD_FOLDER%/generated/f/generated.tph~


//{ Worldmap
	LAF FIND_FREE_PVRZ_INDEX
		INT_VAR
			num_to_reserve = 2
			start_index = 1000
		RET
			firstIndex = free_index
	END
	OUTER_SET secondIndex = (firstIndex + 1)
	
	COPY ~%MOD_FOLDER%/rbg/pvrz/mosmapA.pvrz~ ~override/mos%firstIndex%.pvrz~
	COPY ~%MOD_FOLDER%/rbg/pvrz/mosmapB.pvrz~ ~override/mos%secondIndex%.pvrz~
	
	COPY ~%MOD_FOLDER%/rbg/mos/xamaprbg.mos~ ~override~
	WRITE_LONG 0x34 firstIndex
	WRITE_LONG 0x50 secondIndex
	
	COPY ~%MOD_FOLDER%/rbg/wmp/xamaprbg.wmp~ ~override~
	WRITE_LONG 0x24 RESOLVE_STR_REF(@4136) // Map Name
	
	WRITE_LONG 0x978 RESOLVE_STR_REF(@4137) // Wyrm Crossing Label
		
	//{ Wyrm's Crossing to E Baldur's Gate
		LPF ADD_WORLDMAP_LINKS
			INT_VAR
				distance_scale = 0
				encounter_probability = 0
			STR_VAR
				entry = ~Ext0800e~
				from_area = ~XAA100~
				from_node = ~w~
				to_area = ~XAA103~
		END
	//}
	
	//{ Northwest Baldur's Gate
		//{ NW Baldur's Gate to N Baldur's Gate
		LPF ADD_WORLDMAP_LINKS
			INT_VAR
				distance_scale = 0
				encounter_probability = 0
			STR_VAR
				entry = ~Ext0200w~
				from_area = ~XAA229~
				from_node = ~n~
				to_area = ~XAA130~
		END
		//}
		
		//{ NW Baldur's Gate to W Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0200w~
					from_area = ~XAA229~
					from_node = ~n~
					to_area = ~XAA164~
			END
		//}
	//}
	
	//{ North Baldur's Gate
		//{ N Baldur's Gate to NW Baldur's Gate
		LPF ADD_WORLDMAP_LINKS
			INT_VAR
				distance_scale = 0
				encounter_probability = 0
			STR_VAR
				entry = ~Ext0100e~
				from_area = ~XAA130~
				from_node = ~n~
				to_area = ~XAA229~
		END
		//}
		
		//{ N Baldur's Gate to NE Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0300w~
					from_area = ~XAA130~
					from_node = ~n~
					to_area = ~XAA105~
			END
		//}
		
		//{ N Baldur's Gate to C Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0700n~
					from_area = ~XAA130~
					from_node = ~n~
					to_area = ~XAA107~
			END
		//}
	//}
	
	//{ Northeast Baldur's Gate
		//{ NE Baldur's Gate to N Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0200e~
					from_area = ~XAA105~
					from_node = ~n~
					to_area = ~XAA130~
			END
		//}
		
		//{ NE Baldur's Gate to E Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0800n~
					from_area = ~XAA105~
					from_node = ~n~
					to_area = ~XAA103~
			END
		//}
	//}
	
	//{ West Baldur's Gate
		//{ W Baldur's Gate to NW Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0100s~
					from_area = ~XAA164~
					from_node = ~n~
					to_area = ~XAA229~
			END
		//}
		
		//{ W Baldur's Gate to C Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0700w~
					from_area = ~XAA164~
					from_node = ~n~
					to_area = ~XAA107~
			END
		//}
		
		//{ W Baldur's Gate to SW Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext1100n~
					from_area = ~XAA164~
					from_node = ~n~
					to_area = ~XAA142~
			END
		//}
	//}
	
	//{ Central Baldur's Gate
		//{ C Baldur's Gate to N Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0200s~
					from_area = ~XAA107~
					from_node = ~n~
					to_area = ~XAA130~
			END
		//}
		
		//{ C Baldur's Gate to W Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0600e~
					from_area = ~XAA107~
					from_node = ~n~
					to_area = ~XAA164~
			END
		//}
		
		//{ C Baldur's Gate to E Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0800w~
					from_area = ~XAA107~
					from_node = ~n~
					to_area = ~XAA103~
			END
		//}
		
		//{ C Baldur's Gate to S Baldur's Gate (Docks)
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext1200n~
					from_area = ~XAA107~
					from_node = ~n~
					to_area = ~XAA106~
			END
		//}
	//}
	
	//{ East Baldur's Gate
		//{ E Baldur's Gate to NE Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0300s~
					from_area = ~XAA103~
					from_node = ~n~
					to_area = ~XAA105~
			END
		//}
		
		//{ E Baldur's Gate to C Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0700e~
					from_area = ~XAA103~
					from_node = ~n~
					to_area = ~XAA107~
			END
		//}
		
		//{ E Baldur's Gate to SE Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext1300n~
					from_area = ~XAA103~
					from_node = ~n~
					to_area = ~XAA141~
			END
		//}
		
		//{ E Baldur's Gate to Wyrm's Crossing
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Exit0800~
					from_area = ~XAA103~
					from_node = ~n~
					to_area = ~XAA100~
			END
		//}
	//}
	
	//{ Southwest Baldur's Gate
		//{ SW Baldur's Gate to W Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0600s~
					from_area = ~XAA142~
					from_node = ~n~
					to_area = ~XAA164~
			END
		//}
		
		//{ SW Baldur's Gate to S Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext1200w~
					from_area = ~XAA142~
					from_node = ~n~
					to_area = ~XAA106~
			END
		//}
	//}
	
	//{ South Baldur's Gate (Docks)
		//{ S Baldur's Gate to C Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0700s~
					from_area = ~XAA106~
					from_node = ~n~
					to_area = ~XAA107~
			END
		//}
		
		//{ S Baldur's Gate to SE Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext1300w~
					from_area = ~XAA106~
					from_node = ~n~
					to_area = ~XAA141~
			END
		//}
		
		//{ S Baldur's Gate to SW Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext1100e~
					from_area = ~XAA106~
					from_node = ~n~
					to_area = ~XAA142~
			END
		//}
	//}
	
	//{ Southeast Baldur's Gate
		//{ SE Baldur's Gate to E Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext0800s~
					from_area = ~XAA141~
					from_node = ~n~
					to_area = ~XAA103~
			END
		//}
		
		//{ SE Baldur's Gate to S Baldur's Gate
			LPF ADD_WORLDMAP_LINKS
				INT_VAR
					distance_scale = 0
					encounter_probability = 0
				STR_VAR
					entry = ~Ext1200e~
					from_area = ~XAA141~
					from_node = ~n~
					to_area = ~XAA106~
			END
		//}
		
		
	//}
	COPY ~%MOD_FOLDER%/rbg/bam/xamapico.bam~ ~override~
//}

COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/rbg/d~
COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/rbg/baf~

//{ Replace Rumors
	COPY_EXISTING_REGEXP GLOB ~xaa.+\.sto$~ ~override~ 
	WRITE_ASCII 0x44 ~xarumor~ #8
	BUT_ONLY
//}

ACTION_DEFINE_ARRAY bgAreaScripts
BEGIN
	xaas100
	xaas229
	xaas130
	xaas105
	xaas164
	xaas107 
	xaas103
	xaas142
	xaas106
	xaas141
END

ACTION_PHP_EACH bgAreaScripts AS _ => bgArea
BEGIN
	// Apply Exploration Script & Bence Spawning Script
	EXTEND_TOP ~%bgArea%.bcs~ ~%MOD_FOLDER%/rbg/baf/xalcexpl.baf~
	EXTEND_TOP ~%bgArea%.bcs~ ~%MOD_FOLDER%/rbg/baf/xalcbspw.baf~
END

//{ Script Extensions
	EXTEND_TOP ~player1d.bcs~ 	~%MOD_FOLDER%/rbg/baf/xap1d.baf~
	EXTEND_BOTTOM ~xadings.bcs~	~%MOD_FOLDER%/rbg/baf/xadings.baf~
	EXTEND_TOP ~xabalrbg.bcs~ 	~%MOD_FOLDER%/rbg/baf/xabalegg.baf~
	EXTEND_TOP ~xabalrbg.bcs~ 	~%MOD_FOLDER%/rbg/baf/xabalamu.baf~
	EXTEND_TOP ~baldur.bcs~ 	~%MOD_FOLDER%/rbg/baf/xabalrbg.baf~	
//}

//{ BMP
	COPY ~%MOD_FOLDER%/rbg/bmp/xanarzus.bmp~ ~override~
	COPY ~%MOD_FOLDER%/rbg/bmp/xaneomas.bmp~ ~override~
	COPY ~%MOD_FOLDER%/rbg/bmp/xaf100lm.bmp~ ~override~
//}

//{ CRE

	//{ Block A Base
		COPY_EXISTING ~xaa100.cre~ ~override/xasarevo.cre~ // sarevo
		WRITE_ASCII 0x2CC ~xasarevo~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xasarevo~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xasarevo~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~wtasight~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
	
		//{ Male Townspeople
			ACTION_DEFINE_ARRAY maleTownspeople
			BEGIN
				xaa731
				xaa1190
				xaa849
				xaa694
				xaa877
				xaa695
				xaa463
				xaa151
				xaa166
				xaa180
				xaa172
				xaa250
				xaa170
				xaa132
				xaa452
				xaa583
				xaa498
				xaa1207
				xaa1208
				xaa1209
				xaa123
				xaa124
				xaa128
				xaa126
				xaa131
				xaa958
				xaa959
				xaa960
			END
			
			ACTION_PHP_EACH maleTownspeople AS _ => maleTownsperson
			BEGIN
				COPY_EXISTING ~%maleTownsperson%.cre~ ~override~
				
				// Apply Updated Dialog
				WRITE_ASCII 0x2CC ~xatownm~ #8 	// Dialogue
			END
		//}
		
		//{ Female Townspeople
			ACTION_DEFINE_ARRAY femaleTownspeople
			BEGIN
				xaa548
				xaa987
				xaa696
				xaa560
				xaa167
				xaa375
				xaa251
				xaa130
				xaa134
				xaa129
				xaa291
				xaa605
				xaa127
				xaa140
				xaa163
				xaa135
				xaa168
			END
			
			ACTION_PHP_EACH femaleTownspeople AS _ => femaleTownsperson
			BEGIN
				COPY_EXISTING ~%femaleTownsperson%.cre~ ~override~
				
				// Apply Updated Dialog
				WRITE_ASCII 0x2CC ~xatownf~ #8 	// Dialogue
			END
		//}
			
		//{ Noblemen
			ACTION_DEFINE_ARRAY noblemen
			BEGIN
				xaa257
				xaa200
				xaa524
				xaa372
				xaa396
				xaa730
				xaa1041
				xaa932
				xaa359
				xaa767
				xaa532
				xaa521
				xaa755
			END
			
			ACTION_PHP_EACH noblemen AS _ => nobleman
			BEGIN
				COPY_EXISTING ~%nobleman%.cre~ ~override~
				
				// Apply Updated Dialog
				WRITE_ASCII 0x2CC ~xanoblm~ #8 	// Dialogue
			END
		//}
		
		//{ Noblewomen
			ACTION_DEFINE_ARRAY noblewomen
			BEGIN
				xaa1039
				xaa1353
				xaa1334
				xaa728
				xaa360
				xaa1078
				xaa514
				xaa1090
				xaa361
				xaa397
				xaa402
				xaa369
				xaa370
			END
			
			ACTION_PHP_EACH noblewomen AS _ => noblewoman
			BEGIN
				COPY_EXISTING ~%noblewoman%.cre~ ~override~
				
				// Apply Updated Dialog
				WRITE_ASCII 0x2CC ~xanoblf~ #8 	// Dialogue
			END
		//}
		
		COPY_EXISTING ~xaa274.cre~ ~override/xabrielb.cre~ // Brielbara
		WRITE_ASCII 0x2CC ~xabrielb~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xabrielb~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xainitp1~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xaa463.cre~ ~override/xa800m.cre~ // mtowba
		WRITE_ASCII 0x2CC ~xa800m~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xa800m~ #20  	// Script Name
		WRITE_ASCII 0x248 ~~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xaa465.cre~ ~override/xabrevlk.cre~ // Brevlik
		WRITE_ASCII 0x2CC ~xabrevlk~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xabrevlk~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xabrevlk~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xaa552.cre~ ~override/xalarze.cre~ // Larze
		WRITE_ASCII 0x2CC ~xalarze~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xalarze~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xainitp1~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xaa560.cre~ ~override/xamom.cre~ // ftowba
		WRITE_ASCII 0x2CC ~xamom~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xamom~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xamom~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		SAY NAME1 @4154 /*~Anguished Mother~ */
		SAY NAME2 @4154 /* */
		
		COPY_EXISTING ~xaa560.cre~ ~override/xa800w.cre~ // ftowba
		WRITE_ASCII 0x2CC ~xa800w~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xa800w~ #20  	// Script Name
		WRITE_ASCII 0x248 ~~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xaa1179.cre~ ~override~ // WV Guard 2 iron12
		WRITE_ASCII 0x2CC ~xawvgrd2~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xawvgrd2~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xaguard~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xaa730.cre~ ~override/xavirgil.cre~ // Virgil nobl11
		SAY NAME1 @4082
		SAY NAME2 @4082
		WRITE_ASCII 0x2CC ~xavirgil~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xavirgil~ #20  	// Script Name
		WRITE_ASCII 0x248 ~~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~xavirgil~ #8		// Default Script
		
		
		COPY_EXISTING ~xaa904.cre~ ~override/xaalyth.cre~ // Alyth
		WRITE_ASCII 0x2CC ~xaalyth~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xaalyth~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xainitp1~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xaa957.cre~ ~override~ // Ye Olde Inn Bartender barslim
		WRITE_ASCII 0x2CC ~xabartyo~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~~ #20  	// Script Name
		WRITE_ASCII 0x248 ~shout~ #8		// Override Script
		WRITE_ASCII 0x250 ~runenemy~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xaa949.cre~ ~override/xamerchj.cre~ // Seven Suns Merchant merlea
		WRITE_ASCII 0x2CC ~xamerch~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xamerchj~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xaa687.cre~ ~override~ // Merchant's League Guard iron13
		WRITE_ASCII 0x2CC ~xamerchg~ #8 	// Dialogue
		WRITE_ASCII 0x258 ~xamerchg~ #8		// Race Script
		
		COPY_EXISTING ~xaa1220.cre~ ~override/xawvmer1.cre~ // WV Merchant ironm3
		WRITE_ASCII 0x2CC ~xawvmer~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~~ #20  	// Script Name
		WRITE_ASCII 0x248 ~~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xawvmer1.cre~ ~override/xawvmer2.cre~ // WV Merchant ironm3
		
		COPY_EXISTING ~xaa949.cre~ ~override/xamerlea.cre~ // Merchant's League Merchant
		WRITE_ASCII 0x2CC ~xamerlea~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~~ #20  	// Script Name
		WRITE_ASCII 0x248 ~shout~ #8		// Override Script
		WRITE_ASCII 0x250 ~runenemy~ #8		// Class Script
		WRITE_ASCII 0x258 ~wtrunsgt~ #8		// Race Script
		WRITE_ASCII 0x260 ~xamerlea~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		
		COPY_EXISTING ~xaa1359.cre~ ~override~ // Merchant's League Bartender bart6
		WRITE_ASCII 0x258 ~xamerchg~ #8		// Race Script
		WRITE_ASCII 0x2CC ~xabartml~ #8 	// Dialogue
		
		COPY_EXISTING ~xaa1324.cre~ ~override/xabrandi.cre~ // Brandilar brandi
		WRITE_ASCII 0x280 ~xabrandi~ #20  	// Script Name
		WRITE_ASCII 0x258 ~xamerchg~ #8		// Race Script
		WRITE_ASCII 0x2CC ~xabrandi~ #8 	// Dialogue
		
		COPY_EXISTING ~xaa1316.cre~ ~override/xajhasso.cre~ // Jhasso jhasso
		WRITE_ASCII 0x280 ~xajhasso~ #20  	// Script Name
		WRITE_ASCII 0x2CC ~xajhasso~ #8 	// Dialogue
		WRITE_ASCII 0x250 ~xainitp1~ #8		// Class Script
		
		COPY_EXISTING ~xaa737.cre~ ~override~ // Silvershield Servant serva2
		WRITE_ASCII 0x2CC ~xaserva2~ #8 	// Dialogue
		
		COPY_EXISTING ~xaa108.cre~ ~override/xasemaj.cre~ // Semaj semaj
		WRITE_ASCII 0x2CC ~~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xasemaj~ #20  	// Script Name
		WRITE_ASCII 0x248 ~shout~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~xasemaj~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~wtasight~ #8		// Default Script
		
		COPY_EXISTING ~xaa1039.cre~ ~override/xacurato.cre~ // Curator Magda nobw5
		SAY NAME1 @4048 /* Curator Magda */
		SAY NAME2 @4048
		WRITE_ASCII 0x2CC ~xacurato~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xacurato~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xacurato~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xaa1366.cre~ ~override/xazhalim.cre~ // Zhalimar zhalim
		WRITE_ASCII 0x2CC ~~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xazhalim~ #20  	// Script Name
		WRITE_ASCII 0x248 ~shout~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~wtarsgt~ #8		// Default Script
		
		COPY_EXISTING ~xaa1368.cre~ ~override/xaaasim.cre~ // Aasim aasim
		WRITE_ASCII 0x2CC ~~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xaaasim~ #20  	// Script Name
		WRITE_ASCII 0x248 ~shout~ #8		// Override Script
		WRITE_ASCII 0x250 ~priest5~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~wtasight~ #8		// Default Script
		
		COPY_EXISTING ~xaa1369.cre~ ~override/xadiyab.cre~ // Diyab diyab
		WRITE_ASCII 0x2CC ~~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xadiyab~ #20  	// Script Name
		WRITE_ASCII 0x248 ~shout~ #8		// Override Script
		WRITE_ASCII 0x250 ~priest5~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~wtasight~ #8		// Default Script
		
		COPY_EXISTING ~xaa1370.cre~ ~override/xagardus.cre~ // Gardus gardus
		WRITE_ASCII 0x2CC ~~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xagardus~ #20  	// Script Name
		WRITE_ASCII 0x248 ~shout~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~wtasight~ #8		// Default Script
		
		COPY_EXISTING ~xaa130.sto~ ~override/xabartml.sto~ // Merchants' League Bar
		WRITE_LONG 0xC RESOLVE_STR_REF(@4149)
	//}
	
	//{ Block C Base
		COPY_EXISTING ~xac100.cre~ ~override/xaglint.cre~ // Glint glint7
		WRITE_ASCII 0x2CC ~xaglint~ #8 	// Dialogue
		
		WRITE_ASCII 0x280 ~xaglint~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xainitp1~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xac101.cre~ ~override/xarohma.cre~ // Rohma bdrohma
		WRITE_ASCII 0x2CC ~xarohma~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xarohma~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xarohma1~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xac102.cre~ ~override/xaaudam.cre~ // Audamar bdaudam
		WRITE_ASCII 0x2CC ~xaaudam~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xaaudam~ #20  	// Script Name
		WRITE_ASCII 0x248 ~~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xac103.cre~ ~override/xanederl.cre~ // Nederlok bdnederl
		WRITE_ASCII 0x2CC ~xanederl~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xanederl~ #20  	// Script Name
		WRITE_ASCII 0x248 ~~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xac104.cre~ ~override/xaaldeth.cre~ // Aldeth aldeth
		WRITE_ASCII 0x2CC ~xaaldeth~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xaaldeth~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xainitp1~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xac105.cre~ ~override/xakent.cre~ // Kent kent
		WRITE_ASCII 0x2CC ~xakent~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xakent~ #20  	// Script Name
		WRITE_ASCII 0x248 ~~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xac106.cre~ ~override/xabeno.cre~ // Beno bdfamari
		ADD_CRE_ITEM ~xbow04~ #0 #0 #0 ~IDENTIFIED~ ~WEAPON2~
		ADD_CRE_ITEM ~bolt01~ #20 #0 #0 ~IDENTIFIED~ ~QUIVER1~
		WRITE_ASCII 0x2CC ~xabeno~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xabeno~ #20  	// Script Name
		WRITE_ASCII 0x248 ~~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~xabenof~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xac107.cre~ ~override/xaskie.cre~ // Skie bdskie
		WRITE_ASCII 0x2CC ~xaskie~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xaskie~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xaskie~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		//{ Evil Caelar
			COPY_EXISTING ~xac108.cre~ ~override~ // bdcaela2
			WRITE_ASCII 0x2CC ~z2~ #8 	// Dialogue
			WRITE_ASCII 0x280 ~xac108~ #20  	// Script Name
			WRITE_ASCII 0x248 ~xag1crus~ #8		// Override Script
			WRITE_ASCII 0x250 ~xalcnull~ #8		// Class Script
			WRITE_ASCII 0x258 ~xalcnull~ #8		// Race Script
			WRITE_ASCII 0x260 ~xacaelac~ #8		// General Script
			WRITE_ASCII 0x268 ~xalcnull~ #8		// Default Script
		//}
		EXTEND_BOTTOM ~xag1coal.bcs~ ~%MOD_FOLDER%/rbg/baf/xacrtyrd.baf~
		EXTEND_BOTTOM ~xag1crus.bcs~ ~%MOD_FOLDER%/rbg/baf/xacrtyrd.baf~
		
		//{ Coalition Respawns
			COPY_EXISTING ~xac121.cre~ ~override/xacoal0.cre~ // bddagf35
			COPY_EXISTING ~xac122.cre~ ~override/xacoal1.cre~ // bddagf36
			COPY_EXISTING ~xac123.cre~ ~override/xacoal2.cre~ // bddagf37
			COPY_EXISTING ~xac124.cre~ ~override/xacoal3.cre~ // bddagf38
			COPY_EXISTING ~xac125.cre~ ~override/xacoal4.cre~ // bdfist35
			COPY_EXISTING ~xac126.cre~ ~override/xacoal5.cre~ // bdfist36
			COPY_EXISTING ~xac127.cre~ ~override/xacoal6.cre~ // bdfist37
			COPY_EXISTING ~xac128.cre~ ~override/xacoal7.cre~ // bdfist38
			COPY_EXISTING ~xac129.cre~ ~override/xacoal8.cre~ // bdfist40
			COPY_EXISTING ~xac130.cre~ ~override/xacoal9.cre~ // bdfist41
			COPY_EXISTING ~xac131.cre~ ~override/xacoal10.cre~ // bdfist42
			COPY_EXISTING ~xac132.cre~ ~override/xacoal11.cre~ // bdwtr35
			COPY_EXISTING ~xac133.cre~ ~override/xacoal12.cre~ // bdwtr35
			COPY_EXISTING ~xac134.cre~ ~override/xacoal13.cre~ // bdwtr35
			COPY_EXISTING ~xac135.cre~ ~override/xacoal14.cre~ // bdwtr35

			COPY_EXISTING_REGEXP GLOB ~xacoal.+\.cre$~ ~override~ 
				WRITE_ASCII 0x2CC ~z2~ #8 	// Dialogue
				WRITE_ASCII 0x248 ~xag1coal~ #8		// Override Script
				WRITE_ASCII 0x250 ~xalcnull~ #8		// Class Script
				WRITE_ASCII 0x258 ~xalcnull~ #8		// Race Script
				WRITE_ASCII 0x260 ~xac130~ #8		// General Script
				WRITE_ASCII 0x268 ~xalcnull~ #8		// Default Script
			BUT_ONLY
		//}
		
		//{ Crusader Respawns
			COPY_EXISTING ~xac136.cre~ ~override/xacrus0.cre~ //bdcru40
			COPY_EXISTING ~xac137.cre~ ~override/xacrus1.cre~ //bdcru41
			COPY_EXISTING ~xac138.cre~ ~override/xacrus2.cre~ //bdcru42
			COPY_EXISTING ~xac139.cre~ ~override/xacrus3.cre~ //bdcru43
			COPY_EXISTING ~xac140.cre~ ~override/xacrus4.cre~ //bdcru44
			COPY_EXISTING ~xac141.cre~ ~override/xacrus5.cre~ //bdcru45
			COPY_EXISTING ~xac142.cre~ ~override/xacrus6.cre~ //bdcru46
			COPY_EXISTING ~xac143.cre~ ~override/xacrus7.cre~ //bdcru47
			COPY_EXISTING ~xac144.cre~ ~override/xacrus8.cre~ //bdcru51
			COPY_EXISTING ~xac145.cre~ ~override/xacrus9.cre~ //bdcru52
			COPY_EXISTING ~xac146.cre~ ~override/xacrus10.cre~ //bdcru53
			COPY_EXISTING ~xac147.cre~ ~override/xacrus11.cre~ //bdcru54
			COPY_EXISTING ~xac148.cre~ ~override/xacrus12.cre~ //bdcru55
			COPY_EXISTING ~xac149.cre~ ~override/xacrus13.cre~ //bdcru56
			COPY_EXISTING ~xac150.cre~ ~override/xacrus14.cre~ //bdcru57
			COPY_EXISTING ~xac151.cre~ ~override/xacrus15.cre~ //bdcru58
			COPY_EXISTING ~xac167.cre~ ~override/xacrus16.cre~ //bdcru118
			COPY_EXISTING ~xac171.cre~ ~override/xacrus17.cre~ //bdcru117
			COPY_EXISTING ~xac175.cre~ ~override/xacrus18.cre~ //bdcrum31
			COPY_EXISTING ~xac176.cre~ ~override/xacrus19.cre~ //bdcrum32
			COPY_EXISTING ~xac177.cre~ ~override/xacrus20.cre~ //bdcrum30
			COPY_EXISTING ~xac190.cre~ ~override/xacrus21.cre~ //bdcrus36
			COPY_EXISTING ~xac192.cre~ ~override/xacrus22.cre~ //bdcrus35
			COPY_EXISTING ~xac200.cre~ ~override/xacrus23.cre~ //bdcrus29
			COPY_EXISTING ~xac202.cre~ ~override/xacrus24.cre~ //bdcrus39
			COPY_EXISTING ~xac204.cre~ ~override/xacrus25.cre~ //bdcrux31
			COPY_EXISTING ~xac205.cre~ ~override/xacrus26.cre~ //bdcrue30
			COPY_EXISTING ~xac206.cre~ ~override/xacrus27.cre~ //bdcrux30
			COPY_EXISTING ~xac207.cre~ ~override/xacrus28.cre~ //bdcrue33
			COPY_EXISTING ~xac209.cre~ ~override/xacrus29.cre~ //bdcrur30
			COPY_EXISTING ~xac213.cre~ ~override/xacrus30.cre~ //bdcrus38
			COPY_EXISTING ~xac214.cre~ ~override/xacrus31.cre~ //bdcrus20
			COPY_EXISTING ~xac219.cre~ ~override/xacrus32.cre~ //bdcrur33
			COPY_EXISTING ~xac221.cre~ ~override/xacrus33.cre~ //bdcrur31
			COPY_EXISTING ~xac222.cre~ ~override/xacrus34.cre~ //bdcrur34
			COPY_EXISTING ~xac223.cre~ ~override/xacrus35.cre~ //bdcru101
			COPY_EXISTING ~xac224.cre~ ~override/xacrus36.cre~ //bdcrur32
			COPY_EXISTING ~xac227.cre~ ~override/xacrus37.cre~ //bdcrur29
			COPY_EXISTING ~xac228.cre~ ~override/xacrus38.cre~ //bdcrus33
			COPY_EXISTING ~xac230.cre~ ~override/xacrus39.cre~ //bdcru111
			COPY_EXISTING ~xac231.cre~ ~override/xacrus40.cre~ //bdcrus95
			COPY_EXISTING ~xac233.cre~ ~override/xacrus41.cre~ //bdcrur27
			COPY_EXISTING ~xac235.cre~ ~override/xacrus42.cre~ //bdcrur28
			COPY_EXISTING ~xac236.cre~ ~override/xacrus43.cre~ //bdcru100
			COPY_EXISTING ~xac237.cre~ ~override/xacrus44.cre~ //bdcrur26
			COPY_EXISTING ~xac238.cre~ ~override/xacrus45.cre~ //bdcrus98
			COPY_EXISTING ~xac240.cre~ ~override/xacrus46.cre~ //bdcrue32
			COPY_EXISTING ~xac241.cre~ ~override/xacrus47.cre~ //bdcrue31
			COPY_EXISTING ~xac243.cre~ ~override/xacrus48.cre~ //bdcru112
			COPY_EXISTING ~xac246.cre~ ~override/xacrus49.cre~ //bdcru103
			COPY_EXISTING ~xac247.cre~ ~override/xacrus50.cre~ //bdcru104
			COPY_EXISTING ~xac250.cre~ ~override/xacrus51.cre~ //bdcru115
			COPY_EXISTING ~xac251.cre~ ~override/xacrus52.cre~ //bdcru116
			COPY_EXISTING ~xac254.cre~ ~override/xacrus53.cre~ //bdcrus90
			COPY_EXISTING ~xac255.cre~ ~override/xacrus54.cre~ //bdcrus97
			COPY_EXISTING ~xac256.cre~ ~override/xacrus55.cre~ //bdcrus93
			COPY_EXISTING ~xac257.cre~ ~override/xacrus56.cre~ //bdcrus96
			COPY_EXISTING ~xac272.cre~ ~override/xacrus57.cre~ //bdcrus32

			COPY_EXISTING_REGEXP GLOB ~xacrus.+\.cre$~ ~override~ 
				WRITE_ASCII 0x2CC ~z2~ #8 	// Dialogue
				WRITE_ASCII 0x248 ~xag1crus~ #8		// Override Script
				WRITE_ASCII 0x250 ~xalcnull~ #8		// Class Script
				WRITE_ASCII 0x258 ~xalcnull~ #8		// Race Script
				WRITE_ASCII 0x260 ~xac130~ #8		// General Script
				WRITE_ASCII 0x268 ~xalcnull~ #8		// Default Script
			BUT_ONLY
		//}
	//}
	
	//{ Block D Base
		COPY_EXISTING ~xad123.cre~ ~override/xaff1248.cre~ // Flaming Fist bdfistcc Enforcer
		WRITE_ASCII 0x2CC ~~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~XAFF1248~ #20  	// Script Name
		WRITE_ASCII 0x248 ~~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xad123.cre~ ~override/xaff1271.cre~ // Flaming Fist bdfistcc Enforcer
		WRITE_ASCII 0x2CC ~~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~XAFF1271~ #20  	// Script Name
		WRITE_ASCII 0x248 ~~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xad123.cre~ ~override/xaff1272.cre~ // Flaming Fist bdfistcc Enforcer
		WRITE_ASCII 0x2CC ~~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~XAFF1272~ #20  	// Script Name
		WRITE_ASCII 0x248 ~~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xaff1271.cre~ ~override/xab147b.cre~
		SAY NAME1 @3058
		SAY NAME2 @3058
		WRITE_ASCII 0x280 ~XAB147B~ #20  	// Script Name
		
		COPY_EXISTING ~xaff1272.cre~ ~override/xab149b.cre~
		SAY NAME1 @3058
		SAY NAME2 @3058
		WRITE_ASCII 0x280 ~XAB149B~ #20  	// Script Name
		
		COPY_EXISTING ~xaff1248.cre~ ~override/xab144a.cre~
		SAY NAME1 @4151
		SAY NAME2 @4151
		WRITE_ASCII 0x2CC ~xabridge~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~XAB144A~ #20  	// Script Name
		
		COPY_EXISTING ~xaff1271.cre~ ~override/xab145a.cre~
		SAY NAME1 @4151
		SAY NAME2 @4151
		WRITE_ASCII 0x2CC ~xabridge~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~XAB145A~ #20  	// Script Name
		
		COPY_EXISTING ~xaff1272.cre~ ~override/xab147a.cre~
		SAY NAME1 @4151
		SAY NAME2 @4151
		WRITE_ASCII 0x2CC ~xabridge~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~XAB147A~ #20  	// Script Name
		
		COPY_EXISTING ~xac105.cre~ ~override/xab149a.cre~ // kent
		SAY NAME1 @4151
		SAY NAME2 @4151
		WRITE_ASCII 0x2CC ~xabridge~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~XAB149A~ #20  	// Script Name
	//}
	
	//{ Block F Base
		COPY_EXISTING ~xaf100.cre~ ~override/xaangelo.cre~ // Angelo angelo
		WRITE_ASCII 0x2CC ~~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xaangelo~ #20  	// Script Name
		WRITE_ASCII 0x248 ~shout~ #8		// Override Script
		WRITE_ASCII 0x250 ~mage3~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~wtasight~ #8		// Default Script
	//}
	
	//{ BG2 Base
		COPY_EXISTING ~bonebld.cre~ ~override/xabondag.cre~ // Bone Dagger
		SAY NAME1 @4159 /* ~Bone Dagger~ */
		SAY NAME2 @4159 /* ~Bone Dagger~ */
		WRITE_ASCII 0x248 ~~ #8		// Override Script
		WRITE_LONG 0x14 500	// Exp
		WRITE_SHORT 0x24 10		// Current HP
		WRITE_SHORT 0x24 10 	// Max HP
		WRITE_SHORT 0x46 0		// Natural AC
		WRITE_SHORT 0x48 0		// Effective AC
		
	
		COPY_EXISTING ~ankheg01.cre~ ~override/xamutank.cre~ // Mutated Ankheg
		SAY NAME1 @4077
		SAY NAME2 @4077
		WRITE_LONG 0x14 2000	// Exp
		WRITE_SHORT 0x24 72		// Current HP
		WRITE_SHORT 0x24 72 	// Max HP
		WRITE_BYTE 0x52 8 		// THAC0
		WRITE_SHORT 0x46 0		// Natural AC
		WRITE_SHORT 0x48 0		// Effective AC
	
		COPY_EXISTING ~boy1.cre~ ~override/xapercy.cre~
		WRITE_ASCII 0x2CC ~xapercy~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xapercy~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xapercy~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		SAY NAME1 @4155/*~Percy~ */
		SAY NAME2 @4155
		
		COPY_EXISTING ~xapercy.cre~ ~override/xatimoty.cre~
		WRITE_ASCII 0x2CC ~xatimoty~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xatimoty~ #20  	// Script Name
		SAY NAME1 @4156/* ~Timotey~*/
		SAY NAME2 @4156
		WRITE_LONG 0x20 128 // Stone Death
	
		COPY_EXISTING ~chicke.cre~ ~override/xachick.cre~ // Chicken
		WRITE_ASCII 0x2CC ~xachick~ #8 	// Dialogue
		WRITE_ASCII 0x250 ~xachick~ #8		// Class Script
		
		COPY_EXISTING ~neb.cre~ ~override/xaneb.cre~ // Flaming Fist Enforcer
		WRITE_LONG 0x14 7000	// XP Value
		WRITE_SHORT 0x24 145	// Current HP
		WRITE_SHORT 0x26 145	// Max HP
		WRITE_ASCII 0x2CC ~xaneb~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xaneb~ #20  	// Script Name
		WRITE_ASCII 0x250 ~xaneb~ #8		// Class Script
		
		COPY_EXISTING ~CHWRAITH.CRE~ ~override/xachwrai.cre~
		WRITE_LONG 0x14 2000 // XP Value
		WRITE_SHORT 0x24 33
		WRITE_SHORT 0x26 33
		WRITE_SHORT 0x46 3
		WRITE_SHORT 0x48 3
		WRITE_BYTE 0x52 7
		WRITE_ASCII 0x2CC ~~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xachwrai~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xachwrai~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~wtasight~ #8		// Default Script
		
		COPY_EXISTING ~amcust02.cre~ ~override/xarbnb01.cre~
		SAY NAME1 @4140
		SAY NAME2 @4140
		WRITE_ASCII 0x2CC ~~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xarbnb01~ #20  	// Script Name
		WRITE_ASCII 0x248 ~~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~~ #8		// Race Script
		WRITE_ASCII 0x260 ~~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
		
		COPY_EXISTING ~xarbnb01.cre~ ~override/xarbnb02.cre~
		WRITE_ASCII 0x280 ~xarbnb02~ #20  	// Script Name
		
		COPY_EXISTING ~xaschael.cre~ ~override/xacc3.cre~ // Corwin
		WRITE_ASCII 0x2CC ~xacc3~ #8 	// Dialogue
		WRITE_ASCII 0x280 ~xacc3~ #20  	// Script Name
		WRITE_ASCII 0x248 ~xacc3~ #8		// Override Script
		WRITE_ASCII 0x250 ~~ #8		// Class Script
		WRITE_ASCII 0x258 ~shout~ #8		// Race Script
		WRITE_ASCII 0x260 ~xafigh01~ #8		// General Script
		WRITE_ASCII 0x268 ~~ #8		// Default Script
	//}
	
	//{ ToB Base
		COPY_EXISTING ~illasera.cre~ ~override/xaillase.cre~ // Illasera
		WRITE_ASCII 0x2CC ~xaillase~ #8 	// Dialogue
		WRITE_ASCII 0x250 ~xaillase~ #8	// Class Script
	//}
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xahowspy.cre~ // Hall of Wonders Spy
	WRITE_ASCII 0x248 ~xahowspy~ #8		// Override Script
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xacell.cre~ // Cell Spy
	WRITE_ASCII 0x248 ~xacell~ #8		// Override Script
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xaskieiv.cre~ // Skie invisible
	SAY NAME1 @3070 /* Skie */
	SAY NAME2 @3070
	WRITE_ASCII 0x34 ~xaskies~ #8 // Portrait
	WRITE_ASCII 0x2CC ~xaskie~ #8 	// Dialogue
	WRITE_ASCII 0x280 ~xaskie~ #20  	// Script Name
	WRITE_ASCII 0x248 ~xaskie~ #8		// Override Script
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xabeno2.cre~ // Beno invisible
	SAY NAME1 @4064 /* Beno Famari */
	SAY NAME2 @4064
	WRITE_ASCII 0x2CC ~xabeno2~ #8 	// Dialogue
	WRITE_ASCII 0x280 ~xabeno2~ #20  	// Script Name
	WRITE_ASCII 0x248 ~xabeno2~ #8		// Override Script
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xaglint2.cre~ // Glint invisible
	SAY NAME1 @4074 /* Glint */
	SAY NAME2 @4074
	WRITE_ASCII 0x34 ~xac100~ #8 // Portrait
	WRITE_ASCII 0x280 ~xaglint~ #20  	// Script Name
	WRITE_ASCII 0x248 ~xaglint~ #8		// Override Script
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xarohma3.cre~ // Rohma invisible
	SAY NAME1 @4079 /* Rohma */
	SAY NAME2 @4079 /* Rohma */
	WRITE_ASCII 0x280 ~xarohma3~ #20  	// Script Name
	
	COPY_EXISTING ~xalcspy.cre~ ~override/xapspy.cre~ // Paint Spy
	WRITE_ASCII 0x248 ~xapaint~ #8		// Override Script
	
	COPY_EXISTING ~xaffval1.cre~ ~override/xaffexec.cre~ // Flaming Fist Executioner
	SAY NAME1 @4072
	SAY NAME2 @4072
	WRITE_ASCII 0x280 ~xaffexec~ #20  	// Script Name
	WRITE_ASCII 0x2CC ~xaffexec~ #8 	// Dialogue
	
	//{ New CRE
		COPY ~%MOD_FOLDER%/rbg/cre/xaaudam2.cre~ ~override~
		SAY NAME1 @4067
		SAY NAME2 @4067
		
		COPY ~%MOD_FOLDER%/rbg/cre/xagorion.cre~ ~override~
		WRITE_ASCII 0x250 ~mage14a~ #8		// Class Script
		
		COPY ~%MOD_FOLDER%/rbg/cre/xajasper.cre~ ~override~
		SAY NAME1 @4092
		SAY NAME2 @4092
		
		COPY ~%MOD_FOLDER%/rbg/cre/xalyriel.cre~ ~override~
		SAY NAME1 @4049
		SAY NAME2 @4049
			
		COPY ~%MOD_FOLDER%/rbg/cre/xanarzu.cre~ ~override~
		WRITE_LONG 0x28 0xE279 // expressed as a hexadecimal
		SAY NAME1 @4050
		SAY NAME2 @4050
		
		COPY ~%MOD_FOLDER%/rbg/cre/xaneoma.cre~ ~override~
		SAY NAME1 @4046
		SAY NAME2 @4046
		
		COPY ~%MOD_FOLDER%/rbg/cre/xarohma2.cre~ ~override~
		SAY NAME1 @3067
		SAY NAME2 @3067
		
		COPY ~%MOD_FOLDER%/rbg/cre/xatianna.cre~ ~override~
		SAY NAME1 @4078
		SAY NAME2 @4078
		
		COPY ~%MOD_FOLDER%/rbg/cre/xavoidfe.cre~ ~override~
		SAY NAME1 @4147
		SAY NAME2 @4147
		
		COPY ~%MOD_FOLDER%/rbg/cre/xavoidle.cre~ ~override~
		SAY NAME1 @4148
		SAY NAME2 @4148	
		
		COPY ~%MOD_FOLDER%/rbg/cre/xavoidwe.cre~ ~override~
		SAY NAME1 @4146
		SAY NAME2 @4146
	//}
//}

//{ MOS, Text Screens
	COPY ~%MOD_FOLDER%/rbg/mos/xabadend.mos~ ~override~
	COPY ~%MOD_FOLDER%/rbg/mos/xabg.mos~ ~override~
	COPY ~%MOD_FOLDER%/rbg/mos/xadinner.mos~ ~override~
	COPY ~%MOD_FOLDER%/rbg/mos/xaptsara.mos~ ~override~
//}

//{ 2da
	COPY ~%MOD_FOLDER%/rbg/2da/xabad1.2da~ ~override~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4098)
	SET_2DA_ENTRY 2 1 3 RESOLVE_STR_REF(@4097)
	SET_2DA_ENTRY 2 2 3 RESOLVE_STR_REF(@4097)
	
	COPY_EXISTING ~xabad1.2da~ ~override/xabad2.2da~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4099)
	
	COPY_EXISTING ~xabad1.2da~ ~override/xabad3.2da~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4100)
	
	COPY ~%MOD_FOLDER%/rbg/2da/xabg.2da~ ~override~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4103)
	SET_2DA_ENTRY 2 1 3 RESOLVE_STR_REF(@4101)
	SET_2DA_ENTRY 2 2 3 RESOLVE_STR_REF(@4101)
	
	COPY_EXISTING ~xabg.2da~ ~override/xabgrom.2da~ 
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4102)
	
	COPY ~%MOD_FOLDER%/rbg/2da/xadinner.2da~ ~override~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4104)
	SET_2DA_ENTRY 2 1 3 RESOLVE_STR_REF(@4105)
	SET_2DA_ENTRY 2 2 3 RESOLVE_STR_REF(@4105)
	
	COPY_EXISTING ~xadinner.2da~ ~override/xadinrom.2da~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4106)
	
	COPY ~%MOD_FOLDER%/rbg/2da/xasara1.2da~ ~override~
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4108)
	SET_2DA_ENTRY 2 1 3 RESOLVE_STR_REF(@4107)
	SET_2DA_ENTRY 2 2 3 RESOLVE_STR_REF(@4107)
	
	COPY_EXISTING ~xasara1.2da~ ~override/xasara2.2da~ 
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4109)
	
	COPY_EXISTING ~xasara1.2da~ ~override/xasara3.2da~ 
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4110)
	
	COPY_EXISTING ~xasara1.2da~ ~override/xasara4.2da~ 
	SET_2DA_ENTRY 2 3 3 RESOLVE_STR_REF(@4111)
//}

//{ New Items

	//{ Farseer
		COPY_EXISTING ~misc64.itm~ ~override/xafarsee.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4117)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4117)
	//}
	
	//{ Ledger
		COPY_EXISTING ~book71.itm~ ~override/xaledger.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4119)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4119)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4120)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4120)
	//}
	
	//{ Manifest 1
		COPY_EXISTING ~scrl3d.itm~ ~override/xamanfst.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4121)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4121)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4122)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4122)
	//}
	
	//{ Manifest 2
		COPY_EXISTING ~scrl3d.itm~ ~override/xamanfs2.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4123)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4123)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4124)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4124)
	//}
	
	//{ Manifest 3
		COPY_EXISTING ~scrl3d.itm~ ~override/xamanfs3.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4125)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4125)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4126)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4126)
	//}
	
	//{ Beno's Head
		COPY_EXISTING ~misc9h.itm~ ~override/xabenohd.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4013)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4013)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4014)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4014)
	//}
	
	//{ Soultaker Dagger (Beno)
		COPY_EXISTING ~dagg10.itm~ ~override/xastdagb.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@3158)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@3158)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4015)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4015)
	//}
	
	//{ Soultaker Dagger (Fake)
		COPY_EXISTING ~dagg10.itm~ ~override/xastdagf.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@3158)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@3158)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4016)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4016)
	//}
	
	//{ Rohma's Doll
		COPY_EXISTING ~misc1g.itm~ ~override/xardoll.itm~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4115)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4115)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4116)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4116)
	//}
	
	// Left off 4/27
	
	//{ Hen that Laid the Golden Egg
		COPY ~%MOD_FOLDER%/rbg/itm/xachick.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4001)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4001)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4002)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4002)
	//}
	
	//{ Lyriel's Gratitude
		COPY ~%MOD_FOLDER%/rbg/itm/xalyamul.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4003)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4003)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4004)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4004)
	//}
	
	//{ Dragonspear Medallion
		COPY ~%MOD_FOLDER%/rbg/itm/xamedal.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4005)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4005)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4006)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4006)
	//}
	
	//{ Aureate Egg
		COPY ~%MOD_FOLDER%/rbg/itm/xaegg.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4007)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4007)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4008)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4008)
	//}
	
	//{ Quiver + 4
		COPY ~%MOD_FOLDER%/rbg/itm/xaquiver.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4009)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4009)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4010)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4010)
	//}
	
	//{ Mindshield Ring
		COPY ~%MOD_FOLDER%/rbg/itm/xamsring.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4011)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4011)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4012)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4012)
	//}
	
	//{ Baatezu's Gift
		COPY ~%MOD_FOLDER%/rbg/itm/xasword.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4039)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4039)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4040)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4040)
		
		COPY ~%MOD_FOLDER%/rbg/bam/xaswordi.bam~ ~override~
		COPY ~%MOD_FOLDER%/rbg/bam/xaswordd.bam~ ~override~		
	//}
	
	//{ Engagement Rings
		//Refer to ringabilities.txt and ringbits.xlsx
		COPY ~%MOD_FOLDER%/rbg/itm/xaring99.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4017)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4017)
		WRITE_LONG 0x536 RESOLVE_STR_REF(@2010)
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring07.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4018)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4018)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring11.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4019)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4019)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring13.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4020)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4020)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring14.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4021)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4021)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring19.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4022)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4022)
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring21.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4023)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4023)
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring22.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4024)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4024)
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring25.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4025)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4025)
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring26.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4026)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4026)
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY_EXISTING ~xaring99.itm~ ~override/xaring28.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4027)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4027)
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY ~%MOD_FOLDER%/rbg/itm/xarng99a.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@4017)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@4017)
		WRITE_LONG 0x536 RESOLVE_STR_REF(@2010)
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng07a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4028)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4028)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng11a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4029)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4029)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0

		COPY_EXISTING ~xarng99a.itm~ ~override/xarng13a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4030)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4030)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng14a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4031)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4031)
		WRITE_BYTE 0x444 0
		WRITE_BYTE 0x474 0
		WRITE_BYTE 0x4A4 0
		WRITE_BYTE 0x4D4 0
		WRITE_BYTE 0x504 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng19a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4032)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4032)
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng21a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4033)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4033)
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng22a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4034)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4034)
		WRITE_BYTE 0x3E4 0
		WRITE_BYTE 0x414 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng25a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4035)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4035)
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng26a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4036)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4036)
		WRITE_BYTE 0x174 0
		WRITE_BYTE 0x1A4 0
		WRITE_BYTE 0x1D4 0
		WRITE_BYTE 0x204 0
		WRITE_BYTE 0x234 0
		WRITE_BYTE 0x264 0
		WRITE_BYTE 0x294 0
		WRITE_BYTE 0x594 0
		WRITE_BYTE 0x5C4 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
		
		COPY_EXISTING ~xarng99a.itm~ ~override/xarng28a.itm~
		WRITE_LONG 0x50 RESOLVE_STR_REF(@4037)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@4037)
		WRITE_BYTE 0x84 0
		WRITE_BYTE 0xB4 0
		WRITE_BYTE 0xE4 0
		WRITE_BYTE 0x114 0
		WRITE_BYTE 0x144 0
		WRITE_BYTE 0x2C4 0
		WRITE_BYTE 0x2F4 0
		WRITE_BYTE 0x324 0
		WRITE_BYTE 0x354 0
		WRITE_BYTE 0x384 0
		WRITE_BYTE 0x3B4 0
		WRITE_BYTE 0x564 0
	//}
//}

//{ Kidnap Music
	ADD_MUSIC xamu04	~%MOD_FOLDER%/rbg/mus/xamu04.mus~
	COPY ~%MOD_FOLDER%/rbg/mus/xamu04a.acm~ ~MUSIC/xamu04/xamu04a.acm~	
//}

//{ Sanctum Music
	ADD_MUSIC xamu05	~%MOD_FOLDER%/rbg/mus/xamu05.mus~
	COPY ~%MOD_FOLDER%/rbg/mus/xamu05a.acm~ ~MUSIC/xamu05/xamu05a.acm~	
//}

//{ Kidnap Quest End Music
	ADD_MUSIC xamu06	~%MOD_FOLDER%/rbg/mus/xamu06.mus~
	COPY ~%MOD_FOLDER%/rbg/mus/xamu06a.acm~ ~MUSIC/xamu06/xamu06a.acm~	
//}

//{ Preparations Music
	ADD_MUSIC xamu07	~%MOD_FOLDER%/rbg/mus/xamu07.mus~
	COPY ~%MOD_FOLDER%/rbg/mus/xamu07a.acm~ ~MUSIC/xamu07/xamu07a.acm~	
//}

//{ Block A Area Modifications
	//{ Places where Brevlik can spawn
		ACTION_DEFINE_ARRAY brevSpawns
		BEGIN
			xaas137 // ar0114
			xaas138 // ar0103
			xaas159 // ar0133
			xaas242 // ar0119
			xaas479 // ar0157
		END

		ACTION_PHP_EACH brevSpawns AS _ => spawnArea
		BEGIN
			EXTEND_TOP ~%spawnArea%.bcs~ ~%MOD_FOLDER%/rbg/baf/xabrvspw.baf~
		END
	//}
	
	//{ ar0100 xaa233 NW Baldur's Gate
		COPY_EXISTING ~xaa233.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x3E7C 256
		WRITE_LONG 0x3F40 256
		WRITE_LONG 0x4004 256
		WRITE_LONG 0x40C8 256
		WRITE_LONG 0x418C 256
		WRITE_LONG 0x4250 256
		WRITE_LONG 0x4314 256
		
		// Remove Ocellis
		WRITE_LONG 0x2BD4 0
	//}
	
	//{ ar0101 xaa475 Silvershield Estate L1
		COPY_EXISTING ~xaa475.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x990 256
	//}
	
	//{ ar0102 xaa592 Silvershield Estate L2
		EXTEND_TOP ~xaas592.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0102.baf~
	
		COPY_EXISTING ~xaa592.are~ ~override~

		// Replace Dialogues
		WRITE_ASCII 0x164 ~xabrilla~ #8 // Brilla
		WRITE_ASCII 0x384 ~xacook~ #8 // Cook
				
		// Disable NPCs
		WRITE_LONG 0x484 0 // Entar
	//}
	
	//{ ar0103 xaa138 Splurging Sturgeon L1
		EXTEND_TOP ~xaas138.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0103.baf~
		
		COPY_EXISTING ~xaa138.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0xDA4 256
		
		// Disable NPCs
		WRITE_LONG 0x594 0 // Lusselyn
		
		// Replace Lantanara Dialogue
		WRITE_ASCII 0x6B4 ~xalantan~ #8
	//}
	
	//{ ar0104 xaa260 Splurging Sturgeon L2
		COPY_EXISTING ~xaa260.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x264 0 // Mr. Shade
		WRITE_LONG 0x374 0 // Mustard Jelly
	//}
	
	//{ ar0112 xaa228 Undercellar
		EXTEND_TOP ~xaas228.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0112.baf~
	
		COPY_EXISTING ~xaa228.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x2024 0 // Quenash
	//}
	
	//{ ar0114 xaa137 
		COPY_EXISTING ~xaa137.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x374 0 // Larze
		WRITE_LONG 0x484 0 // Vivienne
	//}
	
	//{ ar0116 xaa481 
		COPY_EXISTING ~xaa481.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x374 0 // Farluck
		WRITE_LONG 0x264 0
		WRITE_LONG 0x594 0
		WRITE_LONG 0x484 0
	//}
	
	//{ ar0117 xaa580
		COPY_EXISTING ~xaa580.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Guard
		WRITE_LONG 0x264 0 // Guard
		WRITE_LONG 0x374 0 // Noblewoman
	//}
	
	//{ ar0118 xaa582
		EXTEND_TOP ~xaas582.bcs~ ~%MOD_FOLDER%/rbg/baf/xaar0118.baf~
	//}
	
	//{ ar0119 xaa242
		COPY_EXISTING ~xaa242.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0xDA4 256
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Bellamy
	//}
	
	//{ ar0120 xaa457
		COPY_EXISTING ~xaa457.are~ ~override~
		
		// Replace Ithtyl Dialogue
		WRITE_ASCII 0x164 ~xaithtyl~ #8
	//}
	
	//{ ar0121 xaa605
		COPY_EXISTING ~xaa605.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Areana
	//}
	
	//{ ar0123 xaa106
		EXTEND_TOP ~xaas106.bcs~ 	~%MOD_FOLDER%/rbg/baf/xauc.baf~
	
		COPY_EXISTING ~xaa106.are~ ~override~
		
		// Deactivate Exit Back to Maze
		WRITE_LONG 0x1560 256
		
		// Replace Ambush Party with Shadows
		WRITE_ASCII 0x2AC ~SHADFI01~ #8
		WRITE_ASCII 0x3BC ~SHADOW01~ #8
		WRITE_ASCII 0x4CC ~xac158~ #8 // bdshsoul Shadowed Soul
		WRITE_ASCII 0x5DC ~xac152~ #8 // bdwrai01 Wraith
		WRITE_ASCII 0x6EC ~SHADFI01~ #8
		WRITE_ASCII 0x7FC ~SHADOW01~ #8
		
		// Replace Magma Bulwark with Healing Potions
		WRITE_ASCII 0x1FEC ~POTN55~ #8
		WRITE_SHORT 0x1FF6 2
		
		// Replace Battle Song
		WRITE_LONG 0x24B8 xaf3
		
		// Replace Area Triggers
		WRITE_ASCII 0x1474 ~xauctemp~ #8
		
		//{ Update Spawn Points to use BG2 and SoD Assets
			//{ Spawn Point 0
				WRITE_ASCII 0x15E8 ~xabondag~ #8 // Bone Dagger
				WRITE_ASCII 0x15F0 ~skelsu07~ #8
				WRITE_ASCII 0x15F8 ~skelsu11~ #8
				WRITE_ASCII 0x1600 ~xac158~ #8 // bdshsoul Shadowed Soul
			//}
			
			//{ Spawn Point 1
				WRITE_ASCII 0x16B0 ~xabondag~ #8 // Bone Dagger
				WRITE_ASCII 0x16B8 ~ghastgsu~ #8
				WRITE_ASCII 0x16C0 ~ghastf01~ #8
				WRITE_ASCII 0x16C8 ~xac154~ #8 // bdwight2 Imbued Wight
			//}
			
			//{ Spawn Point 2
				WRITE_ASCII 0x1778 ~xabondag~ #8
				WRITE_ASCII 0x1780 ~xac153~ #8 // bdbonbat Bone Bat
				WRITE_ASCII 0x1788 ~xac155~ #8 // bdskgr07 Skeletal Mage
			//}
			
			//{ Spawn Point 3
				WRITE_ASCII 0x1840 ~xabondag~ #8
				WRITE_ASCII 0x1848 ~ghast01~ #8
			//}
			
			//{ Spawn Point 4
				WRITE_ASCII 0x1908 ~xabondag~ #8 // Bone Dagger
				WRITE_ASCII 0x1910 ~skelsu01~ #8
				WRITE_ASCII 0x1912 ~zombie01~ #8
			//}
			
			//{ Spawn Point 5
				WRITE_ASCII 0x19D0 ~xabondag~ #8 // Bone Dagger
				WRITE_ASCII 0x19D8 ~xac152~ #8
				WRITE_ASCII 0x19E0 ~xac158~ #8 // bdshsoul Shadowed Soul
			//}
			
			//{ Spawn Point 6
				WRITE_ASCII 0x1A98 ~xabondag~ #8 // Bone Dagger
			//}
			
			//{ Spawn Point 7
				WRITE_ASCII 0x1B60 ~xabondag~ #8 // Bone Dagger
			//}
			
			//{ Spawn Point 8
				WRITE_ASCII 0x1C28 ~xabondag~ #8 // Bone Dagger
			//}
			
			//{ Spawn Point 9
				WRITE_ASCII 0x1CF0 ~xabondag~ #8 // Bone Dagger
			//}
			
			//{ Spawn Point 10
				WRITE_ASCII 0x1DB8 ~xabondag~ #8 // Bone Dagger
			//}
		//}
	//}
	
	//{ ar0126 xaa361 Ragefast's Home
		COPY_EXISTING ~xaa361.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Ragefast
		WRITE_LONG 0x264 0 // Abela	
	//}
	
	//{ ar0127 xaa291 Merchant's League L1
		COPY_EXISTING ~xaa291.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x6A4 0 // Irlentree
		
		// Replace Doppelgangers
		WRITE_ASCII 0x3BC ~xamerlea~ #8
		WRITE_ASCII 0x4CC ~xamerlea~ #8
		WRITE_ASCII 0x5DC ~xamerlea~ #8
	//}
	
	//{ ar0128 xaa406 Merchant's League L2
		EXTEND_TOP ~xaas406.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0128.baf~
	
		COPY_EXISTING ~xaa406.are~ ~override~
		
		// Adjust script for cook
		WRITE_ASCII 0x17C ~xamerchg~ #8
		
		// Disable NPCs
		WRITE_LONG 0x6A4 0 // Zorl
		
		// Replace Merchants
		WRITE_ASCII 0x3BC ~xamerlea~ #8
		WRITE_ASCII 0x4CC ~xamerlea~ #8
	//}
	
	//{ ar0130 xaa363 Hall of Wonders
		EXTEND_TOP ~xaas363.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0130.baf~
		
		COPY_EXISTING ~xaa363.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0xB84 256
		WRITE_LONG 0xC48 256
	//}
	
	//{ ar0134 xaa330 Low Lantern B1
		EXTEND_TOP ~xaas330.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0134.baf~
	
		COPY_EXISTING ~xaa330.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x374 0 // Desreta
		WRITE_LONG 0x484 0 // Vay-ya
		
	//}
	
	//{ ar0135 xaa540 Low Lantern B2
		COPY_EXISTING ~xaa540.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Yago
	//}
	
	//{ ar0138 xaa670 Ramazith L5
		EXTEND_TOP ~xaas670.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0138.baf~
	
		COPY_EXISTING ~xaa670.are~ ~override~
		
		// Disable Containers
		WRITE_LONG 0x270 32
		WRITE_LONG 0x330 32
		WRITE_LONG 0x3F0 32
		WRITE_LONG 0x4B0 32
		WRITE_LONG 0x570 32
		WRITE_LONG 0x630 32
		WRITE_LONG 0x6F0 32
		WRITE_LONG 0x7B0 32
		WRITE_LONG 0x870 32
		
		//{ Tower Trouble Quest
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 170
					fj_loc_y = 138
					fj_orientation = 14 
				STR_VAR
					fj_structure_type = actor
					fj_name = xatimoty
					fj_cre_resref = xatimoty
			END
			LPF fj_are_structure
				INT_VAR
					fj_loc_x = 193
					fj_loc_y = 176
					fj_orientation = 14 
				STR_VAR
					fj_structure_type = actor
					fj_name = basgrt01
					fj_cre_resref = basgrt01
			END
		//}
	//}
	
	//{ ar0139 xaa461 Ramazith L2
		COPY_EXISTING ~xaa461.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Mustard Jelly
		WRITE_LONG 0x264 0 // Mustard Jelly
	//}
	
	//{ ar0140 xaa603 Ramazith L3
		COPY_EXISTING ~xaa603.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Ghast
		WRITE_LONG 0x264 0 // Ghast
		WRITE_LONG 0x374 0 // Ghast
		WRITE_LONG 0x484 0 // Ghast
		WRITE_LONG 0x594 0 // Ghast
	//}
	
	//{ ar0141 xaa646 Ramazith L4
		COPY_EXISTING ~xaa646.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Hobgoblin
		WRITE_LONG 0x264 0 // Hobgoblin
		WRITE_LONG 0x374 0 // Hobgoblin
		WRITE_LONG 0x484 0 // Hobgoblin
		WRITE_LONG 0x594 0 // Hobgoblin
		WRITE_LONG 0x6A4 0 // Hobgoblin
	//}
	
	//{ ar0142 xaa668 Ramazith L5
		COPY_EXISTING ~xaa668.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Kobold Commando
		WRITE_LONG 0x264 0 // Kobold Commando
		WRITE_LONG 0x374 0 // Kobold Commando
		WRITE_LONG 0x484 0 // Kobold Commando
		WRITE_LONG 0x594 0 // Kobold Commando
		WRITE_LONG 0x6A4 0 // Kobold Commando
	//}
	
	

	//{ ar0153 xaa192 Thieves' Guild
		COPY_EXISTING ~xaa192.are~ ~override~
		
		// Replace Dialog
		WRITE_ASCII 0x484 ~xaalatos~ #8
		
		// Disable NPCs
		WRITE_LONG 0x264 0 // Resar
	//}

	//{ ar0161 xaa482 Degrodel's Home
		COPY_EXISTING ~xaa482.are~ ~override~
		
		// Change Creatures
		WRITE_ASCII 0x154 ~xaa548~ #8 // ftowb5
		WRITE_ASCII 0x264 ~xaa151~ #8 // mtowba_a
		
		// Disable NPCs
		WRITE_LONG 0x374 0 
		WRITE_LONG 0x484 0 
		WRITE_LONG 0x594 0
		WRITE_LONG 0x6A4 0
		WRITE_LONG 0x7B4 0
	//}
	
	//{ ar0162 xaa478 Louise and Laerta's Home
		COPY_EXISTING ~xaa478.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Louise
		WRITE_LONG 0x264 0 // Laerta
	//}
	
	//{ ar0165 xaa477 Tavern
		EXTEND_TOP ~xaas477.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0165.baf~

		COPY_EXISTING ~xaa477.are~ ~override~
		
		// Replace Dialog
		WRITE_ASCII 0x164 ~xaconnol~ #8
	//}
	
	//{ ar0166 xaa589 Tavern
		COPY_EXISTING ~xaa589.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x264 0 // Borinole
	//}
	
	//{ ar0167 xaa483 Pheirkas Home
		EXTEND_TOP ~xaas483.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0116.baf~
		
		COPY_EXISTING ~xaa483.are~ ~override~
		
		// Change Creatures
		WRITE_ASCII 0x154 ~xaa548~ #8 // ftowb5
	//}
	
	//{ ar0200 xaa134 N Baldur's Gate
		EXTEND_TOP ~xaas134.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0200.baf~
	
		COPY_EXISTING ~xaa134.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x4574 256
		WRITE_LONG 0x4638 256
		WRITE_LONG 0x46FC 256
		WRITE_LONG 0x47C0 256
		WRITE_LONG 0x4884 256
		WRITE_LONG 0x4948 256
		WRITE_LONG 0x4A0C 256
		
		// Disable NPCs
		WRITE_LONG 0x3014 0 // Petrine
		WRITE_LONG 0x2F04 0 // Ramazith
		WRITE_LONG 0x3674 0 // Rodnim
		WRITE_LONG 0x3564 0 // Tartusse
		WRITE_LONG 0x3454 0 // Tick
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 3765
				fj_loc_y = 1640
				fj_orientation = 7 
			STR_VAR
				fj_structure_type = actor
				fj_name = xamom
				fj_cre_resref = xamom
		END
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 3820
				fj_loc_y = 1620
				fj_orientation = 7 
			STR_VAR
				fj_structure_type = actor
				fj_name = xapercy
				fj_cre_resref = xapercy
		END
		
		WRITE_LONG 0x4610 RESOLVE_STR_REF(@4157) // update info trigger for Ramazith's Tower
		
		WRITE_ASCII 0x768C ~~ #8 // remove door closing script for Ramazith's Tower
		WRITE_LONG 0x7634 1 // Set door flag to open (and nothing else)
		WRITE_LONG 0x3E64 0 // Remove travel trigger connection to door
		WRITE_LONG 0x8C60 RESOLVE_STR_REF(@4157) // update map note text for Ramazith's Tower
	//}
	
	//{ ar0224 xaa301 BG Sewers (Sewerfolk)
		COPY_EXISTING ~xaa301.are~ ~override~
		
		// Change Spiders to BG2 assets
		WRITE_ASCII 0x19C ~spidgi01~ #8
		WRITE_ASCII 0x2AC ~spidhu01~ #8
		
		// Change Sewerfolk to Carrion Crawlers
		WRITE_ASCII 0x3BC ~carcra01~ #8
		WRITE_ASCII 0x4CC ~carcra01~ #8
		WRITE_ASCII 0x5DC ~carcra01~ #8
		WRITE_ASCII 0x6EC ~carcra01~ #8
		WRITE_ASCII 0x7FC ~carcra01~ #8
		WRITE_ASCII 0x90C ~carcra01~ #8
		WRITE_ASCII 0x3BC ~carcra01~ #8
		WRITE_ASCII 0xA1C ~carcra01~ #8
		
		// Sleep Creatures
		WRITE_ASCII 0x37B8 ~spidgi01~ #8 // use the BG2 asset
		
		//{ Update spawn points to use BG2 assets
			//{ Spawn Point 0
				WRITE_ASCII 0x1C8C ~ghoul01~ #8
				WRITE_ASCII 0x1C94 ~ghast01~ #8
			//}
			
			//{ Spawn Point 1
				WRITE_ASCII 0x1D54 ~spidsm01~ #8
			//}
			
			//{ Spawn Point 2
				WRITE_ASCII 0x1E1C ~spidsm01~ #8
				WRITE_ASCII 0x1E24 ~spidph01~ #8
			//}
			
			//{ Spawn Point 3
				WRITE_ASCII 0x1EE4 ~spidwr01~ #8
			//}
		//}
	//}
	
	//{ ar0225 xaa160 BG Sewers (Ratchild)
		EXTEND_TOP ~xaas160.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0225.baf~
	
		COPY_EXISTING ~xaa160.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x374 0 // Ratchild
		
		//{ Update spawn points to use BG2 assets
			//{ Spawn Point 0
				WRITE_ASCII 0x1CB8 ~jellgr~ #8
				WRITE_ASCII 0x1CC0 ~jellmu~ #8
				WRITE_ASCII 0x1CC8 ~jelloc~ #8
			//}
			
			//{ Spawn Point 1
				WRITE_ASCII 0x1D80 ~jellygr~ #8
				WRITE_ASCII 0x1D88 ~jellgr~ #8
			//}
			
			//{ Spawn Point 2
				WRITE_ASCII 0x1E48 ~jellygr~ #8
				WRITE_ASCII 0x1E50 ~jelloc~ #8
				WRITE_ASCII 0x1E58 ~slfis01~ #8
			//}
		//}
	//}
	
	//{ ar0226 xaa123 BG Sewers (Ogre Mage)
		COPY_EXISTING ~xaa123.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x374 0 // Ogre Mage
		
		//{ Change Creatures - use BG2 assets
			WRITE_ASCII 0x19C ~spidph01~ #8
			WRITE_ASCII 0x2AC ~spidph01~ #8
			WRITE_ASCII 0x4CC ~carcra01~ #8
			WRITE_ASCII 0x5DC ~carcra01~ #8
			WRITE_ASCII 0x6EC ~carriosu~ #8
			WRITE_ASCII 0x7FC ~carriosu~ #8
			WRITE_ASCII 0x90C ~carcra01~ #8
		//}
		
		//{ Update Spawn Points to use BG2 assets
			//{ Spawn Point 0
				WRITE_ASCII 0x18B8 ~carcra01~ #8
			//}
			
			//{ Spawn Point 1
				WRITE_ASCII 0x1980 ~carriosu~ #8
			//}
			
			//{ Spawn Point 2
				WRITE_ASCII 0x1A48 ~carcra01~ #8
			//}
		//}
	//}
	
	//{ ar0300 xaa107
		COPY_EXISTING ~xaa107.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x2ECC 256
		WRITE_LONG 0x2F90 256
		WRITE_LONG 0x3054 256
		WRITE_LONG 0x3118 256
		
		// Disable NPCs
		WRITE_LONG 0x2244 0 // Brielbara 
		WRITE_LONG 0x1E04 0 // Lothander
		WRITE_LONG 0x1F14 0 // Marek
	//}
	
	
	//{ ar0600 xaa168
		EXTEND_TOP ~xaas168.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0600.baf~
		
		COPY_EXISTING ~xaa168.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x493C 256
		WRITE_LONG 0x4A00 256
		WRITE_LONG 0x4AC4 256
		WRITE_LONG 0x4B88 256
		WRITE_LONG 0x4C4C 256
		
		// Disable NPCs
		WRITE_LONG 0x3AB4 0 // Dun 
		WRITE_LONG 0x3BC4 0 // Varci 
	//}
	
	//{ ar0601 xaa290 - Seven Suns L1
		COPY_EXISTING ~xaa290.are~ ~override~
		
		WRITE_ASCII 0x19C ~xamerchj~ #8
		WRITE_ASCII 0x2AC ~xamerchj~ #8
		WRITE_ASCII 0x3BC ~xamerchj~ #8
	//}
	
	//{ ar0602 xaa409 - Seven Suns L2
		EXTEND_TOP ~xaas409.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0602.baf~
		
		COPY_EXISTING ~xaa409.are~ ~override~
		
		// Replace Doppelgangers
		WRITE_ASCII 0x19C ~xamerchj~ #8
		WRITE_ASCII 0x2AC ~xamerchj~ #8
	//}
	
	//{ ar0603 xaa410 - Seven Suns Cellar
		COPY_EXISTING ~xaa410.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x264 0	// Doppelganger
		WRITE_LONG 0x154 0	// Jhasso		
	//}
	
	//{ ar0607 xaa287
		EXTEND_TOP ~xaas287.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0607.baf~
	//}
	
	//{ ar0608 xaa416
		EXTEND_TOP ~xaas416.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0608.baf~
	//}
	
	//{ ar0612 xaa309
		EXTEND_TOP ~xaas309.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0612.baf~
	//}
	
	//{ ar0613 xaa529
		EXTEND_TOP ~xaas529.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0613.baf~
	//}
	
	//{ ar0614 xaa563
		EXTEND_TOP ~xaas563.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0614.baf~
	//}
	
	//{ ar0615 xaa662
		EXTEND_TOP ~xaas662.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0615.baf~
		
		COPY_EXISTING ~xaa662.are~ ~override~
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 2
				fj_box_left		= 724
				fj_box_top		= 779
				fj_box_right	= 791
				fj_box_bottom	= 861
				fj_cursor_idx	= 22
				fj_alt_x		= 760
				fj_alt_y		= 822
				fj_flags		= 1024
				fj_vertex_0     = 724 + (807 << 16)
				fj_vertex_1     = 791 + (779 << 16)
				fj_vertex_2     = 791 + (834 << 16)
				fj_vertex_3     = 724 + (861 << 16)
			STR_VAR
				fj_structure_type = region
				fj_name = ~XAP0615~
				fj_reg_script = ~XAP0615~
		END
	//}
	
	//{ ar0619 xaa364
		COPY_EXISTING ~xaa364.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Fenten 
	//}
	
	//{ ar0700 xaa109
		COPY_EXISTING ~xaa109.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x7440 256
		WRITE_LONG 0x7504 256
		WRITE_LONG 0x75C8 256
		
		// Disable NPCs
		WRITE_LONG 0x5FE4 0 // Lady Hannah
		
		// Lock Doors 
		WRITE_LONG 0x6FA8 2050 // Oberan Estate
		WRITE_LONG 0x9DDC 1090 // Force Locked Door to use Key
		WRITE_ASCII 0x9E2C ~ACIDMIST~ #8 // Key
		
	//}
	
	//{ ar0705 xaa119
		EXTEND_TOP ~xaas119.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0705.baf~
	//}
	
	//{ ar0706 xaa210
		EXTEND_TOP ~xaas210.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0706.baf~
		
		COPY_EXISTING ~xaa206.are~ ~override~
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 2
				fj_box_left		= 215
				fj_box_top		= 447
				fj_box_right	= 271
				fj_box_bottom	= 510
				fj_cursor_idx	= 22
				fj_alt_x		= 270
				fj_alt_y		= 527
				fj_flags		= 1024
				fj_vertex_0     = 215 + (479 << 16)
				fj_vertex_1     = 270 + (447 << 16)
				fj_vertex_2     = 271 + (475 << 16)
				fj_vertex_3     = 217 + (510 << 16)
			STR_VAR
				fj_structure_type = region
				fj_name = ~XAP0706~
				fj_reg_script = ~XAP0706~
	END
	//}
	
	//{ ar0726 xaa175 Diviner's Tent
		COPY_EXISTING ~xaa175.are~ ~override~
		
		// Diviner Dialogue
		WRITE_ASCII 0x164 ~xadivine~ #8
	//}
	
	//{ ar0800 xaa104
		EXTEND_TOP ~xaas104.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0800.baf~
	
		COPY_EXISTING ~xaa104.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x6534 256
		WRITE_LONG 0x65F8 256
		WRITE_LONG 0x66BC 256
		WRITE_LONG 0x6780 256
		WRITE_LONG 0x6844 256
		WRITE_LONG 0x6908 256
		WRITE_LONG 0x69CC 256
		WRITE_LONG 0x6A90 256
		
		// Disable NPCs
		WRITE_LONG 0x4FF4 0 // Elminster
		WRITE_LONG 0x4DD4 0 // Niklos
	//}
	
	//{ ar0900 xaa100
		EXTEND_TOP ~xaas100.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar0900.baf~
		EXTEND_TOP ~xaas100.bcs~	~%MOD_FOLDER%/rbg/baf/xamaprbg.baf~
		
		COPY_EXISTING ~xaa100.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x9B0 256
		
		// Disable Ankheg & Tenya
		WRITE_LONG 0x6A4 0
		WRITE_LONG 0x264 0
	//}
	
	//{ ar1100 xaa146
		COPY_EXISTING ~xaa146.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x5460 256
		WRITE_LONG 0x5524 256
		WRITE_LONG 0x55E8 256
		WRITE_LONG 0x56AC 256
		WRITE_LONG 0x5770 256
		WRITE_LONG 0x5834 256
		WRITE_LONG 0x58F8 256
	//}
	
	//{ ar1111 xaa293 Sunin's Home
		COPY_EXISTING ~xaa293.are~ ~override~
		
		// Change Actor to Nobleman
		WRITE_ASCII 0x19C ~xaa730~ #8
	//}
	
	//{ ar1113 xaa288 Slime Inn
		COPY_EXISTING ~xaa132.sto~ ~override/xasto00.sto~
		WRITE_LONG 0xC RESOLVE_STR_REF(@4150)
	
		COPY_EXISTING ~xaa288.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x6A4 0 // Slime
		WRITE_LONG 0x7B4 0 // Slime
		WRITE_LONG 0xAE4 0 // Slime
		WRITE_LONG 0xBF4 0 // Slime
		WRITE_LONG 0xD04 0 // Slime
		
		// Replace Dialogue
		WRITE_ASCII 0x274 ~xatownm~ #8
		WRITE_ASCII 0x384 ~xatownm~ #8
		WRITE_ASCII 0x494 ~xatownm~ #8
		WRITE_ASCII 0x5A4 ~xatownm~ #8
		WRITE_ASCII 0x8D4 ~xatownm~ #8
		WRITE_ASCII 0x9E4 ~xatownm~ #8
		WRITE_ASCII 0xE24 ~xatownm~ #8
	//}
	
	//{ ar1200 xaa108
		COPY_EXISTING ~xaa108.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x6708 256
		WRITE_LONG 0x67CC 256
		WRITE_LONG 0x6890 256
		WRITE_LONG 0x6954 256
		WRITE_LONG 0x6A18 256
		WRITE_LONG 0x6ADC 256
		
		// Disable NPCs
		WRITE_LONG 0x5324 0 // Entillis Fulsom
		
		// Change Iron Throne to WV
		WRITE_LONG 0x61B0 RESOLVE_STR_REF(@4138)
		WRITE_LONG 0x6BA4 RESOLVE_STR_REF(@4138)
	//}
	
	//{ ar1201 xaa150 Ogre Mage Ambush House
		OUTER_SET expiryOffset = 0x154
		OUTER_SET i = 0
		
		COPY_EXISTING ~xaa150.are~ ~override~
		
		WHILE (i < 5) BEGIN // Disable the existing area actors
			WRITE_LONG expiryOffset 0
			expiryOffset = (expiryOffset + 0x110)
			i = (i + 1)
		END
	//}
	
	//{ ar1207 xaa155
		COPY_EXISTING ~xaa155.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Basilisk
	//}
	
	//{ ar1208 xaa156
		COPY_EXISTING ~xaa156.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x6A4 0 // Noralee
	//}
	
	//{ ar1209 xaa157
		COPY_EXISTING ~xaa157.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0
		WRITE_LONG 0x264 0
		WRITE_LONG 0x374 0
	//}
	
	//{ ar1210 xaa326
		COPY_EXISTING ~xaa326.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0
		WRITE_LONG 0x264 0
	//}
	
	//{ ar1211 xaa158
		COPY_EXISTING ~xaa158.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0
	//}
	
	//{ ar1213 xaa154
		COPY_EXISTING ~xaa154.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0
	//}
	
	
	//{ ar1300 xaa145
		EXTEND_TOP ~xaas145.bcs~ 	~%MOD_FOLDER%/rbg/baf/xaar1300.baf~
		
		COPY_EXISTING ~xaa145.are~ ~override~
		
		// Disable rep traps
		WRITE_LONG 0x48A4 256
		WRITE_LONG 0x4968 256
		WRITE_LONG 0x4A2C 256
		WRITE_LONG 0x4AF0 256
		WRITE_LONG 0x4BB4 256
		WRITE_LONG 0x4C78 256
		WRITE_LONG 0x4D3C 256
		
		// Disable NPCs
		WRITE_LONG 0x3674 0 // Nikolai
	//}
	
	//{ ar1307 xaa428
		COPY_EXISTING ~xaa428.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x6A4 0 // Sanadal
	//}
	
	//{ ar1313 xaa437 Gantolandan's Home
		COPY_EXISTING ~xaa437.are~ ~override~
		
		// Disable NPCs
		WRITE_LONG 0x154 0 // Gantolandan
	//}
//}

//{ Block C Area Modifications
	//{ ar2612 xac100 Candlekeep - Gorion's Quarters
		COPY_EXISTING ~xac100.are~ ~override/xag3.are~
		
		// Change Area Script
		WRITE_ASCII 0x94 ~xag3~ #8 
		
		// Disable NPCs
		WRITE_LONG 0x154 0
		WRITE_LONG 0x264 0
		
		// Disable Triggers
		WRITE_LONG 0x460 256
		WRITE_LONG 0x39C 256
	//}
//}

//{ New ARE
	

	//{ Hall of Wonders Cutscene Area ar0131
		OUTER_SET expiryOffset = 0x154
		OUTER_SET i = 0
	
		COPY_EXISTING ~xaa362.are~ ~override/xacshow.are~ 
		
		// Replace Music
		WRITE_LONG 0x7E0 0
		
		WHILE (i < 4) BEGIN // Disable the existing area actors
			WRITE_LONG expiryOffset 0
			expiryOffset = (expiryOffset + 0x110)
			i = (i + 1)
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 718
				fj_loc_y = 858
				fj_orientation = 10 
				fj_flags = 9
			STR_VAR
				fj_structure_type = actor
				fj_name = xaorph01
				fj_cre_resref = boy3
				fj_dlg_resref = xaorph01
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 748
				fj_loc_y = 894
				fj_orientation = 10 
				fj_flags = 9
			STR_VAR
				fj_structure_type = actor
				fj_name = xaorph02
				fj_cre_resref = girl01
				fj_dlg_resref = xaorph02
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 727
				fj_loc_y = 892
				fj_orientation = 10 
				fj_flags = 9
			STR_VAR
				fj_structure_type = actor
				fj_name = xaorph03
				fj_cre_resref = boy3
				fj_dlg_resref = xaorph03
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 781
				fj_loc_y = 892
				fj_orientation = 10 
				fj_flags = 9
			STR_VAR
				fj_structure_type = actor
				fj_name = xaorph04
				fj_cre_resref = girl01
				fj_dlg_resref = xaorph04
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 832
				fj_loc_y = 927
				fj_orientation = 10 
				fj_flags = 9
			STR_VAR
				fj_structure_type = actor
				fj_name = xaorph05
				fj_cre_resref = boy1
				fj_dlg_resref = xaorph05
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 812
				fj_loc_y = 945
				fj_orientation = 10 
				fj_flags = 9
			STR_VAR
				fj_structure_type = actor
				fj_name = xaorph06
				fj_cre_resref = girl01
				fj_dlg_resref = xaorph06
		END
	//}
	
	//{ Ducal Palace 1FL (Kidnap) ar0108 xaa246
		OUTER_SET expiryOffset = 0x154
		OUTER_SET i = 0
		
		COPY_EXISTING ~xaa246.are~ ~override/xaducal.are~ 
		WRITE_LONG 0x99C xamu07
		WRITE_LONG 0x9A0 xamu07
		
		// Disable Travel Triggers
		WRITE_LONG 0xD2C 256
		WRITE_LONG 0xDF0 256
		WRITE_LONG 0xEB4 256
		WRITE_LONG 0xF78 256
		
		WHILE (i < 11) BEGIN // Disable the existing area actors
			WRITE_LONG expiryOffset 0
			expiryOffset = (expiryOffset + 0x110)
			i = (i + 1)
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 620
				fj_loc_y = 460
				fj_orientation = 10 
			STR_VAR
				fj_structure_type = actor
				fj_name = Belt
				fj_cre_resref = xabelt
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 740
				fj_loc_y = 350
				fj_orientation = 2 
			STR_VAR
				fj_structure_type = actor
				fj_name = Eltan
				fj_cre_resref = xaeltan
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 800
				fj_loc_y = 365
				fj_orientation = 2 
			STR_VAR
				fj_structure_type = actor
				fj_name = Kent
				fj_cre_resref = xakent
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 619
				fj_loc_y = 337
				fj_orientation = 14 
			STR_VAR
				fj_structure_type = actor
				fj_name = Liia
				fj_cre_resref = xalia
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 550
				fj_loc_y = 400
				fj_orientation = 14 
			STR_VAR
				fj_structure_type = actor
				fj_name = Melkor
				fj_cre_resref = xamelkor
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 740
				fj_loc_y = 321
				fj_orientation = 2 
			STR_VAR
				fj_structure_type = actor
				fj_name = Nederlok
				fj_cre_resref = xanederl
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 860
				fj_loc_y = 470
				fj_orientation = 6 
			STR_VAR
				fj_structure_type = actor
				fj_name = Valiant
				fj_cre_resref = xaffval1
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 780
				fj_loc_y = 512
				fj_orientation = 6 
			STR_VAR
				fj_structure_type = actor
				fj_name = Valiant
				fj_cre_resref = xaffval2
		END
	//}
	
	//{ Ducal Palace 2FL (Debrief) ar0109
		OUTER_SET expiryOffset = 0x154
		OUTER_SET i = 0
		
		COPY_EXISTING ~xaa447.are~ ~override/xaducal2.are~
		WRITE_LONG 0xA34 xaa12
		WRITE_LONG 0xA38 xaa13
		
		WHILE (i < 2) BEGIN // Disable the existing area actors
			WRITE_LONG expiryOffset 0
			expiryOffset = (expiryOffset + 0x110)
			i = (i + 1)
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 872
				fj_loc_y = 437
				fj_orientation = 2 
			STR_VAR
				fj_structure_type = actor
				fj_name = Belt
				fj_cre_resref = xabelt
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 552
				fj_loc_y = 376
				fj_orientation = 14 
			STR_VAR
				fj_structure_type = actor
				fj_name = Bence
				fj_cre_resref = xabence
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 792
				fj_loc_y = 390
				fj_orientation = 2 
			STR_VAR
				fj_structure_type = actor
				fj_name = Eltan
				fj_cre_resref = xaeltan
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 900
				fj_loc_y = 467
				fj_orientation = 2 
			STR_VAR
				fj_structure_type = actor
				fj_name = Entar
				fj_cre_resref = xaentar
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 720
				fj_loc_y = 260
				fj_orientation = 2 
			STR_VAR
				fj_structure_type = actor
				fj_name = Kent
				fj_cre_resref = xakent
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 830
				fj_loc_y = 412
				fj_orientation = 2 
			STR_VAR
				fj_structure_type = actor
				fj_name = Liia
				fj_cre_resref = xaliia
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 761
				fj_loc_y = 292
				fj_orientation = 2 
			STR_VAR
				fj_structure_type = actor
				fj_name = Nederlok
				fj_cre_resref = xanederl
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 986
				fj_loc_y = 466
				fj_orientation = 2 
			STR_VAR
				fj_structure_type = actor
				fj_name = Skie
				fj_cre_resref = xaskie
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 880
				fj_loc_y = 600
				fj_orientation = 6 
			STR_VAR
				fj_structure_type = actor
				fj_name = Valiant
				fj_cre_resref = xaffval1
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 570
				fj_loc_y = 307
				fj_orientation = 14 
			STR_VAR
				fj_structure_type = actor
				fj_name = Valiant
				fj_cre_resref = xaffval2
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 620
				fj_loc_y = 275
				fj_orientation = 14 
			STR_VAR
				fj_structure_type = actor
				fj_name = Valiant
				fj_cre_resref = xaffval3
		END
		
		LPF fj_are_structure
			INT_VAR
			fj_type 		= 0
			fj_box_left		= 360
			fj_box_top		= 454
			fj_box_right	= 364
			fj_box_bottom	= 450
			fj_cursor_idx	= 0
			fj_flags		= 0
			fj_vertex_0     = 360 + (450 << 16)
			fj_vertex_1     = 360 + (454 << 16)
			fj_vertex_2     = 364 + (450 << 16)
			fj_vertex_3     = 364 + (454 << 16)
			STR_VAR
			fj_structure_type = region
			fj_name = ~TrigCC~
		END
		
		LPF fj_are_structure
			INT_VAR
			fj_type 		= 0
			fj_box_left		= 750
			fj_box_top		= 500
			fj_box_right	= 752
			fj_box_bottom	= 498
			fj_cursor_idx	= 0
			fj_flags		= 0
			fj_vertex_0     = 752 + (498 << 16)
			fj_vertex_1     = 752 + (500 << 16)
			fj_vertex_2     = 750 + (498 << 16)
			fj_vertex_3     = 750 + (500 << 16)
			STR_VAR
			fj_structure_type = region
			fj_name = ~TrigCC2~
		END
		
		LPF fj_are_structure
			INT_VAR
			fj_type 		= 0
			fj_box_left		= 600
			fj_box_top		= 150
			fj_box_right	= 600
			fj_box_bottom	= 150
			fj_cursor_idx	= 0
			fj_flags		= 0
			fj_vertex_0     = 600 + (150 << 16)
			STR_VAR
			fj_structure_type = region
			fj_name = ~TrigExit~
		END
		
		LPF fj_are_structure
			INT_VAR
			fj_type 		= 0
			fj_box_left		= 360
			fj_box_top		= 504
			fj_box_right	= 364
			fj_box_bottom	= 500
			fj_cursor_idx	= 0
			fj_flags		= 0
			fj_vertex_0     = 360 + (500 << 16)
			fj_vertex_1     = 360 + (504 << 16)
			fj_vertex_2     = 364 + (500 << 16)
			fj_vertex_3     = 364 + (504 << 16)
			STR_VAR
			fj_structure_type = region
			fj_name = ~TrigP1~
		END
		
		LPF fj_are_structure
			INT_VAR
			fj_type 		= 0
			fj_box_left		= 700
			fj_box_top		= 465
			fj_box_right	= 702
			fj_box_bottom	= 463
			fj_cursor_idx	= 0
			fj_flags		= 0
			fj_vertex_0     = 702 + (463 << 16)
			fj_vertex_1     = 702 + (465 << 16)
			fj_vertex_2     = 700 + (463 << 16)
			fj_vertex_3     = 700 + (465 << 16)
			STR_VAR
			fj_structure_type = region
			fj_name = ~TrigP12~
		END
		
		LPF fj_are_structure
			INT_VAR
			fj_type 		= 0
			fj_box_left		= 800
			fj_box_top		= 530
			fj_box_right	= 802
			fj_box_bottom	= 528
			fj_cursor_idx	= 0
			fj_flags		= 0
			fj_vertex_0     = 800 + (530 << 16)
			fj_vertex_1     = 800 + (528 << 16)
			fj_vertex_2     = 802 + (530 << 16)
			fj_vertex_3     = 802 + (528 << 16)
			STR_VAR
			fj_structure_type = region
			fj_name = ~TrigSS~
		END
	//}
	
	
	
	//{ Ducal Palace 3FL
		COPY ~%MOD_FOLDER%/rbg/bmp/xaa625lm.bmp~ ~override~
		COPY ~%MOD_FOLDER%/rbg/bmp/xaa625sr.bmp~ ~override~
		COPY ~%MOD_FOLDER%/rbg/bmp/xaa625ht.bmp~ ~override~
		
		COPY ~%MOD_FOLDER%/rbg/are/xaduc3.are~ ~override~
		WRITE_LONG 0x1A2C xamu06
		WRITE_LONG 0x1A30 xamu06
	//}
	
	//{ Painting One
		
		EXTEND_TOP ~xacs101.bcs~ ~%MOD_FOLDER%/rbg/baf/xag1.baf~
		
		COPY ~%MOD_FOLDER%/rbg/are/xag1.are~ ~override~
		WRITE_LONG 0x5B94 xac2
		WRITE_LONG 0x5B98 xac2
	//}
	
	//{ Painting Two
		COPY ~%MOD_FOLDER%/rbg/are/xag2.are~ ~override~
		WRITE_LONG 0x59B0 xaa21
		WRITE_LONG 0x59B4 xaa21
		WRITE_LONG 0x59BC xaa22
	//}
	
	//{ Corwin's Home, L1 ar1316
		OUTER_SET expiryOffset = 0x154
		OUTER_SET i = 0
		
		COPY_EXISTING ~xaa272.are~ ~override/xahome.are~ 
		WRITE_LONG 0x688 xamu02
		WRITE_LONG 0x68C xamu02
		
		WHILE (i < 2) BEGIN // Disable the existing area actors
			WRITE_LONG expiryOffset 0
			expiryOffset = (expiryOffset + 0x110)
			i = (i + 1)
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 440
				fj_loc_y = 164
				fj_orientation = 14 
			STR_VAR
				fj_structure_type = actor
				fj_name = Audamar
				fj_cre_resref = xaaudam
				fj_bcs_override = wdasight
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 160
				fj_loc_y = 300
				fj_orientation = 14 
			STR_VAR
				fj_structure_type = actor
				fj_name = Rohma
				fj_cre_resref = xarohma
				fj_bcs_override = wdasight
		END
	//}	
		
	//{ Corwin's Home, L2 ar1317
		OUTER_SET expiryOffset = 0x154
		OUTER_SET i = 0
		
		COPY_EXISTING ~xaa431.are~ ~override/xahom2.are~
		WRITE_LONG 0x784 xamu02
		WRITE_LONG 0x788 xamu02
		
		WHILE (i < 2) BEGIN // Disable the existing area actors
			WRITE_LONG expiryOffset 0
			expiryOffset = (expiryOffset + 0x110)
			i = (i + 1)
		END
		
	//}
	
	//{ Corwin's Home, Rohma Kidnapped ar1316
		OUTER_SET expiryOffset = 0x154
		OUTER_SET i = 0
		
		COPY_EXISTING ~xaa272.are~ ~override/xakidnap.are~
		
		WHILE (i < 2) BEGIN // Disable the existing area actors
			WRITE_LONG expiryOffset 0
			expiryOffset = (expiryOffset + 0x110)
			i = (i + 1)
		END
		
		WRITE_LONG 0x688 xamu04
		WRITE_LONG 0x68C xamu04
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 389
				fj_loc_y = 257
				fj_orientation = 8 
			STR_VAR
				fj_structure_type = actor
				fj_name = Audamar
				fj_cre_resref = xaaudam2
		END
	//}
	
	
	
	//{ Demon's Sanctum
		COPY_EXISTING ~xaf100.are~ ~override/xademsan.are~
		
		// Disable NPCs
		WRITE_LONG 0x154 0
		WRITE_LONG 0x264 0
		WRITE_LONG 0x374 0
		WRITE_LONG 0x484 0

		WRITE_LONG 0x5EC 1 // Disable Ambient

		// Add Music
		WRITE_LONG 0x630 xamu05
		WRITE_LONG 0x634 xamu05
		WRITE_LONG 0x63C xaa22

		// Add Area Script
		WRITE_ASCII 0x94 ~xademsan~ #8
	//}
	
	//{ Lyriel Painting
		COPY ~%MOD_FOLDER%/rbg/are/xapaint1.are~ ~override~
	//}
	
	//{ Walk Home Cutscene Area
		COPY ~%MOD_FOLDER%/rbg/are/xawlkhom.are~ ~override~
		
		// Replace Music
		WRITE_LONG 0x5BE8 0
	//}
	
	//{ Undercity Temple ar0125
		OUTER_SET expiryOffset = 0x154
		OUTER_SET triggerFlagOffset = 0x116C
		OUTER_SET i = 0
		OUTER_SET j = 0
	
		COPY_EXISTING ~xaa101.are~ ~override/xauctemp.are~
		
		WRITE_ASCII 0x94 ~xauctemp~ #8 // Area Script
		
		WHILE (i < 21) BEGIN // Disable the existing area triggers
			WRITE_LONG triggerFlagOffset 256
			triggerFlagOffset = (triggerFlagOffset + 0xC4)
			i = (i + 1)
		END
		
		WHILE (j < 3) BEGIN // Disable Unneeded NPCs
			WRITE_LONG expiryOffset 0
			expiryOffset = (expiryOffset + 0x110)
			i = (i + 1)
		END
		
		// Battle Music
		WRITE_LONG 0x1364 xaa22
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 755
				fj_loc_y = 660
				fj_orientation = 0 
			STR_VAR
				fj_structure_type = actor
				fj_name = Beno
				fj_cre_resref = xabeno
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 610
				fj_loc_y = 690
				fj_orientation = 15 
			STR_VAR
				fj_structure_type = actor
				fj_name = Illasera
				fj_cre_resref = xaillase
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 740
				fj_loc_y = 780
				fj_orientation = 0 
			STR_VAR
				fj_structure_type = actor
				fj_name = Rohma
				fj_cre_resref = xarohma2
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_loc_x = 750
				fj_loc_y = 790
				fj_orientation = 0 
			STR_VAR
				fj_structure_type = actor
				fj_name = Rohma
				fj_cre_resref = xarohma3
		END
		
		LPF fj_are_structure
			INT_VAR
				fj_type 		= 0
				fj_box_left		= 730
				fj_box_top		= 670
				fj_box_right	= 740
				fj_box_bottom	= 680
				fj_cursor_idx	= 0
				fj_vertex_0     = 740 + (670 << 16)
				fj_vertex_1     = 730 + (670 << 16)
				fj_vertex_2     = 730 + (680 << 16)
				fj_vertex_3     = 740 + (680 << 16)
			STR_VAR
				fj_structure_type = region
				fj_name = ~xatrbeno~
		END
	//}
	
	//{ Dinner Cutscene - Three Old Kegs ar0119
		COPY_EXISTING ~xaa242.are~ ~override/xatok.are~
		
		// Disable NPCs
		WRITE_LONG 0xAE4 0
		
		// Deactivate Triggers
		WRITE_LONG 0xCE0 256
		WRITE_LONG 0xC1C 256
	//}
	
	//{ Proposal Area ar0900
		COPY_EXISTING ~xaa100.are~ ~override/xawyrm.are~
		
		// Disable NPCs
		WRITE_LONG 0x154 0
		WRITE_LONG 0x264 0
		WRITE_LONG 0x374 0
		WRITE_LONG 0x484 0
		WRITE_LONG 0x594 0
		WRITE_LONG 0x6A4 0
		WRITE_LONG 0x7B4 0
		WRITE_LONG 0x30BC xamu03
		WRITE_LONG 0x30C0 xamu03
	//}
//}

//{ Script & Dialogue Music
	COPY_EXISTING ~xanarzu.dlg~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		REPLACE_TEXTUALLY ~PlaySong(1023)~ ~PlaySong(%xaa22%)~
	END
//}

//{ Basilisk Figurine
	COPY ~%MOD_FOLDER%/rbg/bam/xaibas.bam~ ~override~

	COPY_EXISTING ~figspid.eff~ ~override/xabasfig.eff~
	WRITE_ASCII 0x30 ~basgrt01~ #8
	
	COPY_EXISTING ~misc3e.itm~ ~override/xabasfig.itm~
	WRITE_ASCII 0x3A ~xaibas~ #8
	WRITE_LONG 0x34 6000
	WRITE_LONG 0xC RESOLVE_STR_REF(@4152)
	WRITE_LONG 0x54 RESOLVE_STR_REF(@4153)
	WRITE_ASCII 0x58 ~xacbas~ #8
	WRITE_ASCII 0xEE ~xabasfig~ #8
	WRITE_ASCII 0x76 ~xaibas~ #8
//}

//{ Stores
	COPY ~%MOD_FOLDER%/rbg/sto/xamelkor.sto~ ~override~
	WRITE_LONG 0xc RESOLVE_STR_REF(@4158)
	
	COPY ~%MOD_FOLDER%/rbg/sto/xawvbar.sto~ ~override~
	WRITE_LONG 0xc RESOLVE_STR_REF(@4138)
	WRITE_ASCII 0x44 ~xarumor~ #8
//}