OUTER_SET sod_carryover = 1


//{ Archery Boost
	COPY ~%MOD_FOLDER%/sod/spl/xalcarch.spl~ ~override~
	SAY NAME1 @2002				 /* ~Corwin's Tutelage~*/
	SAY UNIDENTIFIED_DESC @2002	 /* ~Corwin's Tutelage~*/
	SAY DESC @2002 				 /* ~Corwin's Tutelage~*/
//}

//{ CRE
	COPY ~%MOD_FOLDER%/sod/cre/xalcspy.cre~ ~override~
	COPY_EXISTING ~xalcspy.cre~ ~override/xacorltr.cre~
	WRITE_LONG 0x08 RESOLVE_STR_REF(@2001)
	WRITE_LONG 0x0C RESOLVE_STR_REF(@2001)
	WRITE_ASCII 0x34 ~SCHAELS~ #8
	WRITE_ASCII 0x3C ~SCHAELS~ #8
	WRITE_ASCII 0x2CC ~XACORLTR~ #8
	WRITE_ASCII 0x248 ~XACORLTR~ #8
//}

//{ New Items
	COPY_EXISTING ~scrl3z.itm~  ~override/xaltrcor.itm~ 
	SAY NAME1 @2001
	SAY NAME2 @2001
	SAY UNIDENTIFIED_DESC @2007
	SAY DESC @2007
	
	COPY_EXISTING ~scrl3z.itm~  ~override/xaltrsch.itm~ 
	SAY NAME1 @2003
	SAY NAME2 @2003
	SAY UNIDENTIFIED_DESC @2006
	SAY DESC @2006
	
	COPY ~%MOD_FOLDER%/sod/bam/xaamulet.bam~ ~override~
	COPY ~%MOD_FOLDER%/sod/itm/xaamulet.itm~ ~override~
	SAY NAME1 @2005
	SAY NAME2 @2005
	SAY UNIDENTIFIED_DESC @2008
	SAY DESC @2008
	WRITE_LONG 0x9e RESOLVE_STR_REF(@2009)
	
	
	//{ Corwin's Amulet (SoD)
		COPY ~%MOD_FOLDER%/sod/itm/xaamul1.itm~ ~override~
		WRITE_LONG 0x08 RESOLVE_STR_REF(@2013)
		WRITE_LONG 0x0C RESOLVE_STR_REF(@2013)
		WRITE_LONG 0x50 RESOLVE_STR_REF(@2014)
		WRITE_LONG 0x54 RESOLVE_STR_REF(@2014)
		WRITE_LONG 0x9E RESOLVE_STR_REF(@2010)
	//}
//}

