IF
	True()
THEN
	RESPONSE #100
		
		CutSceneId("XACORWIN")
		Wait(1)
		DisplayStringHead("XACORWIN", @0)
		Wait(1)
		DisplayStringHead("XAROHMA", @1)
		ActionOverride("XAROHMA", MoveToPoint([228.344]))
		MoveToPoint([266.336])
		ActionOverride("XAAUDAM", MoveToPoint([438.249]))
		Wait(2)
		ActionOverride("XAROHMA", FaceObject("XACORWIN"))
		FaceObject("XAROHMA")
		ActionOverride("XAAUDAM", FaceObject("XACORWIN"))
		
		//Dialog J-67
		StartDialog("XACORWIJ", "XAROHMA")
		
END