IF
	Global("PCKeepOwner","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("PCKeepOwner", "GLOBAL", 2)
		Continue()
END

IF
	Global("soa_complete", "GLOBAL", 0)
THEN
	RESPONSE #100
		SetGlobal("soa_complete", "GLOBAL", 1)
		SaveGame(0)
		Continue()
END

IF 
	GlobalLT("XA_LC_BackToBG", "GLOBAL", 1)
THEN
	RESPONSE #100
		Wait(1)
		SetGlobal("XA_LC_BackToBG", "GLOBAL", 1)
		ActionOverride("XACORWIN", StartDialog("XACORWIJ", Player1))
END




