PRINT @850  /* ~Processing LCA Assistant...~ */

COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/assistant/baf~
COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/assistant/d~

ACTION_IF FILE_EXISTS ~BALDUR.BCS~ THEN BEGIN
	EXTEND_BOTTOM ~BALDUR.BCS~ ~%MOD_FOLDER%/assistant/baf/xalcasst.baf~
END

ACTION_IF FILE_EXISTS ~BDBALDUR.BCS~ THEN BEGIN
	EXTEND_BOTTOM ~BDBALDUR.BCS~ ~%MOD_FOLDER%/assistant/baf/xalcasst.baf~
END

ACTION_IF FILE_EXISTS ~BALDUR25.BCS~ THEN BEGIN
	EXTEND_BOTTOM ~BALDUR25.BCS~ ~%MOD_FOLDER%/assistant/baf/xalcasst.baf~
END

//{ bam
	COPY ~%MOD_FOLDER%/assistant/bam/xaassist.bam~ ~override~
//}

//{ cre
	COPY ~%MOD_FOLDER%/assistant/cre/xalcdbg.cre~ ~override~
	SAY NAME1 @851/* ~LCA Assistant~ */
	SAY NAME2 @851/* ~LCA Assistant~*/
//}
