[1235.875]
[1356.826]

IF
	Global("K#CleanAreaBG2","BD4300",0)  // Dragonspear Castle Basement
	GlobalGT("Chapter","GLOBAL",13)
THEN
	RESPONSE #100
		TriggerActivation("TransBD4100",TRUE)
		TriggerActivation("BD5200Entrance",TRUE)
		SoundActivate("SS_Soldier",FALSE)
		ActionOverride("BDAUN",DestroySelf())
		ActionOverride("BDDAZZO",DestroySelf())
		SetGlobal("K#CleanAreaBG2","BD4300",1)  // Dragonspear Castle Basement
		Continue()
END

IF
	Global("BD_DISCOVERED","BD4300",0)  // Dragonspear Castle Basement
	Global("chapter","global",10)
THEN
	RESPONSE #100
		SetGlobal("BD_DISCOVERED","BD4300",1)  // Dragonspear Castle Basement
		CreateCreatureImpassable("bdvoice",[700.920],SE)  // The Voice
		CreateCreature("bdhepher",[755.980],NW)  // Hephernaan
		CreateCreature("bdolvena",[765.1035],NW)  // Olvenaun
		CreateCreature("bdesseri",[825.995],NW)  // Esserin
		ActionOverride("bdhepher",ChangeAIScript("bd4300en",CLASS))
		CreateCreature("bddaeros",[635.1260],NE)  // Daeros
		ActionOverride("bddaeros",SaveObjectLocation("LOCALS","bd_default_loc",Myself))
		CreateCreature("bdgolsto",[1590.1000],SW)  // Stone Golem
		ActionOverride("bdgolsto",SetGlobal("bd_move","locals",2))
		ActionOverride("bdgolsto",ChangeAIScript("",OVERRIDE))
		ActionOverride("bdgolsto",ChangeAIScript("bd4300en",CLASS))
		ActionOverride("bdgolsto",ChangeAIScript("bdshout",RACE))
		CreateCreature("bdgolsto",[1720.1110],SW)  // Stone Golem
		ActionOverride("bdgolsto",SetGlobal("bd_move","locals",2))
		ActionOverride("bdgolsto",ChangeAIScript("",OVERRIDE))
		ActionOverride("bdgolsto",ChangeAIScript("bd4300en",CLASS))
		ActionOverride("bdgolsto",ChangeAIScript("bdshout",RACE))
		Continue()
END

IF
	GlobalGT("bd_explosives_plot","global",4)
	Global("BD_supplies_map_note","BD4300",0)  // Dragonspear Castle Basement
THEN
	RESPONSE #100
		AddMapNoteColor([314.1233],269141,RED)  // Crusade's Supplies
		AddMapNoteColor([1583.1606],269141,RED)  // Crusade's Supplies
		SetGlobal("BD_supplies_map_note","BD4300",1)  // Dragonspear Castle Basement
END

IF
	GlobalGT("bd_plot","global",379)
	Global("bd_remove_hephernaan","bd4300",0)  // Dragonspear Castle Basement
THEN
	RESPONSE #100
		SetGlobal("bd_remove_hephernaan","bd4300",1)  // Dragonspear Castle Basement
		ActionOverride("bdvoice",DestroySelf())
		ActionOverride("bdhepher",DestroySelf())
		ActionOverride("bdolvena",DestroySelf())
		ActionOverride("bdesseri",DestroySelf())
		Continue()
END

IF
	GlobalGT("bd_plot","global",399)
	GlobalLT("bd_plot","global",480)
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("bd_plot","global",480)
		Unlock("Door01")
		Lock("Door02")
		TriggerActivation("food_supplies",FALSE)
		TriggerActivation("water_supplies",FALSE)
		TriggerActivation("TransBD4100",TRUE)
		TriggerActivation("BD5200Entrance",FALSE)
		TriggerActivation("Infopoint16",TRUE)
		AddMapNoteColor([895.509],269142,RED)  // The Vault
		AddMapNoteColor([2059.712],264537,GREEN)  // Stairs Up
		RemoveMapNote([314.1233],269141)  // Crusade's Supplies
		RemoveMapNote([1583.1606],269141)  // Crusade's Supplies
		AddJournalEntry(265604,QUEST)  // The Siege of Dragonspear I must find Bence Duncan in Dragonspear Castle's basement. If the Shining Lady remains in Dragonspear Castle, she's pinned in the basement by Corporal Duncan and his forces. I shall go seek her, and a final end to this conflict, in the bowels of the castle.
		SetGlobal("bd_lift","bd4300",2)  // Dragonspear Castle Basement
		ApplySpellRES("bdremove",Player1)  // No such index
		CreateCreature("bdbence",[1160.770],SE)  // Bence Duncan
		CreateCreature("bdffsol1",[1130.700],SE)  // Flaming Fist Mercenary
		CreateCreature("bdffsol2",[1050.745],SE)  // Flaming Fist Mercenary
		CreateCreature("bdffmage",[1080.795],E)  // Flaming Fist Mage
		CreateCreature("bddaeros",[1445.1200],NE)  // Daeros
		ActionOverride("bddaeros",SaveObjectLocation("LOCALS","bd_default_loc",Myself))
		CreateCreature("bdcutid",[1.1],S)  // No such index
		CreateCreature("bdfist30",[2070.785],SW)  // Flaming Fist Mercenary
		CreateCreature("bdwtr36",[1875.985],NW)  // Waterdhavian Soldier
		CreateCreature("bdfist37",[1850.1020],W)  // Flaming Fist Mercenary
		CreateCreature("bdfist31",[1560.960],SE)  // Flaming Fist Healer
		CreateCreature("bdfistx3",[1510.980],S)  // Flaming Fist Sergeant
		CreateCreature("bdwtr31",[1470.960],SW)  // Waterdhavian Soldier
		Continue()
END

IF
	Global("bd_plot","global",480)
	Global("bd_corwin_not_right","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("corwin")  // Corwin
THEN
	RESPONSE #100
		ActionOverride("corwin",StartDialogueNoSet(Player1))
END

IF
	Global("bd_plot","global",490)
	Global("bd_delancie_talk","bd4300",0)  // Dragonspear Castle Basement
THEN
	RESPONSE #100
		SetGlobal("bd_plot","global",495)
		SetGlobal("bd_delancie_talk","bd4300",1)  // Dragonspear Castle Basement
		AddJournalEntry(266907,QUEST_DONE)  // The Siege of Dragonspear Caelar has escaped into the Nine Hells. Dragonspear Castle is secure, but Caelar is gone. She disappeared after Hephernaan into a portal to Avernus—some sort of plan she had has gone horribly wrong. I don't know what awaits me in Hell, but it can't be good.
		AddJournalEntry(259812,QUEST)  // The Siege of Dragonspear I must use the portal to enter Avernus. I have no choice but to venture into Avernus and find a way to seal the portal between planes.
		AddMapNoteColor([602.420],269143,SLATE)  // Portal to Avernus
		CreateCreature("bdbence",[1110.680],NW)  // Bence Duncan
		CreateCreature("bddelanc",[1080.700],NW)  // Torsin de Lancie
		CreateCreature("bdpatres",[1045.725],NW)  // Patrescus
		ActionOverride("bdbence",ReallyForceSpellRES("bdbump1",Myself))  // No such index
		ActionOverride("bddelanc",ReallyForceSpellRES("bdbump1",Myself))  // No such index
		ActionOverride("bdpatres",ReallyForceSpellRES("bdbump1",Myself))  // No such index
		SetGlobalTimer("bd_mdd1290d_imp_timer","bd4300",FOUR_MINUTES)  // Dragonspear Castle Basement
END

IF
	GlobalGT("bd_plot","global",580)
	GlobalLT("bd_plot","global",585)
	!PartyHasItem("bdkey02")  // Dragonspear Vault Key
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("bd_plot","global",586)
		RemoveMapNote([602.420],269143)  // Portal to Avernus
		RemoveMapNote([2059.712],264537)  // Stairs Up
		AddMapNoteColor([2059.712],264537,RED)  // Stairs Up
		GiveItemCreate("bdkey02",Player1,1,0,0)  // Dragonspear Vault Key
END

IF
	GlobalGT("bd_plot","global",580)
	GlobalLT("bd_plot","global",585)
	PartyHasItem("bdkey02")  // Dragonspear Vault Key
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("bd_plot","global",586)
		RemoveMapNote([602.420],269143)  // Portal to Avernus
		RemoveMapNote([2059.712],264537)  // Stairs Up
		AddMapNoteColor([2059.712],264537,RED)  // Stairs Up
END

IF
	CheckSpellState("BDWRETCH",SPECTACLES_QUEST)
	IsActive("BDWRETCH")
	!HasItemEquiped("bdmisc01",Player1)  // Spectacles of Spectacle
	!HasItemEquiped("bdmisc01",Player2)  // Spectacles of Spectacle
	!HasItemEquiped("bdmisc01",Player3)  // Spectacles of Spectacle
	!HasItemEquiped("bdmisc01",Player4)  // Spectacles of Spectacle
	!HasItemEquiped("bdmisc01",Player5)  // Spectacles of Spectacle
	!HasItemEquiped("bdmisc01",Player6)  // Spectacles of Spectacle
THEN
	RESPONSE #100
		Deactivate("BDWRETCH")
END

IF
	CheckSpellState("BDWRETCH",SPECTACLES_QUEST)
	!IsActive("BDWRETCH")
	OR(6)
		HasItemEquiped("bdmisc01",Player1)  // Spectacles of Spectacle
		HasItemEquiped("bdmisc01",Player2)  // Spectacles of Spectacle
		HasItemEquiped("bdmisc01",Player3)  // Spectacles of Spectacle
		HasItemEquiped("bdmisc01",Player4)  // Spectacles of Spectacle
		HasItemEquiped("bdmisc01",Player5)  // Spectacles of Spectacle
		HasItemEquiped("bdmisc01",Player6)  // Spectacles of Spectacle
THEN
	RESPONSE #100
		Activate("BDWRETCH")
END

IF
	GlobalLT("bd_plot","global",361)
	Global("bd_mephit_dead","bd4300",0)  // Dragonspear Castle Basement
	Dead("bdmephiw")  // Water Mephit
	IfValidForPartyDialog("mkhiin")  // M'Khiin
THEN
	RESPONSE #100
		SetGlobal("bd_mephit_dead","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mephit_dead_timer","bd4300",2)  // Dragonspear Castle Basement
		DisplayStringHead("mkhiin",250384)  // Poor thing. Never had a chance.
END

IF
	GlobalLT("bd_plot","global",361)
	Global("bd_mephit_dead","bd4300",1)  // Dragonspear Castle Basement
	Dead("bdmephiw")  // Water Mephit
	GlobalTimerExpired("bd_mephit_dead_timer","bd4300")  // Dragonspear Castle Basement
	IfValidForPartyDialog("Dynaheir")  // Dynaheir
THEN
	RESPONSE #100
		SetGlobal("bd_mephit_dead","bd4300",2)  // Dragonspear Castle Basement
		DisplayStringHead("Dynaheir",250385)  // No more a chance than it would have given us. Do not mourn this beast, goblin.
END

IF
	GlobalLT("bd_plot","global",361)
	GlobalLT("bd_mephit_dead","bd4300",2)  // Dragonspear Castle Basement
	Dead("bdmephiw")  // Water Mephit
	!GlobalTimerNotExpired("bd_mephit_dead_timer","bd4300")  // Dragonspear Castle Basement
THEN
	RESPONSE #100
		SetGlobal("bd_mephit_dead","bd4300",2)  // Dragonspear Castle Basement
END

IF
	Global("bd_corwin_romanceactive","global",2)
	Global("bd_CorwinRomance6","GLOBAL",0)
	Global("bd_plot","global",590)
	InParty("Corwin")  // Corwin
THEN
	RESPONSE #100
		SetGlobal("bd_CorwinRomance6","GLOBAL",1)
END

IF
	Global("bd_corwin_romanceactive","global",2)
	Global("bd_CorwinRomance6","GLOBAL",1)
	InParty("Corwin")  // Corwin
	IfValidForPartyDialog("Corwin")  // Corwin
	!ActuallyInCombat()
THEN
	RESPONSE #100
		ActionOverride("Corwin",StartDialogueNoSet(Player1))
END

IF
	Global("bd_neera_romanceactive","global",2)
	Global("bd_NeeraRomance6","GLOBAL",0)
	Global("bd_plot","global",590)
	InParty("Neera")  // Neera
THEN
	RESPONSE #100
		SetGlobal("bd_NeeraRomance6","GLOBAL",1)
END

IF
	Global("bd_neera_romanceactive","global",2)
	Global("bd_NeeraRomance6","GLOBAL",1)
	InParty("Neera")  // Neera
	IfValidForPartyDialog("Neera")  // Neera
	!ActuallyInCombat()
THEN
	RESPONSE #100
		ActionOverride("Neera",StartDialogueNoSet(Player1))
END

IF
	GlobalLT("bd_plot","global",350)
	Global("bd_glint_mdd982_ot","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("GLINT")  // Glint
THEN
	RESPONSE #100
		SetGlobal("bd_glint_mdd982_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_belben_delay","bd4300",ONE_ROUND)  // Dragonspear Castle Basement
		DisplayStringHead("GLINT",237783)  // So when do you figure things are going to fall apart? Can't be long now...
END

IF
	GlobalLT("bd_plot","global",350)
	Global("bd_glint_mdd982_ot","bd4300",0)  // Dragonspear Castle Basement
	!IfValidForPartyDialog("GLINT")  // Glint
THEN
	RESPONSE #100
		SetGlobal("bd_glint_mdd982_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_belben_delay","bd4300",1)  // Dragonspear Castle Basement
END

IF
	GlobalLT("bd_plot","global",350)
	OR(2)
		Dead("bdbelben")  // Belben
		!Allegiance("bdbelben",NEUTRAL)  // Belben
THEN
	RESPONSE #100
		SetGlobal("bd_plot","global",350)
END

IF
	GlobalLT("bd_plot","global",360)
	GlobalGT("bd_poison_dsc_supplies","global",0)
THEN
	RESPONSE #100
		SetGlobal("bd_plot","global",360)
END

IF
	!GlobalLT("bd_plot","global",360)
	Global("chapter","global",10)
	Global("bd_lift","bd4300",0)  // Dragonspear Castle Basement
THEN
	RESPONSE #100
		SetGlobal("bd_lift","bd4300",1)  // Dragonspear Castle Basement
		TriggerActivation("BD5200Entrance",FALSE)
		CreateCreature("bdcruz01",[1010.1900],NW)  // Crusader Sergeant
		CreateCreature("bdcruz02",[1030.1945],NW)  // Crusader
		CreateCreature("bdcruz03",[1120.1950],NW)  // Crusader
		Continue()
END

IF
	!GlobalLT("bd_plot","global",360)
	Global("chapter","global",10)
	Global("bd_lift","bd4300",0)  // Dragonspear Castle Basement
	DifficultyGT(NORMAL)
THEN
	RESPONSE #100
		SetGlobal("bd_lift","bd4300",1)  // Dragonspear Castle Basement
		CreateCreature("bdcruz02",[1050.1900],NW)  // Crusader
		CreateCreature("bdcruz03",[1140.1910],NW)  // Crusader
		CreateCreature("bdcrus92",[1050.1900],NW)  // Crusader Mage
		ActionOverride("bdcrus92",ChangeAIScript("BDCRUZ01",OVERRIDE))
		ActionOverride("bdcrus92",ChangeAIScript("BD4300EN",CLASS))
END

IF
	Global("bd_lift","bd4300",1)  // Dragonspear Castle Basement
	Global("chapter","global",10)
	OR(2)
		NumDeadGT("bdcruz02",1)  // Crusader
		GlobalGT("bd_plot","global",364)
	OR(2)
		Dead("bdcruz01")  // Crusader Sergeant
		GlobalGT("bd_plot","global",364)
THEN
	RESPONSE #100
		SetGlobal("bd_lift","bd4300",2)  // Dragonspear Castle Basement
		TriggerActivation("BD5200Entrance",TRUE)
		Continue()
END

IF
	Global("bd_mdd905z_wave","bd4300",0)  // Dragonspear Castle Basement
	Global("chapter","global",10)
	!GlobalLT("bd_plot","global",365)
THEN
	RESPONSE #100
		SetGlobal("bd_mdd905z_wave","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mdd905z_wave_timer","bd4300",TEN_ROUNDS)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd905z_wave","bd4300",1)  // Dragonspear Castle Basement
	Global("chapter","global",10)
	DifficultyGT(NORMAL)
	!GlobalTimerNotExpired("bd_mdd905z_second_wave_timer","bd4300")  // Dragonspear Castle Basement
	OR(2)
		GlobalTimerExpired("bd_mdd905z_wave_timer","bd4300")  // Dragonspear Castle Basement
		!GlobalLT("bd_crus_reinf_killed","bd4300",10)  // Dragonspear Castle Basement
	Switch("bd_mdd905z_second_wave","bd4300")  // Dragonspear Castle Basement
THEN
	RESPONSE #0
		SetGlobalTimer("bd_mdd905z_second_wave_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		CreateVisualEffect("spdimndr",[1485.1155])
		Wait(3)
		CreateCreature("bdcru109",[1485.1155],SW)  // Crusader Mage
		ActionOverride("bdcru109",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("bdcrus91",[1450.1120],SW)  // Crusader
		ActionOverride("bdcrus91",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("BDCRUX31",[1485.1120],SW)  // Crusader Sergeant
		ActionOverride("BDCRUX31",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("bdcrus99",[1520.1120],SW)  // Crusader
		ActionOverride("bdcrus99",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("bdcrus90",[1485.1185],SW)  // Crusader Archer
		ActionOverride("bdcrus90",ChangeAIScript("bd4300ex",OVERRIDE))
		IncrementGlobal("bd_mdd905z_second_wave","bd4300",1)  // Dragonspear Castle Basement
	RESPONSE #1
		SetGlobalTimer("bd_mdd905z_second_wave_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		CreateVisualEffect("spdimndr",[1415.1020])
		Wait(3)
		CreateCreature("bdcru122",[1415.1020],SW)  // Crusader Mage
		ActionOverride("bdcru122",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("BDCRUS22",[1380.985],SW)  // Crusader
		ActionOverride("BDCRUS22",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("bdcru106",[1415.985],SW)  // Crusader Cleric
		ActionOverride("bdcru106",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("BDCRUS34",[1450.985],SW)  // Crusader
		ActionOverride("BDCRUS34",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("bdcrus93",[1415.950],SW)  // Crusader Archer
		ActionOverride("bdcrus93",ChangeAIScript("bd4300ex",OVERRIDE))
		IncrementGlobal("bd_mdd905z_second_wave","bd4300",1)  // Dragonspear Castle Basement
	RESPONSE #2
		SetGlobalTimer("bd_mdd905z_second_wave_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		CreateVisualEffect("spdimndr",[1570.1080])
		Wait(3)
		CreateCreature("bdcrus92",[1570.1080],SW)  // Crusader Mage
		ActionOverride("bdcrus92",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("bdcrus94",[1535.1055],SW)  // Crusader
		ActionOverride("bdcrus94",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("BDCRUX32",[1570.1055],SW)  // Crusader Sergeant
		ActionOverride("BDCRUX32",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("BDCRUS33",[1605.1055],SW)  // Crusader
		ActionOverride("BDCRUS33",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("bdcrus97",[1570.1020],SW)  // Crusader Archer
		ActionOverride("bdcrus97",ChangeAIScript("bd4300ex",OVERRIDE))
		IncrementGlobal("bd_mdd905z_second_wave","bd4300",1)  // Dragonspear Castle Basement
	RESPONSE #3
		SetGlobalTimer("bd_mdd905z_second_wave_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		CreateVisualEffect("spdimndr",[1640.1175])
		Wait(3)
		CreateCreature("bdcru123",[1640.1175],SW)  // Crusader Mage
		ActionOverride("bdcru123",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("BDCRUS37",[1595.1140],SW)  // Crusader
		ActionOverride("BDCRUS37",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("bdcru107",[1640.1140],SW)  // Crusader Cleric
		ActionOverride("bdcru107",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("BDCRUS24",[1685.1140],SW)  // Crusader
		ActionOverride("BDCRUS24",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("bdcrus96",[1640.1115],SW)  // Crusader Archer
		ActionOverride("bdcrus96",ChangeAIScript("bd4300ex",OVERRIDE))
		IncrementGlobal("bd_mdd905z_second_wave","bd4300",1)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd905z_wave","bd4300",2)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mdd905z_wave_timer","bd4300",FIVE_ROUNDS)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd905z_wave","bd4300",2)  // Dragonspear Castle Basement
	Global("chapter","global",10)
	Difficulty(HARDEST)
	OR(2)
		GlobalTimerExpired("bd_mdd905z_wave_timer","bd4300")  // Dragonspear Castle Basement
		!GlobalLT("bd_crus_reinf2_killed","bd4300",15)  // Dragonspear Castle Basement
THEN
	RESPONSE #100
		SetGlobal("bd_mdd905z_wave","bd4300",3)  // Dragonspear Castle Basement
		CreateVisualEffect("DDOORH",[740.1550])
		CreateVisualEffect("DDOORH",[855.1615])
		CreateVisualEffect("DDOORH",[745.1455])
		CreateVisualEffect("DDOORH",[855.1515])
		CreateVisualEffect("DDOORH",[970.1575])
		CreateVisualEffect("DDOORH",[855.1420])
		CreateVisualEffect("DDOORH",[960.1485])
		SmallWait(6)
		CreateCreature("bdinsa01",[740.1550],SW)  // Bengahd Claybelly
		ActionOverride("bdinsa01",SaveObjectLocation("LOCALS","bd_default_loc",Myself))
		CreateCreature("bdinsa02",[855.1615],SW)  // Lynos the Righteous
		ActionOverride("bdinsa02",SaveObjectLocation("LOCALS","bd_default_loc",Myself))
		CreateCreature("bdinsa03",[745.1455],SW)  // Dalia
		ActionOverride("bdinsa03",SaveObjectLocation("LOCALS","bd_default_loc",Myself))
		CreateCreature("bdinsa04",[855.1515],SW)  // Raizarn
		ActionOverride("bdinsa04",SaveObjectLocation("LOCALS","bd_default_loc",Myself))
		CreateCreature("bdinsa05",[970.1575],SW)  // Akame
		ActionOverride("bdinsa05",SaveObjectLocation("LOCALS","bd_default_loc",Myself))
		CreateCreature("bdinsa06",[855.1420],SW)  // Four Winds
		ActionOverride("bdinsa06",SaveObjectLocation("LOCALS","bd_default_loc",Myself))
		CreateCreature("bdinsa07",[960.1485],SW)  // Therren
		ActionOverride("bdinsa07",SaveObjectLocation("LOCALS","bd_default_loc",Myself))
		CreateVisualEffect("spdimndr",[1640.1175])
		Wait(3)
		CreateCreature("BDCRUE31",[1640.1175],SW)  // Crusader Elite
		ActionOverride("BDCRUE31",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("BDCRUE30",[1595.1140],SW)  // Crusader Elite
		ActionOverride("BDCRUE30",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("BDCRUE32",[1640.1140],SW)  // Crusader Elite
		ActionOverride("BDCRUE32",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("BDCRUE33",[1685.1140],SW)  // Crusader Elite
		ActionOverride("BDCRUE33",ChangeAIScript("bd4300ex",OVERRIDE))
		CreateCreature("BDCRUE34",[1640.1115],SW)  // Crusader Elite
		ActionOverride("BDCRUE34",ChangeAIScript("bd4300ex",OVERRIDE))
END

IF
	GlobalGT("bd_plot","global",349)
	GlobalLT("bd_plot","global",370)
	HPPercentLT("bdhepher",50)  // Hephernaan
	InMyArea(Player1)
THEN
	RESPONSE #100
		ApplySpellRES("bdcutspy","bdhepher")  // No such index
		ActionOverride("bdhepher",StartDialogueNoSet(Player1))
END

IF
	GlobalGT("bd_plot","global",490)
	GlobalLT("bd_plot","global",500)
	GlobalTimerExpired("bd_mdd1290d_imp_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_mdd1290d_imp","bd4300",0)  // Dragonspear Castle Basement
	!ActuallyInCombat()
	InMyArea(Player1)
	Global("BD_PORTAL_WAVE","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("BD_PORTAL_WAVE","MYAREA",1)
		SetGlobal("bd_mdd1290d_imp","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mdd1290d_imp_timer","bd4300",THREE_ROUNDS)  // Dragonspear Castle Basement
		CreateCreatureEffect("BDIMP","SPFLESHS",[615.420],E)  // Imp
		SmallWait(5)
		CreateCreatureEffect("bdlemure","SPFLESHS",[490.470],NW)  // Lemure
		SmallWait(5)
		CreateCreatureEffect("bdabibla","SPFLESHS",[630.300],SW)  // Black Abishai
END

IF
	GlobalGT("bd_plot","global",490)
	GlobalLT("bd_plot","global",500)
	GlobalTimerExpired("bd_mdd1290d_imp_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_mdd1290d_imp","bd4300",0)  // Dragonspear Castle Basement
	!ActuallyInCombat()
	InMyArea(Player1)
	Global("BD_PORTAL_WAVE","MYAREA",1)
THEN
	RESPONSE #100
		SetGlobal("BD_PORTAL_WAVE","MYAREA",2)
		SetGlobal("bd_mdd1290d_imp","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mdd1290d_imp_timer","bd4300",THREE_ROUNDS)  // Dragonspear Castle Basement
		CreateCreatureEffect("BDIMP","SPFLESHS",[615.420],E)  // Imp
		SmallWait(5)
		CreateCreatureEffect("bdabigre","SPFLESHS",[490.470],NW)  // Green Abishai
		SmallWait(5)
		CreateCreatureEffect("bdabired","SPFLESHS",[630.300],SW)  // Red Abishai
		SmallWait(5)
		CreateCreatureEffect("bdabibla","SPFLESHS",[745.470],NW)  // Black Abishai
END

IF
	GlobalGT("bd_plot","global",490)
	GlobalLT("bd_plot","global",500)
	GlobalTimerExpired("bd_mdd1290d_imp_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_mdd1290d_imp","bd4300",0)  // Dragonspear Castle Basement
	!ActuallyInCombat()
	InMyArea(Player1)
	Global("BD_PORTAL_WAVE","MYAREA",2)
THEN
	RESPONSE #100
		SetGlobal("bd_mdd1290d_imp","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mdd1290d_imp_timer","bd4300",THREE_ROUNDS)  // Dragonspear Castle Basement
		CreateCreatureEffect("BDIMP","SPFLESHS",[615.420],E)  // Imp
		SmallWait(5)
		CreateCreatureEffect("BDHAMATU","SPFLESHS",[490.470],NW)  // Hamatula
		SmallWait(5)
		CreateCreatureEffect("bdabired","SPFLESHS",[630.300],SW)  // Red Abishai
		SmallWait(5)
		CreateCreatureEffect("BDHAMATU","SPFLESHS",[745.470],NW)  // Hamatula
END

IF
	Global("bd_mdd1290d_imp","bd4300",1)  // Dragonspear Castle Basement
	Switch("bd_mdd1290d_imp_ot","bd4300")  // Dragonspear Castle Basement
THEN
	RESPONSE #0
		DisplayStringHead("BDIMP",244221)  // Hahah! Free, free! Free at last!
		IncrementGlobal("bd_mdd1290d_imp_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_imp","bd4300",2)  // Dragonspear Castle Basement
	RESPONSE #1
		DisplayStringHead("BDIMP",244222)  // Avernus sends its regards!
		IncrementGlobal("bd_mdd1290d_imp_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_imp","bd4300",2)  // Dragonspear Castle Basement
	RESPONSE #2
		DisplayStringHead("BDIMP",244223)  // You will be swallowed by the pit! Avernus will take you all!
		IncrementGlobal("bd_mdd1290d_imp_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_imp","bd4300",2)  // Dragonspear Castle Basement
	RESPONSE #3
		DisplayStringHead("BDIMP",244224)  // Rip and rend and tear and claw and rip and rip, rip, rip!
		IncrementGlobal("bd_mdd1290d_imp_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_imp","bd4300",2)  // Dragonspear Castle Basement
	RESPONSE #4
		DisplayStringHead("BDIMP",244225)  // Your time is over! The Prime will fall to Avernus!
		IncrementGlobal("bd_mdd1290d_imp_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_imp","bd4300",2)  // Dragonspear Castle Basement
	RESPONSE #5
		DisplayStringHead("BDIMP",244226)  // I'm gonna kill you and eat you, not necessarily in that order.
		IncrementGlobal("bd_mdd1290d_imp_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_imp","bd4300",2)  // Dragonspear Castle Basement
	RESPONSE #6
		DisplayStringHead("BDIMP",244227)  // You are ours now! Die!
		IncrementGlobal("bd_mdd1290d_imp_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_imp","bd4300",2)  // Dragonspear Castle Basement
	RESPONSE #7
		DisplayStringHead("BDIMP",244228)  // I'll taste your entrails, pigmortals!
		IncrementGlobal("bd_mdd1290d_imp_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_imp","bd4300",2)  // Dragonspear Castle Basement
	RESPONSE #8
		DisplayStringHead("BDIMP",244229)  // Our master will bathe in your blood!
		SetGlobal("bd_mdd1290d_imp_ot","bd4300",0)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_imp","bd4300",2)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_imp","bd4300",2)  // Dragonspear Castle Basement
	GlobalGT("bd_plot","global",490)
	GlobalLT("bd_plot","global",500)
	!ActuallyInCombat()
	Global("bd_mdd1290d_ot","bd4300",0)  // Dragonspear Castle Basement
THEN
	RESPONSE #100
		SetGlobal("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_voghiln","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("VOGHILN")  // Voghiln
THEN
	RESPONSE #100
		DisplayStringHead("VOGHILN",244230)  // Voghiln is reminded of that tenday he went without a drink. Most unpleasant.
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_voghiln","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_rasaad","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("RASAAD")  // Rasaad
THEN
	RESPONSE #100
		DisplayStringHead("RASAAD",244231)  // We fight an endless army in an enclosed space, <CHARNAME>. It is only a matter of time before we are overwhelmed.
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_rasaad","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_viconia","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("VICONIA")  // Viconia
THEN
	RESPONSE #100
		DisplayStringHead("VICONIA",244232)  // We can't fight off these devils forever. What would you have us do, <CHARNAME>?
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_viconia","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_jaheira","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("JAHEIRA")  // Jaheira
THEN
	RESPONSE #100
		DisplayStringHead("JAHEIRA",244233)  // These attacks are just the beginning. We can't just stand here—we must act, or we will be slain.
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_jaheira","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_khalid","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("KHALID")  // Khalid
THEN
	RESPONSE #100
		DisplayStringHead("KHALID",244234)  // We c-can't get through the vault door. Our op-options appear to be limited.
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_khalid","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_edwin","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("EDWIN")  // Edwin
THEN
	RESPONSE #100
		DisplayStringHead("EDWIN",244235)  // Edwin Odesseiron did not come all this way just to be killed by some infernal imp in a subterranean vault. Fix this, immediately, I command it!
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_edwin","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_minsc","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("MINSC")  // Minsc
THEN
	RESPONSE #100
		DisplayStringHead("MINSC",244236)  // Devils, devils everywhere! But especially the floor, when Minsc is done with them!
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_minsc","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_mkhiin","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("MKHIIN")  // M'Khiin
THEN
	RESPONSE #100
		DisplayStringHead("MKHIIN",244237)  // Can we do something other than die stupid here?
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_mkhiin","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_glint","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("GLINT")  // Glint
THEN
	RESPONSE #100
		DisplayStringHead("GLINT",244238)  // Look, there's a way out of this vault. It's vomiting devils at the moment, but I don't see any other options for getting out of this. Do you?
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_glint","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_dorn","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("DORN")  // Dorn
THEN
	RESPONSE #100
		DisplayStringHead("DORN",244239)  // More! Give me every devil you've got, you gaping hellhole! They shall all fall before me!
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_dorn","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_neera","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("NEERA")  // Neera
THEN
	RESPONSE #100
		DisplayStringHead("NEERA",244240)  // I'd really like to go someplace else.
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_neera","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_safana","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("SAFANA")  // Safana
THEN
	RESPONSE #100
		DisplayStringHead("SAFANA",244241)  // Well, this is no fun.
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_safana","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_dynaheir","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("DYNAHEIR")  // Dynaheir
THEN
	RESPONSE #100
		DisplayStringHead("DYNAHEIR",244242)  // This is another fine mess thou hast gotten us into.
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_dynaheir","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot_baeloth","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("BAELOTH")  // Baeloth
THEN
	RESPONSE #100
		DisplayStringHead("BAELOTH",244243)  // How do you contend we correct this catastrophe, <CHARNAME>?
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot_baeloth","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_ot","bd4300",1)  // Dragonspear Castle Basement
THEN
	RESPONSE #100
		SetGlobal("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
END

IF
	Global("bd_mdd1290d_imp","bd4300",2)  // Dragonspear Castle Basement
	Global("bd_mdd1290d_ot","bd4300",2)  // Dragonspear Castle Basement
THEN
	RESPONSE #100
		SetGlobal("bd_mdd1290d_imp","bd4300",0)  // Dragonspear Castle Basement
		SetGlobal("bd_mdd1290d_ot","bd4300",0)  // Dragonspear Castle Basement
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Corwin","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("CORWIN")  // Corwin
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Corwin","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("CORWIN",239327)  // It's done. Thank the gods.
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Voghil","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("VOGHILN")  // Voghiln
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",3)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Voghil","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("VOGHILN",239328)  // The portal is closed. Voghiln needs a drink.
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Viconi","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("VICONIA")  // Viconia
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",4)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Viconi","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("VICONIA",239329)  // Shar smiles upon you, <CHARNAME>. I don't know why.
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Rasaad","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("RASAAD")  // Rasaad
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",4)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Rasaad","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("RASAAD",239330)  // The portal is closed once again. Thank Selûne.
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Edwin","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("EDWIN")  // Edwin
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",ONE_MINUTE)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Edwin","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("EDWIN",239331)  // Thus ends another chapter in the great tale of Edwin Odesseiron.
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Minsc","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("MINSC")  // Minsc
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Minsc","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("MINSC",239332)  // We are home, Boo!
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Dynahe","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("DYNAHEIR")  // Dynaheir
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",3)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Dynahe","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("DYNAHEIR",239333)  // The rift 'twixt the worlds is closed.
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Dorn","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("DORN")  // Dorn
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",7)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Dorn","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("DORN",239334)  // The portal is closed. Let's get that vault door open. I would speak with Torsin de Lancie about his decision to lock me in here with the hordes of the Hells.
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Neera","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("NEERA")  // Neera
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",2)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Neera","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("NEERA",239335)  // Nowhere to go but up. 
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Safana","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("SAFANA")  // Safana
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",ONE_ROUND)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Safana","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("SAFANA",239336)  // It's a sad state of affairs that a dreary vault has as much appeal as this one now does.
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Glint","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("GLINT")  // Glint
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",ONE_ROUND)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Glint","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("GLINT",239337)  // I went to Avernus and came back. I really did. And nobody who wasn't here will ever believe it...
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Baelot","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("BAELOTH")  // Baeloth
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",ONE_MINUTE)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Baelot","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("BAELOTH",239338)  // Eh. Our Avernal victory won't mean very much till we vacate this vile vault.
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_MKhiin","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("MKHIIN")  // M'Khiin
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",3)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_MKhiin","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("MKHIIN",239339)  // Hellhole's closed. That's good. Still trapped, though. That's not so good.
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Jaheir","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("JAHEIRA")  // Jaheira
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",ONE_MINUTE)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Jaheir","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("JAHEIRA",239340)  // The rift between the planes is healed. Avernus's threat to Toril is ended.
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_Khalid","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("KHALID")  // Khalid
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",4)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_Khalid","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("KHALID",239341)  // It is d-done. Avernus will threaten us no more.
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_darnas","bd4300",0)  // Dragonspear Castle Basement
	InMyArea("bddarnas")  // Darnas
	!Dead("bddarnas")  // Darnas
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",7)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_darnas","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("bddarnas",239343)  // We would not have survived Avernus but for you and your friend. I owe you a debt I shall never be able to repay. 
END

IF
	Global("bd_plot","global",586)
	!GlobalTimerNotExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot2_aun","bd4300",0)  // Dragonspear Castle Basement
	InMyArea("bdaun")  // Aun Argent
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd1341a_ot_timer","bd4300",7)  // Dragonspear Castle Basement
		SetGlobal("bd_ot2_aun","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("bdaun",267488)  // The gate is sealed and Caelar... she has done what she must. It's strange to be in the world again. I must put my life back together.
END

IF
	Global("bd_plot","global",586)
	GlobalTimerExpired("bd_mdd1341a_ot_timer","bd4300")  // Dragonspear Castle Basement
THEN
	RESPONSE #100
		SetGlobal("bd_plot","global",587)
END

IF
	Global("bd_plot","global",370)
	!GlobalTimerNotExpired("bd_mdd905a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot_Khalid","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("KHALID")  // Khalid
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd905a_ot_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		SetGlobal("bd_ot_Khalid","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("KHALID",237856)  // It'd probab-probably b-be wise for us to, to get out of here. N-n-now. 
END

IF
	Global("bd_plot","global",370)
	!GlobalTimerNotExpired("bd_mdd905a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot_Edwin","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("EDWIN")  // Edwin
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd905a_ot_timer","bd4300",ONE_MINUTE)  // Dragonspear Castle Basement
		SetGlobal("bd_ot_Edwin","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("EDWIN",237857)  // Do you value your life, <CHARNAME>? If not, you should at least value mine, and ensure it continues by fleeing this place immediately.
END

IF
	Global("bd_plot","global",370)
	!GlobalTimerNotExpired("bd_mdd905a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot_Edwin","bd4300",1)  // Dragonspear Castle Basement
	IfValidForPartyDialog("EDWIN")  // Edwin
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd905a_ot_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		SetGlobal("bd_ot_Edwin","bd4300",2)  // Dragonspear Castle Basement
		DisplayStringHead("EDWIN",237858)  // (A coward? Odesseiron is no coward! By flee, I simply mean we should conduct a strategic retreat.) 
END

IF
	Global("bd_plot","global",370)
	!GlobalTimerNotExpired("bd_mdd905a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot_Glint","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("GLINT")  // Glint
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd905a_ot_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		SetGlobal("bd_ot_Glint","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("GLINT",237859)  // Hey, uh, are you sure we shouldn't be, how shall I put this, GETTING THE HELLS OUT OF HERE now?
END

IF
	Global("bd_plot","global",370)
	!GlobalTimerNotExpired("bd_mdd905a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot_Dynahe","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("DYNAHEIR")  // Dynaheir
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd905a_ot_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		SetGlobal("bd_ot_Dynahe","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("DYNAHEIR",237860)  // Dost thou wish us all dead, <CHARNAME>? Nothing else can come of our remaining here.
END

IF
	Global("bd_plot","global",370)
	!GlobalTimerNotExpired("bd_mdd905a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot_Dorn","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("DORN")  // Dorn
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd905a_ot_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		SetGlobal("bd_ot_Dorn","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("DORN",237861)  // First blood is ours. We should be satisfied with that for now. Let us take our leave of this place.
END

IF
	Global("bd_plot","global",370)
	!GlobalTimerNotExpired("bd_mdd905a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot_Safana","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("SAFANA")  // Safana
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd905a_ot_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		SetGlobal("bd_ot_Safana","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("SAFANA",237862)  // I don't know about you, but I've had quite enough of this dreary place. Can we go now, please?
END

IF
	Global("bd_plot","global",370)
	!GlobalTimerNotExpired("bd_mdd905a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot_Rasaad","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("RASAAD")  // Rasaad
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd905a_ot_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		SetGlobal("bd_ot_Rasaad","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("RASAAD",237863)  // If we remain here much longer, we are certain to be overwhelmed.
END

IF
	Global("bd_plot","global",370)
	!GlobalTimerNotExpired("bd_mdd905a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot_Baelot","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("BAELOTH")  // Baeloth
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd905a_ot_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		SetGlobal("bd_ot_Baelot","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("BAELOTH",237864)  // Don't be brash, <CHARNAME>. Believe Baeloth Barrityl, 'tis better to bolt than buy the big one blundering about being bold.
END

IF
	Global("bd_plot","global",370)
	!GlobalTimerNotExpired("bd_mdd905a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot_Minsc","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("MINSC")  // Minsc
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd905a_ot_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		SetGlobal("bd_ot_Minsc","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("MINSC",237865)  // Boo says discretion should be our watchword. LISTEN TO BOO, <CHARNAME>! BE DISCREET!
END

IF
	Global("bd_plot","global",370)
	!GlobalTimerNotExpired("bd_mdd905a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot_MKhiin","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("MKHIIN")  // M'Khiin
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd905a_ot_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		SetGlobal("bd_ot_MKhiin","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("MKHIIN",237866)  // We should leave. Soon. Soon like now.
END

IF
	Global("bd_plot","global",370)
	!GlobalTimerNotExpired("bd_mdd905a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot_Voghil","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("VOGHILN")  // Voghiln
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd905a_ot_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		SetGlobal("bd_ot_Voghil","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("VOGHILN",237867)  // Old Voghiln has had his fill of the crusade. Time to be going, ja?
END

IF
	Global("bd_plot","global",370)
	!GlobalTimerNotExpired("bd_mdd905a_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_ot_Viconi","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("VICONIA")  // Viconia
THEN
	RESPONSE #100
		SetGlobalTimer("bd_mdd905a_ot_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		SetGlobal("bd_ot_Viconi","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("VICONIA",237868)  // If I wanted to die horribly beneath the earth, I'd never have left the Underdark. Let's begone from here.
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Safana")  // Safana
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",4)  // Dragonspear Castle Basement
		DisplayStringHead("Safana",260152)  // What a perfectly horrible little man. Killing him was a kindness.
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Jaheira")  // Jaheira
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",8)  // Dragonspear Castle Basement
		DisplayStringHead("Jaheira",260153)  // We might have gotten some usable information from that man. It would do us no harm to consider alternatives to mindless slaughter on occasion...
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Voghiln")  // Voghiln
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",3)  // Dragonspear Castle Basement
		DisplayStringHead("Voghiln",260154)  // Another crusader eats floor, courtesy of the Luskan Lion, ho ho!
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("MKhiin")  // M'Khiin
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",3)  // Dragonspear Castle Basement
		DisplayStringHead("MKhiin",260155)  // That one stank of nasty. Glad he's dead.
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Dorn")  // Dorn
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",2)  // Dragonspear Castle Basement
		DisplayStringHead("Dorn",260156)  // Would that all crusaders fell so easily.
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Minsc")  // Minsc
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",ONE_ROUND)  // Dragonspear Castle Basement
		DisplayStringHead("Minsc",260157)  // And that is why the wise man talks to heavily armed strangers. Attacking them, usually it does not end so well.
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Edwin")  // Edwin
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",ONE_MINUTE)  // Dragonspear Castle Basement
		DisplayStringHead("Edwin",260158)  // Hah! You luminous chimps don't squeal so loudly now, do you? (Nor so loudly as your mistress will.)
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Glint")  // Glint
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",2)  // Dragonspear Castle Basement
		DisplayStringHead("Glint",260159)  // I've had worse welcomes in my life.
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Viconia")  // Viconia
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",4)  // Dragonspear Castle Basement
		DisplayStringHead("Viconia",260160)  // Welcome me with violence, I'll bid you farewell with the same.
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Rasaad")  // Rasaad
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",ONE_MINUTE)  // Dragonspear Castle Basement
		DisplayStringHead("Rasaad",260161)  // I sometimes think death follows you, <CHARNAME>. How else to explain the carnage left in your wake?
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Khalid")  // Khalid
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",ONE_ROUND)  // Dragonspear Castle Basement
		DisplayStringHead("Khalid",260162)  // That was an un-unfortunate but not wholly unex-expected episode. How m-many more must die in C-caelar's name?
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Dynaheir")  // Dynaheir
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",ONE_MINUTE)  // Dragonspear Castle Basement
		DisplayStringHead("Dynaheir",260163)  // It would seem Dragonspear Castle is just as hospitable as its reputation suggests.
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Baeloth")  // Baeloth
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",ONE_ROUND)  // Dragonspear Castle Basement
		DisplayStringHead("Baeloth",260164)  // Classic crusade conduct courtesy of Caelar's cretinous converts, complete with the now-customary consequences.
END

IF
	Global("bd_MDD892a_ot","bd4300",0)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Neera")  // Neera
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_MDD892a_ot_timer","bd4300",4)  // Dragonspear Castle Basement
		DisplayStringHead("Neera",260165)  // Is anyone else getting sick of fighting for their life? I'm getting sick of it.
END

IF
	GlobalLT("bd_MDD892a_ot","bd4300",2)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	IfValidForPartyDialog("Corwin")  // Corwin
	!GlobalTimerNotExpired("bd_MDD892a_ot_timer","bd4300")  // Dragonspear Castle Basement
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",2)  // Dragonspear Castle Basement
		DisplayStringHead("Corwin",260166)  // Let's go. We need to find out what we can about Caelar and Hephernaan before every crusader in Dragonspear is breathing down our necks.
END

IF
	GlobalLT("bd_MDD892a_ot","bd4300",2)  // Dragonspear Castle Basement
	Global("bd_poison_dsc_supplies","global",0)
	Dead("bdbelben")  // Belben
	CombatCounter(0)
	!IfValidForPartyDialog("Corwin")  // Corwin
THEN
	RESPONSE #100
		SetGlobal("bd_MDD892a_ot","bd4300",2)  // Dragonspear Castle Basement
END

IF
	!GlobalLT("bd_plot","global",370)
	!Dead("CRUSADERSERGEANT")
	TriggerOverride("CRUSADERSERGEANT",See([PC]))
	!GlobalTimerNotExpired("bd_mdd905z_ot_timer","bd4300")  // Dragonspear Castle Basement
	!GlobalTimerNotExpired("bd_mdd905z_ot_sarge_timer","bd4300")  // Dragonspear Castle Basement
	Switch("bd_mdd905z_sarge_ot","bd4300")  // Dragonspear Castle Basement
THEN
	RESPONSE #0
		IncrementGlobal("bd_mdd905z_sarge_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mdd905z_ot_timer","bd4300",9)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mdd905z_ot_sarge_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		DisplayStringHead("CRUSADERSERGEANT",269652)  // Protect the lift! No one goes up or down!
	RESPONSE #1
		IncrementGlobal("bd_mdd905z_sarge_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mdd905z_ot_timer","bd4300",9)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mdd905z_ot_sarge_timer","bd4300",THREE_MINUTES)  // Dragonspear Castle Basement
		DisplayStringHead("CRUSADERSERGEANT",269653)  // Belben! BELBEN! Lock down the lift, quickly!
	RESPONSE #2
		IncrementGlobal("bd_mdd905z_sarge_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mdd905z_ot_timer","bd4300",9)  // Dragonspear Castle Basement
		DisplayStringHead("CRUSADERSERGEANT",256785)  // Secure the lift! They mustn't get into the Warrens!
END

IF
	!GlobalLT("bd_plot","global",370)
	!Dead("CRUSADERELITE1")
	TriggerOverride("CRUSADERELITE1",See([PC]))
	!GlobalTimerNotExpired("bd_mdd905z_ot_timer","bd4300")  // Dragonspear Castle Basement
	Global("bd_mdd905z_ot","bd4300",0)  // Dragonspear Castle Basement
THEN
	RESPONSE #100
		SetGlobal("bd_mdd905z_ot","bd4300",1)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mdd905z_ot_timer","bd4300",9)  // Dragonspear Castle Basement
		DisplayStringHead("CRUSADERELITE1",269651)  // Surrender, intruders! Surrender and know the Shining Lady's mercy!
END

IF
	!GlobalLT("bd_plot","global",370)
	!Dead("CRUSADERELITE2")
	TriggerOverride("CRUSADERELITE2",See([PC]))
	!GlobalTimerNotExpired("bd_mdd905z_ot_timer","bd4300")  // Dragonspear Castle Basement
	GlobalLT("bd_mdd905z_ot","bd4300",2)  // Dragonspear Castle Basement
	OR(2)
		Global("bd_mdd905z_ot","bd4300",1)  // Dragonspear Castle Basement
		Dead("CRUSADERELITE1")
THEN
	RESPONSE #100
		SetGlobal("bd_mdd905z_ot","bd4300",2)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mdd905z_ot_timer","bd4300",9)  // Dragonspear Castle Basement
		DisplayStringHead("CRUSADERELITE2",269650)  // There's only one way out for them! Keep them away from the lift!
END

IF
	!GlobalLT("bd_plot","global",370)
	!Dead("CRUSADERELITE3")
	TriggerOverride("CRUSADERELITE3",See([PC]))
	!GlobalTimerNotExpired("bd_mdd905z_ot_timer","bd4300")  // Dragonspear Castle Basement
	GlobalLT("bd_mdd905z_ot","bd4300",3)  // Dragonspear Castle Basement
	OR(2)
		!GlobalLT("bd_mdd905z_ot","bd4300",1)  // Dragonspear Castle Basement
		Dead("CRUSADERELITE1")
	OR(2)
		!GlobalLT("bd_mdd905z_ot","bd4300",2)  // Dragonspear Castle Basement
		Dead("CRUSADERELITE2")
THEN
	RESPONSE #100
		SetGlobal("bd_mdd905z_ot","bd4300",3)  // Dragonspear Castle Basement
		SetGlobalTimer("bd_mdd905z_ot_timer","bd4300",9)  // Dragonspear Castle Basement
		DisplayStringHead("CRUSADERELITE3",269649)  // Don't let the intruders escape!
END

IF
	Global("bd_baeloth_special2","bd4300",0)  // Dragonspear Castle Basement
	GlobalGT("bd_poison_dsc_supplies","global",0)
	!IfValidForPartyDialog("baeloth")  // Baeloth
THEN
	RESPONSE #100
		SetGlobal("bd_baeloth_special2","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_baeloth_special2","bd4300",0)  // Dragonspear Castle Basement
	GlobalGT("bd_poison_dsc_supplies","global",0)
	IfValidForPartyDialog("baeloth")  // Baeloth
	Delay(4)
	!ActuallyInCombat()
THEN
	RESPONSE #100
		SetGlobal("bd_baeloth_special2","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("baeloth",267537)  // A delightfully devious deed.
END

IF
	Global("bd_dorn_special2","bd4300",0)  // Dragonspear Castle Basement
	!IfValidForPartyDialog("dorn")  // Dorn
	!ActuallyInCombat()
	TriggerOverride("Hehp_chest2",Detect([PC]))
THEN
	RESPONSE #100
		SetGlobal("bd_dorn_special2","bd4300",1)  // Dragonspear Castle Basement
END

IF
	Global("bd_dorn_special2","bd4300",0)  // Dragonspear Castle Basement
	IfValidForPartyDialog("dorn")  // Dorn
	!ActuallyInCombat()
	TriggerOverride("Hehp_chest2",Detect("dorn"))  // Dorn
THEN
	RESPONSE #100
		SetGlobal("bd_dorn_special2","bd4300",1)  // Dragonspear Castle Basement
		DisplayStringHead("dorn",267561)  // What is this? Have we found proof of a parasite clinging to Caelar's crusade, or the dark, secret heart that beats beneath its gleaming skin?
END

