IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		LeaveAreaLUA("XADUCAL2","",[700.465],NE)
		ActionOverride("XACORWIN",LeaveAreaLUA("XADUCAL2","",[750.500],NE))  
		FadeFromColor([30.0],0)
		Wait(3)
		
		ActionOverride(Player1,Rest())
		ActionOverride(Player2,Rest())
		ActionOverride(Player3,Rest())
		ActionOverride(Player4,Rest())
		ActionOverride(Player5,Rest())
		ActionOverride(Player6,Rest())
		
		SetGlobal("XA_LC_Ready", "MYAREA", 1)
		EndCutSceneMode()
END