IF 
	Global("XA_LC_TiannaGoodBye", "GLOBAL", 1)
THEN 
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_LC_TiannaGoodBye", "GLOBAL", 2)
		Wait(1)
		StartDialog("XATIANNA", Player1)
		SetInterrupt(TRUE)
END

IF 
	See("XACORWIN")
	IsValidForPartyDialog("XACORWIN")
	GlobalLT("XA_LC_TiannaIntroduction", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("XA_LC_TiannaIntroduction", "GLOBAL", 1)
		StartDialog("XATIANNA", Player1)
		SetInterrupt(TRUE)
END