IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
	GlobalLT("XA_LC_CompletedG3", "GLOBAL", 1)
THEN
	RESPONSE #100
		SetGlobal("XA_LC_EnterG3", "GLOBAL", 1)
		ActionOverride(Player1, StartDialog("PLAYER1", Player1))
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,10)
THEN
	RESPONSE #100
		DisplayString(Myself,@0)
END

IF 
	Clicked([ANYONE])
	Range(LastTrigger,10)
	GlobalGT("XA_LC_CompletedG3", "GLOBAL", 0)
THEN
	RESPONSE #100
		DisplayString(Myself,@1)
END
